### ISSUE TITLE
NUS format detection doesn't work for DLCs

### ISSUE THREAD

**Issue by freuake** [cemu-project/Cemu#1000]
Ever since #981 you can use updates in the `*.app`/`title.tik`/`title.tmd` format but DLC don't work (maybe because they don't have a `title.tik` file?)

**Comment by Squall-Leonhart** [comment]
works for most dlc, what are you having an issue with?

**Comment by Exzap** [comment]
Cemu won't detect titles without title.tik

**Comment by Emil2010** [comment]
congratulations, you opened a 1000 issue

**Comment by freuake** [comment]
So looks like the tickets of DLCs can be easily generated so that's why they were omitted. I generated them just now and it does work now.
