### ISSUE TITLE
anti-aliasing

### ISSUE THREAD

**Issue by Emil2010** [cemu-project/Cemu#1001]
hello team cemu, add anti-aliasing settings, this feature not for a budget/old computer. This feature not for ME, for OTHER players.
![Снимок экрана 2023-10-19 121204](https://github.com/cemu-project/Cemu/assets/120122332/9b7db315-ce4f-42d8-91df-1214db793934)

**Comment by Exzap** [comment]
Generally on Cemu this is handled by graphic packs, but only some games have graphic packs which can change the anti-aliasing. Doing it globally isn't really the way we handle things (for various technical reasons), but there is still value in the request.
I am going to close this in favor of another feature request which includes this. #1032
