### ISSUE TITLE
Devil's Third (crash)

### ISSUE THREAD

**Issue by willianholtz** [cemu-project/Cemu#1002]
I know this problem is already known, although so far I haven't seen any resolution for it.

The fact is that this game, from what I understand, runs smoothly, the problem is that the game randomly crashes and closes the emulator. Just as described on the wiki.

I decided to post the Devils Third problem here, the log is below. I wish this game could work perfectly in the future. I hope it helps!
[log.txt](https://github.com/cemu-project/Cemu/files/13044071/log.txt)

--- -PC-----
Ryzen 7 5700x
RTX 2060 12GB
64GB Ram

**Comment by Exzap** [comment]
I believe #1036 fixes the crashes. At least I can't replicate them on my end anymore. There are still texture corruptions that need to be resolved but those are unrelated to the crash bug

**Comment by willianholtz** [comment]
Thanks. I'll do tests as soon as possible and get back to you!

**Comment by willianholtz** [comment]
@Exzap Ok, sorry for the delay, but I decided to test the game in depth. And I played for a long time, and the game runs well, there are some stutters and frame drops, but nothing that closes the game or interferes with the gameplay.

**Comment by Exzap** [comment]
Glad to hear the crash is gone. I will be closing this issue then. If you find any other problems worth reporting you can open a new issue
