### ISSUE TITLE
[Feature Request] Desktop shortcuts with icons

### ISSUE THREAD

**Issue by cjunisl** [cemu-project/Cemu#1008]
Using the create desktop function, you can create a shortcut (.ink) to the game, but this shortcut uses the same icon as Cemu.exe.

Would it be possible to implement a feature so that the shortcut uses the game icon that appears in the games list?

These icons are located in mlc01/usr/save/gameID/meta/iconTex.tga

The icons would probably have to be converted to be recognized by the OS.

**Comment by TheRealWario** [comment]
bump

**Comment by Exzap** [comment]
Added with #1126
