### ISSUE TITLE
Wii games on Cemu

### ISSUE THREAD

**Issue by upperthecase** [cemu-project/Cemu#1009]
Run Wii games in Cemu will be a great addition on emulator.

Wii U natively run Wii games with more Ram memory and have digital video out. So the gain in quality in comparison with Dolphin will be big.

**Comment by JosJuice** [comment]
> Wii U natively run Wii games with more Ram memory

No, the amount of RAM available to the game is the same.

> and have digital video out.

Dolphin already has digital video out.

Integrating Wii emulation into Cemu wouldn't come with any quality gains, and would require an enormous effort.

**Comment by Adamillo** [comment]
The Wii U compared to the Wii is quite different in terms of hardware, so it's not worth it for Cemu. The Wii U literally includes Wii hardware for backwards compatibility and uses the same RAM. If you want Wii emulation use Dolphin
