### ISSUE TITLE
[Xenoblade Chronicles X] [Vulkan] Graphical Corruption/Flickering in certain menus

### ISSUE THREAD

**Issue by Meepster-836** [cemu-project/Cemu#1011]
[log.txt](https://github.com/cemu-project/Cemu/files/13198749/log.txt)
![Screenshot_20231029_102340](https://github.com/cemu-project/Cemu/assets/127622115/fd4dcefb-e8c2-4e1f-8222-13769eef2654)

When in the Game Options menu in Xenoblade X (in-game, not sure if this happens on the title screen as well), there is inconsistent but fast graphical corruption/flickering occuring. The corruption would also very in intensity at random, sometimes weak and only affecting small parts of the screen, and sometimes affecting all of it. The flickering was too fast for me to take a screenshot of. Moving around the options menu might amplify the issue, but I'm not sure.

When in the Skell menu (the terminal in the BLADE Barracks) and customizing the Skell's equipment, there is full screen flickering black and white, also affecting the UI (This is what the attached screenshot shows). I've also seen it occur isolated to just the Skell, flickering between fullbright white and black.

I have not tested Skell submenus other than equipment, but it seems to not happen in the main Skell menu, only when in the equipment submenu.

Detailed system specs are in the log, but I am using:

Ryzen 9 5900X
Radeon RX 6700 XT
32GB DDR4 RAM
KUbuntu 22.04.3 LTS
Cemu 2.0-59 AppImage
Vulkan Renderer/Asyc Compile on/Accurate Barriers on
Vsync is off

**Comment by Meepster-836** [comment]
I played some more of the game and found 2 more scenarios in which this bug occurs:

1. Specifically when opening the Yes/No prompt for upgrading an Art

2. When going to the _Shop_ menu for Skells and browsing purchasable equipment

**Comment by MNolan147** [comment]
I’m also having this issue (flickering in the equipment select screen). I’ve tried changing graphics pack settings (change resolution to default, 30fps, revert to default) and nothing has worked so far.

I’m using:

AMD Ryzen 7 7800X3D
Radeon RX 7800 XT
64GB DDR4 RAM
Arch Linux
Cemu built from GitHub
Vulcan Renderer/Async Compile On/Accurate Barriers On
V-sync Triple Buffering (issue still occurs with V-sync off)

This could be an issue with the graphics card as we are both using the same card.

**Comment by AKKypher** [comment]
I am having the same issue "flickering in the equipment select screen" I have also tried changing graphics pack settings and more nothing has worked. 

AMD Ryzen 5 1600 6-core
Windows 10 Home 64bit
Cemu version 2.0.4.9
16GB Ram
Vulcan Renderer/Async Compile On/Accurate Barriers On
V-sync Triple Buffering "issue still occurs with V-sync off"
DX 12
Nvidia Geforce GTX 1050ti 4GB

I do not think it is the video cards as we do not have the same and I am having the exact same issues.

**Comment by Meepster-836** [comment]
Good to know that it's not just isolated to a single configuration. In the mean time I've found another instance of the bug, which occurs in the menu where you can change around/view your soul voices.

**Comment by AKKypher** [comment]
Thank you for that info, I just tried the latest test build of cemu 2.0-59 and I have not ran into this problem with it yet as I only tested it for a min. I will do more testing now.

**Comment by Meepster-836** [comment]
https://github.com/cemu-project/Cemu/assets/127622115/43d0a7e2-6e25-43f4-96c6-da65e264432e

I've recorded a video to present to demonstrate some of these issues.

Ironically enough however, my recordings seem to be having graphical issues of their own, and I'm not sure how to fix them. They may or may not show up for you, but it's just some black flickering that comes from the bottom of the screen. Other than that the video should be perfectly watchable.

**Comment by AKKypher** [comment]
The problem is still there for me also after more testing.

**Comment by Meepster-836** [comment]
Just tested on the recently-released Cemu 2.0-60, and I can confirm that the issue is still present.

**Comment by AKKypher** [comment]
I just tested its the same for me also. I hope it can be fixed soon if possible.

**Comment by sky922** [comment]
I found this thread on google and made an account to say I have the same issue. In the menu to change weapons it gradually flickers and in the shop menu it flickers intensely.

**Comment by Meepster-836** [comment]
Thanks to a tip from someone on the discord, I was asked to test this on 2.0-51 and can confirm it does not occur there on the AppImage version. It is still an issue on latest (2.0-61) however.

**Comment by AlexSD1** [comment]
I was having the same problem using a Lenovo Legion Go. I also confirm that going from 2.0-61 to 2.0-51 solved the issue for me

**Comment by AKKypher** [comment]
Confirmed working for me by going back to 2.0-51

**Comment by wasago01** [comment]
Yes 2.0-51 working but from that its a mess.

**Comment by iriyap** [comment]
Was getting intense flickering even in the settings menu on the title screen, but rolling back to 2.0-51 fixed all Vulkan flickering issues (including the inventory flickering in BOTW). Hope the devs look into this sooner rather than later.

**Comment by juan258** [comment]
I'm going to try with this version, I come from 2.0-65 and it is impossible to play the game like this.

**Comment by jimmyvh** [comment]
Can confirm 2.0-51 doesn't have the flickering issue while other versions do. Running on a ryzen 5500 cpu and an amd rx6600.

**Comment by wasago01** [comment]
For me its seams fixed on lastest version.

**Comment by iriyap** [comment]
Yes, looks like it's fixed as of 2.0-66.

**Comment by Meepster-836** [comment]
I'll test it out on latest Cemu later today and see if it's fixed

**Comment by Meepster-836** [comment]
Test on Cemu 2.0-66 (Flatpak), this issue does seem to have been resolved!
