### ISSUE TITLE
Graphic pack causes crash when emulator path contains accents

### ISSUE THREAD

**Issue by Wronschien** [cemu-project/Cemu#1018]
Version 2.0.59 on Windows 10.
Having updated form 2.0.31 (I think) and enabling any item in the graphic pack for BOTW, the game doesn't start and crashes. The game only crashes with the graphic pack though, it launches and plays well without it.
The workaround I found is to move the emulator to a path without accents (and probably no non ansi characters). There the graphic pack doesn't provoke crashes.
Something was changed because it was working correctly with the earlier version, in the same accented path location.

**Comment by Squall-Leonhart** [comment]
do you have UTF8 Beta enabled in the windows settings?

**Comment by Wronschien** [comment]
Probably not, how can I check ?

**Comment by Wronschien** [comment]
Well should I activate UTF8 beta then ? I've searched a bit and found this creates problems with other software. I don't mind if the emulator location has changed as long as it works, but I wanted to tell you about the change in behaviour.

**Comment by Squall-Leonhart** [comment]
Turns out someone did a PR to fix this a while ago

https://github.com/cemu-project/Cemu/pull/1010

**Comment by Wronschien** [comment]
So this will someday be fixed if I understand well ?

**Comment by ViniciusCampaner** [comment]
Hi, I'm having the same problem in which Cemu crashes after changing any graphick pack parameter, but I don't understand what was done to solve this problem, could someone explain it to me?

**Comment by Wronschien** [comment]
Well the current version (2.0-61) apparently doesn't yet fix the problem natively.
What I had done (which still works) is to move the emulator folder from "C:\Émulateurs\Cemu" to "C:\Emulateurs\Cemu", notice the accent over E before and not after.
You may also have in your path an accent or another non English sign like a Spanish tilde, a German umlaut or eszett, something like that. So just move Cemu to a path without them. Try simply "C:\Cemu" for a start, it should work there.
If that's not enough I think the problem is not the same and you should open a new issue.

**Comment by Squall-Leonhart** [comment]
The fix for this will be in 2.0-62, i have confirmed the changes resolve the issue.

**Comment by Wronschien** [comment]
Great, thanks !
