### ISSUE TITLE
[Bug] Cemu crashes when starting game

### ISSUE THREAD

**Issue by martinprad0** [cemu-project/Cemu#1026]
I'm currently using Flatpak's version of Cemu in Fedora 39. I can open Cemu's GUI, however when I try to start a game I get the following error: `(Cemu_relwithdebinfo:23): Gdk-WARNING **: 00:38:24.888: The program 'Cemu_relwithdebinfo' received an X Window System error.`

```
[martin@figaro ~]$ flatpak run info.cemu.Cemu
Gtk-Message: 00:38:22.796: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:38:22.796: Failed to load module "pk-gtk-module"
Gtk-Message: 00:38:22.797: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:38:22.797: Failed to load module "pk-gtk-module"

(Cemu_relwithdebinfo:23): Gtk-CRITICAL **: 00:38:22.986: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Cemu_relwithdebinfo:23): Gdk-WARNING **: 00:38:24.888: The program 'Cemu_relwithdebinfo' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 1608 error_code 8 request_code 149 (unknown) minor_code 4)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

These are the system specs:
**OS:** Fedora Linux 39 (Workstation Edition) x86_64
**Kernel:** 6.4.4-200.fc38.x86_64
**DE:** GNOME 45.1
**CPU:** Intel i5-8250U (8) @ 3.400GHz
**GPU:** Intel UHD Graphics 620 
**GPU:** NVIDIA GeForce MX130
**Memory:** 4075MiB / 15861MiB

**Comment by Squall-Leonhart** [comment]
what nvidia driver is on that

**Comment by martinprad0** [comment]
> what nvidia driver is on that

NVIDIA Settings says the following:

**System Information**
Operating System: Linux-x86_64
NVIDIA Driver Version: 535.129.03
NVML Version: 12.535.129.03

**X Server Information:**
Display Name: figaro:1
Server Version Number: 11.0
Server Vendor String: The X.Org Foundation
Server Vendor Version: 1.20.14 (12014000)
NV-CONTROL Version: 1.29
Screens: 1

**Comment by Mubelotix** [comment]
Happens when I load an rpx file

**Comment by Exzap** [comment]
Does this crash still happen? There have been multiple fixes for similar issues and maybe this is affected?

**Comment by martinprad0** [comment]
Okay, I don't know what happened, but everything is working now. Today I decided to give it another try and selected the NVIDIA integrated card instead of the Intel one like usual, but this time it works flawlessly.
