### ISSUE TITLE
[Bug] Cemu does not compile with fmt 10+

### ISSUE THREAD

**Issue by GloriousEggroll** [cemu-project/Cemu#1031]
Not sure if the cause is on the Cemu side or the fmt side, from what I gather it appears to be the fmt side:

https://github.com/fmtlib/fmt/issues/3710

The compilation bug is the same:

`error: no matching member function for call to 'format'`

It compiles on fedora 38 because they are still on fmt 9, but on fedora 39 they moved to fmt 10 which breaks the build.

I found reverting b3fa3480dd3b5c99b24136382953f1fd21b75488 in fmt 10+ allows cemu to build again.

**Comment by Squall-Leonhart** [comment]
10.1.0 works.

**Comment by GloriousEggroll** [comment]
thanks for the heads up, can confirm it compiles with 10.1. just waiting on fedora to update fmt.
