### ISSUE TITLE
ZombiU sound problems

### ISSUE THREAD

**Issue by LuismaSP89** [cemu-project/Cemu#104]
There's a lot of sound issues in ZombiU.

The game sound only works in stereo mode (also on real console) if the cemu options and/or the game options are set to surround, no music is played.

The stereo sound works overall in the game, but the loading screen sounds are not working, the weapon shoots, or some other sounds in the game are not working, also the voice of the man behind the cameras are played with lag, only saying the second part of some phrases.

I remember this game have sound problems in cemu from the beginning, but I also remember shoot sounds and loading screen sounds working in some earlier builds of cemu "maybe I'm wrong" but the thing is this game is perfectly playable from start to finish but with this big issues on the sound's side.

This was tested in all the versions of cemu from the very beginning of this emulator, but in no one got it working at 100%

Specs: 

i7 4790k
16GB DDR3
GTX 970
Windows 11
Cemu 2.0.0

**Comment by jkcoxson** [comment]
This would be better suited for the compat site, not necessarily GitHub issues.

**Comment by LuismaSP89** [comment]
> This would be better suited for the compat site, not necessarily GitHub issues.

Well, I'm my humble opinion this is not only a compat issue but a emulator's sound core problem itself. Must be an unimplemented function since on the original console works fine.

There are not too much sound issues on this emulator but placing the issue here maybe somebody wants to do any kind of work or improvement on cemu's sound core.

**Comment by Crementif** [comment]
These kinda issues are fine to have on the bug tracker.

**Comment by tqoac** [comment]
You can actually fix this issue by getting the rpl files from your wiiu and dropping them inside cemu

**Comment by LuismaSP89** [comment]
> You can actually fix this issue by getting the rpl files from your wiiu and dropping them inside cemu

Could you please clarify what folders or rpl files? I dumped all my rpl files in cemu long time ago, but this problem persists. Are you sure that is the way to fix this?

I also launched the wiiu menu in the cemu and configured the sound to stereo. The issue still persists.

Thanks a lot.

**Comment by tqoac** [comment]
> > You can actually fix this issue by getting the rpl files from your wiiu and dropping them inside cemu
> 
> Could you please clarify what folders or rpl files? I dumped all my rpl files in cemu long time ago, but this problem persists. Are you sure that is the way to fix this?
> 
> I also launched the wiiu menu in the cemu and configured the sound to stereo. The issue still persists.
> 
> Thanks a lot.

Hello, you need the nn_sl.rpl, snd_user.rpl and snduser2.rpl. After you have obtained these files, create a new folder in your CEMU directory with the name "cafeLibs" and dropping these 3 files in it.

**Comment by LuismaSP89** [comment]
> > > You can actually fix this issue by getting the rpl files from your wiiu and dropping them inside cemu
> > 
> > 
> > Could you please clarify what folders or rpl files? I dumped all my rpl files in cemu long time ago, but this problem persists. Are you sure that is the way to fix this?
> > I also launched the wiiu menu in the cemu and configured the sound to stereo. The issue still persists.
> > Thanks a lot.
> 
> Hello, you need the nn_sl.rpl, snd_user.rpl and snduser2.rpl. After you have obtained these files, create a new folder in your CEMU directory with the name "cafeLibs" and dropping these 3 files in it.

Yes, that's exactly how I have it since some years ago. But still doesn't work.

![imagen](https://user-images.githubusercontent.com/12205048/215547657-5e59b83f-7372-419a-97e2-8f8b28278f63.png)

**Comment by tqoac** [comment]
> > > > You can actually fix this issue by getting the rpl files from your wiiu and dropping them inside cemu
> > > 
> > > 
> > > Could you please clarify what folders or rpl files? I dumped all my rpl files in cemu long time ago, but this problem persists. Are you sure that is the way to fix this?
> > > I also launched the wiiu menu in the cemu and configured the sound to stereo. The issue still persists.
> > > Thanks a lot.
> > 
> > 
> > Hello, you need the nn_sl.rpl, snd_user.rpl and snduser2.rpl. After you have obtained these files, create a new folder in your CEMU directory with the name "cafeLibs" and dropping these 3 files in it.
> 
> Yes, that's exactly how I have it since some years ago. But still doesn't work.
> 
> ![imagen](https://user-images.githubusercontent.com/12205048/215547657-5e59b83f-7372-419a-97e2-8f8b28278f63.png)

Thats really strange... Have you tried placing the other rpl's somewhere else and only playing with the 3 mentioned?

**Comment by LuismaSP89** [comment]
> > > > > You can actually fix this issue by getting the rpl files from your wiiu and dropping them inside cemu
> > > > 
> > > > 
> > > > Could you please clarify what folders or rpl files? I dumped all my rpl files in cemu long time ago, but this problem persists. Are you sure that is the way to fix this?
> > > > I also launched the wiiu menu in the cemu and configured the sound to stereo. The issue still persists.
> > > > Thanks a lot.
> > > 
> > > 
> > > Hello, you need the nn_sl.rpl, snd_user.rpl and snduser2.rpl. After you have obtained these files, create a new folder in your CEMU directory with the name "cafeLibs" and dropping these 3 files in it.
> > 
> > 
> > Yes, that's exactly how I have it since some years ago. But still doesn't work.
> > ![imagen](https://user-images.githubusercontent.com/12205048/215547657-5e59b83f-7372-419a-97e2-8f8b28278f63.png)
> 
> Thats really strange... Have you tried placing the other rpl's somewhere else and only playing with the 3 mentioned?

Tested right now. Still not working.

Could you please confirm this is working for you? I mean, the thing is that the sounds are working, but certain sounds like the shoots, the loading screen, the hits with the cricket bat, etc are no working.

On the wiiu this game is the only one that you need to set the sound to stereo in order to work.

In case all this sounds are working in your end, could you please also share what are your sound settings on cemu?

It would be nice if you can share also the cafelibs files. Maybe it's a bad dump from my console, but I tried twice and the result is exactly the same. : (

**Comment by Masamune3210** [comment]
Sharing the libs is probably a bad idea, considering they are copyrighted code

**Comment by LuismaSP89** [comment]
%$%#! I realized that my libs didn't had the .rpl extension, I don't know if I removed it accidentally, but NOW IT WORKS. This was driving me crazy for years. Thanks a lot @tqoac for all your help. 

Closing.
