### ISSUE TITLE
Cemu 2.0-61 Super Mario 3D World

### ISSUE THREAD

**Issue by Hexaae** [cemu-project/Cemu#1041]
Intel i7-8750h + 32GB RAM + GTX 1070 8GB + 1920x1080 144Hz G-Sync.
Windows 11 23H2.

Super Mario 3D World freezes at VK cache re-compile on startup, at 99%.
Log: https://paste.sh/jVpoP9wb#5jmGeUCAbv8VLE1f-Adz_2GW

**Comment by LuizHenriqueAmaralSoares-lab** [comment]
Hello, try update your GPU drivers. Nvidia GPU drivers recently fix lots of bug with Vulkan

**Comment by Hexaae** [comment]
2.0-65 still hangs at 99% VK caches generated.
GTX 1070 8GB, NVidia 546.33 SD.

**Comment by Hexaae** [comment]
Never mind: I **cleared the shaders** (RMB on the game name and select it from pop-up menu) for this game only and it worked!
