### ISSUE TITLE
Wii U Pro Controller automatically disconnects while Cemu is open

### ISSUE THREAD

**Issue by i-can-not-program** [cemu-project/Cemu#1046]
Wii U Pro Controller will automatically disconnect after being connected so long as Cemu is open. The issue is introduced in 5e84862.
Fixed by #1037 
OS is Linux

**Comment by sune26** [comment]
This is still an issue on windows. Previous versions work but disconnects at version 74

**Comment by Toasty-Engineer** [comment]
> This is still an issue on windows. Previous versions work but disconnects at version 74

same but it disconnects on every version for me

**Comment by thanone2** [comment]
same here :(

**Comment by Dricc-new** [comment]
I have th same problem =(
