### ISSUE TITLE
Image gamma with steam remote play

### ISSUE THREAD

**Issue by Odizinne** [cemu-project/Cemu#1060]
When using Cemu fullscreen with vulkan on windows host, streaming through steam remote play to a device (steam deck in this case) give a way too bright image:

This brightness / gamma is correct on the host.

![IMG_20240111_174730](https://github.com/cemu-project/Cemu/assets/102679854/b29dedc5-449e-4a7e-9684-415c7b95e090)
When exiting fullscreen / focusing other window everything goes back to normal.

![IMG_20240111_174754](https://github.com/cemu-project/Cemu/assets/102679854/f53ab890-6dd1-4959-9796-8df4b554b2fb)

I think it might be related to steam remote window capture, but Cemu is the only app where this issue occurs, so i'm not sure.

Tested with and without graphics pack, result is the same.<br/>
Tested with 2 different games.

OpenGL is working as intended.
Linux host is not affected, only windows.

[log.txt](https://github.com/cemu-project/Cemu/files/13906098/log.txt)

**Comment by Squall-Leonhart** [comment]
This is not a Cemu bug.

https://steamcommunity.com/groups/homestream/discussions/1/3191368254806677908/

**Comment by Odizinne** [comment]
From what i read:

16 March - Steam Client Update Released
A new Steam client has been released and will be automatically downloaded.

Remote Play
Fixed washed out colors streaming D3D9 games 

This does not appear to be related to vulkan

**Comment by Squall-Leonhart** [comment]
on second look, your windows PC has hdr on with Auto-hdr optimizing the appearance of Cemu, this only occurs fullscreen unless the DXGI swapchain is enabled in the video driver where it is then performed either way.

**Comment by Odizinne** [comment]
HDR / auto HDR is off. I don't use it. the pictures are from my steam deck.

**Comment by Squall-Leonhart** [comment]
Is this a steamdeck connected to a tv?

**Comment by Odizinne** [comment]
No, streaming my main PC to it.

Cemu added as a non steam game on windows host PC, launched via steam on the deck (linux) using the built in remote play feature.

No hdr enabled on the host (at least in windows settings), idk about AMD drivers, but never seen such option ( DXGI swapchain)

**Comment by Squall-Leonhart** [comment]
enabling Triplebuffering in the Radeon control panel will turn on DXGI Swapchain.

**Comment by Odizinne** [comment]
![image](https://github.com/cemu-project/Cemu/assets/102679854/afd7dec5-23ec-48a6-ac39-8cf3263a752a)

This is off and has never been on

**Comment by Squall-Leonhart** [comment]
Crap, AMD is automatically using the DXGI swapchain on Vulkan, only Opengl requires TB enabled to turn it on.

if i'm right, opengl should be broken with that toggled too.

**Comment by Odizinne** [comment]
Yeah was reading that too. I'll try with OpenGL and this setting

**Comment by Squall-Leonhart** [comment]
Hey, this issue may be resolved in [SteamOS 3.5.8](https://steamcommunity.com/games/1675200/announcements/detail/3870343609914277086?snr=2_9_100015_)

**Comment by Odizinne** [comment]
I already tried beta builds, infortunately it does not change anything for Cemu.

Eating right now, and i'll follow back with opengl test. If the same occurs with triple buffering, i guess we can call the driver problem and clsoe this issue

**Comment by Odizinne** [comment]
So:

- Doom 2016 (Vulkan) no issue
- Hades (Vulkan) no issue
- Cemu (OpenGL with triple buffering in drivers) no issue
- Yuzu (Vulkan) no issue

Not sure why only Cemu is affected

**Comment by Odizinne** [comment]
Performed a factory reset, switch back to preview channel on the deck, and it's seems to be gone.

Weird as i was already on the preview channel before the reset.

This issue can be closed. Thanks a lot for the help on troubleshooting!

**Comment by Exzap** [comment]
Not sure what the current state of this is, but I am closing it since it's up to Valve to fix this anyway. We have no control over their way of capturing Cemu's output
