### ISSUE TITLE
working cemu for macos 10.13.6

### ISSUE THREAD

**Issue by fortniteburger3** [cemu-project/Cemu#1069]
i have macbook air 2015 and its stuck with version 10.13.6 so i cant really install newer version of cemu is there a way to install working old one because everytime i install old cemu version it doesnt work

**Comment by JaimieVandenbergh** [comment]
Cemu for Mac requires macOS 12+ currently. 
Cemu 2.0-27 and below will run on macOS 11.

A 2015 Air would run Cemu very poorly in macOS anyway due to the Vulkan->Metal conversion. Your best bet is installing a Windows or Linux Boot Camp volume.
