### ISSUE TITLE
Yoshi's Woolly World boots to black screen using Cemu 2.0

### ISSUE THREAD

**Issue by Hexaae** [cemu-project/Cemu#108]
CEMU 2.0 exp, Windows 10 (2H21), i7-8750h, GTX 1070 8GB, NVidia drivers 512.96 SD.

Yoshi's Woolly World freezes with black screen after loading caches (VK api). This bug appeared first with CEMU 1.27.0b and was fixed by 1.27.1exp. Now reappears in CEMU 2.0exp

**Comment by Squall-Leonhart** [comment]
Two issues,

HLECopySurface(): Source texture is not in list of dynamic textures
Special state 8 requires special state 0 but it is not set?

**Comment by Hexaae** [comment]
2.0-1 exp still affected.

**Comment by Squall-Leonhart** [comment]
Fixed by https://github.com/cemu-project/Cemu/commit/1e851fe7e2e7a26e5a97d27fc07ffabec852ca0f
