### ISSUE TITLE
Cemu does not automatically switch sound output on steam deck when docked 

### ISSUE THREAD

**Issue by onnextflix11** [cemu-project/Cemu#1083]
### Current Behavior

When switching from handheld to docked the sound output doesn’t switch to the tv output automatically. other emulators seem to handle this just fine. 

### Expected Behavior

When docked emulator should switch sound output automatically to tv via hdmi. 

### Steps to Reproduce

Dock the steam deck and connect to the tv, then start cemu. Open a game, you will find that there is sound coming from tv as sound output has not changed. 

### System Info (Optional)

OS: steam os Linux 
GPU:

**Comment by Squall-Leonhart** [comment]
Sounds like  you're using cubeb, so this is already addressed in https://github.com/cemu-project/Cemu/pull/1017

**Comment by onnextflix11** [comment]
I’m using the latest Cemu experimental 2.0 .65

 The only option is cubeb is sound api settings.

**Comment by Squall-Leonhart** [comment]
when 1017 merges, a new default device item will be listed, this device will automatically change based on the system device selection.
