### ISSUE TITLE
super mario 3d world crashing on character select

### ISSUE THREAD

**Issue by qqjonson1234** [cemu-project/Cemu#1084]
### Current Behavior

I don't know why but cemu crashes while loading the game after character select, 

### Expected Behavior

Load the game normally showing any character on the map screen

### Steps to Reproduce

IDK how to reproduce i might make a yt video showing how to reproduce it.

### System Info (Optional)

OS: windows 11
GPU: AMD Ryzen 9
Ram: 1 TB
cpu: 14600K (For 4080)

**Comment by qqjonson1234** [comment]
will add log later

**Comment by Squall-Leonhart** [comment]
is this a troll post?

**Comment by qqjonson1234** [comment]
> is this a troll post?

no

**Comment by qqjonson1234** [comment]
> is this a troll post?

What do you mean? I don't troll people with problems with my emulator!

**Comment by qqjonson1234** [comment]
> is this a troll post?

Haven't had time to add a log yet

**Comment by qqjonson1234** [comment]
> > is this a troll post?
> 
> Haven't had time to add a log yet

Plus i don't know where to find the log

**Comment by Squall-Leonhart** [comment]
Close this and join the discord, there isn't a crashing bug in the emulator and the issue tracker isn't for general support.

**Comment by qqjonson1234** [comment]
> Close this and join the discord, there isn't a crashing bug in the emulator and the issue tracker isn't for general support.

Link for discord

**Comment by Exzap** [comment]
Discord invite: https://discord.gg/5psYsup
