### ISSUE TITLE
Donkey Kong Country Tropical Freeze - Platforms resetting prematurely

### ISSUE THREAD

**Issue by spamzilla** [cemu-project/Cemu#1085]
### Current Behavior

In Stage 3-1 directly after the first save point, the moving platforms reset prematurely. I think this means that the level cannot be completed because later on a moving animal head thing that you have to grab onto moves before it is supposed to. If you are standing on the platform, you will reset as well. But, if you jump you will not reset.

### Expected Behavior

That the platforms would not reset early.

### Steps to Reproduce

In Stage 3-1 directly after the first save point, the moving platforms reset prematurely.

### System Info (Optional)

OS: Windows 10 Home
GPU: Intel HD Graphics 520

**Comment by Squall-Leonhart** [comment]
post a video.

**Comment by spamzilla** [comment]
https://youtu.be/yJtl0sao_JQ

**Comment by Squall-Leonhart** [comment]
The movement of just about everything on this level is tied into the audio rate,  if you are not achieving full speed (which you aren't) the audio buffers are exhausting and the movement resets along with each fill and deplete cycle of the audio buffers.

**Comment by Exzap** [comment]
I didn't test this, but a potential workaround could be to set the CPU timer speed in the menu to 0.5x or 0.25x?
I'll be closing this as it's not really a bug and more a performance issue on the users side.

**Comment by spamzilla** [comment]
I changed the CPU timer but it didn't seem to do anything.
