### ISSUE TITLE
Real Wii U Gamepad Support

### ISSUE THREAD

**Issue by erikiorai** [cemu-project/Cemu#1087]
### Your suggestion

I have a suggestion for Cemu that I think would be awesome to have. I would love to see real Wii U Gamepad support in Cemu, so I can enjoy the unique asymmetric gaming experience that some games offer. I don't want to buy a Wii U because I heard they have a scary Nand issue (160-0103) that can brick the console.

I did some research online and I found out that it is possible to connect a Wii U Gamepad to a Linux PC with limited functionality. You need an Ubuntu system, which you can use WSL for, and an 802.11n 5GHz wifi card that supports rt2800 drivers. Then you can use the WSL program to connect to the Wii U Gamepad and get an IP address that you can enter in Cemu, like drc-sim does. This way, Linux handles the connection to the Wii U and Windows acts as the Gamepad screen.

I think this would be a great feature to add to Cemu and I hope you consider it. Thank you for your amazing work on this emulator!

Useful links:
https://patchwork.kernel.org/project/linux-input/cover/20210519085924.1636-1-linkmauve@linkmauve.fr/#24535243
https://github.com/thefloppydriver/pc2drc

**Comment by Exzap** [comment]
This falls under "obvious suggestions" which the suggestion page asks you not open :wink: So I am going to close this

Imho as long as DRC support is limited to specific kernel or drivers it's too niche to be worth the effort. Of course anyone disagreeing is free to work on this and PRs are always welcome
