### ISSUE TITLE
[MacOS] Cemu uses a secondary system language when interface language is set to "Default"

### ISSUE THREAD

**Issue by detekoi** [cemu-project/Cemu#1091]
### Current Behavior

Cemu sets UI language to the second system language set in System Preferences, not the primary language, when "Default" language is set in General Settings.

### Expected Behavior

Cemu UI should use primary system language when interface is set to use "Default" language.

### Steps to Reproduce

1. Open Settings > Language & Region.
2. Click + to add a new language supported by Cemu.
3. When prompted to set a new primary language, click the second option (preserves original language).
4. Open Cemu - see UI is in the second language.

### System Info (Optional)

OS: Sonoma 14.2.1
GPU: M3 Max

**Comment by Behodar** [comment]
Same here, under OS 14.3.1. Cemu 2.0-61 is fine, but 2.0-62 and later exhibit the issue.
