### ISSUE TITLE
Nintendo Land crashes on some attractions (Regression)

### ISSUE THREAD

**Issue by GaussTek** [cemu-project/Cemu#1092]
### Current Behavior

Some attracions from Nintendo Land (single player) like the Zelda and Pikmin ones crash upon trying to load them (Cemu just closes by itself without showing any error). This happens on CEMU 2.0-65

### Expected Behavior

The attractions should load even if there are graphical issues, they work fine on CEMU 2.0-61, so latest versions are causing this issue.

### Steps to Reproduce

Load Nintendo Land, go to Zelda attraction, select Quest game --> 1 player --> select Archer (GamePad) --> 1st Mission.
Cemu closes itself after this.

### System Info (Optional)

OS: Windows 11
GPU: Nvidia GTX 1650

### Emulation Settings (Optional)

Using Vulkan / OpenGL, both crash.

**Comment by Squall-Leonhart** [comment]
just to humour me, from your wii u, extract nn_fp.rpl and put it into the cafelibs folder.

**Comment by GaussTek** [comment]
> just to humour me, from your wii u, extract nn_fp.rpl and put it into the cafelibs folder.

Just tried that, and it crashes just the same for me!

Weird that it works on v2.0-61

**Comment by Exzap** [comment]
This should be fixed in 2.0-66. Can you confirm?

**Comment by GaussTek** [comment]
> This should be fixed in 2.0-66. Can you confirm?

Yes, I can confirm the games work again in the newest release. Thank you so much!!
