### ISSUE TITLE
New update is crashing even on new installs of Cemu.

### ISSUE THREAD

**Issue by Euphonit** [cemu-project/Cemu#1110]
### Current Behavior

I am currently using Cemu version 2.0-67 (Experimental) and I opened it this afternoon to play some games and then it gave me a window saying a new update is available for Cemu. I was using version 2.0-66 before. I updated to the newest version then tried launching Legend of Zelda: Breath of the wild. then I got this message. 
![Screenshot (4)](https://github.com/cemu-project/Cemu/assets/162762431/4a005dd4-705f-440d-a530-70d3452c84f8)
This issue was clearly not happening before so I believe it is an bug with the update. I know graphic packs can change things so I tried a game that worked before without graphic packs enabled (Super Mario Maker) yet it still failed. I use a switch pro controller and I heard that could be an issue but I tried it with a different controller and it still happened. I also had noticed the same error message when updating but I just closed the program and then opened it again. So I tried download Cemu 2.0-66 again to see if it was just my download that was messed up. Same issue. Then I downloaded the newest version from scratch. Same issue. I checked the issue tracker to see if this had already came up. No issue had come up.

### Expected Behavior

I expected the emulator to function fine.

### Steps to Reproduce

Step 1. Download Cemu 2.0-66 or Cemu 2.0-67.  Step 1b. (Skip if download latest version.) Update Cemu. Step 2. Try to load any game. See if results match same error message.

### System Info (Optional)

Processor	AMD Ryzen 5 4500 6-Core Processor                 3.60 GHz
Installed RAM	32.0 GB (31.9 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Education
Version	21H2
Installed on	‎11/‎13/‎2021
OS build	19044.4046
Experience	Windows Feature Experience Pack 1000.19053.1000.0
Graphics Card: Nvidia GTX 770

PS: I own this copy of windows 10 education as it was gifted to me by a family member who worked somewhere where it was available.

### Emulation Settings (Optional)

I have enabled fullscreen menu bar, Audio is Xaudio2, Shaders Async, Match emulated display for VSYNC, and I have crash dump lite enabled.

### Logs (Optional)

Log for breath of the wild: [log.txt](https://github.com/cemu-project/Cemu/files/14544250/log.txt)

Log for super Mario maker: [log.txt](https://github.com/cemu-project/Cemu/files/14544257/log.txt)

**Comment by Squall-Leonhart** [comment]
already fixed in 2.0-68, please note your hardware is on life support driver wise and cemu will eventually no longer work beyond the next major update when cemu starts using vulkan 1.2+ features.
