### ISSUE TITLE
Bugged Out Goddess Statues In Breath Of The Wild On Mac 

### ISSUE THREAD

**Issue by noahgg2** [cemu-project/Cemu#1119]
### Current Behavior

Whenever I go to a goddess statue, the staute is not there, and there is no prompt. I have checked multiple times to make sure I am going to the right places and I am and it still doesn't work. 

### Expected Behavior

I would expect the goddess statue to be there and also for it to have a prompt to I can gain more hearts or stamina 

### Steps to Reproduce

Play the game and then go to a goddess statue

### System Info (Optional)

OS: Mac Os 
GPU: Mac 

### Emulation Settings (Optional)

None 

### Logs (Optional)

[log.txt](https://github.com/cemu-project/Cemu/files/14595166/log.txt)

**Comment by Squall-Leonhart** [comment]
Redump your game, there is no universe where everything else works but the statues are not present.

**Comment by noahgg2** [comment]
@Squall-Leonhart ill do it, but it does seem kind of weird that the rest of the game works perfectly.

**Comment by noahgg2** [comment]
but first could it be the shader cashes?

**Comment by noahgg2** [comment]
Update redumpted the file working
