### ISSUE TITLE
Breath of the Wild freeze after I buy pictures from Symin in Hateno Ancient Tech Lab

### ISSUE THREAD

**Issue by TorCroft** [cemu-project/Cemu#1121]
### Current Behavior

I talked to Symin, bought one picture and then one item unlocked in the Hyrule Compendium, then the game froze.
This is the last frame, after few seconds Cemu crashed.
![Screenshot 3_16_2024 12_04_09 PM](https://github.com/cemu-project/Cemu/assets/96010900/5b01d9fd-2529-40e3-98ea-aa525757a51c)

### Expected Behavior

The game should continue running normally.

### Steps to Reproduce

* Step 1: Teleport to Hateno Ancient Tech Lab
* Step 2: Talk to Symin and buy a picture from him

### System Info (Optional)

OS: Windows 11 Pro 23H2 22631.3296
GPU:  RTX 4080

### Emulation Settings (Optional)

![Screenshot 2024-03-16 121337](https://github.com/cemu-project/Cemu/assets/96010900/f8e25a32-cc82-40d5-a7a6-86dc2390d46c)
![Screenshot 2024-03-16 121347](https://github.com/cemu-project/Cemu/assets/96010900/5e5b7f3f-5312-455e-ae72-3bedb5c5d0f8)

### Logs (Optional)

[log.txt](https://github.com/cemu-project/Cemu/files/14622295/log.txt)

**Comment by Squall-Leonhart** [comment]
delete the custom game profile to return the game to default core settings, and update the video driver from 546.xx to 551.71

**Comment by TorCroft** [comment]
It looks like the crash was caused the cheat `9999 Map Stamps Limit`, the game is running normally after I disabled this cheat.
