### ISSUE TITLE
GPU Crashes since version 2.0-68

### ISSUE THREAD

**Issue by JakefSM** [cemu-project/Cemu#1128]
### Current Behavior

I've been playing a lot of Xenoblade Chronicles, when I updated to -68 none of my games would launch (BOTW, Twilight Princess). I updated my GPU drivers and the problem was solved. I thought it was just a windows update/vs AMD adrenaline conflict. Every version after -68 gives me frequent crashes. Rolling back to -67 or -68 seems to solve the problem.

### Expected Behavior

Game to play without interruption

### Steps to Reproduce

Launch game, play for an hour, screen goes black and you realize you haven't saved...
game Music and other non-cemu activities continue to play sound but there is no screen.

### System Info (Optional)

OS: win 10
GPU: RX 6600XT

**Comment by Squall-Leonhart** [comment]
please post log, and the rest of your system,

Note there are ongoing black screen issues with RDNA2 and have been for the past 6-12 months.

**Comment by inklingboy97** [comment]
You should also try to update to cemu 2.0-72

**Comment by JakefSM** [comment]
> You should also try to update to cemu 2.0-72

It's happened in every version since -68.

**Comment by bullghost** [comment]
@JakefSM  yes i i have same issue , after i read your issue i try to  test  this game since i have use version 2.0.68 same as you,
so then the game wont start , just after finish customize the character then goes black screen, not only black but the cemu freeze , need to kill it, i have also using AMD GPU , and under ARCH Linux. then i try to downgrade to 2.0.67 it work without issue, can pass the character customization screen without any issue.

**Comment by JakefSM** [comment]
Resolution: 
I have it running smoothly again in -72. Here's what I did:

1) Complete wipe of GFX drivers and clean install of drivers and driver software. (Must use software)

2) In AMD Software:
Graphic settings select custom and disable ALL enhancements.
No vertical refresh, AA  "use application settings" and "multisampling"
 "use application settings" for all other options

3) IN CEMU General settings:
I changed VSync from "Triple Buffer" to "Match emulated display"

You can go back to step 2 and turn things back on until you find what makes the Hiccup BUT the game plays fine for me so I left it alone. Also, whatever is making it GPU crash seems to need driver repair before CEMU will run it again, hence the driver wipe and fresh install.  Make sure Windows 10 is not trying to push GPU driver updates, they should come from AMD directly.
