### ISSUE TITLE
[Regression] Portal of Power no longer detected to Cemu.

### ISSUE THREAD

**Issue by hYdos** [cemu-project/Cemu#1139]
### Current Behavior

Going into Skylanders: Trapteam USA after pressing A at the title screen shows the game failed to detect the Portal of Power

### Expected Behavior

Going into Skylanders: Trapteam USA after pressing A at the title screen should show the auto save message and then allow me to progress to the rest of the game

### Steps to Reproduce

1. Obtain a copy of Skylanders Trap Team (Or possibly any other skylander game)
2. Try make it past the main menu
3. Fail

### System Info (Optional)

OS:  Windows 10. Issue present on Windows 11 as well
GPU: Nvidia RTX 2070 SUPER

**Comment by Squall-Leonhart** [comment]
Trap team was tested in https://github.com/cemu-project/Cemu/pull/971

**Comment by hYdos** [comment]
Yes, older builds like that one work I am currently using 2.0-49 which works fine

**Comment by hYdos** [comment]
Of course when I go to provide images of the issue, It magically solves itself. My bad.

**Comment by hYdos** [comment]
Just got it to happen again. However, In Skylanders: Swap Force you just cant place a skylander

**Comment by hYdos** [comment]
Old
![image](https://github.com/cemu-project/Cemu/assets/25501603/3dd6ff6b-f5e8-4ea0-aa36-c58d8808b787)

Latest
![image](https://github.com/cemu-project/Cemu/assets/25501603/76ef8335-2c66-43cd-9aa5-6b40dbde0c8c)

It seems to not happen every time.

**Comment by deReeperJosh** [comment]
Swap force is known to have issues, there is a portal compatibility fix gfx pack somewhere

**Comment by hYdos** [comment]
Did more testing, Skylanders Super Chargers, Skylanders Imaginators, and Skylanders Spyros Adventure (Japanese) all crash with a portal plugged in.
