### ISSUE TITLE
Cemu Logo on README.md

### ISSUE THREAD

**Issue by uranuspucksaxophone** [cemu-project/Cemu#114]

**Comment by Exzap** [comment]
We'll add it in the future but this really does not need to be its own issue.

**Comment by Exzap** [comment]
The readme is pretty low on the list of priorities so I'd prefer if you hold off on that for now. Not that I dont appreciate the input but we're already stretched thin with the existing issues and PRs. At least in my personal opinion the readme is ok the way it is right now, it doesn't have to be perfected within the first two weeks.
