### ISSUE TITLE
Build Failing on Arch Derivative CachyOS (vcpkg Install Failure)

### ISSUE THREAD

**Issue by MooMew64** [cemu-project/Cemu#1142]
### Current Behavior

Attempting to build latest Cemu on CachyOS (Arch derivative) is currently failing using current build instructions.

When running: 
`cmake -S . -B build -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/vcpkg  -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++) -G Ninja`

Output is:

```
error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
-- Running vcpkg install - failed
CMake Error at dependencies/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  /home/moomew/SC.projects/Cemu/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:146 (include)
  CMakeLists.txt:36 (project)


-- Configuring incomplete, errors occurred!
```

Any ideas what could be causing this? All build dependencies are installed and running.

### Expected Behavior

Build Cemu

### Steps to Reproduce

Attempt to build Cemu following Arch build instructions.

**Comment by qurious-pixel** [comment]
Missing logs and the rest of the error. 
See Build guide: [Arch Build](https://github.com/cemu-project/Cemu/blob/main/BUILD.md#for-arch-and-derivatives).

Also try these settings:
```
git clone --recursive https://github.com/cemu-project/Cemu
cd Cemu
cmake -S . -B build -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Ninja -DCMAKE_MAKE_PROGRAM=ninja
cmake --build build
```

For troubleshooting go to Discord: [Discord](https://discord.gg/5psYsup)

**Comment by SolarNyan** [comment]
Huh, it looks like builds succeed when disabling VCPKG_MANIFEST_INSTALL in CMake's GUI program. Odd.

I was also missing Wayland protocols, installing that plus disabling the aforementioned setting above seems to allow the CMake file to properly generate and vcpkg starts behaving as expected.
