### ISSUE TITLE
Changelog link in 'Cemu update' window not accurate

### ISSUE THREAD

**Issue by stormbringer83** [cemu-project/Cemu#1144]
### Current Behavior

Changelog link leads to https://cemu.info/ 

### Expected Behavior

Changelog link leads to https://cemu.info/changelog.html

### Steps to Reproduce

1. Launch an older version of Cemu.
3. Click 'Yes' in 'Update notification' window.
4. Click 'Changelog' link in 'Cemu Update' window.
5. The default browser opens https://cemu.info/.

### System Info (Optional)

OS: OS Name	Microsoft Windows 11 Pro Version	10.0.22631 Build 22631
GPU: n/a

**Comment by Exzap** [comment]
I changed it to link to `https://cemu.info/changelog.html`
