### ISSUE TITLE
macOS releases from 2.0-65 may use the wrong UI language

### ISSUE THREAD

**Issue by JaimieVandenbergh** [cemu-project/Cemu#1151]
### Current Behavior

In a new install (ie no existing settings.xml), since 2.0-65 Cemu will first-launch for me in French, despite my macOS system primary language being English(UK). 

Once passing the Getting Started panels, the UI is still in the wrong language.

### Expected Behavior

System default language to be used.

### Steps to Reproduce

Clean out any existing settings.xml, run a recent Cemu. The Getting started screen may appear in the wrong language. 

The spotter of this bug had theirs come up in Chinese. Mine in French. Their macOS Settings/General/Language was set to English (Australian) primary, then English, then Chinese. 
Mine is English (UK primary), then French.

In settings.xml, <language> is initialised to 0 which should get the system default, but instead seems to fall through to... the first non-English entry? Weird.

They were running Ventura 13.6.5, I'm on Sonoma 14.5beta

I tested from 2.0-59 upwards, clearing the Application Support/Cemu folder each time. Results were
59-61 - comes up in English
62-64 - broken on macOS, crashing on startup, no settings.xml created
65-73 - comes up in other-language.
So the break came somewhere in 62-65 inclusive.

For all 59-73, the newly created settings.xml <language> is initialising to 0 correctly.

Setting <language> manually to 1 sets US English for the UI.

Thread in Discord #macos channel: https://discord.com/channels/286429969104764928/1043595946719711283/1225039779955998835

**Comment by JaimieVandenbergh** [comment]
Rearranging my macOS languages panel and language=0 falls through to German now, so it is reading the list but not seeing the actual primary/default language.
<img width="719" alt="image" src="https://github.com/cemu-project/Cemu/assets/82263742/e76366f3-9cc1-4b05-bc2b-0fd60911dbc3">

**Comment by Behodar** [comment]
This was also reported as #1091. There's been no movement on it as of yet (i.e. 2.0-78 still exhibits the issue).
