### ISSUE TITLE
Game & Wario Still Crashing

### ISSUE THREAD

**Issue by yoshi200214** [cemu-project/Cemu#1153]
### Current Behavior

Hello 
Game & Wario is still crashing when I select the minigame even in the last version
Please fix this problem

### Expected Behavior

Game & Wario not crashing when select a minigame

### Steps to Reproduce

1. start the game
2. select a file
3. select a minigame

### System Info (Optional)

OS: Windows 11
GPU: NVIDIA GeForce RTX 3060Ti

### Logs (Optional)

[log.txt](https://github.com/cemu-project/Cemu/files/14874600/log.txt)

**Comment by Exzap** [comment]
Closing this because:
- You are using a pirated game
- Game compatibility reports should be done on the [compatibility wiki](https://wiki.cemu.info/wiki/Game_%26_Wario) anyway
- Its not a clean report because you use non-standard settings like a bunch of rpls in cafeLibs/ folder
