### ISSUE TITLE
Libreto Core?

### ISSUE THREAD

**Issue by thanone2** [cemu-project/Cemu#1160]
### Your suggestion

I am suggesting that a libreto core be made for Retroarch, then I believe that there would be an easier time porting the emulator to other platforms, because you would only be compiling once per update, and it would be unlikely for problems to occur because the Retroarch team would be the ones to port their own app to other platforms.

**Comment by cabrerahector** [comment]
Someone already asked about this in #323, the gist of it is "this is a low priority for us, but anyone else is welcome to step in and create a PR to make it happen."

**Comment by Exzap** [comment]
This is kinda an obvious enough suggestion that it doesn't need tracking unless someone is actually working on it. As of now it's very far outside the scope for the current team so I will be closing this
Also your assessment that it will make porting easier isn't correct. It can help a little bit in some regard but the actual blockers wouldn't be resolved. Plus the mountain of work it would require to turn Cemu into a libretro core would offset any benefit.

**Comment by thanone2** [comment]
ok, sorry, but thanks for the explanation!

**Comment by gouchi** [comment]
Hi,

If needed, some promising work has been done in this [repo](https://github.com/danprice142/Cemu-Libretro/tree/libretro).

Thank you.
