### ISSUE TITLE
Enter a title for the bug report here

### ISSUE THREAD

**Issue by stylex122** [cemu-project/Cemu#1169]
### Current Behavior

Everything worked before the update, played as usual in BoTW, no problems with graphics. I played with fps 45-50, which is not bad for my pc.

### Expected Behavior

After updating to 2.0-77 version went to Zelda and after half a minute the image turned into a mess with a bunch of purple artifacts( And if you go back to windowed mode, everything is okay. The problem is exactly in full screen mode.

### Steps to Reproduce

Just went as usual and loaded the game. Well, if detailed, I was standing at the shrine and tried to light a fire. But the picture sharply deteriorated already when I tried to select in the inventory wood and flint. I didn't get to the fire. However, when I pressed Esc, i.e. went into window mode, the picture became normal. Then if you expand to the full screen, after the same 20-30 seconds, everything repeats.

### System Info (Optional)

OS: Windows 11
GPU: gt 1030

### Logs (Optional)

[log.txt](https://github.com/cemu-project/Cemu/files/14948859/log.txt)

**Comment by Squall-Leonhart** [comment]
test with triple buffering or experimental:match display buffering.

**Comment by stylex122** [comment]
Hmm, well there's only the inventory and it looks a bit off. But it's still similar. I'll try playing with the settings.
"Though your graphics packs settings seem excessive for that 2GB graphics card." I can only say that before that I played for 5 days and everything worked fine. Not even a single crash, yes, fps is not 60, but quite playable.

**Comment by stylex122** [comment]
Thank you so much, turned on triple buffering and everything is back to normal. At least I had time to make a fire and browse a bit in the inventory. If I'm not mistaken, I had it turned on before the update and after the update, apparently the setting got messed up. 
By the way, is there any way to set the resolution 1366x768? In the settings of graphics packages it is not there, and 1280x720 looks bad. So I have to sacrifice fps and play in 1600x900.
