### ISSUE TITLE
Paper Mario Color Splash crashing on entering Mondo Woods

### ISSUE THREAD

**Issue by GoodGameInfinity** [cemu-project/Cemu#1174]
### Current Behavior

When I enter Mondo Woods (yes, specifically Mondo Woods) the console/emulator instantly crashes

https://github.com/cemu-project/Cemu/assets/81247214/82da7ae2-2844-47df-9aaa-c2394a15f16c

### Expected Behavior

For the level "Mondo Woods" to actually load and be playable

### Steps to Reproduce

1. Get to the Mondo Woods level
2. Attempt to enter the level

### System Info (Optional)

OS: Archlinux x86_64 Zen kernel 6.5.8
CPU: Intel i7-10700K
GPU: Nvidia Geforce RTX 4070 Ti 

And also wanted to add that I know my Cemu version is behind by one experimental release, but it would be problematic for me to update Cemu to the latest version right now. When I'll update I'll comment if this micro-update (2.0-78) fixed my issue.

### Emulation Settings (Optional)

I used Single-core recompiler for the best performance, but when I tried to specifically mess around with settings to fix this issue nothing helped. Including disabling all graphics packs

### Logs (Optional)

[log.txt](https://github.com/cemu-project/Cemu/files/14968827/log.txt)

**Comment by GoodGameInfinity** [comment]
I think that it's also relevant to say that I tried both Wayland and Xorg, updating Nvidia proprietary drivers, updating my system in general, etc.
Basically the only thing I didn't try is to remove/replace my save file, which I'll try tomorrow

**Comment by Exzap** [comment]
`Failed to read FST block` in your log indicates that your game files are corrupted. Maybe try dumping new files?

**Comment by GoodGameInfinity** [comment]
> `Failed to read FST block` in your log indicates that your game files are corrupted. Maybe try dumping new files?

It worked! Thanks for help. I'm going to close the issue
