### ISSUE TITLE
Crash Zelda BoTW

### ISSUE THREAD

**Issue by stylex122** [cemu-project/Cemu#1177]
### Current Behavior

At the Hatena Institute, the first purchase of photographs for the Hyrule atlas takes place. I tried to buy the lowest category in the list, where ores and chest. Two times and two crashes. Happens in the same place when the atlas and new photos appear in it.

### Expected Behavior

that there will be no crash

### Steps to Reproduce

Walked up to Simin, told him I needed to buy a photo. I bought a photo, show me the atlas and that new photos opened and the game for a few seconds freezes and the emulator crashes

### System Info (Optional)

OS: Windows 11
GPU: gt 1030
CPU: Ryzen 5 5500

### Logs (Optional)

[log.txt](https://github.com/cemu-project/Cemu/files/14988350/log.txt)

**Comment by stylex122** [comment]
There was also 1 time yesterday in Haten that the textures were acting weird. Restarting the emulator helped. Also sometimes flickering textures began to appear, but it is not critical. Before Haten did not notice such a thing.

**Comment by Exzap** [comment]
I think the 9999StampsLimit graphics pack causes this. Try with it disabled

**Comment by stylex122** [comment]
Yes, thank you, it worked. But without unlimited tags on the map, it's not cool(
