### ISSUE TITLE
Allow Download Manager to get updates etc while using a Pretendo account

### ISSUE THREAD

**Issue by JaimieVandenbergh** [cemu-project/Cemu#1179]
### Your suggestion

With the Nintendo servers being shut down, people are moving over to using a Pretendo PNID account instead. But this breaks their ability to download updates and their eshop games from Nintendo's servers using Download Manager.
A way to be able to play using a PNID but also have an NNID account or other active connection for Download Manager would be extremely useful now.
Perhaps this can be done already with alternate accounts inside cemu, but the Account UI doesn't handle that well.
Also part of this request is documentation for people to set up both accounts as needed; it's likely that people will 'upgrade' to PNID on the Wii U and then Cemu and just lose their NNID online files.

**Comment by inklingboy97** [comment]
That would be really hard to do since pretendo connects to its own servers. This means Nintendo servers that let you download updates and digital copies of game are unreachable.

**Comment by inklingboy97** [comment]
Also because you would need to count two accounts as one to do so.

**Comment by Exzap** [comment]
Solved by efbbb817fe1cbe09ee132344b44a0f61f8b8ac96
In order to use the download manager only a valid OTP+SEEPROM is required as purchases are bound to the console and not individual accounts. So someone using a Pretendo account will still be able to use the download manager going forward

**Comment by inklingboy97** [comment]
Thanks for the clarification
