### ISSUE TITLE
Cemu crashes when loading a game with 'Separate GamePad view' option ticked

### ISSUE THREAD

**Issue by aqua-md** [cemu-project/Cemu#1182]
### Current Behavior

Cemu crashes when loading a game with the 'Separate GamePad view' option ticked. It doesn't even load cached shaders.

### Expected Behavior

I expect Cemu to load the game correctly without crashing even if the 'Separate GamePad view' option is ticked. 

### Steps to Reproduce

Open Cemu
Click on Options | Separate GamePad view
Open a game/app
Cemu should crash

### System Info (Optional)

OS: Windows 10 22H2
GPU: Radeon RX 6800

### Logs (Optional)

[log.txt](https://github.com/cemu-project/Cemu/files/15049431/log.txt)

**Comment by Squall-Leonhart** [comment]
send the log with the crash info in it, this one looks like its from a fresh start.

**Comment by Exzap** [comment]
Closing this since op hasn't responded and there is not enough info available to diagnose this
