### ISSUE TITLE
dGPU Not Appearing In List - Flatpak

### ISSUE THREAD

**Issue by Revali25** [cemu-project/Cemu#1183]
### Current Behavior

I have the flatpak version of Cemu, but my RTX 3060 is not showing up as an option in the list. I've edited the permissions to allow access, but no luck so far. 

### Expected Behavior

Ideally, being able to use my GPU.

### Steps to Reproduce

Launch the flatpak version, try to change GPU to the right one in the graphics settings.

### System Info (Optional)

OS: Fedora 39 KDE - Wayland and X11 both
GPU: NVIDIA RTX 3060

**Comment by Squall-Leonhart** [comment]
Prime isn't supported under X11 or Wayland, only XWayland, Assuming you have a hybrid notebook (requires Prime) Xwayland is necessary.
