### ISSUE TITLE
AppImage Not Launching - Version 2.0.78 and 2.0.79

### ISSUE THREAD

**Issue by Revali25** [cemu-project/Cemu#1184]
### Current Behavior

When double clicking the file, nothing happens. When trying to run it from the terminal, it gives some errors, attached in the logs form. 

### Expected Behavior

The application to open.

### Steps to Reproduce

Download the appimage, try to run the file.

### System Info (Optional)

OS: Fedora 39 KDE - Wayland
GPU: NVIDIA RTX 3060

### Logs (Optional)

/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
Squashfs image uses (null) compression, this version supports only xz, zlib.
ERROR: appimage_shall_not_be_integrated : sqfs_open_image error: /home/spice/Applications/Cemu-2.0-78-x86_64_0c7fbd284e0df830bf9b6c7346fc2492.AppImage
AppImageLauncher error: appimage_shall_not_be_integrated() failed (returned -1)
Squashfs image uses (null) compression, this version supports only xz, zlib.
ERROR: appimage_is_terminal_app : sqfs_open_image error: /home/spice/Applications/Cemu-2.0-78-x86_64_0c7fbd284e0df830bf9b6c7346fc2492.AppImage
AppImageLauncher error: appimage_is_terminal_app() failed (returned -1)
execv error: No such file or directory

**Comment by Revali25** [comment]
Tested with the build from yesterday, the AppImage still doesn't launch

**Comment by qurious-pixel** [comment]
AppImageLauncher is preventing Cemu from loading. See: https://github.com/cemu-project/Cemu/issues/653

**Comment by Revali25** [comment]
Heard, it works fine now 👍

**Comment by Revali25** [comment]
Closing
