### ISSUE TITLE
Twilight Princess HD: Maps only loading partway on MacOS

### ISSUE THREAD

**Issue by MegalonVII** [cemu-project/Cemu#1192]
### Current Behavior

Maps are bugged out. Can only see top right half diagonally for any given map.

![Screenshot 2024-05-02 at 3 06 02 AM](https://github.com/cemu-project/Cemu/assets/125611764/94dd5193-3cb6-48b7-947f-a866dbd4dfb7)
![Screenshot 2024-05-02 at 3 06 11 AM](https://github.com/cemu-project/Cemu/assets/125611764/7758f49a-c924-4814-9856-5b3b5e31eae9)

### Expected Behavior

Minimap and map should load properly and fully.

### Steps to Reproduce

Press Right and/or Up on D-pad to open (Mini) map

### System Info (Optional)

OS: MacOS 13.4
GPU: M2 GPU

### Emulation Settings (Optional)

Using Vulkan.

**Comment by JaimieVandenbergh** [comment]
This is due to the external Molten-VK library that translates Vulkan calls to macOS' Metal API not yet supporting the required rendering type. Many other games are similarly affected on Mac.
