### ISSUE TITLE
Sonic & all-stars racing transformed crush in STARRY SPEEDWAY

### ISSUE THREAD

**Issue by Kiminari-Suzuki** [cemu-project/Cemu#1204]
### Current Behavior

![スクリーンショット (496)](https://github.com/cemu-project/Cemu/assets/95355632/e9f0676b-b8a3-47c0-883b-478aff3b2bac)
Game crush in this stage.

### Expected Behavior

Not crush.

### Steps to Reproduce

Select STARRY SPEEDWAY.

### System Info (Optional)

OS: 
GPU:

**Comment by inklingboy97** [comment]
can you send a log file, there isn't enough information to safely assume what causes this issue

**Comment by Kiminari-Suzuki** [comment]
[log.txt](https://github.com/cemu-project/Cemu/files/15365681/log.txt)
Hi. Is this OK?
It happens in "Single Race - Galactic Parade" mode also. only Vulkan GPU API. (with Open GL, it doesn't crush. but graphics are strange in all stages)

**Comment by Exzap** [comment]
Fixed in 2.0-93
