### ISSUE TITLE
Enter a title for the bug report here

### ISSUE THREAD

**Issue by sonich2401** [cemu-project/Cemu#1205]
### Current Behavior

When using my save file from my Wii U, the game crashes after I see the splatoon loading screen for a few seconds. If I delete the save file and create a new one, the program does not crash.

### Expected Behavior

The program to load my save file and not crash

### Steps to Reproduce

1. Download the latest Linux appimage
2. Place my Wii U save file in the MLC folder. 
3. Turn on Splatoon (USA)

OR

1. Download the latest commit. Build on Linux using gcc (both debug and release).
2. Place my Wii U save file in the MLC folder. 
3. Turn on Splatoon (USA)

### System Info (Optional)

OS: Linux x64 - Kubuntu 22.04.4 LTS x86_64 - 6.5.0-28-generic 
GPU: AMD ATI Radeon RX 470

### Logs (Optional)

Logs taken from the debug version of CEMU

[log.txt](https://github.com/cemu-project/Cemu/files/15358544/log.txt)

![Screenshot_2024-05-17_15-03-05](https://github.com/cemu-project/Cemu/assets/34013705/8824f9d2-6eb9-49ea-b2ec-7ed7bda31afb)
![Screenshot_2024-05-17_15-04-51](https://github.com/cemu-project/Cemu/assets/34013705/8ff9d12f-cf78-480e-bb90-63efb4b17e3c)
![Screenshot_2024-05-17_15-04-16](https://github.com/cemu-project/Cemu/assets/34013705/04e42458-8aab-44ae-9ffb-c413a7375636)

**Comment by Exzap** [comment]
You are using a broken & pirated copy of the game.

**Comment by sonich2401** [comment]
> You are using a broken & pirated copy of the game.

![image](https://github.com/cemu-project/Cemu/assets/34013705/b8e395fe-fb1f-4950-9e7d-f6ad6f63ae65)

Pretty bold of you to assume I pirated the game

**Comment by sonich2401** [comment]
I am able to play the game just fine on real hardware using the same save file and the same disk

**Comment by Squall-Leonhart** [comment]
dump the missing update data then.
