### ISSUE TITLE
Wii Fit U Is Unplayable

### ISSUE THREAD

**Issue by ChristopherEccleston2024** [cemu-project/Cemu#1206]
### Current Behavior

The game crashes after you create a save file

### Expected Behavior

Game should not crash before you create a save file

### Steps to Reproduce

Nothing To Say
1. Open Wii Fit U
2. Create Save File
3. Save File Crash (That Is All)

### System Info (Optional)

OS: Windows 11 Home Single Language
GPU: NVIDIA GeForce RTX 4090
CPU: Intel Core i7 12700H 12th Gen 14 Cores

### Logs (Optional)

[log.txt](https://github.com/cemu-project/Cemu/files/15360324/log.txt)

**Comment by ChristopherEccleston2024** [comment]
Also Add Wii Balance Board Support

**Comment by ChristopherEccleston2024** [comment]
Please

**Comment by ChristopherEccleston2024** [comment]
Like Dolphin Emulator Does with Real Wii Balance Board Support

**Comment by Exzap** [comment]
This is already documented on the [compatibility wiki](https://wiki.cemu.info/wiki/Wii_Fit_U). No need to track it here too
