### ISSUE TITLE
MSX Games do not start

### ISSUE THREAD

**Issue by buggii** [cemu-project/Cemu#1208]
### Current Behavior

When a msx game is run just the splash screen of the Virtual Console title is shown then the emulator is stuck in "loading..." with huge load on system.

### Expected Behavior

The game should start with it's main menu.

### Steps to Reproduce

Just try to run any MSX game (tested in particular with NEMESIS3 THE EVE OF DESTRUCTION).

### System Info (Optional)

OS: Win10/Win11
GPU: Nvidia RTX 4070

**Comment by Exzap** [comment]
Fixed in d4c2c3d2098616b3596b743f33fcc37629282ec0
