### ISSUE TITLE
Linux: Cemu Crash with error signal 11 running BoTW

### ISSUE THREAD

**Issue by Clueninja** [cemu-project/Cemu#1216]
### Current Behavior

When running Cemu using the latest  Flatpak, AppImage or natively compiled, running BoTW causes Cemu to crash with error signal 11.
If a shader cache is loaded then it will recompile the shaders, hang for a second on the loading screen and then crash.
I tested with and without --nosocket=wayland, using x11, using OpenGL over Vulkan.

### Expected Behavior

Running BoTW as expected. Windwaker and other games run fine.

### Steps to Reproduce

run Cemu, click to run BoTW

### System Info (Optional)

OS: Endevour OS
GPU: Tested on 
Hybrid graphics: Intel UHD + Quadro P600
dGPU only: Quadro P600
CPU:  i7-9750H
Windowing System: Wayland
Gnome Version: 46
Kernel Version: Linux 6.9.1-arch1-1

### Logs (Optional)

Flatpak:
flatpak run info.cemu.Cemu
(Cemu_relwithdebinfo:23): Gtk-CRITICAL **: 19:29:24.139: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Cemu_relwithdebinfo:23): Gtk-WARNING **: 19:29:27.588: gtk_disable_setlocale() must be called before gtk_init()
Segmentation fault!
Error: signal 11:
Cemu_relwithdebinfo(+0x206b7a) [0x615f65aa4b7a]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x3ee80) [0x764ea3c51e80]
Cemu_relwithdebinfo(+0x206b7a) [0x615f65aa4b7a]
Cemu_relwithdebinfo(+0x2f149a) [0x615f65b8f49a]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x568a0) [0x764ea3c698a0]

Stacktrace and additional info written to:
/home/samb/.var/app/info.cemu.Cemu/data/Cemu/log.txt

https://pastebin.com/ZYHF10zZ

AppImage:
Gtk-Message: 19:37:38.988: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:37:38.989: Failed to load module "canberra-gtk-module"

(AppRun.wrapped:27210): Gtk-CRITICAL **: 19:37:50.628: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Segmentation fault!
Error: signal 11:
/tmp/.mount_Cemu-2FafjFf/AppRun.wrapped(PPCInterpreterContainer<PPCItpCafeOSUsermode>::PPCInterpreter_LWZ(PPCInterpreter_t*, unsigned int)+0x26) [0x5e3d6b1981e6]
/usr/lib/libc.so.6(+0x3cae0) [0x763fe85c7ae0]
/tmp/.mount_Cemu-2FafjFf/AppRun.wrapped(PPCInterpreterContainer<PPCItpCafeOSUsermode>::PPCInterpreter_LWZ(PPCInterpreter_t*, unsigned int)+0x26) [0x5e3d6b1981e6]
/tmp/.mount_Cemu-2FafjFf/AppRun.wrapped(coreinit::__OSFiberThreadEntry(void*)+0x368) [0x5e3d6b3359e8]
/usr/lib/libc.so.6(+0x56be0) [0x763fe85e1be0]

Stacktrace and additional info written to:
/home/samb/.local/share/Cemu/log.txt

https://pastebin.com/kMJeaYjN

**Comment by Exzap** [comment]
From the log it looks like the game crashes when trying to load sound files. So most likely you got corrupted or missing game files

**Comment by Clueninja** [comment]
> From the log it looks like the game crashes when trying to load sound files. So most likely you got corrupted or missing game files

Thanks! I'll have a look to see what might have caused that

**Comment by Clueninja** [comment]
> From the log it looks like the game crashes when trying to load sound files. So most likely you got corrupted or missing game file
that fixed it!! thank you so much for helping me
