### ISSUE TITLE
With the latest version, Skylanders: SuperChargers and Skylanders: Imaginators are crashing on main menu

### ISSUE THREAD

**Issue by ghost** [cemu-project/Cemu#1218]
I have an older version of Cemu (Cemu 2.0-41-Experimental [Jul 17 2023]) that also supports the Portal of Power emulation and every game works there.

However, i've tried using a newer version from here : https://github.com/cemu-project/Cemu/actions/runs/9126066603 and observed that Skylanders: SuperChargers and Skylanders: Imaginators are crashing on main menu. The rest of the older games are fine. Only those two have this problem.

Then i loaded the official [Cemu release from the main branch](https://github.com/cemu-project/Cemu) and the behavior was the same (SuperChargers and Imaginators are crashing)

So i reckon you did some changes on the main version after the build from Jul 17 2023 i have and then all other branches that are using those changes (as the one from [deReeperJosh](https://github.com/deReeperJosh/Cemu/tree/emulatedusbdevices)) are also inheriting this problem.

@deReeperJosh FYI

**Comment by t3hsuppli3r** [comment]
I did some digging.

So it seems right after the intro video, there will be a check from the games (SuperCharger and Imaginator) if the Portal of Power is connected.

Using Cemu up to version [Cemu 2.0-61 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-61) will just show "Portal of Power disconnected" here as it should.

However, after version [Cemu 2.0-62 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-62) onward is where this crashing starts to occur.

**Comment by Squall-Leonhart** [comment]
Is this the libfmt crash? i'm not sure if the fix for that is in master yet.

**Comment by Squall-Leonhart** [comment]
oh, it was back in march with https://github.com/cemu-project/Cemu/pull/1106

**Comment by deReeperJosh** [comment]
The description of the issue should be changed, the experimental version from the PR is just an experimental version so any issues relating to that should be raised on the PR itself, but if the issue with a real portal doesn't exist on version 61 of main Cemu and does with a real portal on version 62 then that is what the issue should mention :)

**Comment by Exzap** [comment]
This issue is continued in #1321
