### ISSUE TITLE
Commit 065fb7e freeze Xenoblade Chronicles X at start

### ISSUE THREAD

**Issue by shadowwa** [cemu-project/Cemu#1221]
### Current Behavior

- Launch Xenoblade Chronicles X [USA] 00050000101c4d00
- see the compiling cached shader message
- See the Vulkan pipeline loading
- See the "progress bar" moving on bottom right of the screen
- See the "progress bar" stopping and stay at this stage

### Expected Behavior

- Launch Xenoblade Chronicles X [USA] 00050000101c4d00
- see the compiling cached shader message
- See the Vulkan pipeline loading
- See the "progress bar" moving on bottom right of the screen
- see the _Connecting. Please wait_ message
- pass the offline mode notice and play the game

### Steps to Reproduce

Compile Cemu with the commit 065fb7eb58855ec2d8c009f2dfabc3e815b91915
The version v2.0-82 worked fine.
If I revert the commit, versions v2.0-83 and v2.0-84 also work fine.

### System Info (Optional)

OS: Mageia Cauldron
GPU: Quadro K2200

**Comment by bloomingchad** [comment]
same happens on cemu v2.0-83, 
OS elementaryOS 7 (linux v6.5)
GPU Intel Iris Xe 80EU

But the Expected behaviour happens for windows 11 with the same hardware

**Comment by Exzap** [comment]
Fixed by 1ee9d5c78c1c5216c92764977363fad38b0d4f0b

**Comment by shadowwa** [comment]
Thanks!
