### ISSUE TITLE
GPU listings are repeated

### ISSUE THREAD

**Issue by JamShady** [cemu-project/Cemu#1225]
### Current Behavior

My laptop has a GTX 1080 internally. I recently acquired an eGPU, and use an RTX 2070S for this. As far as my PC is concerned, everything is normal and works nicely with the two GPUs.

In CEMU, when I don't have the eGPU connected (i.e. normal), the GPU list (under 'General Settings' -> 'Graphics Device') just shows the option for the GTX 1080, which is correct.

However, when I have the eGPU connected, the listing shows:
- RTX 2070S
- RTX 2070S
- GTX 1080
- GTX 1080

### Expected Behavior

Each distinct GPU should only be listed once. It seems that each GPU is being listed in the quantity of however many GPUs there are.

### Steps to Reproduce

Use multiple GPUs?

### System Info (Optional)

OS: 
GPU:

**Comment by JamShady** [comment]
![image](https://github.com/cemu-project/Cemu/assets/167395/169994e0-0ee4-46ee-a306-e33d2c666ce6)

**Comment by Squall-Leonhart** [comment]
This occurs because the 2 devices are not running from the same driver, so each instance of the driver has its own instance of the loader parsing the available devices.

Install the latest driver so both are on the same one.

**Comment by JamShady** [comment]
I'm not sure what you mean? I'm using GeForce Experience which installs the drivers automatically, and it says they're up-to-date. In fact, when it detected the eGPU, it updated the driver itself and added a new feature so I could see what each GPU was running.

I can't update the drivers for them separately?? Not as far as I know anyway?

**Comment by Exzap** [comment]
Closing this since the source of the problem lies outside of Cemu. Cemu just lists the devices it gets from the system.
If you still want to track this down I recommend posting it to our discord which is generally where most troubleshooting happens.
