### ISSUE TITLE
I can't delete Cemu or the emulator folder

### ISSUE THREAD

**Issue by Barnitz** [cemu-project/Cemu#1230]
### Current Behavior

I can't delete Cemu or the emulator folder

### Expected Behavior

I can't delete Cemu or the emulator folder

### Steps to Reproduce

I can't delete Cemu or the emulator folder

### System Info (Optional)

OS: 
GPU:

**Comment by Exzap** [comment]
Discord or the subreddit are a better place for troubleshooting. Github is only for confirmed bugs. But to answer your question you can try this:
Restart your PC and try deleting the Cemu folder again.
If that does not work, rename the folder, then restart and then delete it.
If that also does not work then you have to give us more info, like what kind of error you get.
