### ISSUE TITLE
Latency regression in v2.0-77

### ISSUE THREAD

**Issue by Soreepeong** [cemu-project/Cemu#1239]
### Current Behavior

From v2.0-77, Sonic Boom: Rise of Lyric is late to respond to jump command.
![bb](https://github.com/cemu-project/Cemu/assets/3614868/67e9b035-a606-44ba-8408-da0d79bdb179)

### Expected Behavior

In v2.0-75 and before, the game responds immediately to jump command.
![aa](https://github.com/cemu-project/Cemu/assets/3614868/f03da494-ffcf-4af2-9e86-ec06956dad43)

### Steps to Reproduce

Use 84cad8b280afa9db7637ec1fd125d1b59970b548 or any commit after that, and use Graphic Pack "Uncapped Framerate" with 60fps option.

Reverting that commit in particular from the latest commit (v2.0-86) will make the problem disappear.

### System Info (Optional)

OS: Windows 11 22631.3737
GPU: RTX 2070 Super

### Emulation Settings (Optional)

Enabled Graphic Packs:
* "Uncapped Framerate" (60fps)
* "Graphics" (TV resolution=1440p)

**Comment by goeiecool9999** [comment]
Could you try setting "Maximum pre-rendered frames" in the NVIDIA control panel to a lower value for cemu and see if that fixes the issue?

**Comment by Soreepeong** [comment]
Driver version 555.99 DCH; I'm not seeing that option from Manage 3D settings.

![image](https://github.com/cemu-project/Cemu/assets/3614868/b05849c1-3ef3-426a-a088-9f2c1dc291ab)

Closest thing is "Virtual Reality pre-rendered frames", which seemingly is 1 by default which is the minimum accepted value.

**Comment by goeiecool9999** [comment]
Aha okay. It's been a while since I've used an card. Although I read somewhere that they renamed it to or replaced it with low latency mode. Try messing with that setting. Also, what VSync setting are you using?

**Comment by Soreepeong** [comment]
Using v2.0-86: Changing "Low Latency Mode" to "Ultra" did not result in any difference.

* On RTX 2070 Super, only "Double Buffering" made input latency consistently high, both in 1440p and 900p configuration from Graphic Pack.
* On Intel UHD 770, the game played fine in any VSync mode on 900p. It consistently stuttered on 1440p.
  * RTX2070S and UHD770 are on the same PC; display is only displayed through RTX2070S.
* On Adreno on Snapdragon Elite, the game played fine in any VSync mode in 900p. It played smoothly on 1440p, but input latency kept increasing as time went, seemingly without upper limits.
  * Using v2.0-75 does not change this.

**Comment by Squall-Leonhart** [comment]
this is the same commit that reintroduced the flashing equipment subscreen in BOTW

**Comment by goeiecool9999** [comment]
Hi, if it's not too much hassle, could you grab the CI build for #1290 and tell me if the issues persist?

**Comment by Soreepeong** [comment]
[log.txt](https://github.com/user-attachments/files/16597207/log.txt)

Sadly it crashes while loading the game. Tried removing `shaderCache` and `dump` folders just in case, but it's the same. It ran once in the sixth attempt, but it would crash again after.

When it did run though, the issue was fixed; no delays I could find.

From Event Viewer/Windows Logs/Application, there are two faulting offsets: 0x10c8f9 and 0x675284.

**Comment by goeiecool9999** [comment]
Apparently the crashing DLL, graphics-hook64.dll, is a part of OBS. Did you have it running and if so can you check if it everything works without OBS and if it also happens on the latest cemu release?

**Comment by Soreepeong** [comment]
* The PR: Without OBS running, it started fine every run attempts (10 times).
* v2.0-92: With OBS running, it crashes.
* v2.0-86, 80, 75: ditto.

Since I did use OBS to record gameplays in the past, I'd say that this is a bug introduced on OBS' side. Seems that the PR works fine without OBS running!

**Comment by Squall-Leonhart** [comment]
OBS is not compatible with overlay software from asus, evga, msi(rtss), etc as they use a low effort implementation of detours which doesn't safely work with custom hooking methods.

RTSS is the only case where a user-settable compatibility method is available in the options that can be set globally or per game.

**Comment by Julinkk** [comment]
I have exactly the same problem, I compared using basic installations, applied exactly the same settings and the problem is on all versions from 2.0-77 up to 2.1
