### ISSUE TITLE
Cemu/XCX: Save game persistence issue leading to crashes shortly after load

### ISSUE THREAD

**Issue by MacreadyX** [cemu-project/Cemu#1245]
### Current Behavior

See https://bugs.cemu.info/issues/693

### Expected Behavior

No crashing

### Steps to Reproduce

Linked issue includes attached save game with steps to repro

### System Info (Optional)

OS: Win11
GPU: NVIDIA RTX 4080

**Comment by Exzap** [comment]
I tried replicating this a few times but I can't get it to crash. Can you upload log.txt after a crash?

**Comment by MacreadyX** [comment]
Hi,

Thanks for looking at this so quickly.  And thank you for this amazing emulator.

I just restored the save and crashed the game in Armory Alley.  Log.txt attached.

Interesting that you cannot reproduce the crash.  There must be some aspect of my setup that makes me a problem child.  Since first posting this issue, I've spent more time testing my theory, and I'm even more convinced that it's accurate.  I played for about four hours tonight.  At the start I immediately ran into trouble (this was in Primordia just crossing into Noctilum) and was having fairly repeatable crashes.  All I had to do to resolve was fast travel back to town and then run back and the problems were gone.  After that, hours of perfect stability.  The crashing is somehow connected to transient data in the world state immediately surrounding me upon first loading in.  It doesn't always happen, but when it does, that's pretty much how it plays out.

Anyway, thanks again for your efforts.  If you need anything more from me or want me to test something, let me know.

[log.txt](https://github.com/user-attachments/files/16038701/log.txt)

**Comment by Exzap** [comment]
You got a lot of mods enabled so let's narrow down if this is a Cemu core problem or a mod problem.

1. Disable all mods and graphic packs
2. Attempt to replicate the crash without any mods enabled. If the crash still occurs, it’s a Cemu issue. Otherwise continue steps 4-6
4. Re-enable your mods and graphic packs one by one
5. Test the game after enabling each mod to see if the crash occurs
6. Keep doing this until you isolated the mod that causes the instability

**Comment by MacreadyX** [comment]
Yeah, sorry.  That would have been a sensible thing to try on my own, eh?

It's FPS++, which makes me want to cry.  But although I can replicate the crash consistently at my desired cap of 120fps, it doesn't seem to happen at the mod's 60fps default (at least I was 3 for 3 in clean passes through Armory Alley).  Well, 60fps is doable.

Two final questions, if you've the time:

1) What's the appropriate forum for reporting a graphics pack issue?

2) This glitch absolutely is, in my testing, tied to loading a saved game.  Although it's not a baseline Cemu issue, I'm still interested in your opinion as a technologist.  How does a FPS mod develop sensitivity to recently-loaded-world-state?

**Comment by Exzap** [comment]
> 1. What's the appropriate forum for reporting a graphics pack issue?

You can report it [here](https://github.com/cemu-project/cemu_graphic_packs/issues).

> 2. This glitch absolutely is, in my testing, tied to loading a saved game. Although it's not a baseline Cemu issue, I'm still interested in your opinion as a technologist. How does a FPS mod develop sensitivity to recently-loaded-world-state?

Quite frankly, it doesn't make much sense to me that the save file would be partially corrupted causing the game to crash more. I think what's more likely is that the crash has non-tangible and non-intuitive conditions and loading from a save gives you the same baseline every time. Games do have a lot of non-visible internal state that will affect things. Combined with the human tendency to see patterns in random noise one has to be careful to not jump to conclusions based on a small sample size.

It would be different if it crashed during loading or there was some other evidence of direct correlation. But loading a save and then crashing x seconds or minutes later? Probably not connected

**Comment by MacreadyX** [comment]
I'll report it there now, thanks.
