### ISSUE TITLE
Randomly crashing with "Unrecoverable error in Vulkan renderer" in Rast Racing NEO

### ISSUE THREAD

**Issue by DavidBeh** [cemu-project/Cemu#1248]
### Current Behavior

The Emulator randomly crashes while playing fast racing neo. This has happened:
- Before a race track loaded
- When pausing

### Expected Behavior

No Crashing

### Steps to Reproduce

Play the game for a while (20 minutes maybe). Pause, unpause, start and stop races.

Was playing on 2.0-86. Commits since then do not seem to be related.

### System Info (Optional)

Surface Pro 8
OS: Windows 11 Pro
GPU: Intel(R) Iris(R) Xe Graphics
CPU: 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz

### Emulation Settings (Optional)

Mods:
- Static FPS: 60FPS
- Graphics: TV: 1920x1080, Gamepad: 320x180

![image](https://github.com/cemu-project/Cemu/assets/67109172/8291583c-6bfe-4f4b-a75c-8924ae1cbeff)

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/16040881/log.txt)

**Comment by Squall-Leonhart** [comment]
do you know what Iris driver you're on?

**Comment by DavidBeh** [comment]
The version is 26.10.2022

I checked it here. Not sure if this is the right place.
[image](https://github.com/cemu-project/Cemu/assets/67109172/350ec5d2-7b8d-4873-b436-251404badc91)

If could probably give you verbose logs if you tell me how to enable them.

**Comment by Squall-Leonhart** [comment]
thats the date, but updating to thte latest Iris Xe and Ark driver may fix this, as it has fixedd vulkan errors in other games.

**Comment by DavidBeh** [comment]
This solved the issue
