### ISSUE TITLE
everytime i try to run paper mario color splash it just shows a black screen even i use stuff to upgrade the peformance (Cemu 2.0-88)

### ISSUE THREAD

**Issue by paperguy4** [cemu-project/Cemu#1249]
### Current Behavior

black screen
![Cemu 2 0-88 (experimental) 30_06_2024 4_02_39 PM](https://github.com/cemu-project/Cemu/assets/162562466/75c04532-4022-41d0-b231-d11ca85658bc)

### Expected Behavior

nothig

### Steps to Reproduce

no idea

### System Info (Optional)

OS: idk
GPU: how am i supposed to know

### Emulation Settings (Optional)

opengl

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/16043815/log.txt)

**Comment by Exzap** [comment]
Try installing a newer driver for your integrated graphics card. It should be [this one](https://www.intel.com/content/www/us/en/download/776137/intel-7th-10th-gen-processor-graphics-windows.html). This may or may not work, older Intel GPUs are known to have issues so I am not sure there is a solution.

Also in the future please use our discord or subreddit for troubleshooting. Github issues are for tracking confirmed bugs.
