### ISSUE TITLE
Teslagrad Unsupported depth texture format

### ISSUE THREAD

**Issue by Triticum0** [cemu-project/Cemu#1262]
### Current Behavior

The game crashes on the first frame when trying to boot.
Seems to be an Unsupported depth texture format.
`Unsupported depth texture format 001a`

### Expected Behavior

Should make it into the menu.

### Steps to Reproduce

1. Load game

### System Info (Optional)

OS: Windows 10 Home
GPU: NVIDIA GeForce RTX 3060 Ti
CPU: AMD Ryzen 7 5700X 8-Core Processor

### Emulation Settings (Optional)

Default

### Logs (Optional)

[Teslagrad.txt](https://github.com/user-attachments/files/16316419/Teslagrad.txt)

**Comment by Exzap** [comment]
Fixed by 5328e9eb10b2abeaf303310b06b37269d79dde12
