### ISSUE TITLE
Control Wiimote Pointer with Mouse

### ISSUE THREAD

**Issue by GloriousGlider8** [cemu-project/Cemu#1271]
### Your suggestion

Some games require Wiimotes to be pointed at certain places to play or start playing.
If someone does not own a Wiimote or doesn't have Bluetooth, they cannot play.

There should be an option in the input menu (e.g. Pointer X+, Pointer Y+) that can be controlled using the mouse's coordinates or a joystick / d-pad on a game controller.

**Comment by Squall-Leonhart** [comment]
You already can tho....

**Comment by GloriousGlider8** [comment]
How?

**Comment by legend800** [comment]
You can't. Not sure what Squall is talking about. Regardless, dup of my issue here: https://github.com/cemu-project/Cemu/issues/232. I'll update with your request above.
