### ISSUE TITLE
Draft: Opengl and vulkun black screen issues

### ISSUE THREAD

**Issue by Triticum0** [cemu-project/Cemu#1273]
This is a list of games that don't render anything on OpenGL and Vulkan or only render on one render.

### Opengl
- [ ] A Drawing's Journey
- [ ] A.C.E. - Alien Cleanup Elite
- [ ] AVOIDER
- [ ] Absolutely Unstoppable MineRun
- [ ] Color Bombs
- [ ] Cubeshift
- [ ] Daikon Set
- [ ] Draw 2 Survive
- [ ] Escape From Flare Industries
- [ ] [INVANOID](https://wiki.cemu.info/wiki/INVANOID)
- [ ] [Jackpot 777](https://wiki.cemu.info/wiki/Jackpot_777)
- [ ] [Jewel Quest](https://wiki.cemu.info/wiki/Jewel_Quest)
- [ ] [Midnight 2 ](https://wiki.cemu.info/wiki/Midnight_2)
- [ ] Olympia Rising
- [ ] Panda Love
- [ ] [PEG SOLITAIRE](https://wiki.cemu.info/wiki/PEG_SOLITAIRE)
- [ ] PictoParty
- [ ] Rorrim
- [ ] SDK Spriter
- [ ] SKEASY
- [ ] Splashy Duck
- [ ] TITANS TOWER
- [ ]  Word Logic by POWGI 
- [ ] Word Puzzles by POWGI
### Both renders
- [ ] Cubit The Hardcore Platformer Robot HD
- [ ] [Job the Leprechaun](https://wiki.cemu.info/wiki/Job_the_Leprechaun)
- [ ] Don't Starve: Giant Edition
- [ ] Words Up! Academy

### Only renders UI

- [ ] Cars 3: Driven to Win

### System Info (Optional)

OS: Windows 10
GPU: AMD Ryzen 7 5700X 8-Core Processor

Logs (Optional)

[A.C.E. - Alien Cleanup Elite log.txt](https://github.com/user-attachments/files/16401675/log.txt)

**Comment by JaimieVandenbergh** [comment]
Add a log file from any game so at least we know what release of Cemu you're using, plus your gfx hardware.

**Comment by Squall-Leonhart** [comment]
This would be better off on the Cemu wiki i guess, but add Toon Tanks EU to that opengl list, US is fine with both.

**Comment by ElBread3** [comment]
Please add the Disney Infinity games next to Cars 3 as they exhibit the same issue of only rendering UI (cause same devs as Cars 3, similar engine to Cars 3 I bet as well) and I would love to see these games fixed as the Infinity Base is now emulated and the game can boot!

**Comment by Exzap** [comment]
These should be reported on the [compatibility wiki](https://wiki.cemu.info/wiki/Main_Page). For more info see my response in #1276
