### ISSUE TITLE
PixelJunk Monsters  Crash

### ISSUE THREAD

**Issue by Triticum0** [cemu-project/Cemu#1276]
### Current Behavior

The game crashes on the splash screen before the intro

### Expected Behavior

Should not crash

### Steps to Reproduce

1. Click on the game icon on cemu

### System Info (Optional)

OS: Windows 10
CPU: AMD Ryzen 7 5700X 8-Core Processor  
GPU: NVIDIA GeForce RTX 3060 Ti

### Emulation Settings (Optional)

Default settings

### Logs (Optional)

[PixelJunk Monsters.txt](https://github.com/user-attachments/files/16419811/PixelJunk.Monsters.txt)

**Comment by Exzap** [comment]
I appreciate that you are testing all these games that normally don't get a lot of attention. But when you create a new issue the guidelines explicitly mention to report game-specific issues on the [compatibility wiki](https://wiki.cemu.info/wiki/Main_Page) and not here.
The wiki is also what powers the [compatibility page](https://compat.cemu.info) which has functionality for filtering by status, which is a lot more useful to us than having to manually sieve through github issues when it comes to finding broken games.

That said, the lines of what belongs on the wiki and what belongs on here are a little blurry and so sometimes I keep these kind of issues open. But generally anything of the form "Game xyz crashes on boot/title screen" should be reported directly on the wiki.

**Comment by Exzap** [comment]
Besides me, nobody else is really fixing games so I was just giving you feedback on what is actually helpful to me. Log.txt is good for troubleshooting and getting a quick overview of issues but when it comes to actually fixing games then there is no way around locally debugging it. This is why the wiki is sufficient and you don't need to upload log.txt for cases where a game is just plain broken.

> Secondly, OpenGL black screening isn’t game-specific usually happens when something is unimplemented on one render so thought it was an easy fix.

Yeah this is a common assumption but it's not really true. On a surface level something might look "easy" but the underlying cause can be quite complex and hard to address.

> Also, about the wiki compatibility, if a game only works on one renderer should I leave it in the unplayable category and mention in known issues it only works on one renderer or do I do the opposite and move it to playable and mention it as only working on one renderer.

It's still playable even if the tweaking of settings is necessary. You would mention in the test report what settings/renderer is required.

> Lastly, there are some bots on the Wiki page posting garbage so you might want to delete their posts.

Yeah that is unfortunately an ongoing problem.
