### ISSUE TITLE
Controllers not recognized in linux

### ISSUE THREAD

**Issue by Shoegzer** [cemu-project/Cemu#1278]
### Current Behavior

When you configure controllers with a fresh configuration file, any controllers plugged-in are not recognized and you get the following error:

![pic](https://github.com/user-attachments/assets/c297bc89-2cf4-4392-881a-d3b34e7db144)

### Expected Behavior

Controller should be recognized.  Interestingly enough, with an old configuration from a previous Cemu build, the controller is actually recognized.  This only occurs with new configuration files.

### Steps to Reproduce

Make sure controller is turned on and recognized in the OS, start Cemu with a fresh configuration file and attempt to configure the controller.

### System Info (Optional)

OS: Linux Mint 22 / kernel 6.8
GPU: Nvidia GTX 3070
Controller: DualSense 5
Commit tested: 517e68fe57ac1ac112f37c321d3d40a30ea5a8d6

**Comment by Squall-Leonhart** [comment]
Your linux mint distro is lacking the image library responsible for png's

**Comment by Shoegzer** [comment]
The last one that worked was a build from an April commit, though I'm not convinced it's the build itself. These are all built from source, not from an appimage.

Also, I noticed that if I let Cemu build the `~/.config/Cemu/controllerProfiles/` directory on first run, and then add the `controller0.xml` file which was created from an earlier build, it then recognizes the gamepad, though I'm not sure why it can't build that file from scratch now.

In case it helps, here's the file (with .txt extension to pass the GitHub filter): [controller0.xml.txt](https://github.com/user-attachments/files/16436918/controller0.xml.txt)

**Comment by Shoegzer** [comment]
This was tracked down to an SDL2 issue that has since been locally resolved, closing.
