### ISSUE TITLE
Appimage doesn't provide libstdc++.so.6 with GLIBCXX_3.4.32, resulting in inability to initialise vulkan 

### ISSUE THREAD

**Issue by 20943204920434** [cemu-project/Cemu#1280]
### Current Behavior

Cemu can't load Vulkan because of a Vulkan implementation's dependencies. In my case it looked like an inability to find the GPU. The problem here is that mesa's Vulkan implementation `libvulkan_radeon.so` uses `libz3.so.4`, which is in my case is compiled to work with `libstdc++.so.6` of version `GLIBCXX_3.4.32`, but the Appimage does not contain versions newer than `GLIBCXX_3.4.30.` So the root cause is that the Appimage forces its own libraries on any shared libraries used by the program, even the ones installed in OS, while not providing any possible versions of basic libraries.

Temporal fix (It looks like it can load BOTW, but I didn't bother testing it properly):
1. Extract the appimage with `./Cemu-2.0-91-x86_64.AppImage --appimage-extract`
2. Delete or rename `squashfs-root/usr/lib` directory
3. Use `squashfs-root/usr/bin/Cemu` as usual

### Expected Behavior

Cemu is supposed to be able to load Vulkan properly.

### Steps to Reproduce

1. Install the latest debian 12 and change the default repository to 'testing'
2. Download [Cemu 2.0-91](https://github.com/cemu-project/Cemu/releases/tag/v2.0-91) 
3. Run it

### System Info (Optional)

OS: Debian 12 Bookworm, Custom kernel
GPU: AMD Radeon 780M

**Comment by Samueru-sama** [comment]
[Is the issue related to this change? ](https://github.com/cemu-project/Cemu/commit/b6aaf6633063be47d89a8216e269e32aec5a4b49)

Can you try on a older version of cemu (before that commit) and see if the issue is still present? 

In any case I think what needs to be done is use this [plugin](https://github.com/darealshinji/linuxdeploy-plugin-checkrt).

**Comment by 20943204920434** [comment]
> [Is the issue related to this change? ](https://github.com/cemu-project/Cemu/commit/b6aaf6633063be47d89a8216e269e32aec5a4b49)
> 
> Can you try on a older version of cemu (before that commit) and see if the issue is still present?
> 
> In any case I think what needs to be done is use this [plugin](https://github.com/darealshinji/linuxdeploy-plugin-checkrt).

Yeah, it looks so. I made a [PR](https://github.com/cemu-project/Cemu/pull/1292) to fix the problem.
