### ISSUE TITLE
Incorrect translation and a superfluous & sign (German translation!)

### ISSUE THREAD

**Issue by GhostRice23** [cemu-project/Cemu#1297]
### Current Behavior

![image](https://github.com/user-attachments/assets/468c15d3-f962-43a8-87d4-e6c1b7329b67)
In the German version of Cemu! there is a superfluous & sign in the window title. It should just say "Über Cemu". I don't know if this is also the case in other languages.
![image](https://github.com/user-attachments/assets/dd9ec2f1-59da-470e-9734-19528df0e1f4)
Wrong translation for the tab “Nutzerk” it actually means "Netzwerk" in German!
![image](https://github.com/user-attachments/assets/2bf09ec2-7700-4467-b77b-dd4e1bfe0225) 
"View texture cache info" means "Textur-Cache-Info anzeigen" in German!
"Open logging window" means "Logging-Fenster öffnen" in German!
![image](https://github.com/user-attachments/assets/fdfca77c-47c4-4a4f-a16b-2fc4c4eeb6ba)
"Invalid API usage" means "Ungültige API-Verwendung" in German!
"texture cache warnings" means "Textur-Cache-Warnungen" in German!
"OpenGL debug output" means "OpenGL-Debug-Ausgabe" in German!
"Log PPC context for API" means "PPC-Kontext für API protokollieren" in German!
"CafeOS modules logging" means "Protokollierung der CafeOS-Module" in German!
![image](https://github.com/user-attachments/assets/ea2a8d8f-9450-4473-82c3-f8ecfc0f2a11)
"Open MLC Folder" means "MLC-Ordner öffnen" in German!

### Expected Behavior

I would like to help with the German translation for this emulator if I should not do this here please write me a possibility or something similar how i can help with it pls!

### Steps to Reproduce

There are no steps to Reproduce!

**Comment by GhostRice23** [comment]
I think the Invalid Tag would be right for this issue!

**Comment by Exzap** [comment]
Translations are community managed for the most part. The best thing you can do is submit a fix for it. How to do so is described [here](https://wiki.cemu.info/wiki/Tutorial:How_to_translate_Cemu_UI)
