### ISSUE TITLE
CEMU is great, but why does CEMU 2.0 perform about 6% worse than 1.26.2?

### ISSUE THREAD

**Issue by YuWongXX** [cemu-project/Cemu#1302]
### Current Behavior

I tested the performance of Breath of the Wild. CEMU 1.26.2 runs at 4K 85fps, while CEMU 2.0 runs at 80fps. I'm curious what causes this performance difference.

### Expected Behavior

I expect CEMU 2.0 will be better than CEMU 1.26.2

### Steps to Reproduce

Downgrade to CEMU 1.26.2

### System Info (Optional)

OS: Intel i7 12700h
GPU: RTX 4070

**Comment by Exzap** [comment]
If you turn off accurate barriers under debug you should get pretty much equal performance to 1.26.2. In some games it will be better, in some it might be worse. But at any rate we try our best and if it happens that a Cemu version performs slightly worse then that was a necessary sacrifice for a feature or bug fix. Eventually we plan to recapture any lost performance.

**Comment by YuWongXX** [comment]
> If you turn off accurate barriers under debug you should get pretty much equal performance to 1.26.2. In some games it will be better, in some it might be worse. But at any rate we try our best and if it happens that a Cemu version performs slightly worse then that was probably due to a necessary sacrifice for a feature or bug fix. Eventually we plan to recapture any lost performance.

The only noticeble difference from 1.26 to 2.0 is F11 fullscreen, It's a useful feature. Otherwise I don't notice any difference.
