### ISSUE TITLE
New SUPER MARIO BROS. U + New Super Luigi U Crash

### ISSUE THREAD

**Issue by i0x404** [cemu-project/Cemu#1320]
### Current Behavior

The game crashes after clicking "a" on the menu screen to start the game

![image](https://github.com/user-attachments/assets/47fd81b5-6207-4a7f-b130-54c1b409e193)

### Expected Behavior

The game starts

### Steps to Reproduce

Just start the game and click "A' button to start

### System Info (Optional)

OS: Windows 10
GPU: NVIDIA 920M

### Emulation Settings (Optional)

default

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/16821235/log.txt)

**Comment by Crementif** [comment]
This is because you don't have the mii files, which are required to pass that screen. This issue has been posted before, and a solution is offered on our wiki page. See for this duplicate issue, and a link to the wiki page https://github.com/cemu-project/Cemu/issues/607.

**Comment by i0x404** [comment]
thanks a lot man it worked
