### ISSUE TITLE
Skylanders Emulated Portal of Power won't save progress instantly

### ISSUE THREAD

**Issue by skylandersNFC** [cemu-project/Cemu#1322]
### Current Behavior

This problem occurs with Cemu release 2.1, but it was observed for a while since it persist from the older version as well.

The Emulated Portal of Power will save progress on some kind of a trigger, but this won't happens instantly as the real portal.

### Steps to Reproduce

So if you have 90 gold for example and collect 2 gold and then change the Skylander (using the "Load" option on the Emulated POP), this 2 gold won't be saved (even if you left the game for 10-15 minutes before doing the change).

However, if you progress thru the game at some point this new acquired gold will be saved, along with other changes but again those might not be up to speed, since you don't really know when was the last flash to the NFC dump.

For example i was running with my 90 gold coins and found a chest which increased my gold to 155 and I've changed the NFC dump right after this and the new gold amount was saved successfully.

Then i've returned with my 155 gold and progress further where I've found several more gold coins up to 161. Then I've used the "Load" dump functionality with a new dump and then reloaded my old dump and the extra 6 gold coins were lost.

@deReeperJosh I think the Emulated POP was implemented by you, so im tagging you here. Apologies if that's not the case.

### Expected Behavior

The progress to be saved instantly to the dump file.

**Comment by deReeperJosh** [comment]
Does this happen with a real portal as well? The emulated portal of power code saves all data to the Skylander file each time the Write Block command is called by the game, so if the game isn't calling the Write Block command then the information won't be saved to the Skylander. This code is also called when the Skylander is removed from the UI tool as well, so it is likely the game doesn't call the Write Block command each time a small amount of coins are collected, but only when certain points in a level are reached or a larger amount of coins are collected.

**Comment by skylandersNFC** [comment]
> Does this happen with a real portal as well? The emulated portal of power code saves all data to the Skylander file each time the Write Block command is called by the game, so if the game isn't calling the Write Block command then the information won't be saved to the Skylander. This code is also called when the Skylander is removed from the UI tool as well, so it is likely the game doesn't call the Write Block command each time a small amount of coins are collected, but only when certain points in a level are reached or a larger amount of coins are collected.

Just tested this under Cemu 2.1 with Giants Portal of Power using the GIants game == same behavior.
For the first level of Giants, small gold changes won't be registered at all when swapping tags, until i open a chest and then the gold is instantly saved on the current tag used.
Also it seems changing hats helps, as they will trigger this save data even to the NFC dump/figure.

**Comment by skylandersNFC** [comment]
Ok, I've also tested this on Xbox360 with Trap Teams portal and this is not a bug in Cemu, since i had the same behavior.
It seems the game was designed this way to save the write cycles to the real tags, since otherwise they will die more often.
So you need to do a game event or some kind of a checkpoint to be sure that the data was written to the tag.
If not, you can always change a hat and this will force save your progress.

@deReeperJosh Thank you

**Comment by SuperSamus** [comment]
Just for some extra info, here's what the [official FAQ](https://web.archive.org/web/20220525044625/https://support.activision.com/articles/skylanders-toy-faq) says:

> Data is automatically saved to a toy about every 30 seconds and whenever one of the following happens:
>- The Skylander gains a level
>- You collect 100 pieces of gold
>- You buy a skill upgrade
>- You change hats
>- You change the Skylanders’ nickname or the owner
>- You reset the toy
>- You place a Skylanders toy on the Portal of Power for the first time
>- The Skylander gets a stat boost after completing a challenge.
>
>Always wait about ten seconds after any of these events before taking a Skylander off the Portal of Power. This will give the game time to save data on the toy.
