### ISSUE TITLE
Botw Crashes when loading game

### ISSUE THREAD

**Issue by Moddedmyth** [cemu-project/Cemu#1328]
### Current Behavior

Starting Botw at anytime will result in 8 second loading screen followed up with a crash as the game immediately closes.  

### Expected Behavior

The game should have launched without issues at the beginning of the game.

### Steps to Reproduce

I have two ways to play this game one on a WUX file the other on a Rom folder containing the base UPD and DLC folders, When I use the Rom files to load the game it closes before it can fully launch.

### System Info (Optional)

OS: (C:)
GPU:

**Comment by Exzap** [comment]
For obvious reasons we can't provide help if you use a pirated copy of the game.

**Comment by Moddedmyth** [comment]
That's okay, I'll figure it out.
