### ISSUE TITLE
[Tekken Tag Tournament 2] Unable to mount title error/Game doesn't appear in the library/stuck on infinity loading screen on 2.0+ versions

### ISSUE THREAD

**Issue by Bloodhit** [cemu-project/Cemu#1333]
### Current Behavior

On any 2.0+ version, it doesn't appear in the library when installed, and when trying it run via loading tekken.rpx it shows  "Unable to mount title error", deleting app.xml makes it run but it gets stuck on the infinity loading screen instead then.

### Expected Behavior

Works fine on Cemu 1.26.2f, no issues with both installing and running it via direct load.

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/fced5a9f-6952-423e-b1ef-2b026459e6fd)

**Comment by Squall-Leonhart** [comment]
This is called getting caught out, dump your own game, don't use someone elses.

**Comment by Exzap** [comment]
Since 1.27.0 Cemu cares about meta data being correct (that includes app.xml). This is so it can detect updates and DLC directly from the game folder.
At any rate, dump your own games legally and you won't have this issue. https://cemu.cfw.guide/dumping-games.html
