### ISSUE TITLE
Android Launcher amStartArguments Request

### ISSUE THREAD

**Issue by davehartleyuk** [cemu-project/Cemu#1335]
### Your suggestion

What would the amStartArguments be for launching games using Daijishou Launcher?

Took a guess but no joy.

`"amStartArguments": "-n info.cemu.Cemu/info.cemu.Cemu.ui.main.MainActivity\n  -a android.intent.action.VIEW\n  -e AutoStartFile {file.uri}"`

**Comment by Exzap** [comment]
Please dont open issues for a version of Cemu that is neither finished nor has officially been released
