### ISSUE TITLE
Android Beta V.7 - Community Graphic Packs not working

### ISSUE THREAD

**Issue by intelliaim** [cemu-project/Cemu#1336]
### Current Behavior

Community Graphic Packs download OK and can be enabled OK in Settings. Looks like it should work, but they aren't actually active. Tested Wind Waker with the v1.1 Contrasty graphic pack, no change to game colors.

### Expected Behavior

Tested Wind Waker with the v1.1 Contrasty graphic pack, no change to game colors.

### Steps to Reproduce

Install any graphic pack and enable it.

### System Info (Optional)

OS: Android 13
GPU: Ayaneo Pocket S (Adreno A32)

**Comment by Crementif** [comment]
The Android version is still very much in its development, and isn't meant for general users yet. Please wait until SSimco, its developer, believes it to be ready. You'll then likely be able to find it on Cemu's official website without bugs like these.
