### ISSUE TITLE
[Feature Request] Move new/known compability issues for games/dlc into its own git repository

### ISSUE THREAD

**Issue by some-username-here1** [cemu-project/Cemu#135]
The Xenia emulator repository, and technically RPCS3 too (but more of their own dedicated forums), has done it as well.
This is to keep the list of issues not as clustered and to have a dedicated repository page solely for game issues.

**Comment by Exzap** [comment]
I gave this a bit of time to see how many game issues would be reported and it's generally a pretty small amount. It's not worth the increased organization effort of having two separate repos, at least for now.
