### ISSUE TITLE
cemu on andriod

### ISSUE THREAD

**Issue by ahmedtalha31** [cemu-project/Cemu#1352]
### Your suggestion

Is that emulator will be avaliable for andriod devices in the future?

**Comment by cabrerahector** [comment]
See: https://github.com/cemu-project/Cemu/issues/1351

Also, for general questions like this one please go to Cemu's Discord server.

**Comment by Erayke-a** [comment]
The configuration to play cemu android must also be Snapdragon 855, but if I use Snapdragon 732g in the game, it will crash.

**Comment by Erayke-a** [comment]
The configuration to play cemu android must also be Snapdragon 855, but if I use Snapdragon 732g in the game, it will crash.
