### ISSUE TITLE
Taiko no tatsujin not opening

### ISSUE THREAD

**Issue by CarlosNunezMX** [cemu-project/Cemu#1357]
### Current Behavior

Game starts with its notice, but in BANDAI logo it crashes.

### Expected Behavior

Game should open :D

### Steps to Reproduce

Download taiko tomodachi, and its dlc.
I use emulated pro controller
FPS Overlay

### System Info (Optional)

OS: Android 14 - S20FE - OneUI 6.1
GPU: Snapdragon 865

**Comment by Exzap** [comment]
If piracy is involved we cannot provide help. But also we do not accept issues for the Android build in general yet. See the [Android FAQ](https://rentry.org/cemu-android)
