### ISSUE TITLE
IMPORTANT Feature request: Enable generation of settings files from terminal in Cemu

### ISSUE THREAD

**Issue by davidhedlund** [cemu-project/Cemu#1359]
### Current Behavior

Currently, Cemu does not support generating settings files, such as `settings.xml`, directly from the terminal. When Cemu is launched for the first time, users must manually click the "Close" button in the second dialog box to generate the `settings.xml` file. This process can be inconvenient for users who prefer or require automation.

## Expected Behavior

The `settings.xml` file should be automatically generated when Cemu is launched from the terminal without requiring any manual intervention through the GUI.

## Proposed Solution

Implement a feature in Cemu that allows for the automatic generation of configuration files when it is executed from the terminal. This would enhance usability for users who rely on scripts and automation tools.

## Additional Context

Automating this process would align with practices seen in other emulators and improve user experience by reducing manual steps required during initial setup or batch operations.

## Steps to Reproduce

1. **Script Execution:**
   - Run the following command:
     ```bash
     timeout 5 ./Cemu-2.2-x86_64.AppImage
     ```
   - Observe that `~/.config/Cemu/settings.xml` is not generated.
   - ![image](https://github.com/user-attachments/assets/d2d53524-03dc-4707-aa19-10484fa6ca12)

2. **GUI Method:**
   - Open `Cemu-2.2-x86_64.AppImage`.
   - ![image](https://github.com/user-attachments/assets/9e7fe251-379a-4133-9560-5d309f2c52b5)
   - Click on the "Close" button.
   - ![image](https://github.com/user-attachments/assets/4ed4770d-98a1-459f-8901-c54b8e6dfcbe)
   - Verify that `~/.config/Cemu/settings.xml` is generated.

### System Info (Optional)

OS: 
GPU:

**Comment by davidhedlund** [comment]
Sorry, please replace the "bug" label with the "feature request" label.

**Comment by Exzap** [comment]
There are many ways to work around this, e.g. by supplying a pre-generated settings.xml file. Overall I feel this feature request is extremely niche and outside the scope of the project. If you want to see this happen then I invite you to add this yourself an submit it is as a PR.

**Comment by davidhedlund** [comment]
> There are many ways to work around this, e.g. by supplying a pre-generated settings.xml file. Overall I feel this feature request is extremely niche and outside the scope of the project. If you want to see this happen then I invite you to add this yourself an submit it is as a PR.

Workaround: `mkdir -p ~/.config/Cemu/ && touch ~/.config/Cemu/settings.xml && timeout 5 ./Cemu-2.2-x86_64.AppImage`
