### ISSUE TITLE
Document that `flatpak override` is required for custom MLC paths

### ISSUE THREAD

**Issue by davidhedlund** [cemu-project/Cemu#1360]
### Current Behavior
"Failed to create the default MLC files in the selected directory. The MLC path has not changed"

![image](https://github.com/user-attachments/assets/bba2ee81-ce6f-4963-8e96-acdd57c917f5)

### Expected Behavior

Document `sudo flatpak override info.cemu.Cemu --filesystem="$HOME/custom/path/mlc01:create"` in
* The [FAQ](https://cemu.info/faq.html)
* The text "Failed to create the default MLC files in the selected directory. The MLC path has not changed" can be extended with this text link "[Flatpak requires override configuration](https://cemu.info/faq.html)", here displayed on a modified screenshot (blue text):
![image](https://github.com/user-attachments/assets/3c013c5f-1eff-4ade-af30-68af3f8ab4a6)

### Steps to Reproduce

* mkdir -p ~/test/
* Navigate to: Options -> General settings
* Click on the "Change" button under "Custom MLC path", and choose /home/yourusername/test/. Important note: Do not select a directory named mlc01, that will prevent this issue from being reproduced.

![image](https://github.com/user-attachments/assets/78af8de1-dbf1-4eef-a682-b29cf9b4705d)

### AppImage (control)
* mkdir -p ~/test/
* Navigate to: Options -> General settings
* Click on the "Change" button under "Custom MLC path", and choose /home/yourusername/test/
* The memory card directories "sys" and "usr" will be added to ~/test/

### System Info (Optional)

OS: Ubuntu MATE 22.04
GPU: Any
Cemu: 2.2 flatpak package

**Comment by davidhedlund** [comment]
Bug bounty of $10 for fixing this issue. I've lost data twice over the past two years because I forgot to save it. Best! @Exzap

**Comment by CDarkmatter** [comment]
If you're using the flatpak version, you must give Cemu read and write access to this directory, You can use a tool like flatseal to make the process easier, for example if the path of your mlc directory is ~/WiiU/MLC you should add `~/WiiU/MLC:create` to your overrides.

**Comment by davidhedlund** [comment]
> If you're using the flatpak version, you must give Cemu read and write access to this directory, You can use a tool like flatseal to make the process easier, for example if the path of your mlc directory is ~/WiiU/MLC you should add `~/WiiU/MLC:create` to your overrides.

Thank you very much! 😁 I updated the top post.

**Comment by davidhedlund** [comment]
@Exzap I completely rewrote this issue from the ground up. It should now be relatively straightforward to resolve!

**Comment by davidhedlund** [comment]
> > If you're using the flatpak version, you must give Cemu read and write access to this directory, You can use a tool like flatseal to make the process easier, for example if the path of your mlc directory is ~/WiiU/MLC you should add `~/WiiU/MLC:create` to your overrides.
> 
> Thank you very much! 😁 I updated the top post.

":create" only grant permission to create the directory:
`flatpak override info.cemu.Cemu --user --filesystem=/home/yourusername/gamesaves/Cemu/mlc01:create`

Do you know how to create the directory with flatpak or flatpak-builder?
