### ISSUE TITLE
Rename "Remember main window position" to "Remember main window size and position"

### ISSUE THREAD

**Issue by davidhedlund** [cemu-project/Cemu#1361]
How to permanently maximize the main window:
1. Options -> General settings -> Enable: "Remember main window position"
2. Close "General settings"
3. Maximize the main window.
4. Close Cemu
5. Start Cemu
6. The window will be started maximized.

# Issue
It's not possible to figure out that "Remember main window position" is related to the window size. It should be renamed to "Remember main window size and position"

**Comment by davidhedlund** [comment]
How to permanently maximize the Game list window:
1. Options -> General settings -> Enable: Remember main window position
2. Close "General settings"
3. Maximize the Game list window

**Comment by davidhedlund** [comment]
Please change this label to "bug"

**Comment by Exzap** [comment]
Why not just submit this as a PR?

**Comment by davidhedlund** [comment]
> Why not just submit this as a PR?

Here you go:
* https://github.com/cemu-project/Cemu/pull/1365

**Comment by Exzap** [comment]
Decided to keep it as it is for now. More info in the PR.

**Comment by davidhedlund** [comment]
Can we replace "Remember main window position" with "Remember main window size" for now?
