### ISSUE TITLE
Crash when loading BOTW shaders with latest AMD Drivers

### ISSUE THREAD

**Issue by Valkyr2** [cemu-project/Cemu#1369]
### Current Behavior

 When launching BOTW, the emulator closes suddenly during shaders loading. 
Only occurs using OpenGL, Vulkan works "fine" (is it was not for the black squares-like artifacts of RDNA3).
Same thing with or without GFX packs, and with or without Shader multiplication accuracy.
Only happens with 24.9.1 driver and the latest preview driver (both supporting AFMF2).

### Expected Behavior

Cemu not closing when loading the shaders

### Steps to Reproduce

launch BOTW

### System Info (Optional)

OS: Windows 11 23H2
GPU: 7900XTX with 24.9.1 driver

### Logs (Optional)

no log file is generated

**Comment by Valkyr2** [comment]
I saw that one, but they say it's on vulkan, while in this case vulkan works and not openGL, so I thought it might be worth reporting

**Comment by Squall-Leonhart** [comment]
your system has nahimic installed and is crashing on opengl  due to that.

**Comment by Valkyr2** [comment]
Thanks for your suggestion, I indeed had it installed. Unfortunately, after uninstalling it following this guide https://www.reddit.com/r/MSI_Gaming/comments/l45fnj/guide_how_to_uninstall_nahimic_completely_from/
and trying other versions of cemu (2.1, 2.0), OpenGL still crashes

**Comment by Valkyr2** [comment]
I can see this in event viewer, don't know if that helps
![image](https://github.com/user-attachments/assets/076c52a2-b5e6-4faa-9ff9-2f3a47265b1d)

**Comment by Squall-Leonhart** [comment]
uninstallation does not always fully remove the service, is it present in services.msc?

**Comment by Valkyr2** [comment]
I don't think it is, can't see any process or service running named nahimic (or anything similar)
