### ISSUE TITLE
Amiibo in Mario Kart 8 don't work

### ISSUE THREAD

**Issue by Jhon-ito** [cemu-project/Cemu#1372]
### Current Behavior

When I try to scan an amiibo using a .bin file in mario kart 8 to unlock mii costumes it doesn't work, nothing happens, and if I try multiple times it freezes the game.

### Expected Behavior

The mii costume gets unlocked upon loading the amiibo .bin file.

### Steps to Reproduce

Try to scan an amiibo in mario kart 8.

### System Info (Optional)

OS: 
GPU:

**Comment by HatInLime** [comment]
Having the same issue. I'm a wee bit of a completionist-nerd and the mii costumes are the only thing preventing me from complete 100% of the game. Holding out hope it gets fixed soon. :p
