### ISSUE TITLE
Add checkbox to toggle screen for controller

### ISSUE THREAD

**Issue by damil42** [cemu-project/Cemu#1373]
### Your suggestion

Currently you can define a button to show the gamepad screen. It would be great if we could add a checkbox to toggle the button instead of holding it down. That means you only have to press once and the other screen will be shown permanently. Press again to go back. Just like CTRL+TAB on the keyboard. Just for the controller. I want to play with the controller and quickly switch screens without interrupting myself by using the keyboard.

![{205C94CE-D38E-4BA5-AEA0-5C2B8AC29FFB}](https://github.com/user-attachments/assets/f619faee-ca4c-4dea-9de0-a0bb7cfe1ad4)

**Comment by NazaDwnt3d** [comment]
I 100% agree that this feature should be added, it would make Cemu much less of a hassle to use with just a controller and single monitor
