### ISSUE TITLE
Skylanders Portal audio works, but is very broken

### ISSUE THREAD

**Issue by moonleaks** [cemu-project/Cemu#1377]
### Current Behavior

On skylanders trap team, the portal audio now works, but its botchy and doesnt work right

### Expected Behavior

I thought the portal audio would be clear

### Steps to Reproduce

load into trap team, go to the villian vault and listen to the audio, OR put a trap in your portal and listen to the audio, OR if your on the first level and you capture gulper you'll hear the audio

**Comment by Exzap** [comment]
Duplicate of #1146

**Comment by skylandersNFC** [comment]
![200w](https://github.com/user-attachments/assets/449b09f6-1823-4527-a813-233379428ec9)
