### ISSUE TITLE
[FEATURE REQUEST] Android version

### ISSUE THREAD

**Issue by PeterNjeim** [cemu-project/Cemu#138]
Obviously a huge task, but possible now due to the recent open-sourcing. The Wii U is the last major Nintendo console not available for emulation on Android, so would be nice to complete the set. Anyways, my programming experience doesn't touch emulation, so I'm opening this as basically a forum to talk about this potential far-away feature, not demanding anything obviously.

**Comment by Titaniumtown** [comment]
From what I know, the current JIT would have to utilize LLVM instead in order to allow usage on other platforms as the JIT only creates amd64 machine code.

**Comment by bitscher** [comment]
Currently there's no support to make it run on anything than X86-64.
Support may come eventually but not in the near future as changing the JIT is a huge task.

**Comment by elliot-sawyer** [comment]
What do we need to do to even get started with this? I've compiled a few other emulators before on a Raspberry Pi, but not sure where to begin with an Android build

**Comment by bitscher** [comment]
That's some of the code that requires porting to target the ARM ISA (or modify to use LLVM)

https://github.com/cemu-project/Cemu/tree/main/src/Cafe/HW/Espresso/Recompiler

**Comment by kevincrans** [comment]
If you want it to go step by step, first port it to Android x86.

**Comment by davidhedlund** [comment]
Games released for handheld game consoles don't have non-network multiplayer mode. So handheld game console emulators installed on mobile devices (smartphones, tablets, etc) cannot be used for this purpose. Instead you have to install home video game console emulators on the mobile device.

For example:
* ''New Super Mario Bros. 2'', distributed for Nintendo 3DS (handheld game console), does not have a two player mode. So Citra (Nintendo 3DS) is not useful for multiplayers in this game.
* ''New Super Mario Bros. Wii U'', distributed for Nintendo Wii U (home video game console), has four player mode. To play it on a smartphone, it would be awesome if **Cemu for Android** was released, so two or more game pads to the Bluetooth on the phone.

**Comment by thealidev** [comment]
It would be better if someone create libretro core for cemu

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/14416

**Comment by davidhedlund** [comment]
> It would be better if someone create libretro core for cemu

That's a separate project. However, it has been submitted here:
* https://github.com/libretro/RetroArch/issues/14416

**Comment by thanone2** [comment]
> If you want it to go step by step, first port it to Android x86. If you really want to, you can use DRC-SIM, then it only works when connected to the host, just like a real Wii U.

DRC-SIM is to connect the Wii U gamepad to ubuntu or debian. If you already knew this, can you enlighten me on why you mentioned this?

**Comment by kevincrans** [comment]
It's been a year, but I understand that it connects a computer to an actual Wii U, so with the playstore app, it's more for if you bought an incomplete Wii U and needs a PC too. It's repository is inactive for 6 years, so there it ends from a Cemu perspective for now.

**Comment by Blake96** [comment]
I've found an Android version of Cemu emulator on this website: https://apkod.com/cemu-emulator-android/
But I don't see this app on the official GitHub page

**Comment by thanone2** [comment]
> I've found an Android version of Cemu emulator on this website: https://apkod.com/cemu-emulator-android/
> But I don't see this app on the official GitHub page

likely a fake

**Comment by Masamune3210** [comment]
If its not mentioned on the official site or this github, its not backed by the people you are talking to here and therefore should be not trusted

**Comment by thanone2** [comment]
it was a fake i tested it on my s8, it never loaded

**Comment by Masamune3210** [comment]
Please be careful randomly installing and launching unknown apps, just because you can't see them doing anything doesn't mean they arent doing anything.

**Comment by thanone2** [comment]
> Please be careful randomly installing and launching unknown apps, just because you can't see them doing anything doesn't mean they arent doing anything.

https://youtu.be/4_wwoKAlV9Q

**Comment by CobeSoft-App** [comment]
I've tried this https://apkod.com/cemu-emulator-android/
But doesn't work on my device, I'm sure is not an official version

**Comment by Titaniumtown** [comment]
@CobeSoft-App looks like a virus lol

**Comment by PeterNjeim** [comment]
The exact same virus was shared earlier in this thread lol

**Comment by Riot20058** [comment]
Keep mind this is early build does work only some 2d games run full speed
[Uploading cemu experimental.zip…]()

**Comment by PeterNjeim** [comment]
New development: https://github.com/XForYouX/Cemu-Android

**Comment by Exzap** [comment]
I deleted a link to some very sketchy looking repository. As a reminder, [SSimco's fork](https://github.com/SSimco/Cemu) is the one where development actually happens

**Comment by PeterNjeim** [comment]
@Exzap I've never heard of that fork, was there an announcement of some kind? The one I shared had a working Android version, according to Reddit users. I can't seem to find a working release for the fork you shared

**Comment by thanone2** [comment]
This one doesn't look like click bait, and many people confirm it working, it was tested on a snapdragon 888 and NSMBU ran at 45-51 fps

**Comment by PeterNjeim** [comment]
@thanone2 Yeah that's the one I shared, but it was deleted by the mod

**Comment by thanone2** [comment]
> @thanone2 Yeah that's the one I shared, but it was deleted by the mod

That is suspect 🤔

**Comment by Exzap** [comment]
That repository literally has a link to ROM downloads, please stop posting it.

**Comment by thanone2** [comment]
Oh, I didn't see that

**Comment by Exzap** [comment]
> @Exzap I've never heard of that fork, was there an announcement of some kind? The one I shared had a working Android version, according to Reddit users. I can't seem to find a working release for the fork you shared

Generally development happens before anything is announced. But there is an FAQ with some more info: https://rentry.org/cemu-android

Keep in mind that open source development means that people are free to take whatever state the code is in right now and compile an APK from it. Since there is no official releases yet (it's not finished) you should be very careful with any "Cemu APKs" you find on the web. At best it's just a snapshot of the currently unfinished version which still has plenty of issues, and at worst it's a virus.

**Comment by PeterNjeim** [comment]
You were speaking cryptically at first and I just now realized what you were trying to say. You're saying that the version I shared is merely a compiled version of some other fork? If it's an unofficial developer I'm not sure why you're linking to it but I can't link to the compiled version, wouldn't the virus argument go both ways? Open source doesn't mean virus-free, most people don't vet code. The person sharing the compiled

In any case, I'm not sure why it warrants deletion, most people don't want to or can't compile an APK themselves. Again, the Reddit users said they could play various games at full speed, so I was offering the link to it for others to try it themselves

**Comment by thanone2** [comment]
> You were speaking cryptically at first and I just now realized what you were trying to say. You're saying that the version I shared is merely a compiled version of some other fork? If it's an unofficial developer I'm not sure why you're linking to it but I can't link to the compiled version, wouldn't the virus argument go both ways? Open source doesn't mean virus-free, most people don't vet code. The person sharing the compiled version also has other emulation-related repos, possibly compiling other tools as well. So I don't think it's a virus but rather someone compiling as a service for others.
> 
> In any case, I'm not sure why it warrants deletion, most people don't want to or can't compile an APK themselves. Again, the Reddit users said they could play various games at full speed, so I was offering the link to it for others to try it themselves

No, he said he took the link down because in that repo, it had links to game roms, and they don't want Cemu DMCA'd

**Comment by thanone2** [comment]
> That repository literally has a link to ROM downloads, please stop posting it.

@PeterNjeim

**Comment by Crementif** [comment]
> @Exzap I've never heard of that fork, was there an announcement of some kind? The one I shared had a working Android version, according to Reddit users. I can't seem to find a working release for the fork you shared

SSimco is the developer that has been working on this feature for almost a year now whenever he has time. He didn't announce it as it hasn't been finished, and when he does I'm sure it'll either be made available on either Cemu's or his own repository.

The other person compiled his work-in-progress code and included some sketchy links with illegally hosted games, which Cemu doesn't condone. That's why it was deleted. There's a separate argument about .apk's (and indeed compiling unverified source code from a random source) is dangerous, but it's not relevant here.

---
Lastly, its disappointing that according to your original message, SSimco didn't seem to have been provided any credit for what is essentially his work. That's why me (and Exzap) try to make it clear who's doing the work here, and how people can guarantee that they use a repository from a trusted developer.

**Comment by PeterNjeim** [comment]
Thanks for your reply, but I think you're misunderstanding with your final paragraph. I never heard of this developer, so how would I know what I was sharing was a derivative of his? I was only nudged to go to his repository, it wasn't said that it was indeed a fork (that's why I said he was talking "cryptically", as in, he wasn't explicit). Anyways, nice to know about this other repository, it's exactly what I'm looking for

**Comment by thanone2** [comment]
> Thanks for your reply, but I think you're misunderstanding with your final paragraph. I never heard of this developer, so how would I know what I was sharing was a derivative of his? I was only nudged to go to his repository, it wasn't said that it was indeed a fork (that's why I said he was talking "cryptically", as in, he wasn't explicit). Anyways, nice to know about this other repository, it's exactly what I'm looking for

Bruh, he was just giving credit where credit was due.

**Comment by PeterNjeim** [comment]
I know that, but that was only explicitly said in his second reply to me. In his first reply it just seemed like an advertisement for his preferred repository

**Comment by thanone2** [comment]
> I know that, but that was only explicitly said in his second reply to me. In his first reply it just seemed like an advertisement for his preferred repository

The preferred one was the official one...

**Comment by PeterNjeim** [comment]
I'm not even sure what you're trying to say.

Here's the order of events:
1. I looked up Cemu Android and found a version on Reddit
2. I shared it here
3. Weeks later, it was deleted, deemed sketchy, and I was directed to a different repository
4. You shared the same link on the same  day mine was deleted (funny coincidence)
5. The mod took town your link, this time saying that it contained a link to ROM downloads (something not mentioned earlier)
6. The mod responds to me saying that it was a derivative repository (something not mentioned earlier)
7. I respond by saying that it isn't warranted to delete even if it is a derivative (I'm ignoring the ROM download as that wasn't mentioned the first time the link was deleted)
8. You respond saying it's deleted because of the ROM download (I know that, but for the first time it was deleted it seemed like that wasn't the reason)
9. A different mod responds to me, explaining the situation, then in the final paragraph attacks me for not doing something I couldn't possibly have done
10. I take issue with this attack saying that it was impossible for me to give credit. I end the discussion by saying I'm glad I have been introduced to this other repository
11. You reopen the discussion by saying that the mod was giving credit, I respond saying I know that already, given the above discussion
12. You respond by saying that the repository they shared is "official", no, it was confirmed to be unofficial, however it is the true source of the code of the repository we both shared. Not sure why we're going in circles, we just discussed this

**Comment by thanone2** [comment]
> I'm not even sure what you're trying to say.
> 
> Here's the order of events:
> 1. I looked up Cemu Android and found a version on Reddit
> 2. I shared it here
> 3. Weeks later, it was deleted, deemed sketchy, and I was directed to a different repository
> 4. You shared the same link on the same  day mine was deleted (funny coincidence)
> 5. The mod took down your link, this time saying that it contained a link to ROM downloads (something not mentioned earlier)
> 6. The mod responds to me saying that it was a derivative repository (something not mentioned earlier)
> 7. I respond by saying that it isn't warranted to delete even if it is a derivative (I'm ignoring the ROM download as that wasn't mentioned the first time the link was deleted)
> 8. You respond saying it's deleted because of the ROM download (I know that, but for the first time it was deleted it seemed like that wasn't the reason)
> 9. A different mod responds to me, explaining the situation, then in the final paragraph attacks me for not doing something I couldn't possibly have done
> 10. I take issue with this attack saying that it was impossible for me to give credit. I end the discussion by saying I'm glad I have been introduced to this other repository
> 11. You reopen the discussion by saying that the mod was giving credit, I respond saying I know that already, given the above discussion
> 12. You respond by saying that the repository they shared is "official", no, it was confirmed to be unofficial, however it is the true source of the code of the repository we both shared. Not sure why we're going in circles, we just discussed this

Oh, sorry, I misunderstood what you said then

**Comment by Exzap** [comment]
Closing this in favor of #1351

The updated FAQ also contains a link to official preview APKs now
