### ISSUE TITLE
Android: Missing analog range.

### ISSUE THREAD

**Issue by AlexS2412** [cemu-project/Cemu#1387]
### Current Behavior

due to not being able to set analog range certain directions do not fully move in zelda games with half range analogs like the one found in the backbone one. a simple option to double or half stick range should resolve this. i couldn't find a specific place to report the issue so i put it here.

### Expected Behavior

full analog movement in games.

### Steps to Reproduce

use the android version by ssimco with an affected controller.

### System Info (Optional)

OS: 
GPU:

**Comment by cabrerahector** [comment]
The Android build isn't officially supported at this time, see https://rentry.org/cemu-android
