### ISSUE TITLE
cemu botw crash sanctuary of HIRO'HIRA

### ISSUE THREAD

**Issue by Riceuh** [cemu-project/Cemu#1388]
### Current Behavior

This bug occurred when I entered a sanctuary and when I wanted to change abilities my game crashed without closing CEMU

### Expected Behavior

I would like someone to give me an answer so I can continue the adventure because this is blocking me a lot

### Steps to Reproduce

Go to Sanctuary of Hiro'Hira and try to switch your abilities if the crash happens

### System Info (Optional)

OS: Windows 11
GPU: NVIDIA RTX 4060

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/17445322/log.txt)

**Comment by Squall-Leonhart** [comment]
Get and dump your own copy of the game.

**Comment by Ambarasodor** [comment]
Yup, the problem here is that you're using a pirated copy of the game
