### ISSUE TITLE
AMD Adrenalin 24.10.1 crash BotW

### ISSUE THREAD

**Issue by borrrris** [cemu-project/Cemu#1395]
### Current Behavior

The emulator crash while compiling pipeline cache

### Expected Behavior

That the emulator completes compiling shaders without crashing

### Steps to Reproduce

Open BotW and wait to the emulator start to compiladed shaders.

### System Info (Optional)

OS: Windows 11 Pro 23H2
GPU: AMD Radeon RX 5700

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/17532006/log.txt)

**Comment by JaimieVandenbergh** [comment]
Yes, we know. AMD have screwed up and delivered buggy drivers. You need to revert to 24.7.1

**Comment by Exzap** [comment]
Duplicate of #1323
