### ISSUE TITLE
I cant play any games

### ISSUE THREAD

**Issue by Tarukigamer** [cemu-project/Cemu#1399]
### Current Behavior

I've been trying to play paper mario, or any other game and when i try to instal them on the emulator i cant, i only see the graphic part of the games not the games themselves

### Expected Behavior

the file gets accepted and i run paper mario

### Steps to Reproduce

just download do every step and press on "files" then "instal ???" then go to the graphics folder ( there arent any other ) take the game of your choice and launch it

### System Info (Optional)

OS: 
GPU:

**Comment by Exzap** [comment]
Please use the [discord](https://discord.gg/5psYsup) or [subreddit](https://www.resetera.com/threads/cemu-ot-wii-u-in-full-glory.3532/) for troubleshooting
