### ISSUE TITLE
Paper Mario Color Splash stuck in titlescreen

### ISSUE THREAD

**Issue by Nico-Shock** [cemu-project/Cemu#1410]
### Current Behavior

When I start up the game, the A button won’t work on the title screen, so I can’t boot the game up. On every other game, everything works fine.

### Expected Behavior

I expected the A button to work on the title screen so I could start the game, just like it does with other games.

### Steps to Reproduce

1. Start up the game.
2. Wait for the title screen to appear.
3. Press the A button to attempt to start the game.
4. Observe that the title screen cannot be dismissed, and the game does not start, unlike in other games where this works correctly.

### System Info (Optional)

OS: Nobora 40
GPU: RTX 4070 Super

**Comment by Squall-Leonhart** [comment]
This game uses the Wii U Gamepad,  it won't work with an emulated pro controller.
