### ISSUE TITLE
Crash after playing BOTW for a while

### ISSUE THREAD

**Issue by jamescarterdon1** [cemu-project/Cemu#1418]
### Current Behavior

After around a couple not necessarily consecutive hours of playing, BOTW starts to lag and after a couple more hours Cemu crashes and Windows turns into a black screen requiring a restart to fix.

### Expected Behavior

I expected performance to not degrade and no crashes or if performance degraded for restarting Cemu or clearing the shader cache to fix this issue temporarily.

### Steps to Reproduce

Open BOTW and keep it running for around 8 hours

### System Info (Optional)

OS: Windows 11
GPU: Intel(R) Iris(R) Xe Graphics

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/17725861/log.txt)

**Comment by Squall-Leonhart** [comment]
there is little to no support for running this emulator on an IGP, no matter how improved the Iris Xe is over previous interations its still consuming half of your system memory unlike a dedicated graphics processor.

Cemu didn't crash your pc, Windows hit memory exhaustion and the driver never recovered from a OOM triggered TDR.
