### ISSUE TITLE
Breath of Wild slow

### ISSUE THREAD

**Issue by jguillermo222** [cemu-project/Cemu#1419]
### Current Behavior

I checked various games and mario kart 8 was a little bit slow and zelda breath has only 8-20 fps.  In general, many games improved for pc. I3-1005g1 with 20 gb ram

### Expected Behavior

Slow motion

### Steps to Reproduce

Problems with 2 games. I tried like 8 games.  in 1005g1 i3

### System Info (Optional)

OS: Windows 11
GPU:

**Comment by Exzap** [comment]
For BotW there is an [optimization guide](https://cemu.cfw.guide/optimizing-cemu.html). But for most other games if they run slow on your hardware that is just what it is and there is not much room for tweaking. Integrated Intel GPUs dont perform super well to begin with. You can try lowering the resolution via graphic packs and that might help.

Anyway, for troubleshooting performance problems use our [discord](https://discord.gg/5psYsup) or [subreddit](https://www.reddit.com/r/cemu/) for troubleshooting performance issues.
