### ISSUE TITLE
LEGO DIMENSIONS  massive light issues: No shadows whatsoever they are basically disabled and alot of other shadow bugs that i can't even name

### ISSUE THREAD

**Issue by K0IDzZz** [cemu-project/Cemu#1426]
### Current Behavior

Lego dimensions has no shadows and has alot of lighting bugs that i can't even name ,Some slight screentearing 

### Expected Behavior

I expected the game to have shadows 

### Steps to Reproduce

Basically just run lego dimensions on 1920x1080 resoloution patch and 60 fps and even if u run the game iwhtout anything the shadows are still really buggy

### System Info (Optional)

OS: 
GPU: 

### Emulation Settings (Optional)

Even with default settings the issue still occourers

**Comment by Exzap** [comment]
This is documented on the [compatibility wiki](https://wiki.cemu.info/wiki/LEGO_Dimensions) already
