### ISSUE TITLE
Star fox zero app crash to homescreen

### ISSUE THREAD

**Issue by Flatmotion1** [cemu-project/Cemu#1429]
### Current Behavior

Game crashes in the tutorial sequence back to homescreen.
I've tried different settings for graphics to no avail. 

### Expected Behavior

No crashing 

### Steps to Reproduce

Just flying in the intro sequence. Not sure if certain objects trigger the crash. 

### System Info (Optional)

OS: Android 13
GPU: snapdragon 8 gen2

### Emulation Settings (Optional)

All settings default 

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/17899350/log.txt)

**Comment by Exzap** [comment]
Please read https://rentry.org/cemu-android
