### ISSUE TITLE
Cemu 2.4 (Flatpak) crashes whenever windows loses focus, changing window positon or switch workspace on gnome when using nvidia vulkan

### ISSUE THREAD

**Issue by CDarkmatter** [cemu-project/Cemu#1442]
### Current Behavior

Flatpak Cemu v2.4 (commit 74f349d254d59a2262d337d732c9703f45e74e4f2447577a622f37d4525f37b8) crashes whenever windows lose focus, changing window position or switching workspace after launching any game on Gnome when using NVIDIA Vulkan, I tried rolling back to v2.2 commit (51ad5f5f887a07fdb52f948afe7db09d1c3fa9d23fc6d558f1358bcbaa8b3f55) and everything worked as expected.

Sorry for the clutter and thanks in advance.

### Expected Behavior

Not to crash when it loses focus.

### Steps to Reproduce

* Use Fedora 41 Gnome
* Use flatpak Cemu v2.4 (commit 74f349d254d59a2262d337d732c9703f45e74e4f2447577a622f37d4525f37b8)
* Set options to nvidia vulkan
* Try moving the window, switch workspace or change focus from window.

### System Info (Optional)

OS: Fedora Linux 41
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU

### Emulation Settings (Optional)

* Changed Graphics API to Vulkan
* Changed GPU from Intel's iGPU to Nvidia's dGPU

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/18050923/log.txt)

**Comment by CDarkmatter** [comment]
Updated Nvidia driver to v565 and everything is working perfectly now.

**Comment by ieris19** [comment]
I'm still experiencing this with a similar setup. The issue isn't resolved for me and I'm already on the proprietary drivers version 565.57.01

I have an NVIDIA 1050Ti, also a laptop with NVIDA Optimus (dual GPU with an Intel Iris), and when running CEMU v2.4 from FlatHub any attempt at moving windows, opening something else or interacting with anything but the game being emulated will crash the whole emulator. This happens to me in all games, but some are more stable than others, for example, Pokken Tournament is giving me no wiggle room, can't even load an Amiibo, but Twilight Princess is more lenient as long as CEMU remains in focus.

I don't think it's relevant but just in case, I'm also running a derivative of Fedora, Nobara Linux 40 (GNOME Edition)
