### ISSUE TITLE
(issues on the latest very early beta build on android) Twilight Princess HD

### ISSUE THREAD

**Issue by MemelordRye13** [cemu-project/Cemu#1447]
### Current Behavior

Every time when i try and get the Dungeon map from Snow peak ruins in twilight princess HD, the game closes (or crashes?). Its just puts me back on the screen where my games are. Im aware it is still very early development on the android version, but i at least wanted to play through twilight princess HD, and make a note for all of the major bugs ive come across while playing on my Samsung galaxy S24 ultra.

List:

Snowpeak ruins dungeon map crash upon recieving.

Mini map cut in half or is replaced with a black square. 

### Expected Behavior

I expected to get the dungeon map in snowpeak ruins and continue playing without it crashing after i get it.

### Steps to Reproduce

Playthrough the game up until you get the dungeon map in snow peak ruins (i can provide my save file if needed to save time, latest save is right inside the dungeon before the map.) 

Talk to the NPC who gives you the dungeon map

Crashes after cutscene when receiving the map.

### System Info (Optional)

OS: Android v14
Processor: 
CPU speed - 
3.39GHz, 3.1GHz, 2.9GHz, 2.2GHz,

CPU Type - 
Octa-Core

Storage/Memory:
Memory(Ram) - 12

Storage - 256GB

(If needed i can provide more info)

### Emulation Settings (Optional)

[settings.txt](https://github.com/user-attachments/files/18098818/settings.txt)

### Logs (Optional)

[log(Copy).txt](https://github.com/user-attachments/files/18098810/log.Copy.txt)

**Comment by JaimieVandenbergh** [comment]
Wrong github for this report - Android isn't in Cemu yet. You need to report to ssimco's github.

**Comment by Squall-Leonhart** [comment]
Wonder if a quick pr directing android issues there wouldn't be illogical in the bug form.
