### ISSUE TITLE
[Linux] Splatoon: Failed to create texture sampler on NVK/nouveau drivers

### ISSUE THREAD

**Issue by ashquarky** [cemu-project/Cemu#1449]
### Current Behavior

I am experimenting with the nouveau/NVK video drivers on my Linux system, and noted that Splatoon will get through the initial loading screens before crashing when attempting to render the title screen (presumably the first use of 3D).

The same setup works fine on the proprietary NVIDIA graphics drivers, so I presume there is some missing feature in the open drivers that Cemu needs.

### Expected Behavior

Cemu does not crash and the game renders correctly

### Steps to Reproduce

1- Use a recent Mesa driver on your Linux system (Fedora is a good testbed for this - they ship recent Mesa and don't include the proprietary drivers by default)
2- If coming from another driver, delete the shader cache (`~/.cache/Cemu/shaderCache`)
3- Open Cemu and launch Splatoon v288
4- Game crashes after the loading screen

### System Info (Optional)

OS: Fedora Linux 41 w/ Mesa 24.2.8
GPU: NVIDIA GeForce RTX 2070 SUPER

### Emulation Settings (Optional)

Pretendo Network is set up and MLC location is customised (I use multiple instances in parallel for different tests - this issue appears even with a single instance, though)

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/18121427/log.txt)

**Comment by Squall-Leonhart** [comment]
> [15:47:19.131] VK_FORMAT_R4G4_UNORM_PACK8 not supported
> [15:47:19.131] VK_FORMAT_R5G5B5A1_UNORM_PACK16 not supported

These are present on proprietary drivers.

**Comment by Exzap** [comment]
Can you run Cemu with `debug -> Vulkan validation layer` enabled and upload the log afterwards? It requires Vulkan validation layer installed which I think is in package `vulkan-validation-layers`

**Comment by ashquarky** [comment]
Sure. I've done two runs, the first is with whatever shader cache was present (possibly from an old Cemu build?), which seems to have caused a lot of noise in the logs:  [log-wcache.txt](https://github.com/user-attachments/files/18138627/log-wcache.txt)

This second run was done with a clean shader cache:  [log.txt](https://github.com/user-attachments/files/18138628/log.txt)

To me, this is the most interesting message, but I'm curious what you see in it:
```
[13:25:33.859] Validation Error: [ VUID-vkCreateSampler-maxSamplerAllocationCount-04110 ] | MessageID = 0xb408bc0b | vkCreateSampler():  Number of currently valid sampler objects (4095) is not less than the maximum allowed (4000).
```

**Comment by ashquarky** [comment]
Also, since there's mention of transform feedback and other extensions: [vulkaninfo.txt](https://github.com/user-attachments/files/18138639/vulkaninfo.txt)

**Comment by Exzap** [comment]
Thanks for the log. We are hitting the hard limit of 4096 Vulkan sampler objects in NVK.
I implemented an optimization so that Cemu avoids creating redundant samplers which brings down the number quite a lot. Can you try the appimage from here: https://github.com/Exzap/Cemu/actions/runs/12344307699

**Comment by ashquarky** [comment]
![image](https://github.com/user-attachments/assets/6025544a-fb9b-4617-90c9-305bf24dcd84)

Works great now, thank you! I was able to play locally with decent performance (even with Vulkan validation on). Looks like I will be able to continue using these drivers :)
Logs from a successful session: [log.txt](https://github.com/user-attachments/files/18143971/log.txt)
