### ISSUE TITLE
Shader pre-cashing or something like that

### ISSUE THREAD

**Issue by thanone2** [cemu-project/Cemu#1458]
### Your suggestion

my idea is, like in Forza Horizon where it does a pc benchmark mode, but do something like that for each game you start so it doesn't slow down from compiling things while playing, like some of the community when playing mk8 for the first time on their install of cemu, they let it play through the clips to let it compile the shaders and pipelines before they play so there's next to no slowdowns.

**Comment by JaimieVandenbergh** [comment]
If you read the official guide you'll see there's a repository of shader caches you can choose to use. 
https://cemu.cfw.guide/optimizing-cemu.html

**Comment by mrthethatone** [comment]
https://chriztr.github.io/cemu_shader_and_pipeline_caches/
