### ISSUE TITLE
[Feature Request] Windows High DPI Support (Make Cemu DPI Aware)

### ISSUE THREAD

**Issue by BigheadSMZ** [cemu-project/Cemu#155]
When Windows scaling is set to something higher than 100%, which is common on 2160p displays or even 1440p, Windows scales the GUI using a bilinear filter which in turn makes it appear blurry. This can be worked around with [Right Click > Properties > Compatibility Tab > Change high DPI settings >Override high DPI scaling behavior. Scaling performed by: Application], but scaling it this way creates some imperfections and hidden GUI elements. Making Cemu DPI Aware could solve this issue so this workaround is no longer needed, and the GUI would look clean when larger scaling values are used.

**Comment by bitscher** [comment]
For anyone interested in fixing this issue: https://docs.wxwidgets.org/trunk/overview_high_dpi.html

**Comment by leifliddy** [comment]
![Screenshot from 2022-09-03 03-11-05](https://user-images.githubusercontent.com/12903289/188250485-0ee7b79f-7c70-42a4-a6be-1e38acec1bf6.png)
Not sure if this is related or not. But in Linux (Fedora 37, Cinnamon). If I set the the scaling to 200% on a 4k display -- the output will be relegated to the upper-left quadrant of the cemu window. If the scaling is set to 100% the full window will be used.
