### ISSUE TITLE
[Feature Request] MSYS2/MinGW64 compilation

### ISSUE THREAD

**Issue by thesword53** [cemu-project/Cemu#158]
Since Linux/GCC is spported, it would be great to have MinGW64/GCC.

**Comment by Zopolis4** [comment]
I've had a look, and vcpkg seems to be getting in the way. I tried 
 ```
-DCMAKE_HOST_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCE
SSOR=x86_64 -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++
```
But it appears vcpkg does not like compiling windows triplets on anything but the VS command prompt.
Community triplets might work.

**Comment by capitalistspz** [comment]
Using the latest vcpkg repo with `x64-mingw-static` triplet, it fails when it reaches `glslang`

**Comment by Zopolis4** [comment]
Same thing happened to me. Looking at the logs, it seems the mingw version of g++ is not updated enough, being only on gcc 10 and thus not having enough compatibility with the stdlib.

**Comment by capitalistspz** [comment]
I usually use Fedora with `dnf` but Fedora repos with `dnf` don't have a few of the required `mingw64` packages I used `pacman`

I added mingw64 and msys to the bottom of my `/etc/pacman.conf`
```
[mingw64]
Server = https://repo.msys2.org/mingw/mingw64/

[msys]
Server= https://repo.msys2.org/msys/$arch/
```
When installing mingw packages they seem to install to `/mingw64` by default

Add keys for pacman
```
sudo pacman -S msys2-keyring
```
This didn't work for me originally so I went and manually added the keys manually from 
https://www.msys2.org/dev/keyring/

Installed the build packages
```
sudo pacman -S mingw-w64-x86_64-SDL2 mingw-w64-x86_64-wxWidgets3.2 mingw-w64-x86_64-pugixml mingw-w64-x86_64-glslang mingw-w64-x86_64-rapidjson mingw-w64-x86_64-boost mingw-w64-x86_64-libzip mingw-w64-x86_64-glm mingw-w64-x86_64-fmt8 mingw-w64-x86_64-libpng
```
Used `vcpkg` to install `imgui`:
```
vcpkg install imgui:x64-mingw-static
```
copied the files from vcpkg/packages/imgui to dependencies/mingw_manual

cmake configure with these args on top of the usual args
`-DCMAKE_FIND_ROOT_PATH=$CMakeProjectDir$/dependencies/mingw_manual;/mingw64 -DENABLE_VCPKG=false -DMINGW=true -DCMAKE_FIND_DEBUG_MODE=true`

And then it fails to find opengl
- Installing `mingw64/mingw-w64-x86_64-mesa` and also symlinking `opengl32.dll.a` to `opengl.a` `opengl32.a` `OpenGL32.a`
- Using the path of mingw libs that are installed when you add the mingw compiler from fedora repos (args changed to `-DCMAKE_FIND_ROOT_PATH=$CMakeProjectDir$/dependencies/mingw_manual;/usr/x86_64-w64-mingw32/sys-root/mingw -DENABLE_VCPKG=false -DMINGW=true -DCMAKE_FIND_DEBUG_MODE=true`)
Regardless of these it could not find opengl

**Comment by Zopolis4** [comment]
That might just be a regular Cemu issue, the vcpkg disabled mode is somewhat broken.

**Comment by capitalistspz** [comment]
Removing the cmake build directory and restarting my IDE caused cmake to find opengl. 

It then couldn't find wxWidgets (forgot to install that) and installed it
```
sudo pacman -S mingw-w64-x86_64-wxwidgets3.2-common mingw-w64-x86_64-wxwidgets3.2-common-libs mingw-w64-x86_64-wxwidgets3.2-gtk3 mingw-w64-x86_64-wxwidgets3.2-gtk3-libs mingw-w64-x86_64-wxwidgets3.2-msw mingw-w64-x86_64-wxwidgets3.2-msw-libs
```
And it couldn't find it.

I then tried 
```
sudo dnf install mingw64-wxWidgets3-static
```
and cmake found it, but it's outdated (repo version was 3.0).
I changed the `CMakeLists.txt` to accept wxWidgets 3.0 and it got past that without error. And the next error was about cubeb, but it ignored it.

#### Then I hit this
```
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "CemuCommon" of type SHARED_LIBRARY
    depends on "CemuCafe" (weak)
    depends on "CemuConfig" (weak)
    depends on "CemuComponents" (weak)
  "CemuGui" of type SHARED_LIBRARY
    depends on "CemuAudio" (weak)
    depends on "CemuCafe" (weak)
    depends on "CemuCommon" (weak)
    depends on "CemuComponents" (weak)
    depends on "CemuConfig" (weak)
    depends on "CemuInput" (weak)
    depends on "CemuResource" (weak)
    depends on "CemuUtil" (weak)
  "CemuCafe" of type SHARED_LIBRARY
    depends on "CemuAudio" (weak)
    depends on "CemuCommon" (weak)
    depends on "CemuComponents" (weak)
    depends on "CemuConfig" (weak)
    depends on "CemuGui" (weak)
    depends on "CemuInput" (weak)
    depends on "CemuResource" (weak)
    depends on "CemuUtil" (weak)
    depends on "imguiImpl" (weak)
  "CemuComponents" of type SHARED_LIBRARY
    depends on "CemuCafe" (weak)
    depends on "CemuCommon" (weak)
    depends on "CemuConfig" (weak)
    depends on "CemuGui" (weak)
    depends on "CemuUtil" (weak)
  "CemuConfig" of type SHARED_LIBRARY
    depends on "CemuCafe" (weak)
    depends on "CemuCommon" (weak)
    depends on "CemuUtil" (weak)
  "CemuInput" of type SHARED_LIBRARY
    depends on "CemuCafe" (weak)
    depends on "CemuCommon" (weak)
    depends on "CemuConfig" (weak)
    depends on "CemuGui" (weak)
    depends on "CemuUtil" (weak)
  "CemuAudio" of type SHARED_LIBRARY
    depends on "CemuCafe" (weak)
    depends on "CemuCommon" (weak)
    depends on "CemuConfig" (weak)
    depends on "CemuGui" (weak)
    depends on "CemuUtil" (weak)
  "CemuUtil" of type SHARED_LIBRARY
    depends on "CemuCommon" (weak)
    depends on "CemuConfig" (weak)
  "imguiImpl" of type SHARED_LIBRARY
    depends on "CemuCafe" (weak)
    depends on "CemuCommon" (weak)
    depends on "CemuGui" (weak)
    depends on "CemuInput" (weak)
    depends on "CemuResource" (weak)
    depends on "CemuUtil" (weak)
  "CemuResource" of type SHARED_LIBRARY
    depends on "CemuCommon" (weak)
    depends on "CemuComponents" (weak)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
CMake Generate step failed.  Build files cannot be regenerated correctly.

[Failed to reload]
```
Now I have absolutely no idea what to do about that so I give up

**Comment by Zopolis4** [comment]
Alright even on debian sid my mingw is outdated, one could try to use something [else](https://www.mingw-w64.org/downloads/), I'll wait until debian sid updates the mingw gcc to 11/12/whatever supports `std::mutex`.

**Comment by kevincrans** [comment]
Can't you just use [WSL](https://devblogs.microsoft.com/cppblog/c-with-visual-studio-2019-and-windows-subsystem-for-linux-wsl/)?

**Comment by Zopolis4** [comment]
Where does WSL come into play here?

**Comment by kevincrans** [comment]
When u want to compile with linux tools on windows, without things that don't natively come with Windows, Linux and Cemu build requirements.

**Comment by Zopolis4** [comment]
uhh
WSL still has to be installed and enabled on Windows, its not the default. It also still offers the same, if not more outdated, versions of mingw-gcc, and requires admin to set up.
MSYS2 offers more up-to-date versions of mingw, and doesn't require admin and is portable.

**Comment by kevincrans** [comment]
Not more outdated because it's literally the real Linux you pick and a part of WSL is already installed inside the NT kernel. It also doesn't need MinGW, wsl Ubuntu has gcc without it.

**Comment by capitalistspz** [comment]
> Can't you just use [WSL](https://devblogs.microsoft.com/cppblog/c-with-visual-studio-2019-and-windows-subsystem-for-linux-wsl/)?

I can't use WSL on Linux to compile targetting Windows

**Comment by Zopolis4** [comment]
You technically can (it's how i tested) but it's dependency hell if your package manager uses precompiled binaries, and you get a more outdated version of mingw-gcc.

**Comment by Exzap** [comment]
Closing since there is a lack of interest. If anyone wants to spearhead this feel free to open a draft PR or a new issue.
