### ISSUE TITLE
[Linux] unshare: failed to execute ./Cemu: No such file or directory

### ISSUE THREAD

**Issue by bg2908** [cemu-project/Cemu#182]
Just updated `aur/cemu-git` to version `2.0.r85.ga54a3ec-1` and it started to have this error:
`unshare: failed to execute ./Cemu: No such file or directory`

Edit line 20 of `/usr/bin/cemu` from
`exec unshare --map-user=$UID --map-group=$GID --wd="\$overlay" ./Cemu "\$@"`
to
`exec unshare --map-user=$UID --map-group=$GID --wd="\$overlay" ./Cemu_release "\$@"`
and it work again.

Maybe something to do with commit [4ed18a6](https://github.com/cemu-project/Cemu/pull/179/commits/6ce4ee137b16ccb8ad282ea947d69b20aecf1562)

**Comment by Crementif** [comment]
The cemu-git is unofficial and not something we support.
