### ISSUE TITLE
[Linux] Audio refused to work on PipeWire

### ISSUE THREAD

**Issue by YidaozhanYa** [cemu-project/Cemu#197]
Cemu version: 2.0-1
Distro: Arch Linux
Audio backend: cubeb (the only avaliable option)
PipeWire: 0.3.57

When I start the game with Cemu's audio enabled, it crashes and returns a SIGSEGV! error (I don't know if this is a problem unique to PipeWire or if it's a problem with all Linux)

```
SIGSEGV!
Error: signal 11:
cemu(+0x91c80f)[0x55f3cb02f80f]
/usr/lib/libc.so.6(+0x38a40)[0x7fd0bce51a40]
cemu(+0xc32aa4)[0x55f3cb345aa4]
cemu(+0xc1a559)[0x55f3cb32d559]
cemu(+0xc16146)[0x55f3cb329146]
cemu(+0xb774e5)[0x55f3cb28a4e5]
cemu(+0x6f798c)[0x55f3cae0a98c]
cemu(+0x649c88)[0x55f3cad5cc88]
cemu(+0x6489b7)[0x55f3cad5b9b7]
cemu(+0x651a6d)[0x55f3cad64a6d]
/usr/lib/libstdc++.so.6(+0xd62f3)[0x7fd0bd0d62f3]
/usr/lib/libc.so.6(+0x8678d)[0x7fd0bce9f78d]
/usr/lib/libc.so.6(__clone+0x44)[0x7fd0bcf208e4]
terminate called without an active exception
zsh: IOT instruction (core dumped)  cemu
```

**Comment by YidaozhanYa** [comment]
![图片](https://user-images.githubusercontent.com/73830635/188867648-95ed9915-e539-4427-b7ba-0d49808ded7b.png)

**Comment by kugelvlitz** [comment]
Having the same issue, is there a workaround?
