### ISSUE TITLE
(Steam Deck) Missing textures on Twilight Princess HD

### ISSUE THREAD

**Issue by nameless1** [cemu-project/Cemu#212]
Includes Versions 1.27.1 through 2.0.1 experimental.
There are missing textures while using vulkan shader on the steam deck including both the waterfall and rupee textures just during the beginning of the game, haven't gone further than that. Textures show up fine using opengl but the performance is unusable on deck. All textures load fine on windows machine so possibly a driver issue on the deck?

**Comment by JakobDev** [comment]
You write about Version 1.27.1 and 2.0.1. Did you run 2.0.1 with Proton or as the native Linux Version?

**Comment by nameless1** [comment]
Proton, Only saw a native ubuntu build on the download section and the last time I tried to set up a build environment on my deck I had to reimage it, so waiting for an arch build or appimage.

**Comment by Tk-Glitch** [comment]
Native Linux builds are currently slower than using older Windows builds through Proton (~30% perf drop on my 5950x vs 1.22.9d but it's apparently worse with slower CPUs if reports on reddit are anything to go by), so you may not get the desired perf level on a Steam Deck.

**Comment by IAmTheRedSpy** [comment]
Darbus/Fyrus' firey arm textures don't show during his boss fight in Goron Mines. The black textures and fire effects display correctly.

Howling Stones don't display what to play or what you're playing.

Sometimes the warp animation makes models invisible - most noticable during cutscenes like the one after finishing Goron Mines. Maybe this is an transparent texture?

Tested with 1.27.1 on Proton 7.0. Unfortunately OpenGL is just barely too intense for the Steam Deck.

**Comment by Exzap** [comment]
I'm assuming this is fixed since there have been no new reports. If there are still broken textures then please open a new issue and provide screenshots and a save file.

**Comment by jackgllghr** [comment]
Can confirm this is still an issue. Will post version details etc later as I don't have my Deck to hand, updated Cemu through EmuDeck yesterday.

The issue is as described above, rupee counter isn't shown, and during the wolf howling stones, notes to play aren't displayed nor is what the player inputs, haven't tried switching to OpenGL, this is with the EmuDeck default settings(which I believe is using Vulcan)

**Comment by jackgllghr** [comment]
Can confirm that updating to Cemu 2+ fixes this and other missing UI issues like ammo count. 

For anyone using Emudeck on Steam Deck, you actually have to go to Emudeck -> Tools & Stuff -> Update Emulators & Tools, and then select the 2+ version of Cemu when prompted, the default updater installs 1.27.1 which has the above issue
![image](https://user-images.githubusercontent.com/6088001/216316696-4f71add2-aa51-4545-bfe3-e7dcf215008a.jpeg)

**Comment by Crementif** [comment]
Thanks for commenting how you fixed your issues. And yeah, the fix Exzap made in september will only be for Cemu 2.0 and beyond.
