### ISSUE TITLE
[Feature Request] Option to launch into Wii U Menu itself from dropdown list?

### ISSUE THREAD

**Issue by some-username-here1** [cemu-project/Cemu#213]
Like what was implemented into RPCS3, and if it isn't too hard to implement, an option to launch into the Wii U's Menu from the "File" dropdown, emulating a cold boot.

**Comment by Exzap** [comment]
FYI you can launch the Wii U menu from the game list if you have it dumped. But it's pretty useless right now because it's just a launcher and Cemu does not yet support title switching.
