### ISSUE TITLE
Improve mouse selection triple click in BUILD.md

### ISSUE THREAD

**Issue by superbonaci** [cemu-project/Cemu#225]
In file `BUILD.md` the instructions 1, 2, 3 and 4 work fine to select command line with mouse triple click. However point 5 and GCC command if you do triple mouse click it selects the entire line instead of just the command.

OK:

![](https://i.imgur.com/7MRzfcu.png)

NOT OK:

![](https://i.imgur.com/gOWOUo1.png)

![](https://i.imgur.com/qH4MDnP.png)

**Comment by Exzap** [comment]
If you find a way to change this you are free to do a pull-request. But I doubt we can change browser behavior.
