### ISSUE TITLE
The Cemu build docs need to have vcpkg as a dependency

### ISSUE THREAD

**Issue by samiscool51** [cemu-project/Cemu#230]
when configuring the source for compiling, it complains that vcpkg isnt installed.
as far as i know there aren't any pre-compiled packages of it but a link to the vcpkg repo in the dependency's will lower the barrier to entry for new users trying to compile cemu.
https://github.com/Microsoft/vcpkg#getting-started

**Comment by Exzap** [comment]
vcpkg is bundled as a git submodule, you don't need to install it separately. You probably forgot the `--recursive` flag during git clone.
