### ISSUE TITLE
Donkey Kong Country: Tropical Freeze - crash on load

### ISSUE THREAD

**Issue by Shoegzer** [cemu-project/Cemu#235]
While other titles are now loading and going ingame on Linux, the above title still crashes for some reason.

Information:
* OS: Linux Mint 21 (Ubuntu 22.04 base)  / kernel 5.15
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070 / driver 515.65
* Commit: 3349d7b4245e9bee862ee53a04196357fbedc99d
* Backtrace: [backtrace.txt](https://github.com/cemu-project/Cemu/files/9539365/backtrace.txt)

**Comment by MaranBr** [comment]
Stuck on the loading screen on Windows 10 21H2 too.

**Comment by Shoegzer** [comment]
Tested this title against 5e968eff4fee065bfc117d580d51553896cd5a88 which includes #264 that I guessed may have resolved the issue, but it still crashes on load.

**Comment by kturques** [comment]
Game is working here.

OS: OpenSuse Tumbleweed - Kernel: 5.19.8-1
CPU: AMD Ryzen 9 5900X
GPU: AMD Radeon RX 5700 XT / Mesa 22.1.7
Using CEMU version: 5e968ef, but the game has been working since cf598e3

Maybe the problem only occurs on Nvidia drivers

**Comment by Shoegzer** [comment]
Could be, though it would help to have another Nvidia user confirm.  I deleted shader cache too which was known to cause issues, but it still crashed.

@MaranBr Could you please retest against latest master and also let us know your Nvidia driver version?

**Comment by MaranBr** [comment]
I tested it again with the last commit [9f02733](https://github.com/cemu-project/Cemu/commit/9f02733a0dfa7f8e35bbe0ed245b443b23c6f4a8). But the game still doesn't get past the loading screen.

* NVIDIA Driver: 516.94

**Comment by Shoegzer** [comment]
Thanks, you're not too far off from drivers on this test system, as noted above.  Also, do you have any title updates installed?  Testing here was performed with and without the last update for the title (so v2 and v16 respectively).

**Comment by askotx** [comment]
Win 10 21H2 confirmed
Nvidia gt 1030
Cemu 2.0-4 (Experimental) still with issues

**Comment by AMDBartek** [comment]
I can confirm that it is stuck on the loading screen (v16), this crash also happens even if you have the 4 "FFL" files dumped from a Wii U.

![image](https://user-images.githubusercontent.com/46637209/193456803-6adf1768-b3c5-4a6f-a01c-0173f39b5b7e.png)
(I know it says Minecraft but hunting down these files from my old Wii U dump has fixed several games as well as Minecraft however DKC: Tropical Freeze still freezes (lol) even with them present)

**Comment by Shoegzer** [comment]
Update: Crashing seems to be gone as of commit 4519a59d746dc0eb2a427c0f379c6c4c600d89dd, though given that we've had a range of results on this one, I'd like to have at least one other tester that recently reported this issue confirm positive results before closing.  Thanks.

**Comment by AMDBartek** [comment]
Unfortunately that commit did not fix the issue for me. I have compiled Cemu with GCC 11.2.0 on an Ubuntu-based system.

If you need additional info then please feel free to ask

**Comment by MaranBr** [comment]
Still stuck on the load screen with the last commit.

**Comment by MaranBr** [comment]
It looks like the problem has been resolved. In the latest version available [271a4e4]([271a4e4](https://github.com/cemu-project/Cemu/commit/271a4e4719463ece58db74b9c390f83bf6e956cf)), the problem no longer occurs.

**Comment by Shoegzer** [comment]
Thanks, and yeah this is resolved.  Closing.

**Comment by dmanlfc** [comment]
This is not resolved on Linux please re-open.

**Comment by Exzap** [comment]
No need to hijack resolved issues. If there is an additional problem then please open another issue and provide as much detail as possible (back trace, log.txt etc).
