### ISSUE TITLE
Make a commitment to support non-systemd systems

### ISSUE THREAD

**Issue by throwaway1037** [cemu-project/Cemu#24]
#18 seems to imply that Cemu depends on `systemd-libs`.

Please may the Cemu team make a commitment to support non-systemd distros by making the dependency on systemd optional, or ideally, by dropping it entirely?

**Comment by dmanlfc** [comment]
Agreed

**Comment by oatmealine** [comment]
Is there any particular reason systemd is needed for Cemu? I can't imagine many reasons why such a dependency is needed. Void Linux (runit) user here; would also love to see non-systemd system support!

**Comment by Exzap** [comment]
This is currently being looked into. It was not an intentional decision.

**Comment by Tachi107** [comment]
Linking to libsystemd doesn't necessarily mean that systemd is required to use Cemu :)

**Comment by adcdam** [comment]
i dont know others mention its a hard dependency, having  support non-systemd distros by making the dependency on systemd optional would be great. I want to package this.

**Comment by Tachi107** [comment]
Have you actually tried building Cemu? On my system (Debian Testing) I've been able to build Cemu without having `libsystemd-dev` installed.

**Comment by Exzap** [comment]
To bypass the systemd requirement Cemu can be build with system libraries instead of vcpkg (`-DENABLE_VCPKG=OFF`).
Why exactly the wxWidgets port for vcpkg requires systemd is still not known. Someone would have to investigate or bring this up upstream with whoever maintains the port.
