### ISSUE TITLE
[Feature Request] A Command-Line Flag to Choose an Input Profile

### ISSUE THREAD

**Issue by notabirb1** [cemu-project/Cemu#242]
One thing many people like to do is put shortcuts to their Wii U Games in launchers such as Steam. This has gotten even more popular with the release of the Steam Deck. However, it is currently impossible to create a shortcut to a Cemu game with a custom shortcut without a separate installation of Cemu. This can be very inconvenient, as having separate installations of Cemu for every game isn't ideal. Having a command line flag to launch Cemu with a specified input profile would be a nice feature for many people.

**Comment by Exzap** [comment]
Not sure if you were aware, but you can configure per-game input profiles via the game profile window. Right click a game in the game list -> Controller tab.

**Comment by notabirb1** [comment]
Oh, it appears you can! Sorry, I didn't realize you could do this.
