### ISSUE TITLE
TV Audio setting does not select automatically playback device

### ISSUE THREAD

**Issue by superbonaci** [cemu-project/Cemu#244]
Tested latest commit on Arch linux:
[6cf5dc9](https://github.com/cemu-project/Cemu/commit/6cf5dc9a569315969aeaec71f058b4fa8bf16993)

Going to `Options - General settings - Graphics` does indeed properly select `Graphics API` and `Graphics Device` (example Nvidia GTX xxxx)
However `Audio - TV - Device` is set to `Disabled` after compilation, with `API=Cubeb`.
There isn't any major issue since I can switch to the playback device that uses my dekstop environment.
Could be possible to auto-detect audio playback device or is not recommended?

**Comment by Squall-Leonhart** [comment]
duplicate
