### ISSUE TITLE
[Feature Request] Remote Gamepad support.

### ISSUE THREAD

**Issue by Bitwolfies** [cemu-project/Cemu#250]
Yeah, long shot and tons of work I know, and its something that can sorta be achieved already with specialized VNC configs. But regardless, now that we have the Steam Deck, we actually have a good way to preserve the gamepad experience. Being able to run the cemu workload on our pc's while streaming the screen output/controller/gyro/speaker/mic inputs to the deck would be as close to a real Wii U experience as we can get. 

Its a long shot, not critical at all, but would be amazing.

**Comment by capitalistspz** [comment]
Couldn't you use Steam's game streaming, Sunshine/Moonlight gamestream, or Parsec for this purpose? These all support inputs, audio and video being sent across the network for the purpose of gaming.

**Comment by Bitwolfies** [comment]
> Couldn't you use Steam's game streaming, Sunshine/Moonlight gamestream, or Parsec for this purpose? These all support inputs, audio and video being sent across the network for the purpose of gaming.

You “can” but they only allow mirrored screens, so no proper separate game pad view.

**Comment by Haxorzz** [comment]
> > Couldn't you use Steam's game streaming, Sunshine/Moonlight gamestream, or Parsec for this purpose? These all support inputs, audio and video being sent across the network for the purpose of gaming.
> 
> You “can” but they only allow mirrored screens, so no proper separate game pad view. If they update with the option to treat the second screen as a second monitor my request would be moot.

https://twitter.com/_GameXData/status/1566487730531467268?t=Ti2eBc0NxOhgVNVOGDCOFA&s=19

**Comment by Bitwolfies** [comment]
> > > Couldn't you use Steam's game streaming, Sunshine/Moonlight gamestream, or Parsec for this purpose? These all support inputs, audio and video being sent across the network for the purpose of gaming.
> > 
> > 
> > You “can” but they only allow mirrored screens, so no proper separate game pad view. If they update with the option to treat the second screen as a second monitor my request would be moot.
> 
> https://twitter.com/_GameXData/status/1566487730531467268

Requires a cable hooked into a second screen, which is what im trying to avoid, the Wii U wasn't wired.

**Comment by Haxorzz** [comment]
There are streaming programs that allow you to just stream a certain window

**Comment by Exzap** [comment]
It would be nice to have alternatives to the GamePad (e.g. via phone or Steam Deck) natively integrated into Cemu but it's quite a lot of effort and outside of the scope of the project for now.
