### ISSUE TITLE
[Feature Request] preventing linux to go in to standby while playing

### ISSUE THREAD

**Issue by hannescam** [cemu-project/Cemu#259]
i have archlinux with x11 gnome and cemu built from source running mariokart 8 and i am using a dualshock ps4 controller over bluetooth but after the set ammount of inactivity time the screen turns off and cemu doesnt prevent that

**Comment by AMDBartek** [comment]
I was experiencing the same issue, as a workaround I have used caffeine-ng. 

I don't use Arch however I found the official AUR package for caffeine-ng: https://aur.archlinux.org/packages/caffeine-ng

Usage: `caffeinate COMMAND`

In this case: `caffeinate ./Cemu_release` in the Cemu bin folder or wherever you have Cemu installed.

I hope this helps, I wrote this on my phone so sorry for the bad layout.

**Comment by kturques** [comment]
I think that should work like in Firefox and Steam, they prevent suspension while playing audio/video or a game:
![Screenshot_20220917_151015](https://user-images.githubusercontent.com/72952967/190871039-3f60cf25-8378-40c7-a0af-a7f38ea3d7e3.png)
![Screenshot_20220917_151347](https://user-images.githubusercontent.com/72952967/190871058-0d654cd2-fa5e-4783-baae-eefc5ce365d2.png)

Dolphin (Emulator) also have this feature:
![Screenshot_20220917_152926](https://user-images.githubusercontent.com/72952967/190871544-8b61a6e1-67ce-4b09-96b0-ea2e7ebd342c.png)
Shouldn't be necessary to install external apps when the same can be achieved by the application

**Comment by hannescam** [comment]
thankyou i did try to play a audio in the background and muting it but my cpu was struggling with the game alone and with the audio mario kart 8 was unplayable

**Comment by lisa-wolfgang** [comment]
Using `gamemode` as a built-in C library seems like it would be easily doable. [See this example](https://github.com/FeralInteractive/gamemode/tree/master/example).

**Comment by lisa-wolfgang** [comment]
Upon further investigation, GameMode requires an external installation, which is not ideal for a basic function such as screen saver inhibition. The following are potential implementations that do not require additional installation:
- The [org.freedesktop.ScreenSaver interface](https://people.freedesktop.org/~hadess/idle-inhibition-spec/re01.html) -- used by [GameMode](https://github.com/FeralInteractive/gamemode/blob/b11d2912e280acb87d9ad114d6c7cd8846c4ef02/daemon/gamemode-dbus.c#L711)
- xdg-screensaver -- used by [Dolphin](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/UICommon/X11Utils.cpp#L48)
