### ISSUE TITLE
[Bug] Characters clothes or faces in Tekken Tag Tournament 2 either have missing textures or have one color only

### ISSUE THREAD

**Issue by GoodWall533** [cemu-project/Cemu#269]
Tekken Tag Tournament 2 has an issue where characters clothes, or even sometimes their faces, are all one single color or have missing textures. To reproduce the issue, simply go to any match in any mode as any characters and this issue will happen regardless. Cemu version is 2.0-2 (experimental).

Here's a screenshot of the issue in question: 
![screenshot_1](https://user-images.githubusercontent.com/73701483/190902640-41291811-0ab3-46ec-9ce5-c6ef4da9ea63.png)

Here's the game supposed to look with a screenshot from real hardware: 
![2022-09-18 (2)](https://user-images.githubusercontent.com/73701483/190902712-77ef93be-1e8f-4183-8336-b17e0a6a804f.png)

Specs:
GTX 960 2gb
Ryzen 5 3500x
16GB Ram

**Comment by s8n187** [comment]
same issue here , slightly different hardware.

Intel CPU
AMD GFX Card
Cemu v2.0-4

**Comment by leifliddy** [comment]
duplicate issue https://github.com/cemu-project/Cemu/issues/23

**Comment by GoodWall533** [comment]
Weird, I actually tried to see if there was another open issue for Tekken Tag Tournament 2 before i made this one but couldn't find one because the name of the game wasn't spelled correctly. Oh well. since it's a duplicate, i'll be closing this.
