### ISSUE TITLE
[Linux] [Skylanders] USB Support for Portal of Power

### ISSUE THREAD

**Issue by louisefindlay23** [cemu-project/Cemu#275]
It would be great to have USB support in the Linux build of Cemu for games that require USB accessories to function such as Skylanders and its Portal of Power. 

The Portal is recognised under Linux (at least SteamOS) with lsusb and lights up but is not detected in-game.

Using Cemu 1.26.2f via EmuDeck on Steam Deck playing Skylanders Trap Team with the Traptanium Portal.

Also tried the Windows version via Lutris and several Proton versions but the error persists (except for Proton 6.3 which claims incompatible portal - can confirm I'm using the correct portal as works with Dolphin).

Happy to help test if needed as I have portals from several games to confirm compatibility.

**Comment by andygrillo** [comment]
I believe the emudeck version of cemu is windows using wine

**Comment by andygrillo** [comment]
I am also interested in this. I run Cemu via Wine in HoloISO, and the portal isnt recognized. 

I compiled Cemu for arch linux and it runs, but the performance isnt great. Hopefully when this is fixed, then we can enjoy using the portal with native Cemu in Linux.

**Comment by louisefindlay23** [comment]
> I am also interested in this. I run Cemu via Wine in HoloISO, and the portal isnt recognized. 
> 
> 
> 
> I compiled Cemu for arch linux and it runs, but the performance isnt great. Hopefully when this is fixed, then we can enjoy using the portal with native Cemu in Linux.

Does the portal work with native version? I've only tried emulating Windows via Proton and Wine.

**Comment by chimeforest** [comment]
I'd like for this to be a thing too. I also have a Traptanium Portal and a Steam Deck with EmuDeck.

**Comment by RubixDev** [comment]
Issue #107 describes the progress of Linux support, and HID devices are not supported yet. I can also confirm that running Cemu through Proton (I use EmuDeck) also does not detect such devices. For Lego Dimensions I'm currently using the PS3 version with the RPCS3 emulator which works with the ToyPad on Linux, but the performance is much worse there, so I would love to see Cemu support this on Linux too.

**Comment by Vicourld51** [comment]
I saw that the RPCS3 code for portal of power had been used on dolphin, is it possible to adapt it to cemu?

**Comment by FlashFyreMods** [comment]
I like how this is closed as completed, AND HID support is checked off in issue #107, yet this still doesn't seem to work.
