### ISSUE TITLE
Cemu crashes when closing seperate GamePad view

### ISSUE THREAD

**Issue by Her0brineCreeper** [cemu-project/Cemu#278]
Whenever the seperate "GamePad view" window is closed while a game is running, the Cemu emulator crashes immediately. It doesn't matter wether the X (close) button of the window or the Options->Seperate GamePad view button is used. When no game is running, the window can be opened and closed without any problems. The crash occures with every game I tested.
No crash dump is being created eventhough the option is set in the settings. Maybe the attached [log.txt](https://github.com/cemu-project/Cemu/files/9608526/log.txt) file contains any useful information.

System details:
Cemu 2.0-2 (Experimental)
Windows 10 21H2 64-Bit
AMD Ryzen 5 2600X
16 GB RAM
NVIDIA GeForce RTX 2060 SUPER

**Comment by Squall-Leonhart** [comment]
This is vulkan specific, and only affects nvidia drivers.

**Comment by goeiecool9999** [comment]
Can you try again with the latest version see if the crash still occurs?

**Comment by Her0brineCreeper** [comment]
The issue is fixed for me with the latest version of Cemu (2.0-15). Closing the windows works fine now according to my tests.
Thank you very much for your work in fixing this issue :D

**Comment by SessionLoops** [comment]
@goeiecool9999 Hi, could you share what might cause the crash? I'm a developer and facing same issues too. Thanks in advance!

**Comment by Squall-Leonhart** [comment]
review the referenced changes
