### ISSUE TITLE
Steamdeck build process / feedback for Cemu 2.0

### ISSUE THREAD

**Issue by brookpatten** [cemu-project/Cemu#281]
I have built Cemu 2.0 (native linux, not windows) to run on steamdeck.
I used Docker, and the below dockerfile and the instructions provided in build.md for arch.
As requested in build.md, I wanted to share some findings.

```
FROM ekultails/steamos:latest
RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm git cmake gcc ninja nasm base-devel linux-headers gtk3 libsecret libgcrypt systemd freeglut zip libpulse unzip glu

RUN git clone --recursive https://github.com/cemu-project/Cemu.git
WORKDIR /Cemu
RUN git checkout tags/v2.0-2

RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja
RUN cmake --build build
```

- First, I needed to include the "glu" package or wxwidgets failed.

- Second, I needed to append -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja to the dependency build.

- Third, I needed to use gcc instead of clang.

Otherwise, this process appears to produce a working build for steamdeck.
I hope these details are helpful to someone, I could PR an update to build.md if desired, but I am hesitant because to be honest I am not actually much of a C/C++/Linux developer.

I assume once flatpak is sorted out none of this matters.

**Comment by Haxorzz** [comment]
> I assume once flatpak is sorted out none of this matters.
yes, but it seems that it still far away, and I kinda need my cemu fix, so thank you for this.

**Comment by Star-X555** [comment]
Just a question.  How'd you deal with Cemu run as a nonsteam game in Game Mode CONSTANTLY opening the onscreen keyboard if even one key is pressed either through Steam Input or via a physical keyboard pluggeed in, and sometimes just entirely randomly?  It's insanely aggrivating, and can eventually get to the point where the Steam Deck Overlay just gives up and becomes completely unresponsive, forcing a hard shutdown.

This is on SteamOS Stable btw, haven't tried the prerelease or beta with Cemu yet.  Thanks for the dockerfile though, it actually managed to make Cemu boot on the Steam Deck! :D

**Comment by Exzap** [comment]
Building Cemu on Steam Deck is certainly possible but personally I'd advise against it because it will clutter it with gigabytes of dev packages. Really not worth it for the average user imho. In related news, the appimage build is finished and the next experimental build will have it. Flatpak should be ready soon too.
