### ISSUE TITLE
Feature request: main window navigation with controller

### ISSUE THREAD

**Issue by Hexaae** [cemu-project/Cemu#282]
Please can you implement controller navigation in main window to select + run a game?

**Comment by v-fox** [comment]
Something like [ppsspp](https://github.com/hrydgard/ppsspp/)'s menu navigation and use of DualShock's middle button to go into system menu/overlay from the game would be nice, indeed. Would be quite non-trivial though.

**Comment by Hexaae** [comment]
Even just a main window control to choose and launch the game would be enough for me, like yuzu emulator for example...

**Comment by Exzap** [comment]
Duplicate of #1073
