### ISSUE TITLE
Cemu don't Open in Ubuntu 22.04

### ISSUE THREAD

**Issue by kskssk** [cemu-project/Cemu#286]

**Comment by rexhent** [comment]
thats not very helpful.  run it in the terminal, what is the error. I get this error:
`./Cemu: error while loading shared libraries: libsepol.so.1: cannot open shared object file: No such file or directory`

**Comment by rexhent** [comment]
None of the libsepol packages I could find on Ubuntu did anything to fix the issue.

**Comment by kskssk** [comment]
CMake Error at dependencies/vcpkg/scripts/buildsystems/vcpkg.cmake:826 (_find_package):
  Could not find a package configuration file provided by "boost_filesystem"
  (requested version 1.74.0) with any of the following names:

    boost_filesystemConfig.cmake
    boost_filesystem-config.cmake

  Add the installation prefix of "boost_filesystem" to CMAKE_PREFIX_PATH or
  set "boost_filesystem_DIR" to a directory containing one of the above
  files.  If "boost_filesystem" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:258 (boost_find_component)
  build/vcpkg_installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  dependencies/vcpkg/scripts/buildsystems/vcpkg.cmake:780 (include)
  CMakeLists.txt:89 (find_package)

**Comment by Alejandro9509** [comment]
> thats not very helpful. run it in the terminal, what is the error? I get this error on pop 22.04: `./Cemu: error while loading shared libraries: libsepol.so.1: cannot open shared object file: No such file or directory`


Recompile it, that library is only in Ubuntu 20.04.
