### ISSUE TITLE
Switching from AUR Wine build to 2.0.x build wiped the contents of my ~/.cemu/mlc01 directory

### ISSUE THREAD

**Issue by JPLeBreton** [cemu-project/Cemu#291]
When I upgraded from the Wine-based build that was previously in AUR to the new native version, the first time I ran Cemu the first run wizard popped up and asked me if I had an existing mlc01 directory to use for my data. I did (100+ hour Breath of the Wild save) and pointed it to that. When I launched BotW for the first time, it behaved as if I had no save data for the game. I checked my ~/.cemu/mlc01 directory and its content had been wiped! Not sure if this behavior is just part of the first run wizard, Cemu's general init code, a case-sensitivity issue, or something else but overwriting/deleting user data like this should never ever happen.

**Comment by Crementif** [comment]
We don't really have a hand in the creation of either of those packages. Cemu's itself should never delete stuff out of the mlc01 folder nor deletes it to recreate it.

If it's only your save file that was deleted, maybe you played with an older version of BotW in the native version which thought the save created by the newer version was maybe corrupted?

**Comment by JPLeBreton** [comment]
> If it's only your save file that was deleted, maybe you played with an older version of BotW in the native version which caused the game to think the save created by the newer version was maybe corrupted? Or there could be something wrong with file insensitivity regarding save file operations, and couldn't read the folder and thus overwrote your save file? Can do a lot of speculation without details on how to replicate it, and setting up aur sounds like a bother.

It's the same version of BotW as before, nothing else changed about my setup. Some case sensitivity nuance is my best guess as well.
I had a backup of that save from about an hour of play time back, so nothing too bad as far as data loss. Hopefully I'm the only person who ever saw this?

**Comment by Crementif** [comment]
I've not seen it mentioned by anyone else, but who knows.
