### ISSUE TITLE
Possibility to exclude building x64-linux-dbg

### ISSUE THREAD

**Issue by superbonaci** [cemu-project/Cemu#293]
When building it builds first `x64-linux-dbg` then `x64-linux-rel`. Could be possible to skip the dbg build to make the process faster?

**Comment by Exzap** [comment]
You can create a custom triplet for vcpkg that only compiles either debug or release. But when I tried this for our CI I ran into compilation issues with boost. I don't think it's something that is officially supported so some ports may not handle it well.

**Comment by superbonaci** [comment]
Fine
