### ISSUE TITLE
[Linux] Text doesn't display correctly on 'About Cemu' window while using system's Dark theme

### ISSUE THREAD

**Issue by BoofOof32** [cemu-project/Cemu#296]
- Current Version: `2.0-4` (compiled manually, commit [101ff77](https://github.com/cemu-project/Cemu/commit/101ff7783ea8d39bbf0d8f2ec7c3f65168870d65), issue present since `2.0`) 
- issue is GUI related, can't find a relevant log to show

Not really much to say here, when opening the `About Cemu` tab, it's missing the majority of text, only displaying links for the libraries/utils. No version number, no compile date, no Patreon supporter list, mostly blank
![Screenshot_20220924_162852](https://user-images.githubusercontent.com/66644514/192122695-effab41f-f241-4670-a5d0-164626df63e3.png)

This however isn't an issue when running the Windows version via Wine
![Screenshot_20220924_163535](https://user-images.githubusercontent.com/66644514/192122671-2b08308c-1390-41fc-86f6-c827d5e4194d.png)

**Comment by qurious-pixel** [comment]
it is very light or white text on a white background.

![image](https://user-images.githubusercontent.com/62252937/192123397-beb1fd3a-0a56-4dff-9112-3c0437fd1c5c.png)

**Comment by BoofOof32** [comment]
Oh fascinating, I didn't even notice that, lol. You think it could be an issue with system theming? I'm only using KDE's Dark Breeze theme

**Comment by BoofOof32** [comment]
Hm, sure enough, switching to KDE's Breeze light theme fixed the issue with text
![Screenshot_20220924_175310](https://user-images.githubusercontent.com/66644514/192123724-115d228c-6d1d-4f2f-94c7-d3f66adc16e9.png)
though this isn't particularly ideal since it's... well, light mode.

My guess is the text is assuming the `About Cemu` panel is dark like the rest of the Windows and displays white text to contrast it

**Comment by qurious-pixel** [comment]
you might also notice on the controller input screen when using a dark theme.

It was mentioned in https://github.com/cemu-project/Cemu/pull/241

**Comment by BoofOof32** [comment]
Ah, I missed that issue, I suppose I didn't search hard enough to make sure this wasn't a duplicate issue, my bad

**Comment by vesper8** [comment]
Similar issues on Mac when using dark mode in the OS. All field text is white on white when configuring input settings

**Comment by Amnesia1000** [comment]
Not only the error is in the About tab, also in the title manager and the input panel, showing an item with black background and white text and the next with white background and white text in the title manager and white text on a white background in the input settings.
![Captura desde 2022-10-16 09-16-47](https://user-images.githubusercontent.com/45115804/196034956-b35ac98f-4f98-498d-beb6-19bedb3271fe.png)
![Captura desde 2022-10-16 09-16-58](https://user-images.githubusercontent.com/45115804/196034961-59e5c756-df4b-475a-99a6-d3f03e5d1102.png)
