### ISSUE TITLE
No localization on macOS

### ISSUE THREAD

**Issue by FRtranslator** [cemu-project/Cemu#297]
Localization is not loaded on macOS, Cemu build 2.0-4: the UI sticks to English even if you choose "French" for instance.

**Comment by goeiecool9999** [comment]
I want to add to that that it also doesn't work on Arch Linux and it crashes when you select a different language. If anyone knows if it works on Ubuntu that would be helpful.

**Comment by jamescastells** [comment]
May be related, but if I select "English" as a UI language I get this pop-up every time I start Cemu:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/5696029/192436578-306ec8bd-1816-426d-b4d4-e6d9de41b659.png">
