### ISSUE TITLE
Cemu not set as executable on macOS (2.0-4)

### ISSUE THREAD

**Issue by FRtranslator** [cemu-project/Cemu#298]
The Cemu executable file is not set as "executable" (x) on macOS.

Workaround: do a **chmod 755** on it to start it.

Using latest version of macOS 12 with the official 2.0-4 asset from this GitHub repository.

**Comment by vesper8** [comment]
Or you can `chmod +x Cemu`

**Comment by FRtranslator** [comment]
Correct.
In any case, this must be added to the build script.
