### ISSUE TITLE
Crash on macOS when starting a game

### ISSUE THREAD

**Issue by FRtranslator** [cemu-project/Cemu#299]
Using latest version of macOS 12 and Cemu 2.0-4 official download here, on an M1 Mac.

After setting Cemu as executable and passed 1st start wizard, double-clicking on a game just crashes Cemu instantly. IT doesn't even show the render window.
Whatever the game format is (.wux, or directory structure).

Only OpenGL is available (not sure it will work fine on actual macOS...).

Error log on Console:
[Cemu-2022-09-25-103501.ips.zip](https://github.com/cemu-project/Cemu/files/9640329/Cemu-2022-09-25-103501.ips.zip)

**Comment by Pedro-Beirao** [comment]
You have to install molten-vk yourself in order to use vulkan.

brew install molten-vk

**Comment by vesper8** [comment]
You have to install the x86_64 version of molten-vk, and then you must select 'Vulkan' in the graphics settings

```

# install x64 brew
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# create an alias ibrew (optional)
alias ibrew='arch -x86_64 /usr/local/bin/brew'

# install x64 dependencies using your new x64 brew with the alias
ibrew install molten-vk

# or
arch -x86_64 /usr/local/bin/brew install molten-vk
```

**Comment by rmm805** [comment]
> You have to install the x86_64 version of molten-vk, and then you must select 'Vulkan' in the graphics settings
> 
> ```
> # install x64 brew
> arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
> 
> # create an alias ibrew (optional)
> alias ibrew='arch -x86_64 /usr/local/bin/brew'
> 
> # install x64 dependencies using your new x64 brew with the alias
> ibrew install molten-vk
> 
> # or
> arch -x86_64 /usr/local/bin/brew install molten-vk
> ```

Thank you, these steps worked for me.

**Comment by FRtranslator** [comment]
Although I have found the solution after posting (sorry), although I think that it would be a good solution to include the library (libMoltenVK.dylib) with the build, like does Dolphin emu.

Maybe, a future update will add Metal support (it looks like Dolphin has been able to support Metal without too much effort from MoltenVK).

**Comment by inzar98** [comment]
> Although I have found the solution after posting (sorry), although I think that it would be a good solution to include the library (libMoltenVK.dylib) with the build, like does Dolphin emu.
> 
> Maybe, a future update will add Metal support (it looks like Dolphin has been able to support Metal without too much effort from MoltenVK).

Metal and arm support image the heaven !!

**Comment by Exzap** [comment]
Closing as the original issue seems to be resolved. And yeah we plan to eventually bundle libMoltenVK with Cemu.

**Comment by BugenZhao** [comment]
Installing `molten-vk` under the x86_64 arch really works! How about documenting this somewhere in case it's confusing to new Apple Silicon users?
