### ISSUE TITLE
[Linux] Arch Linux 2022.09.03 build instructions missing `llvm` package

### ISSUE THREAD

**Issue by TheTollingBell** [cemu-project/Cemu#307]
On commit 25dae98ce015c18ff1ae62a19e63cf12d2ae7c9a

In `BUILD.md` there is no reference to download the `llvm` package or related packages which are essential to the build. It would've made my life a lot less facepalm-full if this was included in the arch linux dependencies section for people who rarely used llvm.

Build fails at
`FAILED: dependencies/discord-rpc/src/libdiscord-rpc.a
: && /usr/bin/cmake -E rm -f dependencies/discord-rpc/src/libdiscord-rpc.a && "CMAKE_CXX_COMPILER_AR-NOTFOUND" cr dependencies/discord-rpc/src/libdiscord-rpc.a  dependencies/discord-rpc/src/CMakeFiles/discord-rpc.dir/discord_rpc.cpp.o dependencies/discord-rpc/src/CMakeFiles/discord-rpc.dir/rpc_connection.cpp.o dependencies/discord-rpc/src/CMakeFiles/discord-rpc.dir/serialization.cpp.o dependencies/discord-rpc/src/CMakeFiles/discord-rpc.dir/connection_unix.cpp.o dependencies/discord-rpc/src/CMakeFiles/discord-rpc.dir/discord_register_linux.cpp.o && "CMAKE_CXX_COMPILER_RANLIB-NOTFOUND" dependencies/discord-rpc/src/libdiscord-rpc.a && :
/bin/sh: line 1: CMAKE_CXX_COMPILER_AR-NOTFOUND: command not found`
without `llvm` installed.

**Comment by goeiecool9999** [comment]
I was sceptical that llvm was required as it's only an optional dependency for clang but I just confirmed this.

**Comment by Crementif** [comment]
Closed with #308
