### ISSUE TITLE
export support in 2.0

### ISSUE THREAD

**Issue by S41L0R** [cemu-project/Cemu#31]
I see that cemuhook is no longer supported, and it seems that the ability to inject a dll and call exports such as memory_getBase and osLib_registerHLEFunction have been dropped... Have they been dropped? Is there a new way to call these?

**Comment by S41L0R** [comment]
I've seen that cemuhook is no longer supported, so maybe that's connected to other DLLs not working properly

**Comment by Exzap** [comment]
Seems like it doesn't pick up exports.def for some reason. The exports are there, but not under their undecorated names (e.g. looking up `memory_getBase` doesnt work but `?memory_getBase@@YAPEAXXZ` would). I'll look into this when I get a chance.

**Comment by S41L0R** [comment]
Ah so that's what those funny names were. Thanks so much for your work towards this by the way (:

**Comment by S41L0R** [comment]
Seems to be a problem with the WIN32 flag in CMakeLists.txt. I replaced line 68 with if(true) and it works fine.
