### ISSUE TITLE
Consistent coding style

### ISSUE THREAD

**Issue by pascalpuffke** [cemu-project/Cemu#32]
I would highly recommend that we add some sort of documentation on how to format code.

The best solution for this IMO would be a `.clang-format` file. That way the `clang-format` tool can format everything in a consistent style.

These are pretty easy to set up, and IDEs like CLion support them out of the box for automatic, on file save / hotkey formatting. A minimal `.clang-format` file only needs two lines if Exzap is okay with using a predefined style. (Just don't pick GNU.)

[Here's an example of good documentation](https://github.com/SerenityOS/serenity/blob/master/Documentation/CodingStyle.md) regarding this topic, and [here's a sample .clang-format](https://github.com/SerenityOS/serenity/blob/master/.clang-format).

**Comment by Wunkolo** [comment]
+1 for a `.clang-format`
It would make Pull-Request reviews and contributions that much easier when a whole classification of style-reviews can be ruled out.

**Comment by Zopolis4** [comment]
I was thinking about adding clang-format, I'll open a PR soon.
