### ISSUE TITLE
Error in MacOS cmake -S command

### ISSUE THREAD

**Issue by GumbyXGames** [cemu-project/Cemu#333]
Paths declared in cmake command in step 3 of building Cemu on MacOS (https://github.com/cemu-project/Cemu/blob/main/BUILD.md#build-cemu-using-cmake-and-clang-1) for llvm@14 compilers and ninja are incorrect

Currently:
`cmake -S . -B build -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=/usr/local/opt/llvm@14/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm@14/bin/clang++ -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/local/bin/ninja`

brew for MacOS does not install llvm@14 or ninja to those paths.

llvm@14 clang path is `/opt/homebrew/opt/llvm@14/bin/clang`
llvm@14 clang++ path is `/opt/homebrew/opt/llvm@14/bin/clang++`

The following cmake command works:
`cmake -S . -B build -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm@14/bin/clang -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm@14/bin/clang++ -G Ninja -DCMAKE_MAKE_PROGRAM=/opt/homebrew/opt/ninja/bin/ninja`

**Comment by emiyl** [comment]
On ARM brew installations, the homebrew path is `/opt/homebrew`.  
On Intel brew installations, the homebrew path is `/usr/local`

Before compiling, run `arch -x86_64 zsh`. Then, install brew again (this won't conflict with your ARM brew installation), and all dependencies.

**Comment by GumbyXGames** [comment]
So there are no plans for an arm64 build?

**Comment by GumbyXGames** [comment]
> On ARM brew installations, the homebrew path is /opt/homebrew.
On Intel brew installations, the homebrew path is /usr/local

Before compiling, run arch -x86_64 zsh. Then, install brew again (this won't conflict with your ARM brew installation), and all dependencies.

Installing brew and the dependencies while inside arch -x86_64 zsh will install everything to /usr/local.

Ya it doesn't. It's still trying to install from the arm64 brew install. I'm not going to complete change my dev environment just for this.

**Comment by emiyl** [comment]
> So there are no plans for an arm64 build?

On the [Cemu roadmap](https://wiki.cemu.info/wiki/Roadmap#LLVM_as_a_CPU_JIT_backend), it's planned to switch to LLVM as a CPU backend, which can then be built for arm64.
