### ISSUE TITLE
Compiling for MacOS: Unable to cmake build due to deprecated calls and "Invalid Conversion" errors

### ISSUE THREAD

**Issue by GumbyXGames** [cemu-project/Cemu#334]
Issue: When attempting to compile Cemu on MacOS multiple errors are thrown relating to deprecated commands and calls.
Commit Hash: `4519a59d746dc0eb2a427c0f379c6c4c600d89dd`
Log output: [https://pastebin.com/x6gqEDh1](https://pastebin.com/x6gqEDh1)

Steps to Reproduce in command line from Cemu folder after cloning repo:
`% cmake -S . -B build -CMAKE_BUILD_TYPE=release -CMAKE_C_COMPILER=/opt/homebrew/opt/llvm@14/bin/clang -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm@14/bin/clang++ -G Ninja -CMAKE_MAKE_PROGRAM=/opt/homebrew/opt/ninja/bin/ninja

% cmake --build build`

Upon wiping out cloned code and pulling a fresh copy with ``, the following errors were thrown:
https://pastebin.com/Bmgfg79B

**Comment by goeiecool9999** [comment]
It seems you're on an M1 mac which means brew probably installed the arm version of clang. You have to use the x86-64 version of clang.
