### ISSUE TITLE
[Regression] Bugs, bugs, bugs. Games no longer boot and in-game audio no longer works starting in Cemu 2.0

### ISSUE THREAD

**Issue by hifihedgehog** [cemu-project/Cemu#337]
I recently upgraded my library to .wua and went with 2.0. In 2.0 release and all experimental builds, game compatibility has been severely compromised. Some games, such as Lego Dimensions and Lego Marvel Avengers, no longer boot and are stuck at the splashscreen. Others have severe issues, such as the Cabela's hunting games, where there is _no_ audio in-game except in the prerendered game videos.

**Comment by Squall-Leonhart** [comment]
> needs snd_user.rpl in cafeLibs in cemu root directory for sound. 

You clearly didn't test the Cabela games at all on a prior version.
