### ISSUE TITLE
MacOS: Using discrete GPU? 

### ISSUE THREAD

**Issue by palmerj** [cemu-project/Cemu#338]
Hi I'm testing out BOTW on my older Macbook pro 15" 2019 with latest version from the CI 8a0fe21 on MacOS 12.6. The Macbook has an 6-Core Intel i7-9750H CPU @ 2.60GHz, burst 
4.50 GHz with Intel UHD Graphics 630, and a Radeon Pro 555X GPU. 

When I configure Cemu to run BOTW using Vulkan and the Radeon Pro 555X GPU. 

<img width="721" alt="Screen Shot 2022-10-05 at 11 17 10 am" src="https://user-images.githubusercontent.com/580022/194030035-ad3e5233-71f5-42f4-b87a-390d39011fdc.png">

I get a terrible framerate (about 5FPS) and the system (iStats Menu which reliable shows me when the GPU switches) seems to report that I'm not using the AMD GPU, rather than intel iGPU. 

<img width="1557" alt="BOTW-GPU" src="https://user-images.githubusercontent.com/580022/194029866-1a4841e1-cc8d-4279-8710-0a694475798a.png">

Two Questions:

1. Is it really not using the AMD GPU
2. Can I expect the framework to improve in future versions, or is this Macbook pro too old?

Here's my debug output if this helps. https://gist.github.com/palmerj/e77a238c147b61e013d0495613c1719c

Thanks heaps

P.S thanks for making this OS and getting MacOS support going!

**Comment by Tillsunset** [comment]
Currently there is a large cpu performance hit when using macOS, currently limiting fps to 5-15fps regardless of cpu or gpu. It is being currently being looked into. Your system should be capable of more. As for if it is using the amd gpu, I assume it is but as stated above it doesn't current really affect performance.

**Comment by Tillsunset** [comment]
I just noticed you have enabled "Async shader compiler". That feature in unsupported on the igpu and will crash Cemu if enabled. So I'm assuming the AMD gpu is being used, which in this situation has the feature supported and presumingly doesn't crash with it enabled.

**Comment by emiyl** [comment]
> That feature in unsupported on the igpu

This is more of an issue with the fact that MoltenVK does not support the extension used by async shader compilation, so it doesn't matter which GPU is being used.

**Comment by lbibass** [comment]
> Currently there is a large cpu performance hit when using macOS, currently limiting fps to 5-15fps regardless of cpu or gpu. It is being currently being looked into. Your system should be capable of more. As for if it is using the amd gpu, I assume it is but as stated above it doesn't current really affect performance.

Could it be due to moltenVK having to do a significant amount of conversion on the CPU, rather than the GPU?

**Comment by emiyl** [comment]
I'm sure the conversion isn't _helping_ performance, but MoltenVK performs very well in other applications, and shouldn't cause performance to degrade to this extent.

**Comment by lbibass** [comment]
That makes sense. Dolphin has noticed a small increase in performance from a native Metal renderer, but MoltenVK generally performs well enough in most cases.

**Comment by Exzap** [comment]
Closing this since the original question has been answered.
