### ISSUE TITLE
[Fatal Frame] Crashes instantly on title screen

### ISSUE THREAD

**Issue by Alecerzea** [cemu-project/Cemu#34]
These all happened on cemu 2.0
After launching the game, both on the USA digital and JP physical version, it crashes after it gets into the emu
On cemu 1.26.2 and 1.27.1 it crashes after entering a chapter, all after the resumes before entering, it crashes also
On cemu 1.27, the game is 100% playable without problems from start to finish

**Comment by Alecerzea** [comment]
> These all happened on cemu 2.0 After launching the game, both on the USA digital and JP physical version, it crashes after it gets into the emu On cemu 1.26.2 and 1.27.1 it crashes after entering a chapter, all after the resumes before entering, it crashes also On cemu 1.27, the game is 100% playable without problems from start to finish

Using Windows 11
I7 9750H
RTX 2060

Acer Nitro 5 AN-515-54

**Comment by Alecerzea** [comment]
On cemu 2.0-1, bith games are fully playable now
Just the same error as in the reported in the wiki

**Comment by xelkiva** [comment]
> On cemu 2.0-1, both games are fully playable now Just the same error as in the reported in the wiki

Sadly the issue mentioned still persist on Cemu 2.4 macOS. Stuttered during 1st cutscene and game crashed afterwards.
