### ISSUE TITLE
don't work on clean installation Ubuntu 22.04: web version don't launch & compile error

### ISSUE THREAD

**Issue by masies-hack** [cemu-project/Cemu#340]
this is only for devolopers:
just on clean installation ubuntu
https://www.youtube.com/watch?v=PE_CcWinMqU
i did video, i better than words
not's for me a priority to work & play.
but maybie must change on build instructions.
or maybie i'm ignorant and it has an easy solution.
thanks anyway.

**Comment by unsightedmetal6** [comment]
Those are warnings, not errors. I got warnings but I was still able to launch Cemu using `./bin/Cemu_release` after building it.

But yes, I was not able to get the file from the releases working. I had to build it instead.

**Comment by masies-hack** [comment]
watch the video well.
at the end of compilation at 99.99% says.... 
"ninja build stopped: subcommand failed"
so there's no ./bin/Cemu_release file or "bin" folder
if when compiling it would generate the executable file and it would work never did this post.
it is simply because you keep it in mind.
I'm not an expert and I'm not trying to solve anything.
I'll try it in a month or two.
anyway thanks for the interest.

**Comment by Exzap** [comment]
If you want this properly troubleshooted then please either use the discord or open a new issue and post full text logs and not a video.
