### ISSUE TITLE
[macOS] Cemu UI Rendering at half Retina resolution

### ISSUE THREAD

**Issue by Veemyu** [cemu-project/Cemu#343]
macOS's Retina Resolutions work by displaying the UI in a logical, for example 1920x1080 resolution ie. also resulting in a size 1080P would normally be displayed on the Monitor. Yet Retina is supposed to render the actual UI in 3840x2160, always double the logical resolution.
Cemu currently renders, like the console prints out, at Scale 1.0

This Results in a 1280x720 Window (logically) taking up 2560x1440 Real pixels but the underlying rendering is only at 1280x720
This results in a really blurry and pixelated look. The UI is mostly fine, the problem is with the Vulkan Canvas.

This should maybe help, the all too familiar Scale 1.0 needs to be 2.0 on Retina screens, not on the whole Apple Platform though!
https://github.com/KhronosGroup/MoltenVK/issues/428 
They have the exact same issue solved up there.

`[mvk-info] Created 3 swapchain images with initial size (1280, 720) and contents scale 1.0 for screen Built-in Retina Display.`

Here are comparison pictures between 1512x982 with Retina (HiDPI) which should display as 3024x1964 everywhere!!
And also 3024x1964 Native in fullscreen which is also supposed to display as 3024x1964 obviously.
<img width="650" alt="Menu Native" src="https://user-images.githubusercontent.com/38016914/194294894-478b75d8-7264-4d5d-86e3-9b8cddd3ca03.png">
<img width="650" alt="Menu HiDPI" src="https://user-images.githubusercontent.com/38016914/194294916-94f5a5ce-c329-4067-bf26-04071593451b.png">
<img width="650" alt="Game Native" src="https://user-images.githubusercontent.com/38016914/194294924-8ec637bc-fba3-4ab1-b449-68ba251dece3.png">
<img width="650" alt="Game HiDPI" src="https://user-images.githubusercontent.com/38016914/194294959-cd2b2653-80cd-415a-88b5-c43915deb3ae.png">

**Comment by 556644O** [comment]
I also found the same issue. Some other softwares have the same issue, such as PPSSPP and Streets of Rage 4. At present, I use Easyres to solve this issue by setting the resolution to 1X. Or is there a better approach out there to solve this issue?
![截屏2022-11-14 11 25 46](https://user-images.githubusercontent.com/116966347/201569957-ac19ff94-9264-4ac8-ad8d-3e98eae6b64d.png)

**Comment by greybaron** [comment]
I have submitted a PR #516 that fixes this. You can either wait for it to be merged. Alternatively, you could use [this build](https://github.com/cemu-project/Cemu/files/10050554/bin.zip) from my branch.

**Comment by 556644O** [comment]
> I have submitted a PR #516 that fixes this. You can either wait for it to be merged. Alternatively, you could use [this build](https://github.com/cemu-project/Cemu/files/10050574/bin.7z.zip) from my branch. (I had to use 7z to get below 25MB)

Thanks a lot for your hard work, your build works well and have solved this issue.

**Comment by Squall-Leonhart** [comment]
This was addressed in https://github.com/cemu-project/Cemu/pull/514

**Comment by Exzap** [comment]
Closing since this should be fixed
