### ISSUE TITLE
Build was failed on macOS 12 M1

### ISSUE THREAD

**Issue by Eggslegend** [cemu-project/Cemu#346]
[cmake error.txt](https://github.com/cemu-project/Cemu/files/9739653/cmake.error.txt)

**Comment by Simonx22** [comment]
Seems like you are partially compiling for the wrong architecture. Try this command instead: `cmake -S .. -B build -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=/usr/local/opt/llvm@14/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm@14/bin/clang++ -G Ninja`

Note: This command assumes that you created and are currently in a folder named `build`, located in the root directory.

**Comment by Eggslegend** [comment]
Still t
[cmake error1.txt](https://github.com/cemu-project/Cemu/files/9739709/cmake.error1.txt)
he same...

This is the cmake log before building

**Comment by darkuser89** [comment]
try brew install pkg-config

**Comment by Tillsunset** [comment]
Try deleting cemu/build/ and follow this [https://cemu.emiyl.com/installation](https://cemu.emiyl.com/installation).

**Comment by Eggslegend** [comment]
> try brew install pkg-config

not working as well...

**Comment by Eggslegend** [comment]
> Try deleting cemu/build/ and follow this https://cemu.emiyl.com/installation. It has dedicated steps for apple silicon

I already had one and worked successfully.

But now I'm testing #280 but it fails...

**Comment by Exzap** [comment]
Please use the discord for troubleshooting compilation issues
