### ISSUE TITLE
[macOS] Unstable FPS with Wind Waker HD

### ISSUE THREAD

**Issue by jamescastells** [cemu-project/Cemu#347]
As the title states, I'm getting unstable FPS with Wind Waker HD. Outdoors the framerate gets up to 30-35 FPS, but inside the houses it's at 120 FPS, making everything run much faster.

Running M1 Macbook Pro with Cemu 2.0-4

**Comment by jkcoxson** [comment]
Sounds like you're using an old build, this was fixed a bit ago.

**Comment by jamescastells** [comment]
I'm using the only build available for macOS.

https://github.com/cemu-project/Cemu/releases/tag/v2.0-4

**Comment by jkcoxson** [comment]
No, that's not the only build. Check the actions tab.

**Comment by jamescastells** [comment]
I'm sorry, I wasn't aware of the Actions tab. I downloaded it from the "Releases" page, as any user would expect.

**Comment by inzar98** [comment]
> I'm sorry, I wasn't aware of the Actions tab. I downloaded it from the "Releases" page, as any user would expect.

Cuz its not release yet. Thats how it works at most of opensource apps :D Dont take that as harassment btw <3

**Comment by Exzap** [comment]
Closing this since the issue was fixed already
