### ISSUE TITLE
[macOS] Cannot set locale to language "".

### ISSUE THREAD

**Issue by jamescastells** [cemu-project/Cemu#349]
Everytime I open Cemu on macOS, I get the same message: "Cemu Warning. Cannot set locale to language ""."

<img width="294" alt="image" src="https://user-images.githubusercontent.com/5696029/194736460-fdbfefec-17ca-4010-96a2-5fc63f0ec711.png">

My general settings contain both "Default" and "English". If I select English, upon restarting it reverts to "Default" while keeping the error message.

<img width="231" alt="image" src="https://user-images.githubusercontent.com/5696029/194736484-de54f575-6eee-491b-bdf7-4c6e7a03b03c.png">

Using the latest version on M1 Macbook pro.

**Comment by Tillsunset** [comment]
can you look in the Cemu folder and see if there is a folder called "resources", and if the folder is there, is it empty or does it have a bunch of sub folders

**Comment by jamescastells** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/5696029/195203232-54d94ab8-38e7-4029-b987-d3d55f83b6a5.png">
No, there's not.

**Comment by Tillsunset** [comment]
Ok I know the problem, the files that are created during pushes don't included the additional files that releases have, such as the language files. What you can do is download the latest release and copy everything excluding the executable, into this folder that you already have and try it again.

**Comment by jamescastells** [comment]
Downloaded the version from the releases tab. It does include a resources folder, but it still happens.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/5696029/195205587-69866595-d1ff-4423-896d-8fb340c3c5b3.png">

**Comment by Tillsunset** [comment]
when you go to select a language does it show a bunch of them or just "default" and "English"

**Comment by darkuser89** [comment]
Download [Cemu 2.0-5 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-5) works without problems

**Comment by jamescastells** [comment]
Using 2.0-6, still happening.

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/5696029/195710732-02deed11-423e-4e4b-b7da-5a475b9fefec.png">

**Comment by Tillsunset** [comment]
Where is the cemu folder located. macOS has a safety thing where programs aren’t allowed access to certain folders such as downloads or documents.

**Comment by jamescastells** [comment]
I've tried various locations, but they all give the same effect.

One thing I've noticed is that there's no "en" folder inside the "resources" one. Creating one and placing any "mo" file (taken from any of the other folders), doesn't solve the issue.

**Comment by Tillsunset** [comment]
Yeah cemu doesn’t come with an “en” folder so it wouldn’t even check for one. I really don’t know the issue then. If you download the prerelease version and it’s still giving you issues, it might just be an issue with your computer.

**Comment by jamescastells** [comment]
Under System Preferences, Language & Region, changing the "Region" to "United States" fixes the problem.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/5696029/195715266-2753e75c-25e1-464b-9640-9a38748ca1af.png">

Apparently there are some regions that Cemu doesn't recognize.
