### ISSUE TITLE
cemu 2.0 it breaks if put in fullscreen [linux - i3wm]

### ISSUE THREAD

**Issue by xFedee** [cemu-project/Cemu#359]

**Comment by v-fox** [comment]
What exactly "breaks" ? Build of version `2.0~6+0~git20221013.d251ce0` works fine for me with KDE under X11.

**Comment by xFedee** [comment]
the game freeze and if I kill and reopen cemu if I launch a game doesn't work, I use i3-gaps (fork of i3wm) on X11
