### ISSUE TITLE
MacOS support (x86 + ARM64)?

### ISSUE THREAD

**Issue by oscarbg** [cemu-project/Cemu#36]
Hi,
I know this is very far from being supported but opening anyway..
think the hardest part is graphics support but some massaging to Vulkan code + MoltenVK enhancements should make it possible eventually (MacOS Metal 3.0 support will be needed?)..
thanks..

**Comment by Etaash-mathamsetty** [comment]
you can just use wine for the meantime, unfortunately wine's mac os support is not as good as it used to be (the maintainer's no long around), so you can try installing wine from homebrew and maybe it will work.

**Comment by servantoftestator** [comment]
In implementing arm64 or other architecture's jit's consider looking at github com/decaf-emu/decaf-emu/tree/master/src/libcpu/src/jit . They have a multi-architectual jit based upon libbinrec. Might save work on implementation should mac osx be considered for support in the future.

**Comment by Zopolis4** [comment]
x86 is highly unlikely, Dolphin dropped support for x86 years ago because of the constraints of the hardware and the Wii U is significantly more powerful than the Wii, which is multiplied by emulation. ARM64 is possible, but an ARM64 JIT would have to be written by hand to do so.

**Comment by ArtemisX64** [comment]
> x86 is highly unlikely, Dolphin dropped support for x86 years ago because of the constraints of the hardware and the Wii U is significantly more powerful than the Wii, which is multiplied by emulation. ARM64 is possible, but an ARM64 JIT would have to be written by hand to do so.
JIT support for ARM64 devices in x86?  Isn't what other emulators like yuzu(dynarmic)/rpcs3/Ryujinx is doing?

**Comment by Zopolis4** [comment]
Yuzu only supports [x86_64](https://yuzu-emu.org/help/quickstart/#hardware-requirements) as a host architecture , as does [Ryujinx](https://github.com/Ryujinx/Ryujinx#step-1), as does [rpcs3](https://github.com/RPCS3/rpcs3-binaries-win/releases/tag/build-fff0c96bf38d1ada075e524c4753a7f263c06449). Not sure what you mean

**Comment by ArtemisX64** [comment]
> Yuzu only supports [x86_64](https://yuzu-emu.org/help/quickstart/#hardware-requirements) as a host architecture , as does [Ryujinx](https://github.com/Ryujinx/Ryujinx#step-1), as does [rpcs3](https://github.com/RPCS3/rpcs3-binaries-win/releases/tag/build-fff0c96bf38d1ada075e524c4753a7f263c06449). Not sure what you mean

Oh my bad. I thought you meant CISC arch in general

**Comment by Exzap** [comment]
ARM64 support is on the [roadmap](https://wiki.cemu.info/wiki/Roadmap) but it won't come any time soon. Any 32bit platforms aren't a realistic target due to the technical constraints. I'll close this issue because it's not something that really needs to be discussed right now.

**Comment by oscarbg** [comment]
@Exzap sorry if can't understand, but why you close the issue, Cemu on Mac still isn't a reality either on X86 or ARM64.. as said Vulkan support must be massaged+ worked jointly with MoltenVK for graphics working on Mac, right?
