### ISSUE TITLE
XAudio2 broken in latest build...

### ISSUE THREAD

**Issue by Kobi-Blade** [cemu-project/Cemu#362]
XAudio2 is no longer working since experimental build [5](https://github.com/cemu-project/Cemu/commit/f42bebd196f38b9eb2dfa47aad2849cfdc0d0c5d).

A picture speaks a thousand words,

![image](https://user-images.githubusercontent.com/15495525/195566403-689b3772-71aa-49b5-a209-54c15d4ec06e.png)

All builds have XAudio2 working perfectly fine up to [4](https://github.com/cemu-project/Cemu/commit/101ff7783ea8d39bbf0d8f2ec7c3f65168870d65), which is also working,

![image](https://user-images.githubusercontent.com/15495525/195567699-f02f60da-ca0d-40e1-94cc-0048b089e724.png)

This is honestly a major issue, since we don't get sound.

**Comment by Exzap** [comment]
I cannot replicate this. Can you upload `log.txt`?

**Comment by Exzap** [comment]
Resolved by d251ce07e0cbbe8a85a4013fbfb15efa0f422b76
New experimental release with this fix will be available in 40 - 60 minutes.
