### ISSUE TITLE
Cemu seems to freeze when the MLC and Game path got selected or changed

### ISSUE THREAD

**Issue by Alecerzea** [cemu-project/Cemu#365]
These all happenes in Cemu 2.0-6
![image](https://user-images.githubusercontent.com/85199063/195649137-2cbc4d12-af2b-4345-98d0-f93d0726ec48.png)
![image](https://user-images.githubusercontent.com/85199063/195649344-a81f760a-1c4b-4a3e-8481-50603739f628.png)

**Comment by cabrerahector** [comment]
Can confirm. Tested on Windows 10 Pro (not Insiders version). Cemu hangs when clicking on "Browse" to pick a custom mlc01 folder.

**Comment by Squall-Leonhart** [comment]
This also affects "Convert to WUA", title manager freezes instead of opening the save dialog.

**Comment by Exzap** [comment]
Fixed in [v2.0-7](https://github.com/cemu-project/Cemu/releases/tag/v2.0-7)
