### ISSUE TITLE
Turn on wiki to enable community documentation

### ISSUE THREAD

**Issue by elliot-sawyer** [cemu-project/Cemu#37]
* Build instructions for different platforms
* Compatibility lists for games
* FAQs and known issues
* etc

**Comment by Zopolis4** [comment]
There's already a Cemu Wiki [here](https://wiki.cemu.info/wiki/Main_Page) with most of what you described. Build instructions are currently in BUILD.md, and can be contributed to via PR's.

**Comment by Exzap** [comment]
We'll consider it for the future but for now the mediawiki suffices.
