### ISSUE TITLE
Cemu crashes on starting super mario maker

### ISSUE THREAD

**Issue by HimanshuBansal112** [cemu-project/Cemu#371]
I started playing super mario maker on cemu today for the first time. When I started, new save data got created and after continuing, cemu crashed. I tested it on older version of cemu(version 1.26.2) and found that super mario maker works fine on it. The log for cemu is:
[log.txt](https://github.com/cemu-project/Cemu/files/9786571/log.txt)

**Comment by Tillsunset** [comment]
Please do not put cemu or any required folders into any system folder. This can prevent cemu from reading files correctly

**Comment by HimanshuBansal112** [comment]
But I am running it as an administrator. Shouldn't it not behave like that as an administrator.

**Comment by Tillsunset** [comment]
In general it’s not a good idea to put cemu into any system folder even if you run as administrator. Windows can do some weird stuff with it system folders. The logs show errors with files in the mlc folder. 

Having other games installed wouldn’t make an issue here. They are organized into different folders and have no effect on each other.

It’s also showing errors with your dumped account. Try using the default account

**Comment by HimanshuBansal112** [comment]
I tried by making a new account in cemu and it fixed the issue. I am closing this issue as it appears that it is an issue with dumped account. Thank you for help.
