### ISSUE TITLE
No Sound on KDE Neon using compiled binary from this website

### ISSUE THREAD

**Issue by Blad3forc3** [cemu-project/Cemu#374]
There is no sound at all in the compiled binary from this website. The binary opens but all options for api sound have nothing to select

**Comment by dmanlfc** [comment]
yes it's a bug. you typically need to exit & re-enter & then you should see the drop down option to select your sound device.

**Comment by Blad3forc3** [comment]
Exit and re-enter the settings tab? If so, that isnt working

**Comment by Exzap** [comment]
Should be resolved on the newest binary
