### ISSUE TITLE
cafeLibs files do not restore in-game audio for Cabela's Dangerous Hunts 2013

### ISSUE THREAD

**Issue by hifihedgehog** [cemu-project/Cemu#384]
- You have read the above.
✔

- You have provided the version (commit hash) of Cemu you are using.
Version 2.0-7 (experimental)

- You have provided sufficient detail for the issue to be reproduced. 
I have the five cafeLibs files (snd_user.rpl through nsyskbd.rpl) in place but in-game audio (pre-main menu's startup video's audio does work) no longer works for "Cabela's Dangerous Hunts 2013 (US)." I have attached a log file with all options except Vulkan validation layer enabled.

- You have provided system specs (if relevant).
From HWiNFO64:
```
Computer:      ASUS 
CPU:           AMD Ryzen 9 7950X (Raphael, RPL-B2)
               4500 MHz (45.00x100.0) @ 5750 MHz (57.50x100.0)
Motherboard:   ASUS TUF GAMING X670E-PLUS WIFI
BIOS:          0614, 09/23/2022
Chipset:       AMD X670E (Promontory PROM21L.1) + AMD 6xx (Promontory PROM21L.1)
Memory:        32768 MBytes @ 3000 MHz, 30-36-36-76
               - 16384 MB PC48000 DDR5 SDRAM - Team Group UD5-6000
               - 16384 MB PC48000 DDR5 SDRAM - Team Group UD5-6000
Graphics:      NVIDIA GeForce RTX 3090 Founders Edition
               NVIDIA GeForce RTX 3090, 24576 MB GDDR6X SDRAM
Graphics:      AMD Raphael - Internal GPU [AMD]
               AMD Radeon, 512 MB LPDDR4 SDRAM
Drive:         Samsung SSD 970 EVO 500GB, 488.4 GB, NVMe
Drive:         ST5000LM000-2AN170, 4883.8 GB, Serial ATA 6Gb/s @ 6Gb/s
Drive:         ST14000NM001G-2KJ103, 13672.4 GB, Serial ATA 6Gb/s @ 6Gb/s
Drive:         Samsung SSD 980 PRO 1TB, 976.8 GB, NVMe
Sound:         NVIDIA GA102 - High Definition Audio Controller
Sound:         ATI/AMD Zen APU - Display HD Audio Controller
Sound:         AMD Zen - Audio Processor - HD Audio Controller
Network:       RealTek Semiconductor RTL8125 Gaming 2.5GbE Family Ethernet Controller
Network:       Intel Wi-Fi 6E AX210 160MHz
OS:            Microsoft Windows 10 Professional (x64) Build 19044.2130 (21H2)
```

- Please also provide:
  - For any issues, a log file

https://easyupload.io/vne93h

**Comment by Squall-Leonhart** [comment]
Working fine here.

**Comment by hifihedgehog** [comment]
> Working fine here.
> 
> You put them into the cafelibs folder yes?

Correct! Pathing is:

Cemu Main Folder/cafeLibs/snd_user.rpl
(...)
Cemu Main Folder/cafeLibs/nsyskbd.rpl

To verify, your in-game audio is working and not just the start-up video? Once I hit the main menu, that's when it becomes dead silence.

I did verbose logging (https://easyupload.io/vne93h) which is linked above. Maybe that holds the answer?

**Comment by Squall-Leonhart** [comment]
all menu sounds working,
my cat took off running when i fired the rifle

**Comment by hifihedgehog** [comment]
> my cat took off running when i fired the rifle

Teehee. So I am amending my issue here. It's not both Cabela's, which was my issue prior to adding the cafeLibs. It is only Dangerous Hunts 2013.

**Comment by hifihedgehog** [comment]
Here are my cafeLibs files' SHA-1's. They are from a Wii U Menu 5.5.2 dump.

E8BA5B872C4F6E3342F043AF92C7C04AD698EA41*cafelibs\nn_sl.rpl
4FBCBF3DA2CAF2E06C995254B57A14BDAC6BC6D0*cafelibs\nsyskbd.rpl
9216590BC5F75FEA68A05EA97693E34DDAC279A1*cafelibs\snduser2.rpl
29165890B0403D68CCE7EFEB211DD5F35EF91D19 *cafelibs\snd_user.rpl
4D88DDD169DA56DE721E4AA9E213A421F7221B4B *cafelibs\swkbd.rpl

**Comment by hifihedgehog** [comment]
I can hop on the Discord really quick if that helps any.

**Comment by Squall-Leonhart** [comment]
[04:40:59.719] Unsupported lib call: snd_user.MIXReleaseChannel

**Comment by hifihedgehog** [comment]
Do you need me to do anything else from my end? Given the fact I am getting audio with other games that use these libs like the regular Cabela's hunting game, I am assuming this is a Cemu issue. Or is it a user error on my part with some bad cafeLibs files?

**Comment by Squall-Leonhart** [comment]
Put a check into "Load shared libraries"

the default profile has this unchecked.

**Comment by hifihedgehog** [comment]
Great! Checking now...

**Comment by hifihedgehog** [comment]
Viola. That did the trick indeedy! Thank you!!! [It may be good to note this on the wiki page until the default profile is changed.](https://wiki.cemu.info/wiki/Cabela%27s_Dangerous_Hunts_2013) Again, thank you!

**Comment by hifihedgehog** [comment]
I just edited the game's wiki page to reflect your instructions. Should I close this issue or is this something that needs to get committed in the default profile?

**Comment by Squall-Leonhart** [comment]
i  beat you to the PR by a minute :D

**Comment by hifihedgehog** [comment]
Hehe! I wouldn't have known *any* of this without your help. So thank you so very, very much! Also, my deepest apologies for terrifying any cats in the fixing of this issue...
