### ISSUE TITLE
Systemd required

### ISSUE THREAD

**Issue by jpen856** [cemu-project/Cemu#395]
Impossible to boot on Linux distrobutions without systemd such as Void, artix, gentoo etc.

is systemd necessary in the build of an emulator? no other emulator has this requirement.

**Comment by Crementif** [comment]
WxWidgets, the GUI framework that Cemu uses, seems to use it as a dependency. No clue if there's a way of compiling wxWidgets without it, but regardless this is a duplicate issue #24.
