### ISSUE TITLE
[Linux] Show screen input setting not working

### ISSUE THREAD

**Issue by Shoegzer** [cemu-project/Cemu#397]
As the title indicates, assigning the "show screen" input to a button and then pressing the assigned button after booting a game does not actually show the gamepad screen.  You can observe that cemu at least recognizes the button press event, because the image rendered to the main window seems to be offset by one horizontal line of pixels when the button is pressed.

Ideally, pressing the assigned button could move a fullscreen main window to the right half of the screen, and render the gamepad on the left half (and pressing it again should perform the reverse).  Also, the input should read something like "Show Gamepad Screen" rather than "show screen" to be more specific as to its purpose (assuming of course that that IS its purpose).

Details:
* OS: Linux Mint 21 / kernel 5.15
* Commit: ada8bbb3b49622e19deccb7358b1c804a766baab

**Comment by dmanlfc** [comment]
alt+tab will show the gamepad view

**Comment by Shoegzer** [comment]
Thanks, I was aware of that.  That doesn't address this issue at all though.

**Comment by jn64** [comment]
Can't repro on Fedora using latest ffa213c. Pressing "show screen" key brings up the gamepad screen. Tried with both binding to a controller button (Xbox guide button on X360 Wired) and keyboard button.

**Comment by Shoegzer** [comment]
Thanks, sounds like it could be related to Ubuntu distros then.

**Comment by jn64** [comment]
Does it happen on the CI builds? https://github.com/cemu-project/Cemu/releases

**Comment by Shoegzer** [comment]
There's an unrelated issue running the CI builds on Ubuntu systems that prevents testing this (specifically, `libsepol.so.1` is not found at runtime, even though it is installed in `/usr/lib/x86_64-linux-gnu/`).  

Also, as far as I know Cemu will only build on Ubuntu systems by removing the `sdl2` reference from `vcpkg.json` (and this was done here).  I'm not sure if that is the cause, however inputs mapped to all functions other than "show screen" do respond.

Ideally if someone with a Ubuntu-based distro could verify this issue, that would help.

**Comment by qurious-pixel** [comment]
Should be fixed with https://github.com/cemu-project/Cemu/pull/510

**Comment by Shoegzer** [comment]
Yeah it does, thanks for reminder.  It functions properly as a toggle from main > gamepad screen, but there are times when you need the gamepad view for longer than that.  Ideally an option to press and hold the button would split the two windows to left and right side of screen, and another press and hold would return to the main screen view, but that's a pretty ambitious feature request so I'll leave it alone.

Either way though, the option "show screen" should really be called something like "Show Gamepad Screen" - but then some of the other options could use an update too ("blow mic > Simulated Microphone Breath Input"?).
