### ISSUE TITLE
[Feature Request] Title-switching

### ISSUE THREAD

**Issue by shydert** [cemu-project/Cemu#409]
Title-switching on cemu would be awesome. I don't know if it's being worked on or not but it would be cool to actually be able to click on the X button on system software apps and get redirected back to the menu as it is on a real Wii U console.

**Comment by Squall-Leonhart** [comment]
duplicate #208

**Comment by shydert** [comment]
Nope. I am talking about implementing something similarly to what Dolphin, the Wii emulator does. If you open up the home menu during a game and then click "Wii Menu" it will redirect you to the Wii Menu, and sadly that's not implemented in Cemu. I am not asking for a reset button or a button to stop emulation on the emulator itself.

**Comment by Masamune3210** [comment]
Unfortunately (or fortunately, depending on which side of the coin you look at it), the WiiU Home Screen is a lot more complicated than the Wii's System Menu and relies on having a lot of other things and lots of parts of the firmware emulated first. So its likely going to be a while until we see the Home Menu running in Cemu in a functional way, if ever at all

**Comment by shydert** [comment]
Yeah I know, I hope that in the future this gets worked on.

**Comment by Exzap** [comment]
This falls into the general topic of improving emulation accuracy which is on the roadmap. Thus I'm closing this issue since there is no need to request something that is planned anyway.
