### ISSUE TITLE
[Zelda BOTW] Invisible Enemies (Textures?)

### ISSUE THREAD

**Issue by Durocks** [cemu-project/Cemu#419]
- Running Zelda Breath of the Wild on the latest Nightly 2.0-999999 commit on a Macbook Pro M1 Pro 10 cores CPU.
- Game running at ~30FPS during actual gameplay.
- Issue: Treasure chests and big enemies (Like guardians) are invisible, making it very hard to fight/find them.
- Anything else I can provide please ask! And thank you very much for your hard work!

**Comment by f411guy** [comment]
I'm seeing the same issue as well--chests & large enemies not appearing.  Macbook Pro M1

**Comment by georgerusu017** [comment]
Hey guys, I do have the same problem, but also, do you see the doors, link's eyes or old man's staff?

**Comment by Dm1tryRin** [comment]
> Hey guys, I do have the same problem, but also, do you see the doors, link's eyes or old man's staff?

I have the same thing - no chests, some enemies, eyes, some doors, some weapons (like a fire sword).

**Comment by f411guy** [comment]
> Hey guys, I do have the same problem, but also, do you see the doors, link's eyes or old man's staff?

I do not see Link’s eyes, doors, certain slate pedestals, treasure chests, guardians, etc.—what is missing seems random, but it seems that others are all missing the same things. 

The chests, for example, are there and I can open them (if I know where to stand); however, Magnesis cannot activate on it.
