### ISSUE TITLE
Xbox Elite 2 controller not working in Cemu 2.0-9 (MacBook M1 Pro)

### ISSUE THREAD

**Issue by JiriKiner** [cemu-project/Cemu#420]
Hello. I tried the Cemu version 2.0-8 and there were no issues with the controller. I am using Xbox Elite 2 Controller via bluetooth and it was found in the settings and working as expected (apart from that I have to remove and add it very time I restart the Cenu). However, after updating to 2.0-9, the controller is not found anymore in the settings. So I had to switch back to 2.0-8. I am using MacBook Pro with the M1 Pro chip. Thank you in advance.

**Comment by Squall-Leonhart** [comment]
these controllers have a flaw when run via bluetooth where vibration command overload causes them to reset into a type of safe mode.

**Comment by Exzap** [comment]
Closing because this issue is stale
