### ISSUE TITLE
[macOS] Error when right clicking a game and selecting Game/Save directory

### ISSUE THREAD

**Issue by jamescastells** [cemu-project/Cemu#426]
When right-clicking a game, and selecting either Game directory or Save directory, instead of a Finder window appearing with the location of the game, an error appears:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/5696029/198675149-f3702de6-9ce7-4331-a1c2-718627bfbfc7.png">

**Comment by Tillsunset** [comment]
I believe I have narrowed down the issue to the path name contains a space, working on a fix now
