### ISSUE TITLE
[MacOS] Feature Request: Give an option to enable Metal 3 Performance HUD

### ISSUE THREAD

**Issue by AndreaCicca** [cemu-project/Cemu#427]
Apple have just release MacOS ventura and with it  new features among which a new Performance HUD that can be enable thanks to a variable that have to be set in Cemu's executable.

I understand that Cemu has it's performance Hud (that it's broken at the moment on MacOS, but this is a different topic), but I think that this can be an interesting thing to add.

<img width="1392" alt="Screenshot 2022-10-28 alle 21 03 33" src="https://user-images.githubusercontent.com/58073848/198715621-245ab47b-f056-4445-b0d2-94bb154415c2.png">

Image description: Cemu 2.0-9 on MacOS Ventura with the Metal 3 Performance HUD enable.

**Comment by UltraHDR** [comment]
The ask is to programatically export `MTL_HUD_ENABLED=1` for this to work     

You can enable it manually now in Terminal by:
```
~$ export MTL_HUD_ENABLED=1                  
~$ /Applications/Cemu.app/Contents/MacOS/Cemu
```

**Comment by AndreaCicca** [comment]
It's what I have done for the screenshot, but think that would be nice to have a flag in Cemu's settings to do this via a GUI.

**Comment by goeiecool9999** [comment]
> I understand that Cemu has it's performance Hud (that it's broken at the moment on MacOS, but this is a different topic)

I noticed it was missing on linux to so I went looking for the code that draw the performance graph and I couldn't find it. I'm not sure where it went but maybe it was going through a rewrite and it wasn't finished before public release.

**Comment by AndreaCicca** [comment]
Now that Apple allows to enable Metal HUD with an hotkey on MacOS Sonoma and Cemu fixed its Performance HUD I am going to close this issue
