### ISSUE TITLE
No sound api found log states can't create cubeb audio api

### ISSUE THREAD

**Issue by Ntemis** [cemu-project/Cemu#428]
[log.txt](https://github.com/cemu-project/Cemu/files/9892721/log.txt)

**Comment by Ntemis** [comment]
wpctl status
PipeWire 'pipewire-0' [0.3.51, demetris@demetris-TA770E3, cookie:2209588130]
 └─ Clients:
        31. xdg-desktop-portal                  [0.3.51, demetris@demetris-TA770E3, pid:3470]
        32. pipewire-media-session              [0.3.51, demetris@demetris-TA770E3, pid:45624]
        33. pipewire-pulse                      [0.3.51, demetris@demetris-TA770E3, pid:45625]
        35. pipewire-media-session              [0.3.51, demetris@demetris-TA770E3, pid:45624]
        36. WirePlumber                         [0.3.51, demetris@demetris-TA770E3, pid:45626]
        37. WirePlumber [export]                [0.3.51, demetris@demetris-TA770E3, pid:45626]
       145. Cinnamon Volume Control             [0.3.51, demetris@demetris-TA770E3, pid:2752]
       146. Cinnamon Volume Control Media Keys  [0.3.51, demetris@demetris-TA770E3, pid:2607]
       147. mplayer                             [0.3.51, demetris@demetris-TA770E3, pid:45739]
       153. wpctl                               [0.3.51, demetris@demetris-TA770E3, pid:47325]

Audio
 ├─ Devices:
 │      48. GM206 High Definition Audio Controller [alsa]
 │      49. Built-in Audio                      [alsa]
 │      54. Built-in Audio                      [alsa]
 │  
 ├─ Sinks:
 │      34. Built-in Audio Pro                  [vol: 1.00]
 │      50. Built-in Audio Pro 10               [vol: 1.00]
 │      51. Built-in Audio Pro 8                [vol: 1.00]
 │      52. Built-in Audio Pro 9                [vol: 1.00]
 │      53. Built-in Audio Pro 7                [vol: 1.00]
 │  *   55. GM206 High Definition Audio Controller Digital Stereo (HDMI 2) [vol: 0.79]
 │      56. Built-in Audio Analog Stereo        [vol: 1.00]
 │  
 ├─ Sink endpoints:
 │  
 ├─ Sources:
 │  
 ├─ Source endpoints:
 │  
 └─ Streams:

Video
 ├─ Devices:
 │  
 ├─ Sinks:
 │  
 ├─ Sink endpoints:
 │  
 ├─ Sources:
 │  
 ├─ Source endpoints:
 │  
 └─ Streams:

Settings
 └─ Default Configured Node Names:
         0. Audio/Sink    alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1

**Comment by Squall-Leonhart** [comment]
install pulseaudio

ALSA is deprecated and no longer maintained in cubeb.

**Comment by jn64** [comment]
They are using pipewire-pulse, not "pure ALSA". pipewire-pulse is widely used with cubeb (e.g. with Firefox on Fedora, Arch).

FWIW I don't have this issue on Fedora 36 with pipewire 0.3.59 and cubeb 0.2, and no other reports of this from Fedora / Arch / Steam Deck users. Only #40 maybe related from Ubuntu users, which was resolved by building with libpulse-dev.

**Comment by jn64** [comment]
I found that libpulse-dev was added to Ubuntu build instructions in https://github.com/cemu-project/Cemu/commit/7d461d1658aab5d8fe9fa8848ae4627963fa6a93 but never added to [the GitHub workflow](https://github.com/cemu-project/Cemu/blame/main/.github/workflows/build.yml#L48).

**Comment by Ntemis** [comment]
fixed
![image](https://user-images.githubusercontent.com/2123893/198830890-8ed1975b-d742-41fa-8b5b-9b0a23cad3e7.png)

**Comment by Ntemis** [comment]
Ubuntu 22.04.1 mate but using cinnamon

**Comment by r2rX** [comment]
I just compiled the latest build on Fedora 36. Although Cubeb is present and selected, there's no audio in any title run. All dependencies are accounted for and installed.

**Comment by jn64** [comment]
> Cubeb is present and selected

@r2rX That's clearly different from this issue, please open a new issue with relevant logs. Make sure you have selected an audio device under TV, and set the volume.

**Comment by r2rX** [comment]
@jn64 Thanks for the feedback. I had deleted my post, before your response, since I figured that I had to manually select the audio device under TV. It's working great now. :+1:
