### ISSUE TITLE
Cemu 2.0 - Crash when disabling separate gamepad view

### ISSUE THREAD

**Issue by bkacjios** [cemu-project/Cemu#432]
Basically, if you enable the separate gamepad view then later decide to disable it, cemu will crash and just exit with no error or anything.

![image](https://user-images.githubusercontent.com/3247233/198850463-8be05449-92fc-43d8-864f-673b95adbb6b.png)

**Comment by goeiecool9999** [comment]
Duplicate of #278?

**Comment by Squall-Leonhart** [comment]
definitely duplicate.

**Comment by bkacjios** [comment]
Ah, yeah, looks like it. Didn't see that when I searched.
