### ISSUE TITLE
[MacOS] Cemu trying to check free space on root disk instead of disk of MLC Path on macOS 12

### ISSUE THREAD

**Issue by ramzzzay** [cemu-project/Cemu#436]
Hello, I've tried to use my external ssd for games and have found Cemu checks mac's ssd for free space instead of external ssd free space.

> My Mac: MacBook Pro (16-inch, 2021), 16 ram / 512 ssd
> macOS: 12.5

> Cemu release tag: 2.0-10, hash: e0aaf631c460cd893c3ec682a237891f2d1baa50 [Cemu 2.0-10 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-10)

<img width="698" alt="image" src="https://user-images.githubusercontent.com/5748239/198885351-1131a799-bac6-465f-a9b7-28504960d64c.png">
<img width="883" alt="image" src="https://user-images.githubusercontent.com/5748239/198885372-85db04ae-abb6-44eb-86c1-a364236d048e.png">
<img width="372" alt="image" src="https://user-images.githubusercontent.com/5748239/198885380-e7eb99a9-3c44-454a-b77c-e40922b968b9.png">

**Comment by Tillsunset** [comment]
This is due to the filesystem structure. On windows each partition is mounted as a different drive letter. On macOS and linux it mounts as a directory on the root mount point. This is a oversimplification but is fine for this issue. I'll get started on this.
