### ISSUE TITLE
[MacOS/Windows] Cemu 2.0-10 can't run games with merged updates, but Cemu 1.26.2f works fine

### ISSUE THREAD

**Issue by ramzzzay** [cemu-project/Cemu#437]
Hello, I've some games that have merged base game with updates and all works fine on my windows PC (but right now I doesn't have it with me, so I've used windows in VM for showcase) with all "old good" Cemu 1.26.2f (and whole 1.xx line), but in Cemu 2.xx titles installs as updates and I can see them in "Title Manager" but can't run. 

> My Mac: MacBook Pro (16-inch, 2021), 16 ram / 512 ssd
> macOS: 12.5

> Cemu release tag: 2.0-10, hash: e0aaf631c460cd893c3ec682a237891f2d1baa50 [Cemu 2.0-10 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-10)

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/5748239/198889119-776242b5-7316-465f-aa84-76ac56667184.png">

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/5748239/198889191-75d971d8-d850-4125-8dc0-8777658303a8.png">

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/5748239/198889632-9ab527f9-9e6f-41a5-bed2-227e5d07f446.png">

**Comment by Exzap** [comment]
Merging updates into the base game via copy&paste was always something that was strongly discouraged as it breaks the meta data. On an actual Wii U the files are always kept separate. We even added a warning to Cemu (red background on the game list) to make people aware that this is something to avoid. Please redump your games and updates and use .wua format if you dislike having multiple folders. But we are certainly not bringing back the ability to run merged titles.
