### ISSUE TITLE
[macOS] Vulkan and Metal behavior difference. Failure to create pipeline

### ISSUE THREAD

**Issue by Tillsunset** [cemu-project/Cemu#444]
Vulkan allows vertex strides of arbitrary size. Metal requires it to be a multiple of 4. [Link 1](https://developer.apple.com/documentation/metal/mtlvertexbufferlayoutdescriptor/1515441-stride?language=objc) [link 2](https://github.com/KhronosGroup/MoltenVK/blob/master/MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm#L1324). 

So far I've just been able to find where the failure starts to propagate from. [Link](https://github.com/cemu-project/Cemu/blob/main/src/Cafe/HW/Latte/Renderer/Vulkan/VulkanPipelineCompiler.cpp#L460). I haven't been able to find where the bufferStride is set. The behavior I've seen with the pipeline failure is bufferStride is set to 1 as opposed to the usual 8/16/24/28. I assume on other platforms this isn't an issue, but on macOS it is due to Metal. I just need help locating where the buffer is allocated and add a minimum stride of 4.

This is causing the failures seen in the logs. I'm assuming this is manifesting as missing textures. I made this an issue to help keep track of it

[log.txt](https://github.com/cemu-project/Cemu/files/9923865/log.txt)

**Comment by goeiecool9999** [comment]
Probably related to #419

**Comment by Cylrx** [comment]
Had the same issue. I managed to temporarily fix it is by completely reinstalling the game and Cemu (except the mlc folder so I can keep my saves). But it crashes again within hours. Super annoying.

**Comment by Tillsunset** [comment]
That seems to be a unrelated issue @Cylrx

**Comment by Cylrx** [comment]
> That seems to be a unrelated issue @Cylrx

I have the exact same logs tho. 
![IMAGE 2022-11-03 07:56:57](https://user-images.githubusercontent.com/117046455/199624003-d03fdcbf-c908-4a9e-a0e8-1741d4b91c2b.jpg)

**Comment by Tillsunset** [comment]
The crashing is unrelated to the failed to pipeline issue

**Comment by Cylrx** [comment]
my bad

**Comment by Exzap** [comment]
The buffer stride and data comes from the game so this isn't something we really have control over. A quick&hacky workaround would be to force the stride to always be a multiple of 4 regardless. At least that way pipeline creation doesn't completely fail and instead there would be corrupted graphics, which may be more desirable than none at all. Furthermore corruptions might be fixable with graphic pack shader edits.

Not sure how to solve this properly. There is no easy solution. We have to manually transform the data before each drawcall which is a PITA to code and comes with a significant performance cost.

**Comment by Tillsunset** [comment]
Fixed with #534
