### ISSUE TITLE
[macOS] Super Mario Maker only renders a black screen on M1 Pro

### ISSUE THREAD

**Issue by federicochiesa** [cemu-project/Cemu#447]
I'm using the cemu 2.0-11 release and my system is an M1 Pro MacBook Pro 16". If I try to play Super Mario Maker I get a black screen after the initial screen even though the game is running(I can hear the sound if I jump).

**Comment by Exzap** [comment]
This is due to missing geometry shader support in MoltenVk. Anyway, lets not make a separate issue for every single game specific problem in the MacOS build considering it is still pretty experimental. The [MacOS compatibility list](https://cemu.emiyl.com/) is far more suitable.
