### ISSUE TITLE
[macOS] MK8 Graphical issues

### ISSUE THREAD

**Issue by FRtranslator** [cemu-project/Cemu#454]
It is probably known that there are graphical glitches on macOS, but I just wanted to report it. I hope it isn't a duplicate issue.

There are many graphical bugs in Mario Kart 8 on macOS.
It can be on the kart, the character, or the ground. Sometimes, stuff is missing like banners.

For instance, at the character selection screen, there are lots of blinking parts on the character.

In this screenshot, look at the kart and the [?] block just behind.
![Kart](https://user-images.githubusercontent.com/27890322/199947259-089c7279-e578-4b20-81f3-2171c4313e60.png)

In this other screenshot, look at the ground at the bottom: there are squares as if it was an ultra-compressed video.
![Ground](https://user-images.githubusercontent.com/27890322/199947284-5e0c152b-e761-4bd5-8c3d-76e1724dd23a.png)

These issues have been reproduced on 2.0-13 and earlier, using a Mac M1.

**Comment by Squall-Leonhart** [comment]
Exzap Says:
> Anyway, lets not make a separate issue for every single game specific problem in the MacOS build considering it is still pretty experimental. The [MacOS compatibility list](https://cemu.emiyl.com/) is a far more suitable resource.
