### ISSUE TITLE
Unable to launch game Path

### ISSUE THREAD

**Issue by YLinXin** [cemu-project/Cemu#456]
Cemu:
  2.0-13(AMD64 experimental)

Permission:
 Full Disk Access

OS:
  Version 13.0 (22A380)

SoC:
  M1(ARM64)

File Type:
  wux

Action:
  `/Applications/Cemu.app/Contents/MacOS/Cemu  -g ~/Downloads/Captain\ Toad\ -\ Treasure\ Tracker\ \(USA\)\ \(EnFrEs\)\ \(v1.01\).wux`

![Screenshot 2022-11-05 at 11 00 17](https://user-images.githubusercontent.com/68999554/200098245-1d13c937-1519-4eda-95ef-9c4e4c4c489c.png)

**Comment by Exzap** [comment]
We don't troubleshoot piracy
