### ISSUE TITLE
[Linux] Controller profiles cannot be selected

### ISSUE THREAD

**Issue by lisa-wolfgang** [cemu-project/Cemu#460]
In the input settings, the dropdown to select controller profiles is unselectable, even though I have multiple profiles for the selected controller. I've confirmed that saving profiles still works -- they appear in the `controllerProfiles` folder.

Cemu version: https://github.com/cemu-project/Cemu/commit/a40b226e003b7ad6a21612f6a1a72ba09f102faa
Operating system: Ubuntu 22.10

**Comment by Crementif** [comment]
Any reason why this is using an older commit? Did you compile it yourself or did you get the unofficial aur package and that is the reason it's out of date?

**Comment by lisa-wolfgang** [comment]
I do build it myself -- I just haven't pulled and rebuilt yet today.

**Comment by Exzap** [comment]
Bugged dropdowns are usually due to using older GTK version

**Comment by lisa-wolfgang** [comment]
The version of `libgtk-3-dev` I have installed is `3.24.34-3ubuntu2`.

**Comment by jn64** [comment]
Can repro on latest 1385101 on Fedora 36. gtk3-devel 3.24.34.

Probably was always broken for me, just didn't notice because I didn't save more than 1 profile.

**Comment by lisa-wolfgang** [comment]
No, I was able to do that successfully earlier today.
