### ISSUE TITLE
Cemu crashes when trying to launch a games

### ISSUE THREAD

**Issue by ricaan** [cemu-project/Cemu#465]
Worked fine for a while, afterwards just started crashing when trying to launch botw
[Buglog.txt](https://github.com/cemu-project/Cemu/files/9948879/Buglog.txt)

**Comment by Exzap** [comment]
Crashes during Vulkan initialization but thats all I can tell from the log. Possibly some issue with the graphics driver?
Anyway, please use the Discord for troubleshooting
