### ISSUE TITLE
CEMU crashing consistently with SDLControllers

### ISSUE THREAD

**Issue by HollyCeuin** [cemu-project/Cemu#468]
If I load a profile that uses an SDLController, then load another that also uses that, CEMU crashes, reliably. v1.26.2.

**Comment by Squall-Leonhart** [comment]
Already fixed in 2.0

**Comment by HollyCeuin** [comment]
I just updated to 2.0 and it did the exact same thing.

Excerpt from log:

Crashlog for Cemu 2.0 (experimental)
Date: 08-11-2022 02:03:51

-----------------------------------------
   Stack trace
-----------------------------------------
0x00007ff7b83a6b78 +0x000d6b78 Cemu.exe         GraphicPack2_GetDescription
0x00007ff7b83a70aa +0x000d70aa Cemu.exe         GraphicPack2_GetDescription
0x00007ff7b83a838d +0x000d838d Cemu.exe         GraphicPack2_GetDescription
0x00007fffde806b1c +0x00156b1c KERNELBASE.dll   UnhandledExceptionFilter
0x00007fffe0f5861d +0x000a861d ntdll.dll        RtlMoveMemory
0x00007fffe0f3f087 +0x0008f087 ntdll.dll        _C_specific_handler
0x00007fffe0f53eaf +0x000a3eaf ntdll.dll        _chkstk
0x00007fffe0eceae6 +0x0001eae6 ntdll.dll        RtlFindCharInUnicodeString
0x00007fffe0f52e9e +0x000a2e9e ntdll.dll        KiUserExceptionDispatcher
0x00007ff7b8823d78 +0x00553d78 Cemu.exe         wxGetEventByName
0x00007ff7b8759bb1 +0x00489bb1 Cemu.exe         wxCheckTree::SetFocusFromKbd
0x00007ff7b875a153 +0x0048a153 Cemu.exe         wxCheckTree::SetFocusFromKbd
0x00007ff7b87433b7 +0x004733b7 Cemu.exe         wxCheckTree::SetFocusFromKbd
0x00007ff7b8742d11 +0x00472d11 Cemu.exe         wxCheckTree::SetFocusFromKbd
0x00007ff7b865d5f3 +0x0038d5f3 Cemu.exe         wxCheckTree::~wxCheckTree
0x00007ff7b86572b5 +0x003872b5 Cemu.exe         wxCheckTree::~wxCheckTree
0x00007ff7b862f595 +0x0035f595 Cemu.exe         wxMainWindowCreated
0x00007ff7b8a2f2d4 +0x0075f2d4 Cemu.exe         wxGetEventByName
0x00007ff7b8a276ff +0x007576ff Cemu.exe         wxGetEventByName
0x00007ff7b8a27aba +0x00757aba Cemu.exe         wxGetEventByName
0x00007ff7b8a27d4f +0x00757d4f Cemu.exe         wxGetEventByName
0x00007ff7b8a2762b +0x0075762b Cemu.exe         wxGetEventByName
0x00007ff7b8a27a2a +0x00757a2a Cemu.exe         wxGetEventByName
0x00007ff7b8a5e4bc +0x0078e4bc Cemu.exe         wxGetEventByName
0x00007ff7b8a5f0e5 +0x0078f0e5 Cemu.exe         wxGetEventByName
0x00007fffe00e8161 +0x00018161 USER32.dll       DispatchMessageW
0x00007fffe00e7c21 +0x00017c21 USER32.dll       DispatchMessageW
0x00007fffe00e8a8d +0x00018a8d USER32.dll       IsDialogMessageW
0x00007ff7b89496d0 +0x006796d0 Cemu.exe         wxGetEventByName
0x00007ff7b8949812 +0x00679812 Cemu.exe         wxGetEventByName
0x00007ff7b894915e +0x0067915e Cemu.exe         wxGetEventByName
0x00007ff7b8a3d723 +0x0076d723 Cemu.exe         wxGetEventByName
0x00007ff7b8a3d8da +0x0076d8da Cemu.exe         wxGetEventByName
0x00007ff7b890aea1 +0x0063aea1 Cemu.exe         wxGetEventByName
0x00007ff7b863d007 +0x0036d007 Cemu.exe         wxCheckTree::~wxCheckTree
0x00007ff7b8a2f2d4 +0x0075f2d4 Cemu.exe         wxGetEventByName
0x00007ff7b8a276ff +0x007576ff Cemu.exe         wxGetEventByName
0x00007ff7b8a27e43 +0x00757e43 Cemu.exe         wxGetEventByName
0x00007ff7b8a2762b +0x0075762b Cemu.exe         wxGetEventByName
0x00007ff7b88f5106 +0x00625106 Cemu.exe         wxGetEventByName
Exception 0xc0000005 at 0x7ff7b8823d78(+0x553d78) in module Cemu.exe
cemu.exe at 0x7ff7b82d0000

RAX=0000000000000000 RBX=0000000005aaeab8 RCX=00000000000a0cf2 RDX=0000000000000000
RSP=0000000004aced48 RBP=0000000004aceee9 RDI=0000000005aae950 RSI=0000000005aae950
R8 =0000000004acf080 R9 =0000000000004000 R10=cf18061710d6ea70 R11=0000000004acee28
R12=0000000004acf080 R13=000000000e46cc48 R14=0000000004acee50 R15=0000000005a66f20

-----------------------------------------
   Game info
-----------------------------------------
Not running

-----------------------------------------
   Active PPC instance
-----------------------------------------
Not active

-----------------------------------------
   PPC threads
-----------------------------------------
None active

**Comment by HollyCeuin** [comment]
That works. Thanks.
