### ISSUE TITLE
[Linux] Don't resume shader compiling phase on Call of Duty Black Ops II

### ISSUE THREAD

**Issue by joao-pedro-barbosa** [cemu-project/Cemu#469]
Sum up: Doesn't show shader compiling progress and doesn't transtition to game start.

cemu version: v2.0-13: a40b226e003b7ad6a21612f6a1a72ba09f102faa
game/title id: Call of Duty: Black Ops II, USA, 000500001010cf00
hardware: i5-11400f, 16GB, Gigabyte 1060 6GB
os: batocera linux 36-dev-64f31543a8 2022/11/08 00:59
occurs on: game launching
log: [cemu-log.txt](https://github.com/cemu-project/Cemu/files/9960063/cemu-log.txt)

**Comment by Squall-Leonhart** [comment]
use the vulkan backend for this title.

**Comment by joao-pedro-barbosa** [comment]
Hi. Same result using vulkan.
Here the log.

[cemu-log.txt](https://github.com/cemu-project/Cemu/files/9961802/cemu-log.txt)

There is some update to the USA version? I'm not using graphic packs.

**Comment by Squall-Leonhart** [comment]
Yes, and its required on the console to even boot the game.

**Comment by joao-pedro-barbosa** [comment]
Ok. I'll try with it then. Thanks!

**Comment by joao-pedro-barbosa** [comment]
After test game in its version 128, still having same behaviour. Someone else can test it, please?

**Comment by joao-pedro-barbosa** [comment]
Working on 138510106c63ff697d31fe8e57391e245e477b5c too.
