### ISSUE TITLE
[Feature Request] Make SDL more UI friendly

### ISSUE THREAD

**Issue by NineKain** [cemu-project/Cemu#478]
Make selecting SDL and other input APIs less hidden on the options

**Comment by Makonede** [comment]
It does worksout of the box, use the [SDL API](https://cemu.cfw.guide/controller-configuration.html).

**Comment by NineKain** [comment]
Its not exactly very noticeable unless you know beforehand, maybe make it more clear on the UI?

**Comment by Exzap** [comment]
There is definitively room for improvement with the input UI but vague issues / requests dont help anyone.
