### ISSUE TITLE
Cemu crashes when booting Mario Kart 8 on Windows

### ISSUE THREAD

**Issue by Eggslegend** [cemu-project/Cemu#482]
Here is the log file:[](url)
[log.txt](https://github.com/cemu-project/Cemu/files/9994336/log.txt)

**Comment by Squall-Leonhart** [comment]
> [14:29:28.854] gameprofile path:  (not present)

This should be present, setting single core recompiler.

**Comment by Eggslegend** [comment]
Still crashed after changing to single recompiler.
[log.txt](https://github.com/cemu-project/Cemu/files/9995329/log.txt)

**Comment by Eggslegend** [comment]
I found that crashes result from my Pretendo account...
Create another account solved this issue.
Thanks for your help!
