### ISSUE TITLE
[Feature Request] Anisotropic Filtering

### ISSUE THREAD

**Issue by NineKain** [cemu-project/Cemu#483]
Makes angles and faraway textures look way smoother and makes for a more overall stable image

**Comment by Crementif** [comment]
This is already a graphic pack feature and is available in most of the popular community graphic packs. Doing it on a specifically tuned basis for only some of the textures prevents some graphical issues that happen when you scale the wrong textures, hence why it's not a global option. If you want to apply it globally for all Cemu games you can use the Nvidia Control Panel and the AMD equivalent to inject AF.
