### ISSUE TITLE
[Windows] Discord rich presence not working?

### ISSUE THREAD

**Issue by nonremittal** [cemu-project/Cemu#487]
Cemu 2.0, Windows 10,

Enabled the 'Discord Presence' option in General settings. Discord didn't automatically detect Cemu while it was running, I added it manually. Just getting the titlebar text like any other program:
![status](https://user-images.githubusercontent.com/58081816/201488974-3733f817-3678-47bc-bfa5-04db3760a94b.png)
Doesn't change while running a game.

**Comment by matt7570** [comment]
Same problem here, still no solution?

**Comment by matt7570** [comment]
Just "fixed" it. I updated Cemu to the latest experimental version.

**Comment by susbaconhairman** [comment]
I have it enabled, and Cemu doesn't even show up on Discord for me.
