### ISSUE TITLE
[Linux] [appimage] 2.0-15 appimage "filesystem error: cannot get free space" on game install  

### ISSUE THREAD

**Issue by QEDeD** [cemu-project/Cemu#489]
filesystem error: cannot get free space: No such file or directory [/-home/$user/CEMU/mlc01/usr/title/00050000&101c9400]

There's plenty of space (>100 GB) and inode doesn't seem to be a problem either.

![cemu_bug](https://user-images.githubusercontent.com/16562457/201517425-b2cf5b67-94d1-4835-9032-558f7be6aca1.png)

**Comment by qurious-pixel** [comment]
Check if that path from the error message actually exists.
The default path for a new install for mlc is `/home/$USER/.local/share/Cemu/mlc01`
You can copy your mlc to this location, or point your mlc path to the existing one.

![image](https://user-images.githubusercontent.com/62252937/201522216-39a6e775-879d-4343-b06d-53ca9b3e849b.png)

**Comment by Mars7x** [comment]
I'm having the same issue. FWIW I receive the same error if I build Cemu from source, so I don't think it's an issue from the appimage.

**Comment by disobeyedtoast** [comment]
I downloaded CEMU from the AUR and I am having the same issue. Even when manually setting the MLC path this still appears.

**Comment by AMuniz1** [comment]
![Captura de tela de 2022-11-16 16-34-35](https://user-images.githubusercontent.com/14057940/202277187-19415b24-d3dd-4915-9b9f-3940be9c6bd3.png)
I also have the same problem, no matter what, when I try to install any update or DLC from Tokyo Mirage Sessions #FE (the only game I have) this same error occurs.
I am going to watch this topic. I am amazed by Cemu's performance. Keep up the excellent work!

**Comment by johalun** [comment]
Same here on macOS. I did some bisecting and it I can install updates on 2.0.4 but not 2.0.14.

**Comment by qurious-pixel** [comment]
Should be fixed with PR https://github.com/cemu-project/Cemu/pull/503

**Comment by johalun** [comment]
I used a custom path without spaces any still had the issue so there might be other issues at play...

**Comment by qurious-pixel** [comment]
@johalun the issue presented is not the path itself, but a check on the path for free space. 
Is there enough space to install?, and the check was returning "no" even if there was space available.

**Comment by greenseeker** [comment]
Confirming that I'm successfully installing as I type this with -17

**Comment by johalun** [comment]
@qurious-pixel Yeah I realize also that my error was not about free space but something else (but similar). Can't remember now but I'll give it a test at the next release.

**Comment by QEDeD** [comment]
Can confirm that _install_ works as expected using version 2.0-17 :+1:
