### ISSUE TITLE
[macOS] [Request] Universal app

### ISSUE THREAD

**Issue by jamescastells** [cemu-project/Cemu#495]
Currently, Cemu is compiled as an Intel application. On M1/M2 Macs, it works through Rosetta 2, though of course there  is a performance hit. If the app is made into an Universal app (Intel + ARM app), Rosetta 2 will no longer be necessary and will run natively on the platform.

**Comment by jamescastells** [comment]
I expected this to remain open until this is achieved.

**Comment by Masamune3210** [comment]
No reason to track it twice, as already stated it's on the roadmap

**Comment by griffi-gh** [comment]
Recompiler needs to be ported to ARM or disabled (which is terribly slow) for this to work
