### ISSUE TITLE
[macOS] Typing with keyboard makes every typed character appear twice

### ISSUE THREAD

**Issue by jamescastells** [cemu-project/Cemu#496]
Tested with Wind Waker, on macOS. When the inputbox is displayed to use my physical keyboard, every inputted letter is displayed twice instead of just once. For example, I'm typing "Treasure" here, but this is displayed:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/5696029/202056780-4ccb33e5-53b7-4d05-a063-02aea9aa2f42.png">

Also, the backspace key doesn't work.

**Comment by JaimieVandenbergh** [comment]
Clicking the backspace button on-screen does work, so that gives you a workaround to get the game going

**Comment by jamescastells** [comment]
>Clicking the backspace button on-screen does work, so that gives you a workaround to get the game going

This is correct, but it's still a bug with the physical keyboard.
