### ISSUE TITLE
[OSX] Arm Unable to install games: Update error

### ISSUE THREAD

**Issue by karmacoma7** [cemu-project/Cemu#498]
Filesystem error: No such file or directory - MlC PATH

**Comment by Rambo6Glaz** [comment]
Also on Windows, Cemu 2.0-16

The error translates to: the path specified could not be found

I had to move the files manually

![image](https://user-images.githubusercontent.com/39063367/202079301-f1c9e380-a6f4-46db-94b8-a1ccdcd31d77.png)

**Comment by itstotallyjan** [comment]
this bug is preventing me from fixing the yellow screen bug in breath of the wild. tried creating the directory manually but that doesn't help.

**Comment by kokutoukiritsugu** [comment]
Windows 11, Cemu 2.0-16,
same error,
creating the directory manually doesn't help.

notice the path has / and \
xxx\mlc01\usr/title/xxx/xxx

**Comment by Exzap** [comment]
This should be fixed
