### ISSUE TITLE
Cemu Appimage Not Opening

### ISSUE THREAD

**Issue by CubixTwist** [cemu-project/Cemu#499]
I installed the newest Cemu Appimage, because the ubuntu zip file didn't work, but the Appimage dosen't work neither.
![Screenshot_2022-11-16_17-44-22](https://user-images.githubusercontent.com/114561247/202254515-83fe6999-6702-475c-9735-171abe021ce7.png)

**Comment by qurious-pixel** [comment]
The minimum supported `libc` version is `libc-2.31`  equivalent to Ubuntu 20.04.

**Comment by CubixTwist** [comment]
ah okay, there should be a Flatpak Build for Cemu however.

**Comment by Th1ngP3rs0n** [comment]
I'm having the same issue. Whenever I try to launch it through the terminal it says `execv error: No such file or directory`.

**Comment by Daniel6372** [comment]
@Th1ngP3rs0n Remove/disable AppImageLauncher and it will work after a reboot.

**Comment by CubixTwist** [comment]
*I use Linux Mint now, so the issue has been fixed.*
