### ISSUE TITLE
[Feature Request] Add Achievements Support with RetroAchievements

### ISSUE THREAD

**Issue by Zenjir0** [cemu-project/Cemu#50]
[Feature Requested]
[RetroAchievements](https://retroachievements.org/) is a web-service that allows for creation of achievements in older systems.

[Requirements]
According to their [official documentation](https://docs.retroachievements.org/System-X-wen/#requirements) the following needs to happen before support can be added:
- Emulation - Either a Standalone or Libretro Core
- Exposed Memory - The emulator must expose the emulated RAM
- Achievement Creation Support - They prefer Libretro Core for easier integration into their toolsets, but other standalones exist.
- Game Identification - Must be able to uniquely identify the games for the system
- Server Support - This is handled on RetroAchievement's side.

[My Thoughts]
This is probably not going to happen any time soon. But I figured I would create this Feature Request to spark interest in anyone who would might want to try adding support, as well as possibly helping point in a direction that might lead to achievement support one day; as several things need to happen first such as exposing the emulated RAM, adding UI elements, and possibly debugging tools. 

[More Reading]
[rcheevos](https://github.com/RetroAchievements/rcheevos): Library to parse and evaluate achievements and leaderboards for RetroAchievements 
[RAIntegration](https://github.com/RetroAchievements/RAIntegration) - The DLL responsible to integrate emulators with RetroAchievements.org 

Other standalones that support Retroachievements: 
- [Duckstation](https://github.com/stenzek/duckstation/pull/1677)
- [PCSX2](https://github.com/PCSX2/pcsx2/pull/6883) - WIP as of this post.

**Comment by Zenjir0** [comment]
Understandable. Thank you for your consideration of the feature request.

**Comment by ThomasHineXYZ** [comment]
Has the stance on this changed at all @Exzap ?

With the advant of Steam Deck, Emudeck, and more handhelds in general, I feel like there are more eyes on a feature like this.
