### ISSUE TITLE
Saving a loaded controller profile under a different name does not update the name correctly

### ISSUE THREAD

**Issue by jn64** [cemu-project/Cemu#501]
Cemu version: latest b1c7058 ~~+ 9afae50 from #500~~
OS: Fedora 36

## Description

When saving a loaded controller profile under a different name, the new name is used for the filename but is not updated in the `<profile>` tag.

~~Note: This is dependent on PR #500 but I think the bug exists before, it's just exposed to me now that I can load profiles.~~

After further testing, it doesn't need #500, can be reproduced from main branch.

## Steps to reproduce

1. Create a profile with name `foo`
2. Save profile → `controllerProfiles/foo.xml` is created containing `<profile>foo</profile>`
3. With profile `foo` loaded, change the name to `bar`
4. Save profile → `controllerProfiles/bar.xml` is created, still containing `<profile>foo</profile>`

## Suspected cause

https://github.com/cemu-project/Cemu/blob/b1c70588fe3f1cdee936ea2d6d83c6170e6c4ab8/src/input/InputManager.cpp#L475-L477

When saving, it's getting the existing profile name to write to the `<profile>` tag?

**Comment by BParks21** [comment]
Yeah I experience this all the time It's annoying.
