### ISSUE TITLE
Translate problem

### ISSUE THREAD

**Issue by rakantoh** [cemu-project/Cemu#506]
Some languages (in my case spanish) dont works, i already try to fresh install/config of cemu and still dont works, this in the latest versions of cemu 2.0 (2.0 -10 or later)

**Comment by latitudeh** [comment]
What doesnt work? The cemu menu translation or the ingame translation?
---
Que no está traducido? El menú o el idioma dentro del juego?

**Comment by rakantoh** [comment]
sorry, i forgot to be specific, the entire cemu menus, the games works fine.

**Comment by FRtranslator** [comment]
Confirmed: if I select Spanish as the UI language, all text is in English.
It works it I select French (although the translation has to be pulled to be updated).

The Spanish file exists in the right folder, but it might not be localized (can't check this right now).
I tried to replace the Spanish file with the French one, select Spanish as UI language, and after restarted Cemu the UI is in French (which is expected). So there might be an issue with the localized file.

@devs: can you push the language repository to Cemu to see if it fixes the issue (as well as updating languages)?

**Comment by zzb16888** [comment]
I set the cemu menu to Chinese and restart it still doesn't work

**Comment by kailous** [comment]
> 我将cemu菜单设置为中文并重新启动它仍然不起作用

你可以把中文的语言包 替换到起作用的语言中 比如俄语

**Comment by jamescastells** [comment]
Still happening as of Cemu 2.0-19. Selecting Spanish as Interface language doesn't translate the UI.

**Comment by Amnesia1000** [comment]
@Exzap  In flatpak, only the Default and English languages are displayed. None other.
