### ISSUE TITLE
[MacOS] xbox controller support

### ISSUE THREAD

**Issue by Suplanus** [cemu-project/Cemu#508]
`2.0-16`

I added the xbox controller via bluetooth. But cannot save the profile, so its lost and I can not use it in game.

![2022-11-18_13-30-46 (1)](https://user-images.githubusercontent.com/2002916/202707324-e4d8bc0b-2769-4c66-80dc-30d9f3b1074b.gif)

I saw other issues that describe that the setting is saved but thats not in my case:
https://github.com/cemu-project/Cemu/issues/420

**Comment by qurious-pixel** [comment]
Test with PR https://github.com/cemu-project/Cemu/pull/500 , but also ensure that you have selected an emulated controller profile. 

Your example shows as disabled.

**Comment by jn64** [comment]
@Suplanus Please refer to [Controller Configuration | Cemu Guide](https://cemu.cfw.guide/controller-configuration.html#instructions), specifically step 3:

> 3. Change `Emulated controller` to "Wii U GamePad"

**Comment by Suplanus** [comment]
Thank you 💖
