### ISSUE TITLE
[MacOS] Audio: Mario World 3D

### ISSUE THREAD

**Issue by Suplanus** [cemu-project/Cemu#509]
`2.0-16`

There is no audio in `Mario World 3D`.

**Comment by Squall-Leonhart** [comment]
Go to discord.

**Comment by Suplanus** [comment]
Sorry, there was no device configured 🙈
<img width="771" alt="image" src="https://user-images.githubusercontent.com/2002916/202707194-01551155-bde3-4ac9-a907-352f3c1ef569.png">
