### ISSUE TITLE
crash 3-3 yoshi woolly world 

### ISSUE THREAD

**Issue by marcelo4768** [cemu-project/Cemu#511]
crash 3-3 yoshi woolly world cemu 2.0-16 mac air m1 ventura 13.0.1
and 3-4 stage some textures are missing
[log.txt](https://github.com/cemu-project/Cemu/files/10045639/log.txt)

**Comment by marcelo4768** [comment]
crash when shader cashe up to x mb

**Comment by marcelo4768** [comment]
3-4 stage some textures are missing

**Comment by emiyl** [comment]
The macOS port is still experimental and is expected to have lots of issues. Try removing shader cache and see if that helps.

**Comment by itsmeelan** [comment]
> crash 3-3 yoshi woolly world cemu 2.0-16 mac air m1 ventura 13.0.1 and 3-4 stage some textures are missing [log.txt](https://github.com/cemu-project/Cemu/files/10045639/log.txt)

@marcelo4768 did you find a solution? I'm getting a crash when I try to play 3-3. How did you even get to 3-4?

**Comment by marcelo4768** [comment]
In easy mode you can use a wild card to pass the stage without having to play. 3-3 cannot be played because the emulator is turned off and 3-4 can be played with difficulty because some textures cannot be seen. Only these two stages of the entire game have problems.

**Comment by itsmeelan** [comment]
> In easy mode you can use a wild card to pass the stage without having to play. 3-3 cannot be played because the emulator is turned off and 3-4 can be played with difficulty because some textures cannot be seen. Only these two stages of the entire game have problems.

thank you so much! that worked :)
