### ISSUE TITLE
[macOS] [Apple M1Max] Frame rate drop (10fps) in Zelda Winwaker HD 

### ISSUE THREAD

**Issue by schabrolles** [cemu-project/Cemu#526]
Hello Evreyone, 

Just to share my experience, I was pleased to have this Cemu emulator working like a charm with my Apple M1 Max cpu and 30fps most of the time. 

But, when there is some "special effect" (some purple stars during the title, or some explosion) there is some slow down in the fps. I can deal with it and continue playing. BUT quickly after the beginning of the game ("Dragon Island" or something like this) It becomes totally unplayable at all during the scenes where there some ashes or dust in the air from the volcano. (10fps).

Am I the only one ? 
Is it because I'm running with Apple M1 and emu is still in x86 mode ? 
Is it due to a bad parameter on my side ?

When everything is OK 30fps=>
<img width="1392" alt="Screenshot 2022-11-22 at 13 46 35" src="https://user-images.githubusercontent.com/19491077/203319474-aa27dac0-6b35-4b60-95be-7bf6131415ad.png">

With volcano active 10fps =>
<img width="1392" alt="Screenshot 2022-11-22 at 13 46 47" src="https://user-images.githubusercontent.com/19491077/203319373-7ab77a79-7bd7-4f67-95d3-92d0e3152915.png">

Thanks

**Comment by cabrerahector** [comment]
Known issue, please see: https://discord.com/channels/286429969104764928/1043595946719711283/1044296991062097980

**Comment by schabrolles** [comment]
@Exzap thanks for the details

**Comment by iMonZ** [comment]
> Badly optimized game plus extra translation overhead from Rosetta (x86 -> ARM) and MoltenVk causes this. There likely won't be any near term solution available

So thats it? CEMU is dead?
