### ISSUE TITLE
Cemu crashes after opening Zelda?

### ISSUE THREAD

**Issue by zzb16888** [cemu-project/Cemu#529]
![image](https://user-images.githubusercontent.com/51110833/203963017-26139509-97d6-4c1a-9cd6-edcb2be05b77.png)

**Comment by zzb16888** [comment]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/51110833/203963623-56b7af01-48b2-4440-b4b7-2fdc3742eaba.png">
I have used the latest version, but I am still stuck here, and it will crash after a few tens of seconds

**Comment by joeyboey** [comment]
I got the same problem. First start worked flawlessly, now it won't open anymore.
Started happening in Version 17, persists in version 18.
There is no additional exception/error etc.

**Comment by zzb16888** [comment]
Zelda imports 00050000101C9300_VKPIPELINE.bin and 00050000101C9300_SHADERS.bin in cemu's cache path, then enters the game and saves the game progress manually, and the game will crash when it is opened for the second time

**Comment by zzb16888** [comment]
I imported the cache file downloaded from here https://chriztr.github.io/cemu_shader_and_pipeline_caches/

**Comment by zzb16888** [comment]
My environment is mac m1 pro

**Comment by Exzap** [comment]
It's a known issue with the MacOS builds. See #396. The workaround is to delete the cache each time.
