### ISSUE TITLE
Mystery 'c' account in Title Manager

### ISSUE THREAD

**Issue by jn64** [cemu-project/Cemu#530]
Cemu version: bc10485 (latest)

## Description

In the Title Manager, when selecting a save folder, the Account dropdown is populated with 2 entries, _80000001 (default)_ and one simply named _c_.

Selecting the _c_ account and clicking *Open directory* does nothing (it works for the default account)

Both *Download Manager* and *General Settings > Accounts* only show the default account.

I have not set up any accounts or changed any account settings. I also deleted the `<Accounts>` node from `settings.xml` to make sure everything related to accounts is default.

### Title Manager with the _c_ account
![screenshot_2022-11-25_19-22-05](https://user-images.githubusercontent.com/23169302/203976103-8a1049d6-ace5-43bf-9fb7-b25cc96c32a7.png)

### General Settings > Accounts does not have the _c_ account
![screenshot_2022-11-25_19-21-15](https://user-images.githubusercontent.com/23169302/203976236-534531e8-8ced-406c-b642-ec1427a8e2c2.png)

**Comment by Exzap** [comment]
Fixed by #590
