### ISSUE TITLE
Zelda manually saves the progress and enters the game for the second time and crashes

### ISSUE THREAD

**Issue by zzb16888** [cemu-project/Cemu#531]
Zelda imports 00050000101C9300_VKPIPELINE.bin and 00050000101C9300_SHADERS.bin in cemu's cache path, then enters the game and saves the game progress manually, and the game will crash when it is opened for the second time

**Comment by zzb16888** [comment]
I imported the cache file downloaded from here https://chriztr.github.io/cemu_shader_and_pipeline_caches/

**Comment by Exzap** [comment]
One issue is enough. #529
