### ISSUE TITLE
[Linux] Build failure due to SDL

### ISSUE THREAD

**Issue by Shoegzer** [cemu-project/Cemu#54]
Building on linux fails at the very end of the compilation process, related to SDL:
```
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libSDL2.a(SDL_waylandevents.c.o): in function `pointer_handle_button':
SDL_waylandevents.c:(.text+0x187e): undefined reference to `libdecor_frame_move'
/usr/bin/ld: SDL_waylandevents.c:(.text+0x1992): undefined reference to `libdecor_frame_resize'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
Relevant info:
* OS: LInux Mint 21 (Ubuntu 22.04 base) / kernel 5.15
* Cmake version: 3.24.0
* SDL version: 2.0.20
* Commit tested: a2abffd37b9ce62d8d5d52031ec6c56a7fd03938
* Full build log: [build.log](https://github.com/cemu-project/Cemu/files/9428099/build.log)

**Comment by bbaster** [comment]
Seems to be a duplicate of #30

**Comment by Shoegzer** [comment]
Quite right, I missed that one. Thanks for the heads-up. Closing.
