### ISSUE TITLE
Crash report for Mac 10.15.7

### ISSUE THREAD

**Issue by kpishere** [cemu-project/Cemu#540]
[Cemu_2022-11-28-155422_Mac-mini.crash.txt](https://github.com/cemu-project/Cemu/files/10107505/Cemu_2022-11-28-155422_Mac-mini.crash.txt)

**Comment by emiyl** [comment]
Please ask in the #macos channel in the Cemu [Discord Server](https://discord.gg/5psYsup) for troubleshooting support.
