### ISSUE TITLE
[macOS] Render bug of Zelda Breath of the Wild

### ISSUE THREAD

**Issue by Fince10086** [cemu-project/Cemu#549]
Version: Cemu 2.0-b361b15
Device: Macbook Pro 14 (M1 Pro)
Game Version: 00050000101c9300 (Japanese version)

Around Stolock Bridge

https://user-images.githubusercontent.com/87692117/205340717-a34880d9-bfe8-42e0-900d-dbf777b49a5d.mp4

<img width="1512" alt="2022-12-03 00 15 24" src="https://user-images.githubusercontent.com/87692117/205340813-f26a5788-3e30-45e5-a1e2-986c21be93f7.png">

**Comment by Yu-Haifeng** [comment]
https://cemu.emiyl.com/installation
<img width="937" alt="image" src="https://user-images.githubusercontent.com/42990940/205418299-d7595f3f-5424-4d5d-bb3a-afb9ee23473b.png">
This may help

**Comment by Fince10086** [comment]
> https://cemu.emiyl.com/installation <img alt="image" width="937" src="https://user-images.githubusercontent.com/42990940/205418299-d7595f3f-5424-4d5d-bb3a-afb9ee23473b.png"> This may help

Sorry but where can I setting it?

**Comment by Yu-Haifeng** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/42990940/205446738-c0d3e354-4d56-46f6-a7d0-39000709760c.png">

open cemu like this can set the env variable.
`export MVK_CONFIG_FAST_MATH_ENABLED=0`
`open -a cemu`

**Comment by Fince10086** [comment]
set variable does not help, but I know the reason now: I'm turn off the Accurate barriers😂
