### ISSUE TITLE
If I use 2 bcml image packages (Master Sword (Relic Reborn) [TotK] and linkebcml) at the same time, the game crashes. Why? Not if you use a single

### ISSUE THREAD

**Issue by zzb16888** [cemu-project/Cemu#554]
![image](https://user-images.githubusercontent.com/51110833/205551991-d883fd46-f83c-4e24-8a85-5d8109111335.png)
No crashes if you use one of them

**Comment by Serfrost** [comment]
Issues with mods should not be reported in this repository.  Compatibility between mods is the responsibility of the mod authors, not Cemu development.  Issues on this repository must have all graphicPacks (that includes mods) disabled before they will be accepted as a possible concern.
