### ISSUE TITLE
[Feature Request] Native DLC support for Tokyo Mirage Sessions and Hyrule Warriors

### ISSUE THREAD

**Issue by Serfrost** [cemu-project/Cemu#557]
At present a graphicPack patch is required for Hyrule Warriors' DLC to load. In the past, these titles would crash with their DLC installed. I believe the reason for Hyrule Warriors receiving a patch was due to it having available symbols to track down what was happening.

On the contrary, Tokyo Mirage Sessions (TMS) DLC has not received such support. It has been said that it lacks symbols to help find the underlying issue. However, these conversations are old and span over a few years.

Ideally Cemu should support both natively without requiring an external patch to help prevent end-user error or confusion. If it's possible to get TMS's DLC functional, this would be the ideal outcome.

**Comment by Squall-Leonhart** [comment]
graphics pack just bypasses the title.tik requirement.

**Comment by Serfrost** [comment]
> if you redownload it directly from Cemu with the title/dlc manager it should create the necessary file properly and work without needing the patch.

That actually makes a lot more sense then.  In that case this request is unnecessary.

**Comment by intra2** [comment]
We will be unable to redownload it from cemu after march 2023 or in 3 months, so this is still an issue

**Comment by Squall-Leonhart** [comment]
Only the purchase capabilities are being removed at that time, and if you don't own the game legitimately anyway then you have no grounds to complain.

**Comment by intra2** [comment]
the purchase capabilities are already gone, even removed the ability to use the switch eshop cards. march 2023 is when the eshop fully closes for good
