### ISSUE TITLE
Super Mario Maker Keeps Crasing

### ISSUE THREAD

**Issue by Purpl-ity** [cemu-project/Cemu#562]
SMM Keeps on crashing and I dont know why, I have been using vulkan with splatoon and it functions fine, opengl is dogshit for me so I am not going back to using opengl. I used pretendo servers, nintendo servers, disabled and enabled online mode and it still doesnt work. I am not storing it in a system folder I am storing it in a usb drive I have plugged in

**Comment by Exzap** [comment]
Please use the discord for troubleshooting
