### ISSUE TITLE
Wii U menu black screen

### ISSUE THREAD

**Issue by NoNameGivenCoder** [cemu-project/Cemu#575]
When loading the Wii U menu in versions after 2.0 Experimental, the Wii U menu only shows a black screen. Nothing more. Hope this gets fixed! 

[log.txt](https://github.com/cemu-project/Cemu/files/10233483/log.txt)

![Screenshot_14](https://user-images.githubusercontent.com/114644239/207765781-0c3aa9ac-f654-447a-90bf-7c5c3c0deffb.png)

**Comment by davidsosa2022** [comment]
same
