### ISSUE TITLE
Right-to-left UI interface

### ISSUE THREAD

**Issue by ahmed3110c** [cemu-project/Cemu#580]
I set system locale in windows in Arabic (Egypt) and the interface is shown right-to-left.
Even if set the language to English, it still shows right to left interface.
When i change the language other than English (French for example), it shows left-to-right inteface normally.
Please fix this locale bug.

![Screenshot 2022-12-16 134303](https://user-images.githubusercontent.com/35050653/208091255-e0ce46b0-e548-4dcc-9d34-e8f1bcdac718.jpg)
![Screenshot 2022-12-16 134347](https://user-images.githubusercontent.com/35050653/208091284-15f815f3-0546-4fb6-b9d4-b640cb111844.jpg)
![Screenshot 2022-12-16 134906](https://user-images.githubusercontent.com/35050653/208091963-d28f9b25-0c89-4c71-aba8-c86d9fbcb7e9.jpg)

**Comment by MythicalPlayz** [comment]
@ahmed3110c  Ok so the temporary fix is to set the Language from Default to English and restart CEMU.

until I find the solution

**Comment by Fs00** [comment]
@ahmed3110c @MythicalPlayz #994 contains a fix for this: could you please try out the build artifact in the PR and see if it works for you?
