### ISSUE TITLE
Splatoon 1 Reflection Glitch?

### ISSUE THREAD

**Issue by VoviTekk** [cemu-project/Cemu#581]
![image](https://user-images.githubusercontent.com/65232880/208174471-738d5aa5-e933-48de-a14d-c3385e92ffcb.png)
This never happened before, as i download the newest update this is now a thing

**Comment by VoviTekk** [comment]
Sorry for my Stupidy i had to switch to vulkan

**Comment by DerpBoxsrandomaccount** [comment]
"guys something is wrong with my plaza"
