### ISSUE TITLE
IR Pointer for emulated Wiimotes

### ISSUE THREAD

**Issue by max-2321** [cemu-project/Cemu#584]

**Comment by Fancy2209** [comment]
Does it even support it for real Wii remotes?

**Comment by legend800** [comment]
Yes, real wiimotes have worked for years. Go to discord for support.

**Comment by Fancy2209** [comment]
> Yes, real wiimotes have worked for years. Go to discord for support.

I was asking specifically if IR worked as I remember someone saying IR doesn't work at all on CEMU.

**Comment by legend800** [comment]
Yes IR on real remotes has worked for a long time. But it's the only way to get IR hence this GitHub issue requesting it for emulated wiimotes.

**Comment by Fancy2209** [comment]
Was misinformed
Was asking since it would make sense for a real ir implementation before a emulated one
Sorry for going off topic

**Comment by JulienJeon77** [comment]
Just like Dolphin emulator?

**Comment by legend800** [comment]
Yes. Dup of https://github.com/cemu-project/Cemu/issues/232

**Comment by Squall-Leonhart** [comment]
Confirmed duplicate, and original issue comment was not properly filled out.
