### ISSUE TITLE
CEMU Audio lag with USB Headphones

### ISSUE THREAD

**Issue by elhroberts56** [cemu-project/Cemu#587]
For some reason, CEMU has a slight audio issue with my Corsair USB headset. I am playing on version 2.0 and tested with all audio backends, and I found out that with my USB headset plugged in to a USB port, the in-game audio will start to lag after about 10 minutes, and the lag gets progressively worse the longer I play on CEMU. When I remove the USB adapter and then plug my headset directly into the audio jack, CEMU doesn't have the audio lag issue at all even if I play for an hour. So it would seem CEMU has a slight issue with my USB adapter for my headset. Even uninstalling the iCUE software for my headset doesn't resolve this issue.

**Comment by Exzap** [comment]
Closing this since nobody else reported this problem. Aside from that it's not up to us to fix broken drivers.

**Comment by Squall-Leonhart** [comment]
This would be https://help.corsair.com/hc/en-us/articles/360033489511-Fix-Corsair-headset-sound-issues-after-an-iCUE-software-update
