### ISSUE TITLE
Disney Infinity/LEGO Dimensions built-In portal emulation

### ISSUE THREAD

**Issue by Fancy2209** [cemu-project/Cemu#588]
As the title says, it would be interesting if CEMU could have a way to emulate those toys to life Portals like how RPCS3 (and soon dolphin from what I have seen) can for the Skylanders Portal at least

**Comment by Squall-Leonhart** [comment]
It already does.

**Comment by Fancy2209** [comment]
> It already does.
> 
> https://wiki.cemu.info/wiki/Skylanders:_Swap_Force

I do not mean native portals 
I mean a Emulated Portal

**Comment by Fancy2209** [comment]
E.g on RPCS3 Manage -> Skylanders Portal

**Comment by spudpiggy** [comment]
> As the title says, it would be interesting if CEMU could have a way to emulate those toys to life Portals like how RPCS3 (and soon dolphin from what I have seen) can for the Skylanders Portal at least

They don't really need to be built in imo. Lego Dimensions' Wii U version is often considered its worst. I personally emulate the PS3 version [using this toypad emulator. inb4 yes it works on cemu](https://github.com/Berny23/LD-ToyPad-Emulator)

**Comment by Fancy2209** [comment]
> 

I've used that before. To be honest I made this issue more for Skylanders/Disney Infinity than for LEGO Dimensions

**Comment by minilandl** [comment]
I am trying to get the original toypad working in cemu on Linux 

Tried using the arch package.
The toypad showed up fine in lsusb 
When launching Lego dimensions the toypad was still not detected.

Could be windows specific as previously I couldn't get the toypad working under Linux but it worked in windows and was detected by cemu

**Comment by Vicourld51** [comment]
I saw that the RPCS3 code for portal of power had been used on dolphin, is it possible to adapt it to cemu?

**Comment by Squall-Leonhart** [comment]
No, as it would require the original contributor to dual license it.

**Comment by Vicourld51** [comment]
So maybe adapt only the RPCS3 code, and name the license like dolphin did. I wasn't talking about taking dolphin's code directly!

**Comment by XargonWan** [comment]
I'm looking for this feature as well, I have the physical one, but I would like an emulated one for when I'm not docked with my Steam Deck.

**Comment by Fancy2209** [comment]
There's #971

**Comment by Exzap** [comment]
Reopening this because only Skylander portal is emulated for now.

**Comment by Fancy2209** [comment]
If this was reopened for the Infinite Base, shouldn't it be reopened for Lego Dimensions' Toy Pad that the title also mentions?

**Comment by Exzap** [comment]
This issue has become kind of messy so I would appreciate a new feature request specific to Lego Dimensions

**Comment by Fancy2209** [comment]
Fair, will do so!
