### ISSUE TITLE
[Feature Request] CEMU Tas Movie Format

### ISSUE THREAD

**Issue by Crain-32** [cemu-project/Cemu#59]
Cemu eventually being able to create/playback TASes is by far one thing I'm excited to see happen sooner due to Open Source Development. That being said we're looking at far more than just a simple Feature Request. I haven't personally used Cemu that much (I already own a WiiU, and mostly play the Gamecube version of Wind Waker), so please correct me if any statements are incorrect due to my ignorance. 

*List of MVP requirements for TASing, in a somewhat logical order*

- Input Recording, Ideally through a controller-specific GUI like seen below (This is Dolphin)
![image](https://user-images.githubusercontent.com/25422785/186809332-33d1a33d-e4f4-480d-816a-d2876b860f73.png)
- Frame Advancing
- Input Recording Playback
- Overwriting Playback

*Additional Features that would Benefit Users*
- Savestates
- Official Input File Editors/Splitters
- Movie Exporting ( Recording of the Game using the Input Files, Likely going to have 3 options, /w Gamepad, /wo GamePad, only Gamepad )

My intended Target of this Discussion is going to be on the most basic of inputs, however discussion of handling more complex situations (GamePad Touchscreen, Gyro, Etc) should be discussed at some point.

# Metadata #
What sort of Metadata do we want to supply it with? (Using the [LawsOfTAS](https://tasvideos.org/LawsOfTAS/OnMovieFileFormats) as our base)

#### Emulator version ####
I'd say this should be the Emulator Version the input was recorded on. However Cemu should playback any valid record, simply with a warning about Mismatched Versions. This *will lead to desyncs* however I prefer to warn users rather then prevent them.
#### Movie format version ####
Nothing to add.
#### ROM filename ####
I'd suggest a Deviation by Splitting this into `ROM Filename` and `Region`. 
#### ROM Checksum ####
Potential deviation by using an Optional List here, with the potential format.
| Version | Name | Checksum |
|:---------|:-------|:------------|
| 0.0.1     | Launch | 123412341234 |
| 0.0.2     | Day 1 Patch | 431243121 |

Required Header `Target Version`, this gives a better experience for users since we can display `Invalid Game Version Provided, Input is for 0.0.1 "Launch" not 0.0.2 "Day 1 Patch"`, instead of  `Invalid Game Provided`
#### GUID ####
Slap on a UUID4, not much more to say
#### RTC ####
If someone can find a game with more advanced requirements for RNG sync, please bring them up in the discussion so we can format that into this Header.
#### Emulator Flags ####
Graphic Pak could be put here, for the time being though I strongly recommend simply failing to run if the provided game isn't running Native Graphics.
#### Flags & Settings for determining console used ####
This might be useful for Movie Output? Like `GamePadOnly:True` or `DisplayGamePad:TopLeft` or Games with different Framerates.
#### Rerecord count ####
Nothing to add
#### Frame Count ####
Optional Header to help validate files easier.
#### Input Count ####
Optional Header for Validation/Quick Stats
#### Controllers ####
Optional List of Controllers and their frame information. Example,
| Controller | Initial Frame | Last Frame | Player Slot |
|:---------|:-------|:------------|:--|
| GamePad    | 0 |  // Blank can mean for the entire movie| 0 |
| Wii Mote | 14000 | 1234151 | 1 |

Useful for Syncing, along with fancy Graphs (Ooo, Graphs!), but not required since we have the Controller ID 
#### Author ####
~~Defaults to CrainWWR~~

## Savestate ##
Reserved for Future Development, for now let's just assume all TASes start on System Boot.

## Input Format ##
(Focusing on Gamepad)
- Controller ID ( 3 Bits, 7 Potential Controllers )
- DPad (4 Bits)
- X/Y/A/B (4 Bits)
- Left Stick (1 Bit for Pushed + 16 for Horizontal/Vertical)
- Right Stick (Mirror Left Stick)
- L/ZL/R/ZR (4 Bits)
- +/- (2 Bits)
- Power/TV/Home/Sync (4 Bits)
- Amiibos (Reserve 6 Bits, this is not MVP)
- Player Slot (3 bits, 8 Total using 0)

64 Total Bits

## Example ##
```yaml
HEADERS // Yaml~ Format?
CemuVersion:2.0
MovieFormat:1.0
ROMFilename:The Legend of Zelda Wind Waker HD
Region:Europe
Versions:
      0.0.1: 123445
      0.0.2: 122343
TargetVersion:0.0.2
GUID:MySickUUID4
RTC:1/1/1987 13:23.00.123 UST 
FrameCount:12342
EmulatorFlags:
      GraphicPak: Disabled
AdditionalSettings:
      Movie:
         DisplayGamePad:TopLeft
         DisplayFrameCount:TopRight
         DisplayReRecordAmount: // Null for false?
     Controllers:
          GamePad:
                 InitialFrame:0
                 PlayerSlot:0
          WiiMote: // YAML wouldn't allow this if we had another WiiMote, so open for suggestions
                 InitialFrame:123454
                 LastFrame:12314111
                 PlayerSlot:1
 ~-~ // You got to have a fancy little section seperator. None of that `NULL` character nonsense. Be Unique, Be Cool
SAVESTATE
UsingSaveState:False
~-~
INPUTS // This should have Whitespace to pad the First Input so the inputs align to 64 bit. I think it already should, but I'm writing this tired.
ab438529AA1211131234123abcb2323aacacabd // 64 Bit Encoded 
```

**Comment by CasualPokePlayer** [comment]
As much as I would like to see TASing here, it's not going to happen for a long while. Before you can even consider adding re-recording support, you would need to have some way to make the core deterministic. Which itself involves effectively single threading everything emulation related, which would require a lot of reworking to the code (while also still having nondeterministic threading available for people who don't like 5fps). And I'm sure there's more things you would need to do there.

Without determinism, you are left with a re-recording that syncs once in a blue moon, and frankly not super useful.

**Comment by Crain-32** [comment]
I fully understand this effort will likely take Several Years to get working, but I have faith it will eventually happen. I don't have the C++ skills to make the changes to the core, but the first steps have to happen eventually, and these are the ones I'm able to do.

**Comment by Exzap** [comment]
I'm closing this because:

- No interest by contributors
- Cemu not being deterministic is a show stopper for this feature request
- There are no plans to make Cemu deterministic due to the complexity and the many downsides (mostly severely reduced performance) and having both a deterministic and non-deterministic mode would further increase complexity
