### ISSUE TITLE
[Linux] Cemu via Flatpak (for auto-updates and easier installation)

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [cemu-project/Cemu#603]
I've installed another emulator called Citra and it is installed via a Flatpak. It updates automatically and can be installed with both the GUI and CLI through Flathub. Could Cemu be packaged as a Flatpak for Linux? I think this would be an improvement.

**Comment by qurious-pixel** [comment]
duplicate https://github.com/cemu-project/Cemu/issues/22
