### ISSUE TITLE
Mac Preview - NSMBU is unplayable. 

### ISSUE THREAD

**Issue by bzuruce** [cemu-project/Cemu#607]
When Launching New Super Mario Bros U, it starts with the title screen, but when you press A on the gamepad or 2 on the Wiimote, Cemu crashes.

**Comment by capitalistspz** [comment]
Have you tried the solutions offered in this page
https://wiki.cemu.info/wiki/New_Super_Mario_Bros._U

**Comment by bzuruce** [comment]
No, thanks
