### ISSUE TITLE
"couldn't save profile" when attempting to save controller settings

### ISSUE THREAD

**Issue by akai-katto** [cemu-project/Cemu#610]
Bug: When attempting to save "input settings", under "profile", the "save" button results in an error of "couldn't save profile". 

![image](https://user-images.githubusercontent.com/28079088/211690871-fc75631b-5155-4f3f-b2b5-eefcccd53647.png)

Version:  Present in experimental 1.27.1 and 1.26.2

What I've attempted:

0) Moving to "Desktop" folder
1) Moving to C:\ drive
2) Moving to a D:\ drive
3) Moving to "Documents" folder
4) Moving to "Photos" folder (lol)
5) Running as administrator
6) Disabling anti-virus
6) Right clicking, properties, security, allowing all user groups "full control"

Games will start, but I can't control anything without a controller input settings setup.

**Comment by Exzap** [comment]
Please use the Discord or Subreddit for troubleshooting. Also give Cemu 2.0 a try, maybe it fixes your problem <https://github.com/cemu-project/Cemu/releases>

**Comment by akai-katto** [comment]
Present in CEMU 2 ): thanks for the help though.

**Comment by Squall-Leonhart** [comment]
This isn't a bug, you're trying to save a profile that

* Has no Emulated controller set
* Has no physical controller set

**Comment by akai-katto** [comment]
> This isn't a bug, you're trying to save a profile that
> 
>     * Has no Emulated controller set
> 
>     * Has no physical controller set
> 
> 
> The profile is just a quick way to switch between controls, it isn't required for the binding to be retained.

Ah, all I had to do was move "emulated controller" to "wii-u gamepad" (i have an xbox controller set, but a tutorial i was following skipped this step).

Thanks.
