### ISSUE TITLE
Native arm64 support

### ISSUE THREAD

**Issue by AMDBartek** [cemu-project/Cemu#611]
As arm64 devices are growing in popularity, it would be good to have native support for them. This could also open up the possibility for Android ports in the future.

Obviously this is a big ask and it would be best to leave this for the future.

**Comment by Exzap** [comment]
It's on the [roadmap](https://wiki.cemu.info/wiki/Roadmap) already. No reason to track it twice.

**Comment by AMDBartek** [comment]
My bad, apologies.

**Comment by Acercandr0** [comment]
Any news on this?

**Comment by salvalie** [comment]
Sorry to insist with the inquiry  @Exzap , but there are commits around arm64 and I wonder if the project compiles to arm64 linux with dynarec or its just for macOS for now. There are cemu forks that do work, but I would like to try out the official cemu instead.

**Comment by Exzap** [comment]
The aarch64 recompiler is available on Linux. Building for ARM linux is not very well tested but it should work.

**Comment by salvalie** [comment]
Thanks to respond @Exzap . Could I open a new issue to track down the compilation fails I encounter today?

**Comment by steinpdh** [comment]
It definitely works on macOS. Got a perfectly working app bundle with `cmake -S . -B build -DCMAKE_BUILD_TYPE=release -DCMAKE_OSX_ARCHITECTURES=arm64 -DMACOS_BUNDLE=ON -G Ninja`. Performance is stellar on M1 Max 64GB!

**Comment by sberghici** [comment]
Tested on SBC Radxa Dragon q6a and it works fine(most of the games run)

**Comment by Tiganjos** [comment]
Hi there tell me is arm64 recompiler been worked on for cemu android or not coming anytime soon because ssimco cemu dev disappear for 5 months and nobody knows is this recompiler going to be added because it is needed for better performance please need an answer?

**Comment by jirkadev** [comment]
You can get `cemu-bin-macos-arm64` from cemu CI https://cemu.info/ActionBuilds.php
