### ISSUE TITLE
Build failure with boost v1.81.0

### ISSUE THREAD

**Issue by Shamus397** [cemu-project/Cemu#615]
The relevant bit of the log:

`/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ccj3vNgN.ltrans70.ltrans.o: in function 'ActiveSettings::LoadOnce(std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&)':
`
`/home/shamus/source/cemu/build/vcpkg_installed/x64-linux/include/boost/filesystem/path.hpp:1365: undefined reference to 'boost::filesystem::path_traits::convert(char const*, char const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
`
`collect2: error: ld returned 1 exit status
`
`ninja: build stopped: subcommand failed.
`

It builds just fine with boost v1.80.0.  This is against commit 1cf72265cd31a15a8c6afce140463dac9917b9fb

**Comment by Squall-Leonhart** [comment]
try adding "add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)" to CMakeLists.tx

**Comment by Shamus397** [comment]
After adding that line to CMakeLists.txt, and doing rm -rf build && cmake -S . -B build -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -G Ninja && cmake --build build:

`/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ccDPWrat.ltrans70.ltrans.o: in function 'ActiveSettings::LoadOnce(std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&)':`
`/home/shamus/source/cemu/build/vcpkg_installed/x64-linux/include/boost/filesystem/path.hpp:1365: undefined reference to 'boost::filesystem::path_traits::convert(char const*, char const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, __mbstate_t> const&)'`
`collect2: error: ld returned 1 exit status`
`ninja: build stopped: subcommand failed.`

Same problem.  Now boost looks a lot like voodoo to me (just look at that function signature), but it seems that they changed something in their ABI between 1.80.0 and 1.81.0 so that ActiveSettings::LoadOnce() doesn't work anymore.  If I knew more about boost I could suggest a fix, but it's not in my wheelhouse.  :-P

**Comment by Shamus397** [comment]
OK, I've figured it out.  For whatever reason the build system was pulling in a reference against the vcproj version of boost (which is v1.79.0) even though the final link was linking against the system's boost (v1.81.0).  The clue is right up there in the previous comment: `".../build/vcpkg_installed/x64-linux/include/boost/filesystem/path.hpp:1365: undefined reference..."`

So the fix is simple: remove all references to boost in vcpkg.json and it builds and links just fine against the system boost.
