### ISSUE TITLE
[Linux] Cannot set locale to language "English" warning (version 2.0-25)

### ISSUE THREAD

**Issue by spacebanana420** [cemu-project/Cemu#616]
I am using Cemu experimental version [2.0-25](https://github.com/cemu-project/Cemu/commit/33bd10b4e0b9c27881fa7d6bf38908791f84d3b2). Whenever I open the appimage build of Cemu, a warning box pops up saying "Cannot set locale to language 'English'".

 This error happens on the appimage build but does not happen on the unpackaged binary ("Ubuntu" archive). In neither builds there is an actual problem with the UI language.

There are no specific steps to reproduce this bug other than to launch the appimage build of version 2.0-25

I am using Debian (testing/bookworm) with kernel version 6.0.12 and KDE Plasma under x11, with the european portuguese and american english locales installed on my system. I can provide more system information if needed but for this kind of issue it doesn't seem necessary.

**Comment by qurious-pixel** [comment]
edit the file /etc/locale.gen, find the line of # en_US.UTF-8 UTF-8 , remove #  part
re-run locale-gen to regenerate locales.

**Comment by spacebanana420** [comment]
Thank you, I will try this out

**Comment by tommyMX** [comment]
@qurious-pixel 
where can I find this file in the Mac version?

**Comment by qurious-pixel** [comment]
@tommyMX 
`export LANG=C.UTF-8`

```
export LANG=C.UTF-8
open Cemu.app
```

**Comment by tommyMX** [comment]
> @tommyMX `export LANG=C.UTF-8`
> 
> ```
> export LANG=C.UTF-8
> open Cemu.app
> ```

Where must I put this in?

**Comment by tommyMX** [comment]
> @tommyMX `export LANG=C.UTF-8`
> 
> ```
> export LANG=C.UTF-8
> open Cemu.app
> ```

@qurious-pixel 

but where must I put this in ? Which file ?

**Comment by qurious-pixel** [comment]
@tommyMX go to Discord for troubleshooting. 

https://discord.gg/5psYsup
