### ISSUE TITLE
Paper Mario Colour Splash Crashes On Latest NVidia Drivers

### ISSUE THREAD

**Issue by Sian-Lee-SA** [cemu-project/Cemu#618]
Every time in the game using the paint hammer, the game would crash using Vulkan. This only started to occur since the latest NVidia driver updates from late last year. I have now changed to openGL which seems to be working ok but not ideal. When downgrading graphics drivers then game works fine but again, not ideal.

**Comment by Squall-Leonhart** [comment]
Tell nvidia.

**Comment by Sian-Lee-SA** [comment]
Nah, They're more ignorant

**Comment by All-The-Foxes** [comment]
I just started having this issue too. Thankfully I already completed the game just before this became an issue. I just went back to see if I could find all of the cutouts, which I hadn't done yet, and now I have this issue.

**Comment by Exzap** [comment]
I can no longer replicate this on the latest Nvidia driver, so I assume it's fixed.

**Comment by Squall-Leonhart** [comment]
> I can no longer replicate this on the latest Nvidia driver, so I assume it's fixed.

Yeah, I told them xD
