### ISSUE TITLE
Unhandled unknown exception; terminating the application.

### ISSUE THREAD

**Issue by DexyStorm** [cemu-project/Cemu#619]
IDK what im doing wrong but when i try to run it, it get
Unhandled unknown exception; terminating the application.
i installed it with yay.
i already posted a comment in the AUR and the maintainer told me to open an issue on github
Kernel: 6.1.6-arch1-1
GPU: NVIDIA GeForce RTX 2070 SUPER
X11

**Comment by Squall-Leonhart** [comment]
2 Thinkgs ab out this issue

**THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:**
https://discord.com/invite/5psYsup/

and

**When submitting an issue, please check the following:**

**- You have read the above.
- You have provided the version (commit hash) of Cemu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).**

**Comment by DexyStorm** [comment]
sorry for the unneccessary issue. i didnt see that there was an appimage. i am now using the appimage and everything is working fine for now.

**Comment by ColinKinloch** [comment]
This was the first search result when trying to fix https://github.com/flathub/info.cemu.Cemu/issues/3 . The relevant issue is #173
