### ISSUE TITLE
Cemu Stuck on Gamepad Screen

### ISSUE THREAD

**Issue by MayorBryce** [cemu-project/Cemu#623]
I’m currently on the latest experimental version of Cemu. From what I can tell, all games are stuck on the Gamepad screen. The only way to circumvent this is to put a weight on the Tab key to force to to display the TV screen.

Later today I will add screenshots.

**Comment by Squall-Leonhart** [comment]
Invalid bug, the template you deleted must be used.

Sounds like a issue unique to this machine though.

**Comment by MayorBryce** [comment]
Weird, I didn’t see the template. My bad I guess.

Sorry about that!
