### ISSUE TITLE
Super mario 64 ds not working

### ISSUE THREAD

**Issue by Iplaygames234** [cemu-project/Cemu#624]

**Comment by Iplaygames234** [comment]
Im using the experimental version of cemu and when i open sm64ds both screens dont really work.

**Comment by Squall-Leonhart** [comment]
https://wiki.cemu.info/wiki/Super_Mario_64_DS

bug not needed.

**Comment by Iplaygames234** [comment]
oh i didnt know that

**Comment by Iplaygames234** [comment]
thank you for telling me

**Comment by spudpiggy** [comment]
@Iplaygames234 U should mark this issue as closed. Click the close issue button.
