### ISSUE TITLE
Cemu Stuck on Gamepad Screen

### ISSUE THREAD

**Issue by MayorBryce** [cemu-project/Cemu#625]
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

-->
Version: Cemu 2.0-25 (Experimental)

Cemu is stuck on the Gamepad screen. It will not display the TV screen without pressing Tab. This is mainly a problem in Splatoon, since it naturally does not have Off-TV support.

Ryzen 7 5800h
16GB Ram
Nvidia Geforce RTX 3070 Laptop

Attached are the Log.txt and a video of the problem taking place.

https://user-images.githubusercontent.com/95039266/213929934-63400d3e-7611-46a3-8d79-a9490287b64d.mp4
[log.txt](https://github.com/cemu-project/Cemu/files/10474985/log.txt)

**Comment by Exzap** [comment]
Are you accidentally hitting Ctrl + Tab somehow? It will toggle the default display between TV and GamePad.

**Comment by MayorBryce** [comment]
That fixed it! Thanks.
