### ISSUE TITLE
NSBMU mods quit Cemu

### ISSUE THREAD

**Issue by tommyMX** [cemu-project/Cemu#629]
Hi,

i am using the new Cemu Mac version.
And every time when I install a nsbmu mod, the Cemu quits instantly :-(

Any idea?

thx

**Comment by Squall-Leonhart** [comment]
Github is not for support / assistance involving mods, your question is suited for the relevant discord channel.

**Comment by tommyMX** [comment]
Thanks for nothing !

**Comment by tommyMX** [comment]
but on Cemu windows its running, maybe a problem with your Cemu Mac version, but goodbye
