### ISSUE TITLE
The Legend of Zelda: Breath of the Wild can't work on Mac

### ISSUE THREAD

**Issue by yourlin** [cemu-project/Cemu#637]
- System: macOS Monterey 12.6.1(21G217)
- System: MacBook Pro (16-inch, 2019)
- Processor: 2.6 GHz Six Core Intel Core i7
- Memory: 16 GB 2667 MHz DDR4
- GPU:
  - AMD Radeon Pro 5300M 4 GB
  - Intel UHD Graphics 630 1536 MB

Cemu Version 2.0-26

Error message shows

```
Unable to mount title.
Make sure the configured game paths are still valid and refresh the game list.

File which failed to load:
/Users/linyesh/Documents/wiiu/THE LEGEND OF ZELDA_Breath Of The Wild JPN [00050000101C9300]/code/U-King.rpx
```

Bug the game file works fine on Windows Cemu 1.26.2

**Comment by Squall-Leonhart** [comment]
move the LOZ folder to a shallower path.

**Comment by spudpiggy** [comment]
Rename the BOTW folder to something shorter. Also why are you using the JP version?

**Comment by yourlin** [comment]
> Rename the BOTW folder to something shorter. Also why are you using the JP version?

The version is he only one I can found.

**Comment by sphericmind** [comment]
hey did you figure it out? i changed the name for a shorter one, still no results

**Comment by yourlin** [comment]
>  hey did you figure it out? i changed the name for a shorter one, still no results

Me too. It dosen't help.
<img width="954" alt="Jietu20230209-232952" src="https://user-images.githubusercontent.com/6930286/217857509-877f4eb1-a86f-41fa-8358-7f940b3f1638.png">

Only 2 games are recognized automatically. The others even can't be loaded by manaul.

**Comment by sphericmind** [comment]
> > hey did you figure it out? i changed the name for a shorter one, still no results
> 
> Me too. It dosen't help. <img alt="Jietu20230209-232952" width="954" src="https://user-images.githubusercontent.com/6930286/217857509-877f4eb1-a86f-41fa-8358-7f940b3f1638.png">
> 
> Only 2 games are recognized automatically. The others even can't be loaded by manaul.

i did, try this [rom](https://pastebin.com/UgreTnnT). with this one the game appears on the menu and can be played. the name's length has nothing to do with it

**Comment by Squall-Leonhart** [comment]
This Github has the same rules as the Discord and the Official Reddit.

> Rule 2:
> Absolutely no piracy! Alluding to or asking for (help with) pirated games or keys is strictly forbidden.

This also goes for supplying pastebins on how to obtain an illegitimate copy that may or may not work.
