### ISSUE TITLE
Cemu crashes when reordering Title Manager by Format

### ISSUE THREAD

**Issue by JaimieVandenbergh** [cemu-project/Cemu#648]
Cemu 2.0-26 (and -19), macOS Ventura.

When in Title Manager, clicking the column headers reorders the rows in the expected way. Except the Format column, which does nothing on first click and crashes Cemu on the second. Or occasionally the third.

(All other columns in Title and Download Managers work fine)

No log.txt, but starting via the command line gets:

```
% /Applications/Cemu-2.0-26.app/Contents/MacOS/Cemu 
Segmentation fault: 11!
Error: signal 11:
0   Cemu                                0x0000000101a8811d _Z20handlerDumpingSignali + 93
1   libsystem_platform.dylib            0x00007ff81356fc1d _sigtramp + 29
2   ???                                 0x0000000000000000 0x0 + 0
3   ???                                 0x0000004e00000000 0x0 + 335007449088

```

**Comment by jn64** [comment]
Can repro on Linux, latest git f3ff919. Second click on the format column crashes.
