### ISSUE TITLE
Star Fox Zero: controller not working (hangs on initial save creation)

### ISSUE THREAD

**Issue by minimeee** [cemu-project/Cemu#650]
When launching Star Fox Zero without an existing save, it hangs on the initial save game creation. However, I'm not sure if it actually fails to create the save or if the problem is that I can't press "OK". I assume the latter, because if using an existing save, the intro starts but the game **doesn't recognize any button presses**. I'm using the same controller as with Super Smash Bros and it works there (I've selected the same controller in both game profiles). It's an 8bitdo Pro 2 in x-input mode (configured as SDL controller).

One thing I noticed, that may be related: each time I restart `cemu`, the input settings are empty and I have to reload the profile for the first controller. But even if I don't, Smash Bros works fine while Star Fox Zero does not.

[log.txt](https://github.com/cemu-project/Cemu/files/10610543/log.txt)

**Comment by Exzap** [comment]
The emulated controller is set to "Wii U GamePad"? It won't accept anything else.

**Comment by minimeee** [comment]
Wow, that was a fast response! And you're right. I changed the controller type from "Pro Controller" to "Wii U  Gamepad" and now it recognizes button presses. Thanks a lot!

However, it seems that the gyro in the controller is not recognized. Not sure if that's a `cemu` issue or a linux driver issue (or maybe an input mode issue). Guess I'll have to solve that too before I can actually start playing...

**Comment by minimeee** [comment]
Update: I've connected the controller in Switch mode (over BT) and now gyro is recognized and working! No need for additional drivers or tinkering (Ubuntu 22.04). Very nice!
