### ISSUE TITLE
Cemu is not compatible with S/X

### ISSUE THREAD

**Issue by jguillermo222** [cemu-project/Cemu#654]
I think to improve emulation the program should be x/s compatible like ps2, ps1, and psp emulator. 
At the moment the WII/GC emulator works like 30% efficient (emulators are not efficient in S/X). 
The console are more powerfull and bugs can be reached easily.

**Comment by Squall-Leonhart** [comment]
You make it compatible with X/S then.

**Comment by Fancy2209** [comment]
You port CEMU to UWP like Duckstation/PCSX2/Xenia/Dolphin than.
UWP is pain from what I have heard.

**Comment by JaimieVandenbergh** [comment]
Note that you’ll need to implement an entire DirectX graphics engine for Cemu, amongst other things.

**Comment by Exzap** [comment]
Setting aside the many technical hurdles, you don't really need to ask for ports. If there is someone amongst the contributors that wants to port it then it can happen, but otherwise not. It's just too big of a task for someone to just casually do it without any intrinsic motivation.

**Comment by cobalt2727** [comment]
It's also worth mentioning that in the case of Dolphin specifically, the community actually offered to _pay_ whichever dev ended up making it happen: https://app.bountysource.com/issues/113011679-bounty-port-dolphin-to-the-universal-windows-platform

SirMangler got $1,330 USD for his work.

**Comment by tashaxing** [comment]
It's been so many years, still no cemu-uwp project come out, what a pity !

**Comment by Squall-Leonhart** [comment]
![image](https://github.com/user-attachments/assets/99f48bcc-77e9-4b1c-b6a4-de52d579963c)

one is not coming.
