### ISSUE TITLE
Cemu on Mac OS crashes on loading screen any game

### ISSUE THREAD

**Issue by Lluc82** [cemu-project/Cemu#655]
Cemu crashes on Mac OS Ventura 13.2 iMac 14,2 (late 2013) NVIDIA 750M.
Crashes on any game (downloaded by WiiU Helper) on loading screen, getting this on console.

----------------

[mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: The value of vkCreateImageView(VkImageViewCreateInfo::components) (VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_ONE), when applied to a VkImageView, requires full component swizzling to be enabled both at the time when the VkImageView is created and at the time any pipeline that uses that VkImageView is compiled. Full component swizzling can be enabled via the MVKConfiguration::fullImageViewSwizzle config parameter or MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE environment variable.
libc++abi: terminating with uncaught exception of type std::runtime_error: failed to create texture image view!
Abort trap: 6!
Error: signal 6:
0   Cemu                                0x000000010a70e11d _Z20handlerDumpingSignali + 93
1   libsystem_platform.dylib            0x00007ff80ca56c1d _sigtramp + 29
2   ???                                 0x0000600000000400 0x0 + 105553116267520
3   libsystem_c.dylib                   0x00007ff80c975ca5 abort + 123
4   libc++abi.dylib                     0x00007ff80c9e6082 abort_message + 241
5   libc++abi.dylib                     0x00007ff80c9d7225 _ZL28demangling_terminate_handlerv + 242
6   libobjc.A.dylib                     0x00007ff80c6d402b _ZL15_objc_terminatev + 104
7   libc++abi.dylib                     0x00007ff80c9e54a5 _ZSt11__terminatePFvvE + 8
8   libc++abi.dylib                     0x00007ff80c9e7d05 __cxa_get_exception_ptr + 0
9   libc++abi.dylib                     0x00007ff80c9e7ccc _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
10  Cemu                                0x000000010a41effd _ZN18LatteTextureViewVk14GetSamplerViewEj + 3117
11  Cemu                                0x000000010a440e70 _ZN14VulkanRenderer29draw_getOrCreateDescriptorSetEP12PipelineInfoP21LatteDecompilerShader + 2912
12  Cemu                                0x000000010a443490 _ZN14VulkanRenderer12draw_executeEjjjjjN5Latte24LATTE_VGT_DMA_INDEX_TYPE12E_INDEX_TYPEEb + 1840
13  Cemu                                0x000000010a37e3ea _Z28LatteCP_processCommandBufferPhiR15DrawPassContext + 618
14  Cemu                                0x000000010a3837dd _Z25LatteCP_ProcessRingbufferv + 3021
15  Cemu                                0x000000010a3b57ba _Z17Latte_ThreadEntryv + 1130
16  Cemu                                0x000000010a31f6fc _ZNSt3__114__thread_proxyB6v15007INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEPFivEEEEEEPvSA_ + 44
17  libsystem_pthread.dylib             0x00007ff80ca2c259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff80ca27c7b thread_start + 15

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by Exzap** [comment]
Please get your games legally
