### ISSUE TITLE
Graphical interface elements are missing

### ISSUE THREAD

**Issue by feliciaifu** [cemu-project/Cemu#659]
this is Windows:
![捕获](https://user-images.githubusercontent.com/93038930/218318476-63f47f11-15e9-4aba-8f9c-3b2761590852.PNG)
this is Archlinux:
![2023-02-12_22-56](https://user-images.githubusercontent.com/93038930/218318575-de411ae5-60f8-4c56-a51a-721bbb0441aa.png)
You can see that the check box disappears. This causes the graphicPacks settings to not be changed
Hardware: Archlinux
Cemu: aur latest
Game: all game

**Comment by JoseZancanaro** [comment]
Same problem here in Manjaro XFCE. 

Checkboxes in graphics packs are missing.

![cemu-checkboxs](https://user-images.githubusercontent.com/48338648/218344658-cb671a60-f6ff-496f-973c-513bc881a4a5.png)

**Comment by JoseZancanaro** [comment]
@feliciaifu, my friend @vinigmartins and i figured out how to revert to the expected state. We analyzed the packages that were updated today by the package manager (in our case pacman), and we noticed two that could change the graphics packs checkboxes. The packages are:

- wxwidgets-common-3.2.2-1
- wxwidgets-gtk3-3.2.2-1

Therefore, we reverted these two packages to a previous version. To do this, you need to run the following commands in the console:

`sudo pacman -U file:///var/cache/pacman/pkg/wxwidgets-common-3.2.1-2-x86_64.pkg.tar.zst`
`sudo pacman -U file:///var/cache/pacman/pkg/wxwidgets-gtk3-3.2.1-2-x86_64.pkg.tar.zst`

Here is the result:
![cemu-checkboxs](https://user-images.githubusercontent.com/48338648/218346689-8ffa60ef-64b4-4fd5-88b8-f86fe69b1d31.png)

**Comment by feliciaifu** [comment]
@JoseZancanaro Problem solved, thank you🥰

**Comment by jn64** [comment]
Please report this to your package maintainers by commenting on the AUR package. There are multiple Cemu packages on AUR so I don't know which one either of you are referring to.

**Comment by JoseZancanaro** [comment]
Sorry for not specifying but the Cemu version here was: https://aur.archlinux.org/packages/cemu

And as requested, I left a comment there explaining about this problem.

**Comment by JoseZancanaro** [comment]
Apparently the problem has been resolved: https://github.com/wxWidgets/wxWidgets/issues/23255
