### ISSUE TITLE
Input Profiles not working

### ISSUE THREAD

**Issue by masterofobzene** [cemu-project/Cemu#660]
https://user-images.githubusercontent.com/94469116/218319091-97fd65bd-9bf3-4cad-8a85-ffc169fd8f5d.mp4

It puts the same input mapping for all profiles.
It crashes when loading a profile.

**Comment by lisa-wolfgang** [comment]
What version of Cemu are you using? (Help > About Cemu)

**Comment by Exzap** [comment]
Can you retest with the latest version (2.0-27) from https://github.com/cemu-project/Cemu/releases
