### ISSUE TITLE
[Linux] AppImage didn't run on Steam Deck

### ISSUE THREAD

**Issue by Nvizzy** [cemu-project/Cemu#662]
`(1)(deck@steamdeck CEMU)$ ./Cemu-2.0-26-x86_64.AppImage`
`Gtk-Message: 22:00:34.969: Failed to load module "canberra-gtk-module"`

I've tried `export LC_ALL=C; unset LANGUAGE`just like https://github.com/cemu-project/Cemu/issues/467 and it doesn't work.
I tried several 2.0-x versions AppImage and encountered the same situation

**Comment by Squall-Leonhart** [comment]
Use the Linux channel of the discord for help.

**Comment by Nvizzy** [comment]
This problem no longer occurs after reinstalling Steamos.
