### ISSUE TITLE
Terrible input ghosting + input lag in NES REMIX

### ISSUE THREAD

**Issue by masterofobzene** [cemu-project/Cemu#665]
On NES REMIX, playing original mario, its impossible to make normal jumps. There is some ghosting happening on the gamepad, cannot press more than 3 buttons at the same because the last button will not get recognized (1 to move mario, 2nd to run, 3rd to jump)

Using xbox one controller + SDL. 
cemu 2.0-27

(controller is new and works with other games)

EDIT: the lag part is input lag not normal lag, sorry.

**Comment by legend800** [comment]
make sure you're using multi-core mode for full speed. Input as always worked fine in this game for years unless this is a recent regression

**Comment by Exzap** [comment]
Closing because this issue is stale and nobody else reported the same problem.
If the problem still occurs then please open another issue but try to provide more detail. E.g. testing with other games, trying different controllers/keyboard, etc.
