### ISSUE TITLE
Clicking main window hides shader progress dialog

### ISSUE THREAD

**Issue by epreston** [cemu-project/Cemu#666]
Version: 2.0-27
Shader Model: Vulkan
Title: Breath of the Wild

This issue is minor but it confused me enough to think there was a crash.

Updating to the latest experimental release, shaders began to recompile from cache as expected.  Clicking on the main window (title bar in Windows) hides that shader loading progress dialog, giving the impression that something is frozen or not working.

It is, in fact, compiling / loading the shaders.

This may be an edge case.  After more than 100 hours play testing, the vulkan cache is sizable.  I clicked on the title bar to adjust the window, then, became confused when the progress bar disappeared mid operation.   I thought it was a crash but it was running.  

Is it possible to keep the progress bar until it has completed ?

steps to reproduce:

- build up a sizeable shader cache to have enough time to interact with the window
- first time or subsequent runs don't matter, either is fine
- while the vulkan cache is loading, click on the menu or title bar
- the progress bar disappears mid-operation but the shaders continue to load correctly

**Comment by jn64** [comment]
Can repro differently on Linux (X11, Xfce/xfwm). Clicking titlebar doesn't cause it, but clicking inside the game window does.

This was introduced in cbb79fd. Doesn't happen with f3ff919.

**Comment by epreston** [comment]
Thank you.
