### ISSUE TITLE
Error Code 102-2932

### ISSUE THREAD

**Issue by erikiorai** [cemu-project/Cemu#668]
Hi im having issues with online play (pretendo) specificity Error Code 102-2932 on every game and Error Code 102-0000 on friends list
My system specs:
CPU: AMD Ryzen 7 4700U with Radeon Graphics 2.00Ghz
RAM: 16GB
SSD: SAMSUNG MZALQ512HALU-000L
[logfc.txt](https://github.com/cemu-project/Cemu/files/10777720/logfc.txt)
2 512GB
OS: Windows 11 home 22H2 10.0.22621.1265
Cemu 2.0-27

also i put my log files of games i tried here
[logmk8.txt](https://github.com/cemu-project/Cemu/files/10777721/logmk8.txt)
[logwsc.txt](https://github.com/cemu-project/Cemu/files/10777722/logwsc.txt)
[logsmkr.txt](https://github.com/cemu-project/Cemu/files/10777723/logsmkr.txt)

**Comment by Exzap** [comment]
Please use the Pretendo Discord for troubleshooting requests related to Pretendo.
