### ISSUE TITLE
Fails to build on Arch Linux

### ISSUE THREAD

**Issue by wantija** [cemu-project/Cemu#681]
Trying to build cemu from source with the latest commit fails,using a fully up-to-date Arch Linux below is logs of relevance:

>[ 96%] Building CXX object src/gui/CMakeFiles/CemuGui.dir/windows/PPCThreadsViewer/DebugPPCThreadsWindow.cpp.o
[ 96%] Building CXX object src/gui/CMakeFiles/CemuGui.dir/windows/TextureRelationViewer/TextureRelationWindow.cpp.o
[ 96%] Building CXX object src/gui/CMakeFiles/CemuGui.dir/wxcomponents/checkedlistctrl.cpp.o
[ 97%] Building CXX object src/gui/CMakeFiles/CemuGui.dir/wxcomponents/checktree.cpp.o
/home/anon/data/gitfiles/cemu-git/src/cemu/src/gui/windows/PPCThreadsViewer/DebugPPCThreadsWindow.cpp: In member function ‘void DebugPPCThreadsWindow::RefreshThreadList()’:
/home/anon/data/gitfiles/cemu-git/src/cemu/src/gui/windows/PPCThreadsViewer/DebugPPCThreadsWindow.cpp:257:42: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  257 |                         sprintf(tempStr, "");
      |                                          ^~
/home/anon/data/gitfiles/cemu-git/src/cemu/src/gui/windows/TextureRelationViewer/TextureRelationWindow.cpp: In member function ‘void TextureRelationViewerWindow::_setTextureRelationListItemTexture(wxListCtrl*, sint32, LatteTextureInformation*)’:
/home/anon/data/gitfiles/cemu-git/src/cemu/src/gui/windows/TextureRelationViewer/TextureRelationWindow.cpp:231:28: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘Latte::E_HWTILEMODE’ [-Wformat=]
  231 |         sprintf(tempStr, "%d", texInfo->tileMode);
      |                           ~^   ~~~~~~~~~~~~~~~~~
      |                            |            |
      |                            int          Latte::E_HWTILEMODE
/home/anon/data/gitfiles/cemu-git/src/cemu/src/gui/windows/TextureRelationViewer/TextureRelationWindow.cpp:235:26: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  235 |         sprintf(tempStr, "");
      |                          ^~
/home/anon/data/gitfiles/cemu-git/src/cemu/src/gui/windows/TextureRelationViewer/TextureRelationWindow.cpp: In member function ‘void TextureRelationViewerWindow::_setTextureRelationListItemView(wxListCtrl*, sint32, LatteTextureInformation*, LatteTextureViewInformation*)’:
/home/anon/data/gitfiles/cemu-git/src/cemu/src/gui/windows/TextureRelationViewer/TextureRelationWindow.cpp:282:26: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  282 |         sprintf(tempStr, "");
      |                          ^~
/home/anon/data/gitfiles/cemu-git/src/cemu/src/gui/MainWindow.cpp: In constructor ‘MainWindow::MainWindow()’:
/home/anon/data/gitfiles/cemu-git/src/cemu/src/gui/MainWindow.cpp:352:57: error: ‘config’ was not declared in this scope; did you mean ‘n_config’?
  352 |                 g_gdbstub = std::make_unique<GDBServer>(config.gdb_port);
      |                                                         ^~~~~~
      |                                                         n_config
make[2]: *** [src/gui/CMakeFiles/CemuGui.dir/build.make:781: src/gui/CMakeFiles/CemuGui.dir/MainWindow.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:391: src/gui/CMakeFiles/CemuGui.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by Exzap** [comment]
Should be fixed by 43c9a4eccdc70d5a0f76d07900a9ef77f697e2ae. Can you pull and retry again?
