### ISSUE TITLE
Controls mapping  not working

### ISSUE THREAD

**Issue by Shituation** [cemu-project/Cemu#683]
version 2.0-27 
windows 10

I'm tired of opening issues about the controls in this software. 
The remapping DOESN'T WORK. 
I'm told to change versions, that is all I'm being told. Changed between experimental to stable to experimental again and the controls on this software ARE BROKEN.

I HOPE SOMEONE MAKES A PROPER EMULATOR FOR THIS CONSOLE SOMETIME.

**Comment by Shituation** [comment]
Read again.

**Comment by Squall-Leonhart** [comment]
You're talking about SDL remapping, which is expected as the SDL Controller DB embedded is expected to automatically assign the appropriate buttons.

Remapping works fine with every other method. As they always have.

**Comment by Shituation** [comment]
Thanks, see? I have to be a complete asshole to get answers. Hate moves the world.
Everybody else just told me change versions AND USE SDL. =)
