### ISSUE TITLE
[Linux] Configuring more controllers proportionally increases input delay

### ISSUE THREAD

**Issue by lisa-wolfgang** [cemu-project/Cemu#684]
When using Cemu for single-player gameplay, input lag is imperceptible.
However, configuring a second controller (as in, having both Controller 1 and Controller 2 configured) results in noticeable, but still manageable, input delay for both players. In my case, both controllers were using DSUController for their input sources.
Configuring a third controller worsens the problem even further, as input delay increases to ~0.25s for each person. In my case, the first two controllers were using DSUController, and the third controller was using SDLController.

It's worth noting that this isn't the case for other applications on the same machine (i.e. it's not a Bluetooth bandwidth issue.) For example, Dolphin can handle two Wiimotes (with Nunchuks) as well as an additional controller connected through SDL, and input lag is as imperceptible as it is with one controller.

Cemu version: 4c697d37558538a8577262e0b74bd18a1bb9f239
Operating system: Ubuntu 22.10

**Comment by Squall-Leonhart** [comment]
dolphin also bypasses most of the bthid via libusb running in multi-pipe mode.

**Comment by lisa-wolfgang** [comment]
Related: on an official Nintendo Switch Pro Controller, trying to use the motion controls from a DSUController source while simultaneously inputting on the other joysticks via an SDLController source (combined into just a single emulated controller) causes the motion control input to be severely interrupted. This is most noticeable in Splatoon and Breath of the Wild (while aiming with a bow.)

**Comment by lisa-wolfgang** [comment]
Marking this as a Linux-only issue because BOTW players on Windows seem to have no issues with motion controls when using Nintendo Switch Pro Controllers.

**Comment by lisa-wolfgang** [comment]
I've been testing myself on Windows and this issue doesn't occur there, so I can confirm this to be a Linux-only issue.

**Comment by lisa-wolfgang** [comment]
This has been resolved in my testing since 6dc73f5.
