### ISSUE TITLE
Playstation 5 (dual sense) gamepad issues

### ISSUE THREAD

**Issue by lordmedo** [cemu-project/Cemu#685]
Cemu 2.0-28
windows 10 x64
SDL controller api 
while using dual sense gamepad with Cemu, vibration is not working in 99.9% of cases. 
Enabling the vibration in the controller window, dual sense vibrates noticeably shorter than the other gamepads . 
Motion sensors are working fine. 
If I simulate Dualshock 4 mode with DualsenseX application, I get the full vibration, but my motion sensors are messed up.

**Comment by Squall-Leonhart** [comment]
Requires SDL 2.024+ and HIDAPI support.

**Comment by lordmedo** [comment]
DualSenseX was the culprit here, even with it's emulation set to off, it disabled the emulation on games and emulators that natively support dual sense.
