### ISSUE TITLE
[Feature Request] Borderless Fullscreen

### ISSUE THREAD

**Issue by Silent-Remux** [cemu-project/Cemu#691]
Please add a true borderless fullscreen mode in addition to the exclusive fullscreen option currently provided.

**Comment by Exzap** [comment]
Cemu is borderless windowed, it has no exclusive fullscreen mode.

**Comment by Squall-Leonhart** [comment]
The nvidia (and i think AMD) driver now has an option to promote vulkan and opengl apps to Flip mode swap chains via the Vulkan/OpenGL present method, by default the Auto method will fall back to the traditional behavior but if you change Cemu(or the global profile) to "Prefer layered over DXGI swapchain" you will get the benefit of instant switching, and compatibility with Auto-HDR if on Windows 11.
