### ISSUE TITLE
Wiimote Sideways support

### ISSUE THREAD

**Issue by coorg** [cemu-project/Cemu#694]
Version 2.0.28

Feature Request: When using a emulated Wiimote  a "sideways" Checkbox in input settings so that  on games that support the Wiimote horizontally -

Dpad settings are accurate
Gyro settings are accurate

- When using an sn30Pro+ the game detects the dpad directions incorrectly, this could be remapped in config,  but also......
- The Gyro rotates on the wrong axis, you need to tilt the controller forward\backward instead of Left\Right.

Fixing both of these things with a single "Sideways" checkbox would be a big improvement.

**Comment by Squall-Leonhart** [comment]
the sn30Pro **isn't** a wiimote, its a motion capable gamepad with no IR, 
so this borders on pointless effort to do.

**Comment by coorg** [comment]
In Pro controller mode they do not have tilt,  and you can  map settings but not gyro. Perhaps Pro controller is a better fit, or a wiimote if you don't want to make an unnecessary layer of possible changes.
