### ISSUE TITLE
[Not Urgent] Inconsistent Settings-Menus in Graphicpacks-Section

### ISSUE THREAD

**Issue by chloecdn** [cemu-project/Cemu#699]
This may seem like a stupid thing, and it isn't something very bad, but i could find this "issue" in a lot of games.

While some settings, like DOF and Anisotropic Filtering have their "high/enabled" setting at the top:
![image](https://user-images.githubusercontent.com/80840951/224823481-14a2dfb7-e645-4080-aa13-979d25149cf8.png)

On the other hand, there are some that have this behavior completely reversed:
![image](https://user-images.githubusercontent.com/80840951/224823458-044a0fd8-d2f6-4aca-8398-2abdfc2549d4.png)

This leads to some very confusing situations, for example it is completely random in the Enhancements-Category:
![image](https://user-images.githubusercontent.com/80840951/224825020-69de722d-25a6-497d-94b0-d3e3a1ec426a.png)

While this isn't something urgent, it'd still be nice if it would be addressed at some point.

**Comment by Crementif** [comment]
Please open this issue on https://github.com/ActualMAndM/cemu_graphic_packs. Good catch though.
