### ISSUE TITLE
Migrate legacy logging to new logging system

### ISSUE THREAD

**Issue by Crementif** [cemu-project/Cemu#703]
### Why
Currently Cemu implements two logging systems, the old one that uses the printf formatting syntax and the new one that uses the much better [fmt library](https://fmt.dev/latest/index.html). The old methods being [these](https://github.com/cemu-project/Cemu/blob/main/src/Cemu/Logging/CemuLogging.h#L120-L122) while the new system is found [here](https://github.com/cemu-project/Cemu/blob/main/src/Cemu/Logging/CemuLogging.h#L78-L106C2).

### How

This basically is just removing all the usages of the `cafeLog_log` logging methods to use `cemuLog_log` instead. The [fmt string formatting syntax](https://hackingcpp.com/cpp/libs/fmt.html#cheat-sheets) these new methods use is pretty different, but it should be straightforward otherwise. There's a lot of it however... hence why it hasn't been done yet! But it's appreciated if someone is willing to help with this. And you are free to do it in parts and create multiple pull requests. Preferred even since it'll be easier to review.

---
If you have any issues with updating some of the more complex logging usages, do let me know and I can help you convert them over. Or if you have any other issues/questions for that matter.

**Comment by why-keith** [comment]
Happy to take a look at this. Any advice on how to test the updated logs? Trying to figure out how to trigger each one might be quite time consuming

**Comment by Crementif** [comment]
Oh, nice to hear.

I don't think there's a great method to reproduce all of them, but I think most of them should be fairly trivial (and I'll also review them so any mistakes I'll probably catch). It's just a lot of busy work. Plus the fmt library does a lot of type checking at compile time.

If you are unsure about a particular line you could place them closer to the initialization point with some fake variables as parameters, just to make sure it's correct. As long as the type matches it should be good.

**Comment by Crementif** [comment]
Btw, while changing them, if you see any "\n" at the end of the strings in one of the old methods, can you also remove them. These currently just add new lines which makes the logging look really messy too.

**Comment by why-keith** [comment]
Presumably any uses of the macros defined [here](https://github.com/cemu-project/Cemu/blob/18a266155f95de398627fbab25851994198fa313/src/Cemu/Logging/CemuLogging.h#L164-L180) need to be replaced as well?

**Comment by Crementif** [comment]
Yeah, those need removing. The forceLogRemoveMe_printf one doesn't have an equivalent though, but I would just leave that one specifically for now or just remove them entirely.

**Comment by why-keith** [comment]
That's useful to know, thanks! I'll probably do a pull request per macro to break it up into more manageable chunks

**Comment by why-keith** [comment]
Added pull request #710

**Comment by why-keith** [comment]
A little bit unsure about converting [this line](https://github.com/cemu-project/Cemu/blob/02ec40b7ba0440538e2e9721d9922c292c9b9e8f/src/Cafe/HW/Latte/Core/LatteShader.cpp#L304). Any ideas?

**Comment by Crementif** [comment]
"Unable to compile shader {:016x}" would be the equivalent to PRIx64.

**Comment by why-keith** [comment]
Added #714. Apologies for the length of this one.

**Comment by why-keith** [comment]
> Thanks for tackling this.
> 
> For printing paths (`fs::path`) please use `_pathToUtf8(path)` instead of `path.generic_string()`. Similarly, for `wxString` there is `std::string wxHelper::MakeUTF8(const wxString& str)` if you ever need it.

Sorted this. Also fixed any issues that I spotted whilst going through stuff. So good to be reviewed again

**Comment by why-keith** [comment]
https://github.com/cemu-project/Cemu/blob/916e9099acf30c70e61b7f6116e86aa887164daa/src/Cafe/OS/libs/snd_user/snd_user.cpp#L597

This line has 5 parameters but only has 4 in the actual text. Any tips on this one?

**Comment by Crementif** [comment]
Oh, looks like a mistake. I would just add the third another {:x} for the third volume.

**Comment by why-keith** [comment]
Added #762

**Comment by why-keith** [comment]
Added #766

**Comment by why-keith** [comment]
https://github.com/cemu-project/Cemu/blob/a640bd079c34f951b2ac59e69406cb6e1caa21a3/src/Cemu/Logging/CemuLogging.h#L174-L175

How should I be handling this? Can't seem to find an equivalent that would only trigger `cemuLog_log(LogType::Force, ...)` during debug

**Comment by why-keith** [comment]
#767, #768 & #769 are ready for review

**Comment by Crementif** [comment]
> https://github.com/cemu-project/Cemu/blob/a640bd079c34f951b2ac59e69406cb6e1caa21a3/src/Cemu/Logging/CemuLogging.h#L174-L175
> 
> How should I be handling this? Can't seem to find an equivalent that would only trigger `cemuLog_log(LogType::Force, ...)` during debug

Afaik this is replaced by cemuLog_logDebug.

**Comment by why-keith** [comment]
For a log where the only argument is LR (see example below), how should I be handling this?

https://github.com/cemu-project/Cemu/blob/41f2c27229fd926186cedfb7d194110cb1c388dc/src/Cafe/OS/libs/nn_act/nn_act.cpp#L127

**Comment by Crementif** [comment]
Just change it to "CreateConsoleAccount(...)"

**Comment by why-keith** [comment]
Added #780. Another big one this time

**Comment by why-keith** [comment]
Added #799 & #800.

With that I believe everything's been migrated to the new system.
