### ISSUE TITLE
Constant stutters with AMD Instant Replay enabled

### ISSUE THREAD

**Issue by TotallyNotInUse** [cemu-project/Cemu#704]
Cemu version: 1.26.2
System specs:
```
CPU: AMD Ryzen 3 3300X
GPU: AMD Radeon RX6600 8GB
RAM: 16GB DDR4 (3200mhz)
```

Reproduction steps:
1. Enable Instant Replay in AMD Software: Adrenalin Edition
2. Open Cemu and play any game
3. Constant stuttering
4. Disable Instant Replay
5. Issue fixed

Although there is a fix to this issue, I would like to be able to save or record video while I'm playing and this issue does not happen with other games. I have the latest driver version (23.3.1).

[log.txt](https://github.com/cemu-project/Cemu/files/11011794/log.txt)

**Comment by Squall-Leonhart** [comment]
this is not a cemu issue, instant replay has been causing problems for 6 months now.
