### ISSUE TITLE
Zelda BOTW dark textures since Cemu 2.0-18 

### ISSUE THREAD

**Issue by linuskallman** [cemu-project/Cemu#707]
Hello, 

I would like to highlight that on MacOS silicon M1, Zelda BOTW has extremely dark textures on all experimental releases since 2.0- 18. I have tried to change to all possible texture packs, but the only solution is to go back to the old release. 

It would be wonderful if this could be looked into.

**Comment by Exzap** [comment]
Can you provide screenshots of the problem? "Dark textures" can mean a lot of things.

**Comment by linuskallman** [comment]
Of course. 

The first image is with version 2.0-18. Everything is bright and clear and is at should be. 

<img width="1282" alt="Screenshot 2023-04-08 at 14 07 27" src="https://user-images.githubusercontent.com/32307019/230706520-ce5bb871-6459-4d52-80b6-228ca4b80e4a.png">

In the second image you can see that everything is much darker, even though it is i the middle of the day. You can barely see anything at night. This is exactly the same time of the day in the game. This is version 2.0-32. I should say it is exactly the same issue with every version since 2.0-18. Can it be fixed? I have reinstalled Cemo many time and the only way to solve it is to go back to version 2.0-18. 

<img width="1274" alt="Screenshot 2023-04-08 at 14 13 13" src="https://user-images.githubusercontent.com/32307019/230706586-f5cc7f56-393b-455d-8cd8-667962345323.png">
