### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by DJZSwag** [cemu-project/Cemu#71]
Just wanted to know if there will be any macOS support in the near future.

**Comment by Squall-Leonhart** [comment]
Join the discord for questions, Issue tracker is for detailed feature requests and bug reports.

**Comment by DJZSwag** [comment]
Thanks for the reply. I mainly use GitHub for suggestions and issue reporting so this is uncommon for me.

**Comment by ArtemisX64** [comment]
> Join the discord for questions, Issue tracker is for detailed feature requests and bug reports.

I think MacOS support can be considered as a feature. (Or this can be more like Current Status of MacOS especially since https://github.com/cemu-project/Cemu/pull/52 is merged)
