### ISSUE TITLE
Italian translation breaking in 2.0-31

### ISSUE THREAD

**Issue by inklingboy97** [cemu-project/Cemu#735]
I saw that some translations broke even if there was the proper entry for some languages listed below by @mx00010. 
this includes:
Load... (Carica...)
Install the game, title, update, or DLC... (Installa il gioco, titolo, aggirnamento o DLC...)
Remove shader caches (Rimuovi cache delle shader)
Open Cemu folder (Apri la cartella di cemu)
Timer speed (Velocità del timer)
Launch with GDB stub (lancia con GFB stub)
Accurate barries (Vulkan) (Barriere accurate (Vulkan))
About Cemu (Che cos'è Cemu)
These are only the Italian ones and I'm probably going to update this issue once I find a solution at least for the Italian language.

**Comment by inklingboy97** [comment]
I might try to find some entries because I realized some of them, even if searching, don't appear.

**Comment by mx00010** [comment]
@inklingboy97
This seem true not only for Italian translation, but also for other translations. Randomly tested a couple of them and some entries are not translated at all. 

This issue seem more large than the italian translation, so can I suggest to update the topic of this ticket with a more accurate title.

Germain translation in 2.0-31 :
![Translation ge](https://user-images.githubusercontent.com/128931214/229566642-826817a0-f335-4cc7-9a9b-d7f7f0ebce93.jpg)

Germain translation in 1.27.1 : 
![Translation ge - 1 2 7 1](https://user-images.githubusercontent.com/128931214/229566823-476fb991-323a-4e0e-a2c2-f626c559957a.jpg)

French translation in 2.0-31 :
![Translation FR](https://user-images.githubusercontent.com/128931214/229548059-2ec56806-52fd-4d9a-b5b8-207be2154bda.jpg)

French translation in 1.27.1 : 
![Translation FR - 1 2 7 1](https://user-images.githubusercontent.com/128931214/229548230-4d98bdf8-04e5-423e-9875-af4f33a81d41.jpg)

Italian translation in 2.0-31 : 
![Translation IT](https://user-images.githubusercontent.com/128931214/229565219-bd1bea6e-52e7-4c96-b480-07f11d595c15.jpg)

Italian translation in 1.27.1 : 
![Translation IT - 1 2 7 1](https://user-images.githubusercontent.com/128931214/229565331-afd47e3f-647e-4494-b243-aa6e585f1298.jpg)

**Comment by inklingboy97** [comment]
Oh thank you, I will update it now

**Comment by Fs00** [comment]
That's because some UI strings have been slightly changed since 1.27.1, and therefore translations need to be updated (I can do that for Italian when I have some time).
In some cases translations in Cemu are outdated even though they have been updated in the [Cemu-Language repository](https://github.com/cemu-project/Cemu-Language), because they also need to be manually rebuilt and imported into this repo.
The overall process could definitely be improved in the future (for example by automatically rebuilding translations in a compile-time step).

**Comment by AndreaCicca** [comment]
I found another broke translation in the debug section, "launch with GBD stub" is not translated.
<img width="461" alt="Screenshot 2023-04-05 alle 19 04 37" src="https://user-images.githubusercontent.com/58073848/230152727-11ce1e30-0a19-4896-9697-86184657e0b3.png">

Another thing that I think it's a MacOS specific problem the "Window" menu, in Italian "Finestre" is entirely in English
<img width="445" alt="Screenshot 2023-04-05 alle 19 03 32" src="https://user-images.githubusercontent.com/58073848/230152655-faf59628-2e17-49d9-9e4c-8cff738f5348.png">

**Comment by Fs00** [comment]
A quick update: the Italian translation has been updated, you will see it in the next experimental release.
Regarding the Window menu on macOS @AndreaCicca: that menu is provided by macOS, Cemu has no control on those strings.
I guess you have set the system language to English? AFAIK wxWidgets (the UI library used by Cemu) is not able to change the language of system menu entries on macOS.

**Comment by Fs00** [comment]
@Exzap I think this issue can be closed: the Italian translation is updated in the latest experimental builds.
(On a sidenote, I see that there are several PRs in the Cemu-Language repo that are waiting to be merged)

**Comment by AndreaCicca** [comment]
> A quick update: that menu is provided by macOS, Cemu has no control on those strings. I guess you have set the system language to English? AFAIK wxWidgets (the UI library used by Cemu) is not able to change the language of system menu entries on macOS.

Sorry, I didn't see the reply, everything is set to Italian on my machine. With others app I don't have a similar problem.
<img width="376" alt="Screenshot 2024-03-19 alle 10 16 45" src="https://github.com/cemu-project/Cemu/assets/58073848/0b679b61-24e2-4e05-99b7-ffa04f5f8a1f">
For example this is the same menu on a different app.

<img width="319" alt="Screenshot 2024-03-19 alle 10 17 24" src="https://github.com/cemu-project/Cemu/assets/58073848/2396ad08-757b-4684-9a1f-5c6058ee6787">
On Cemu is still in English.

**Comment by Fs00** [comment]
Hello @AndreaCicca, I have submitted a PR that should fix the language issue with macOS menus.
Can you try [this artifact](https://github.com/cemu-project/Cemu/actions/runs/8409271985/artifacts/1353578967) and see if it fixes the problem?

**Comment by AndreaCicca** [comment]
@Fs00 thanks. I tried the artifact and the situation has been improved but not everything is translated unfortunately.

I upload some examples.

This is from Cemu v2.0-73 (current experimental build)
<img width="319" alt="Screenshot 2024-03-24 alle 15 12 23" src="https://github.com/cemu-project/Cemu/assets/58073848/5302d947-7bd0-4e6d-b767-40f97aa5516d">

This is from the new artifact
<img width="376" alt="Screenshot 2024-03-24 alle 15 08 51" src="https://github.com/cemu-project/Cemu/assets/58073848/011fd476-25c2-49e2-856c-94bcba648b5c">

Not everything is translated by MacOS, for example the first element of the list is still "Minimize", where it should be "Contrai" in Italian (you can see the Whisky's example above). Same thing for "Zoom" and "Bring All to Front".

**Comment by Fs00** [comment]
Thanks for testing. It's good to see that the situation is improved at least, but there must be some other weird shenanigan going on... This is really the most I can do for now, given my limited knowledge on how wxWidgets and macOS handle localization.
I'd recommend tracking this mixed localization bug in a separate issue @AndreaCicca, because it's different than the one the OP initially reported (which has been fixed) and it's worth not losing track of it 🙂

**Comment by AndreaCicca** [comment]
@Fs00 I open #1136
@inklingboy97 I think that this Issue can be closed
