### ISSUE TITLE
[Linux] Can't open .wux a .wud roms

### ISSUE THREAD

**Issue by rosostolato** [cemu-project/Cemu#736]
Cemu native for linux is not opening and not showing games of .wux and .wud extension files, but it loads .wua files. It's just for the native version, if you run the windows version with proton, all files are loaded correctly.

It looks like some decrypting logic issue, maybe I'm missing some package?

**Comment by inklingboy97** [comment]
That's because they are pirated files. You need to dump them from your console with this guide https://cemu.cfw.guide/using-dumpling.html

**Comment by rosostolato** [comment]
Thank you!

**Comment by toast003** [comment]
Can reproduce in cemu 2.0-88 (with files I dumped myself using wudd).

Other games do work just fine
