### ISSUE TITLE
spanish language broken in all 2.0 releases

### ISSUE THREAD

**Issue by rakantoh** [cemu-project/Cemu#742]
the spanish language/translation in cemu 2.0-x is broken, always shows in english, other languages works.

and a feature request, add a option to pause/stop the actual emulation/game to open another game without close cemu

**Comment by jn64** [comment]
> the spanish language/translation in cemu 2.0-x is broken, always shows in english, other languages works.

Duplicate of #506

> and a feature request, add a option to pause/stop the actual emulation/game to open another game without close cemu

Duplicate of #219

Please search before posting.

**Comment by rakantoh** [comment]
ok, i forget that i already open the spanish issue, however please keep in mind fix the issues and add the features requested, thanks for the great work.

**Comment by Exzap** [comment]
Spanish (and other languages) are fixed in Cemu 2.0-39
