### ISSUE TITLE
[Linux] Build failure

### ISSUE THREAD

**Issue by Shoegzer** [cemu-project/Cemu#743]
Linux builds are failing with recent commits, details:

* OS: Linux Mint 21.1 / kernel 5.15
* CPU: Intel i7-10870H
* Commit tested: 27f7b4d550167768e816882a687bf5959a54c1da
* Last good commit: 9049ad9
* Log: [build.log](https://github.com/cemu-project/Cemu/files/11142039/build.log)

Can bisect if necessary, though it is thought to be caused by #719.

As a side-note, the above "bad" build resulted in a very large set of files (over 4GB compressed compared with a little over 1GB compressed from earlier builds).

Note: This is a duplicate of #723 but a request was made to open a new PR.

**Comment by Shoegzer** [comment]
Update: Tested against master after PR #765 was merged but it still fails unfortunately.  This time however, the results in the build log are different, with the following included:
```
CMake Error at dependencies/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package):
  By not providing "Findglm.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glm", but
  CMake did not find one.

  Could not find a package configuration file provided by "glm" with any of
  the following names:

    glmConfig.cmake
    glm-config.cmake

  Add the installation prefix of "glm" to CMAKE_PREFIX_PATH or set "glm_DIR"
  to a directory containing one of the above files.  If "glm" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:114 (find_package)
```
That being the case, I tested with PR #760 merged, which forces system GLM, but it fails in the same manner.

Log: [build.log](https://github.com/cemu-project/Cemu/files/11224996/build.log)

**Comment by Exzap** [comment]
You need to install `libglm-dev`

**Comment by Shoegzer** [comment]
Thanks, glaring omission - I thought I had installed it immediately prior to testing #760 but I mistyped the package so it installed something else.  Although with `libglm-dev` it still fails unfortunately, at the latter stages of linking:
```
[497/497] Linking CXX executable /home/testing/Desktop/cemu/Cemu/bin/Cemu_release
FAILED: /home/testing/Desktop/cemu/Cemu/bin/Cemu_release
```
Log: [build.log](https://github.com/cemu-project/Cemu/files/11225986/build.log)

**Comment by Exzap** [comment]
Can you pull the latest changes and try building again? In theory 41f2c27229fd926186cedfb7d194110cb1c388dc should fix your issue

**Comment by jonbarrow** [comment]
Not OP but I was getting the same errors previously mentioned on Ubuntu 22.04, and yes pulling the latest commits fixed it for me

**Comment by Shoegzer** [comment]
Indeed, and for me too.  Thanks @Exzap, I'll close this now.
