### ISSUE TITLE
Game quits on start with nvidia driver 531.41 on GTX 970 (Vulkan)

### ISSUE THREAD

**Issue by griever-gf** [cemu-project/Cemu#745]
Game quits on start with Nvidia Driver 531.41 on GTX 970 (Vulkan).
I tried several games (BotW, NES Remix, Mario Party)  - with the same result.
Looks like it's independant on version. I tried 1.26.2, 1.27.1 and 2.0.3 - with the same result.
Switching to OpenGL helps. Sudden quit on start happend only when using Vulkan.
Rolling back to driver version 517.48 helped me.
Intel 6600K, Win 10 64-bit.

**Comment by Squall-Leonhart** [comment]
Issue is with your system, join discord for support. 

https://discord.gg/5psYsup
