### ISSUE TITLE
discord rich presence not working on native discord rpm 

### ISSUE THREAD

**Issue by pollux56** [cemu-project/Cemu#750]
discord rich presence only works on flatpak discord when using cemu flatpak, but on the rpm (fedora) discord version it doesnt show up. the appimage of cemu does come up for the rpm discord, is this normal?

**Comment by Exzap** [comment]
Why did you post this here when you already posted it on the correct place? https://github.com/flathub/info.cemu.Cemu/issues/4
We dont need to track it twice
