### ISSUE TITLE
Input not working Batocera v36

### ISSUE THREAD

**Issue by vladimir1909** [cemu-project/Cemu#755]
I have just noticed that cemu input is not working under batocera 36
Noticed cause tried to play Super Mario 3d World, and couldnt fight a way to use the blow
Tried to manually change the input, didnt work
Tried to edit the xml file under file explorer, so I changed the input with text edit. Trough cemu config seemed to have changed, but in game there was no change.
Im using a logitech f710 gamepad btw

sorry for my english, is not my mother language

**Comment by pekumbe** [comment]
Hi everyone!

I am also having problems with input to the "8BitDo Ultimate Wired Controller" on both Linux Mint (5.15.0-71-generic) and Fedora 38 (latest kernel available).
It seems that the trigger button is being confused with the rotation button. As a result, it is not possible for me to control the camera in Zelda Breath of the Wild.
This is occurring with all emulated controls - "Wii U GamePad", "Wii U Pro Controller"...

This 8BitDo has always worked normally in Steam, so it is a specific problem in Cemu. I tested it on version 2.0-29 and version 36.

**Comment by Exzap** [comment]
A lot of changes have been made since this was originally posted and there is a high chance this is resolved. If the problem still occurs, please open a new issue
