### ISSUE TITLE
Unable to connect using pretendo on linux

### ISSUE THREAD

**Issue by Supervisor360** [cemu-project/Cemu#776]
i dumped all my pretendo files and it still wont connect! am i doing something wrong?  i use the account for online and go to battle but it just says you need news data and a n online ccount and then i press recieve and nothing.

**Comment by Supervisor360** [comment]
PS im using the AppImage thing

**Comment by Squall-Leonhart** [comment]
Support requests belong on [Discord](https://discord.com/invite/5psYsup)

**Comment by Exzap** [comment]
For Pretendo problems the best place to get support is the Pretendo discord. We don't really troubleshoot it

**Comment by Supervisor360** [comment]
i dont have discord, what else can i do?
