### ISSUE TITLE
Compiling large cache with OpenGL crashes the emulator 

### ISSUE THREAD

**Issue by BParks21** [cemu-project/Cemu#785]
I'm using experimental build v2.0-35. I noticed that when booting games with large shader caches with OpenGL the emulator crashes while compiling before getting in game. The caches work fine with Vulkan. So I decided to delete the caches and build new caches from scratch. I built a fresh cache deleting all shader related files associated with the games. I also did a fresh install of the latest Nvidia driver with DDU. The games still crash if the cache is large. Games tested were BoTW and Wooley World. The caches have always worked fine in these games up till the past 4 or 5 builds I wanna say. I'm not sure when it started but it was a recent build for sure. 

Specs:
CPU: i7 8086K
GPU: GTX 1080 Ti 11gb
RAM: 32GB DDR4 3000MHz
OS: Windows 11 22H2

**Comment by Squall-Leonhart** [comment]
With nvidia drivers, you need up to 10GB's of commit for just cemu alone to build the cache and boot the emulator, turning off the pagefile on a 16GB system will not mean theres not enough commit charge for all applications running on a typical pc.

**Comment by BParks21** [comment]
Sorry about that I must have deleted the template by mistake somehow, I usually always use the templates when reporting issues on any repo asking to use them. I have 32gb of system memory and I have been using caches of this size just fine with OpenGL up till the past few recent experimental builds that came out. I know if I go back a few I'll find which version it started with. I'll add the rest of my specs in a minute if that is alright. MB.

**Comment by Squall-Leonhart** [comment]
I can trigger this btw, so its not the page file but does appear to involve a buffer being restricted to 32bit somewhere as the crash always occurs at 4.1GB's memory used

**Comment by BParks21** [comment]
Thanks for looking into it.
