### ISSUE TITLE
GPU doesn't appear in the devices list

### ISSUE THREAD

**Issue by tuxrinku** [cemu-project/Cemu#788]
When setting Vulkan api in the general settings menu, cemu runs on my integrated intel GPU. But the devices list is empty so I can't select my Nvidia GPU.

Cemu version : 2.0-36 AppImage
System : Ubuntu 22.04
RAM: 32 gb
CPU: Intel N6005
GPU: Nvidia GTX 1050 Ti

**Comment by latuh** [comment]
Try updating the card drivers, if this doesn't work you could try installing the NVIDIA Vulkan beta driver, you can download it from here: https://developer.nvidia.com/vulkan-driver

**Comment by tuxrinku** [comment]
My drivers are up to date already, and I have no problem having my nvidia GPU displayed on others emulators, even in AppImage.
