### ISSUE TITLE
[Feature Request] Add integrated Feral Interactive GameMode support for Linux

### ISSUE THREAD

**Issue by deadmeu** [cemu-project/Cemu#790]
This is a feature request for an integrated performance toggle to enable the use of [Feral Interactive GameMode](https://github.com/FeralInteractive/gamemode) on Linux devices. Currently, to use gamemode users have to manually launch cemu with `gamemoderun cemu` or edit their desktop entries to have it automatically run. Having an integrated toggle would allow users to more easily enable the feature and would allow gamemode to be disabled when a game isn't currently running.

[Prism Launcher](https://github.com/PrismLauncher/PrismLauncher) is a good example of how I envision the integration to work, with a simple setting to enable/disable the feature. The Cemu Flatpak would need updating (maybe the same way the [Steam Flatpak was updated](https://github.com/flathub/com.valvesoftware.Steam/pull/384) for gamemode support).

On my system gamemode doesn't bring a ton of performance improvement (maybe an extra 1-2 fps) but could help produce smoother frame latency and may have greater effect on lower power devices such as laptops or handhelds (such as the Steam Deck) with its optimisations.

**Comment by Exzap** [comment]
Implemented with #796
