### ISSUE TITLE
pulseaudio support

### ISSUE THREAD

**Issue by paperboii** [cemu-project/Cemu#791]
cemu running on linux natively is a huge release in my opinion, sadly i get no sound over "cubeb" api.
I want to encourage you to implement pulse audio for the linux version of cemu, which otherwise runs and works amazingly well. are there any plans?

**Comment by Exzap** [comment]
cubeb uses Pulseaudio under the hood. If you are compiling Cemu yourself you need to have `libpulse-dev` (or `libpulse` depending on what distro you use) installed

**Comment by paperboii** [comment]
that sounds promising, I'll definitely try that!

when it's that simple, does that mean pulse-audio hasn't been integrated into the recent release, although it's technically really close?

**Comment by Exzap** [comment]
I'm not sure I understand the question? It's implemented via cubeb and if you select cubeb it will/should use pulseaudio.

Are you using the prebuilt releases and if yes, which one (appimage, flatpak, binary)? Which distro are you using?

**Comment by jn64** [comment]
@paperboii Cubeb is not an opposing choice to PulseAudio, it's the glue that connects Cemu to PulseAudio.

Sounds goes from Cemu → Cubeb → PulseAudio.

This way Cemu developers don't have to reinvent the wheel. Cubeb supports many audio backends on different OSes.

Practically all[^1] Cemu users on Linux already use it with PulseAudio.

[^1]: There's like 1 guy trying to use it with JACK.

**Comment by paperboii** [comment]
OK. I didn't quite get that. i thought if i would compile it myself, i would be able to choose pulse instead.

The distro i'm using is Arch KDE (6.2.12) Plasma (5.27.4), I recently heard about the 2.0 and flatpak release and wanted to try it. At first I installed an aur image using yay, everything worked very nice and the way native builds are expect to be. After finishing the setup I put on my headphones and somehow didn't hear any audio. I spent the whole evening on finding a way to get cubeb running, and installed the flatpak release afterwards, to see if there's a difference. Today I've also tried the appimage version, but it won't start at all. 

The compiling process ended up with two remaining cmake errors, usually i let yay do these type of things.

**Comment by jn64** [comment]
> After finishing the setup I put on my headphones and somehow didn't hear any audio.

So this is your issue. Just lead with this in the future, instead of inventing an alternate reality where Cemu doesn't support PulseAudio.

Did you select an audio device for the TV output in Cemu, and set the volume? See https://github.com/cemu-project/Cemu/issues/107#issuecomment-1331260483

>  Today I've also tried the appimage version, but it won't start at all.

See if it's https://github.com/cemu-project/Cemu/issues/779, if not open a separate issue.

**Comment by paperboii** [comment]
@jn64 

> Did you select an audio device for the TV output in Cemu, and set the volume?

After a day of research and compiling, I can imagine a future were this actually solved the issue. 

Answer: Not even once.


How's that possible. It works. [🍻]
