### ISSUE TITLE
[Linux] Image looks darker when using Vulkan on Wayland

### ISSUE THREAD

**Issue by TheFortunattor** [cemu-project/Cemu#792]
## Description

Cemu version appimage: Cemu-2.0-36

Cemu version flatpak: 2.0~experimental36

Nvidia driver version: 530.41.03

On Fedora Silverblue 38 using Nvidia (RTX 3070), when I open a game on Cemu using the Vulkan backend, the image looks significantly darker than it should. The issue happens when running Cemu natively under wayland and using the Vulkan backend on any game, I've tested on BoTW, Super Mario 3D World and Mario Kart 8. The error doesn't appear when using OpenGL or using X11 (with Vulkan). I've tested this using the flatpak version of Cemu that runs natively under wayland in contrast to the appimage that runs on X11 (xWayland). I tried to make the appimage run on wayland by setting "export GDK_BACKEND=wayland" on my ~/.bash_profile but that doesn't work for me, if you could tell me how to make it work, I would really appreciate it. 

I've uploaded both logs from each version.

Below is a screenshot of the issue. Left is Flatpak on wayland and right is Appimage on X11 (xWayland).

![Screenshot_20230420_162715](https://user-images.githubusercontent.com/50719030/233853703-225bec77-e08b-4a1c-92f4-ad180718e362.png)

Logs:

[log(flatpak wayland).txt](https://github.com/cemu-project/Cemu/files/11304321/log.flatpak.wayland.txt)
[log(appimage X11).txt](https://github.com/cemu-project/Cemu/files/11304322/log.appimage.X11.txt)

Please let me know if you need anything else. Thank you for all your work!

**Comment by qurious-pixel** [comment]
`GDK_BACKEND=wayland ./cemu.AppImage`
Or make sure you reload your bash profile. 
`source ~/.bash_profile`

**Comment by TheFortunattor** [comment]
I don't know what to tell you. I've tried that but it doesn't work for whatever reason. 

I wish I had a better way to show it but here you can see I'm running the appimage like you said but X11 tools are still able to give me the info of the window as well as xeyes following the mouse

![Screenshot_20230423_203401](https://user-images.githubusercontent.com/50719030/233872401-b1559ff1-3417-4153-97b9-fdf15b07d22b.png)

**Comment by Squall-Leonhart** [comment]
You are sending full range video to a limited range display.

**Comment by TheFortunattor** [comment]
Ok, I was not aware of that possibility but as far as I can tell, I don't think that's the case. I have a BenQ EX2510 and in the OSD, I have an option that says "RGB OC Range" and I have two options, (0 ~ 255) or (16 ~ 235). The default is (0 ~ 255)  but setting the latter makes things look washed out so I'm pretty certain my monitor supports full range. Plus, I can run two instances of the app at the same time and run into the problem when choosing Vulkcan on wayland instead of OpenGL. Here is a screenshot of that

Left is using OpenGL, right is using Vulkan. Both running as a native wayland window

![Screenshot_20230424_141419](https://user-images.githubusercontent.com/50719030/234134264-34492d54-3aff-49dd-939d-74c0ce4bd71f.png)

**Comment by ColinKinloch** [comment]
Does the GamePad view have the same issue?

**Comment by ColinKinloch** [comment]
Could you check whether this build fixes the issue?
```bash
flatpak install --user https://dl.flathub.org/build-repo/20389/info.cemu.Cemu.flatpakref
flatpak run info.cemu.Cemu//test
```

**Comment by TheFortunattor** [comment]
Unfortunately, it does not. Though thank you for continuing to look for a fix for this. GamePad view is all the same as well. I'll attach a screenshot and the vulkaninfo output file

![Screenshot_20230427_001155](https://user-images.githubusercontent.com/50719030/234752379-c1a7a368-b34e-4662-8315-4288fc66f2c2.png)

[vulkaninfo.txt](https://github.com/cemu-project/Cemu/files/11339304/vulkaninfo.txt)

**Comment by TheFortunattor** [comment]
That was tested on the build you provided as shown in the screenshot

**Comment by ColinKinloch** [comment]
Could you tell me what this build prints to stdout?
```bash
flatpak install --user https://dl.flathub.org/build-repo/20531/info.cemu.Cemu.flatpakref
```

**Comment by TheFortunattor** [comment]
I'm not sure if I follow, sorry. This is the output when I install that flatpak:

"flatpak install --user https://dl.flathub.org/build-repo/20531/info.cemu.Cemu.flatpakref
The application info.cemu.Cemu depends on runtimes from:
  https://dl.flathub.org/repo/
Configure this as new remote 'flathub' [Y/n]: n

info.cemu.Cemu permissions:
    ipc           network              fallback-x11      pulseaudio      wayland      x11
    devices       file access [1]

    [1] host:ro, xdg-run/app/com.discordapp.Discord:ro, xdg-run/app/com.discordapp.DiscordCanary:ro


        ID                      Branch         Op         Remote              Download
 1. [✓] info.cemu.Cemu          test           i          cemu-origin         44.3 MB / 44.8 MB

Installation complete.
"

Here is a screenshot of this and the output when I run a game on vulkan on that test brach

![Screenshot_20230427_125420](https://user-images.githubusercontent.com/50719030/234920969-f6cda6e4-0bb5-488f-9c06-9f7ddc6894ef.png)
![Screenshot_20230427_125120](https://user-images.githubusercontent.com/50719030/234920976-d856cc28-f71a-4769-8b8f-c672bcb7aed7.png)

If that's not it please let me know how I can get that. Again, thank you for your efforts

**Comment by ColinKinloch** [comment]
Thanks.
I'm just looking for where it says "selected" and "wildcard" in the terminal.
Could you give the terminal output for this build.
Once run forcing x11 with `--nosocket=wayland` and once on wayland.
```bash
flatpak install --user https://dl.flathub.org/build-repo/20592/info.cemu.Cemu.flatpakref
```

**Comment by TheFortunattor** [comment]
I hope these screenshots work. If not, I'll give you a file with all the output

Wayland:

![cemuTestWayland](https://user-images.githubusercontent.com/50719030/234959606-abad9b86-74d7-4fda-9d1f-8f170e0f5568.png)

X11:

![cemuTestX11](https://user-images.githubusercontent.com/50719030/234959618-4c0ab633-ac7f-4634-88f6-cec3ed21eff7.png)

**Comment by TheFortunattor** [comment]
Just in case, here is the log of that. In the screenshots, there is a bit more text because I opened the general settings window and in KDE, it has a quirk that if Cemu is using wayland, it doesn't group the window and shows a wayland icon for the general settings window. I was using that to confirm if it was on wayland or X11 before opening the game

[CemuTestX11.txt](https://github.com/cemu-project/Cemu/files/11346920/CemuTestX11.txt)
[CemuTestWayland.txt](https://github.com/cemu-project/Cemu/files/11346921/CemuTestWayland.txt)

**Comment by ColinKinloch** [comment]
Sorry, wrong build.
This is what I meant:
```bash
flatpak install --user https://dl.flathub.org/build-repo/20614/info.cemu.Cemu.flatpakref
```

**Comment by TheFortunattor** [comment]
No problem, here you go!

[CemuTestX11(20614).txt](https://github.com/cemu-project/Cemu/files/11347141/CemuTestX11.20614.txt)
[CemuTestWayland(20614).txt](https://github.com/cemu-project/Cemu/files/11347143/CemuTestWayland.20614.txt)

Wayland:

![cemuTestWayland-2](https://user-images.githubusercontent.com/50719030/234967200-f46eb6a3-60df-4893-b77e-06d68594bc1b.png)

X11:

![cemuTestX11-2](https://user-images.githubusercontent.com/50719030/234967264-5c68ee62-d297-4c39-b71b-ccf8cbc5607a.png)

**Comment by ColinKinloch** [comment]
I should have read the output of vulkaninfo more carefully.
Your drivers lack support for `FORMAT_B8G8R8A8_SRGB` on `VK_KHR_wayland_surface` surfaces.
I suppose just force x11 with use `--nosocket=wayland` until either the nvidia proprietary drivers improve or the open source NVK is ready.

**Comment by TheFortunattor** [comment]
Huh, I see... thanks Nvidia. I guess I'll just use X11 as a workaround for now. Thank you for looking into this, I'll close this issue here and the one I made for the flatpak

**Comment by Fxzzi** [comment]
Can confirm either the 545 or 550 Nvidia Drivers have finally implemented support for `FORMAT_B8G8R8A8_SRGB`. Playing CEMU natively on wayland with my NVidia RTX 3070 has never been better! However these drivers have other issues right now specifically with XWayland meaning I have rolled back to 535 for now until it's fixed. YMMV.
