### ISSUE TITLE
Update bugs page on official site to HTTPS

### ISSUE THREAD

**Issue by TotalCaesar659** [cemu-project/Cemu#8]
Bugs page on official site (http://bugs.cemu.info) doesn't work with HTTPS. It's a security problem cause all data (especially after registration) may be intercepted by provider or anyone else.

**Comment by Exzap** [comment]
We are phasing out the old bug tracker in favor of github issues. Not worth putting any more effort into it. Furthermore nobody is required to put any sensitive information into it.

**Comment by Crementif** [comment]
Since I was doing some website work I did actually take some time to also upgrade the bug tracker with a certificate, so now it's only accessible through https like it should be.

**Comment by TotalCaesar659** [comment]
Thank you very much @Crementif!
