### ISSUE TITLE
[Bug Report] Graphic Packs don't accept Certain Symbols.

### ISSUE THREAD

**Issue by FLDR86** [cemu-project/Cemu#801]
Hello, I would like to report a couple of problems with the Graphics Pack System:

Visual Issue:
If your Graphic Pack rules.txt file (name, path or description) contains problematic symbols, Cemu's Graphic Pack Manager will display garbled characters instead.

Usability Issue:
If your Graphic Pack path contains problematic symbols, Cemu will not let you enable that Graphic Pack.
(When you open Cemu again, you will see that your Graphic Pack has been automatically deactivated).

 Example of problematic symbols:
  · Accute Accent: ´
  · N with Tilde: ñ 
  · Upside Down Question/Exclamation Mark: ¡ ¿

 On the other hand, there are other symbols that (unlike the above), will not cause any problems in Cemu:

 Example of not problematic symbols:
  · Parentheses: ( )
  · Square Brackets: [ ]
  · Downwards Question Mark: ?
  · Downwards Exclamation Mark: !
  · Grave Accent: `

These two problems have occurred in every version I have tested, including the most recent to date: Cemu 2.0-36 (Experimental). (Commit hash: f48ad6a)

Because of this, I would like to request the correction of these problems, so that such symbols can be entered without causing issues when they are used.
Thank you very much.

![Issue](https://user-images.githubusercontent.com/131767086/234289695-45d8ab6b-33ce-4ff9-a5be-2b3cc156e741.png)

**Comment by goeiecool9999** [comment]
Looks like for whatever reason wxWidgets is interpreting a unicode string as cp 1252
[here](https://github.com/cemu-project/Cemu/blob/main/src/gui/GraphicPacksWindow2.cpp#L442)
[here](https://github.com/cemu-project/Cemu/blob/main/src/gui/GraphicPacksWindow2.cpp#L449)
[as well as here](https://github.com/cemu-project/Cemu/blob/main/src/gui/GraphicPacksWindow2.cpp#L95)
is where the UTF8 strings are handed over to wxWidgets

**Comment by goeiecool9999** [comment]
@FLDR86 There's now a build available here: https://github.com/cemu-project/Cemu/actions/runs/4799717181 (at the bottom of the page in the artifacts section)
You can let us know if it fixes the problem in merge request #802
