### ISSUE TITLE
Zelda: BoTW Aspect Ratio of 3:2 causes crashes

### ISSUE THREAD

**Issue by ItsMeeSeanLee337** [cemu-project/Cemu#804]
Issue:
When running Zelda: Breath Of The Wild using a 3:2 aspect ratio crashing will occur randomly while playing the game. Crashes occur for all resolutions using the 3:2 aspect ratio. Easiest reproducible crash occurs at the start of the game on the first pickup of the sheikah slate. Setting framerate cap to 30 FPS helps crashing but does not completely fix issue, game is still unstable with the framerate cap. Crashes will occur at random times during gameplay(i.e. going to a specific location or completing a certain action) and are reproducible afterwards. Downgrading Cemu versions does not help resolve the issue. I downgraded to version 2.0-29 and 1.26 for testing, both downgraded versions of Cemu also crashed when using a 3:2 aspect ratio.

Cemu Version: 2.0-36
CPU: i7 11370H
GPU: RTX 3050 TI Laptop
RAM: 16 GB DDR4
OS: Windows 11 22H2

**Comment by jn64** [comment]
I can repro with 3:2 aspect ratio and Ultrawide HUD mode set to **Edge HUD (Default)**. Crashes every time I engage a Stone Talus (timing seems variable, sometimes as soon as the stone starts rumbling, sometimes when it's almost fully standing up, but always before the boss HP bar appears)

If I switch to **No HUD Fixes (stretched HUD)** it doesn't crash.

[log-crash.txt](https://github.com/cemu-project/Cemu/files/11360950/log-crash.txt)

Cemu version: f48ad6a
OS: Linux (Fedora 38)

**Comment by Exzap** [comment]
Please report this over at the graphic packs repository: https://github.com/cemu-project/cemu_graphic_packs

**Comment by jn64** [comment]
@Exzap You can [transfer the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository).
