### ISSUE TITLE
[Linux] Cemu doesn't start

### ISSUE THREAD

**Issue by Kakiking** [cemu-project/Cemu#806]
Version: 2.0 (experimenal) installed via flatpak
Distro: Manjaro 

Starting cemu results in it getting stuck in an endless loop. Configuring my controller worked when I launched it the first time.
```
$ flatpak run --branch=stable --arch=x86_64 --command=/app/bin/Cemu-wrapper info.cemu.Cemu
Gtk-Message: 17:33:45.105: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:33:45.106: Failed to load module "canberra-gtk-module"
```
No idea why this happens, how can I debug this further and get some actually useful logs?

**Comment by Squall-Leonhart** [comment]
join the discord and ask in the linux channel, your log looks like a general support issue rather than a bug issue.

**Comment by Kakiking** [comment]
Ok, thanks
