### ISSUE TITLE
Update Cemu Wiki

### ISSUE THREAD

**Issue by Amnesia1000** [cemu-project/Cemu#812]
The Cemu Wiki is outdated, today I wanted to see how I could connect my DualSense to use the motion sensor in linux, and everything was referring to the windows version, besides being prior to version 2.0.

**Comment by Squall-Leonhart** [comment]
don't open issues for wiki updates, register an account and update the wiki.

**Comment by Exzap** [comment]
Reminder that the wiki is maintained by the community and doesn't really have a direct connection to this repo. It lives off of contributions by people so if you feel like a page needs updating, the best you can do is update it yourself.
