### ISSUE TITLE
[Linux] Switch Pro input doesn't work if not continuously connected from launch

### ISSUE THREAD

**Issue by lisa-wolfgang** [cemu-project/Cemu#821]
When using an official Nintendo Switch Pro Controller with Cemu on Linux, controller input is only recognized when the controller was connected at launch and hasn't disconnected since. When connecting or reconnecting the controller after Cemu is launched, inputs won't be recognized by games. The input settings window doesn't seem to recognize the inputs either (as evidenced by attempting to remap buttons) but it will recognize that the controller is connected.

This occurs in both wired and Bluetooth modes of the controller. The controller was using the SDL API. The motion source from `joycond-cemuhook` (DSU) was able to reconnect and work properly after launch. I was able to test a Wii Remote (using both the SDL and DSU APIs) and it didn't seem to be affected by this bug.

Cemu version: v2.0-39
Operating system: Ubuntu 22.10

**Comment by Squall-Leonhart** [comment]
This is technically an [upstream issue going back several years,](https://github.com/libsdl-org/SDL/issues/3468) an application can mitigate that issue by using a polling loop though, as the developer in that github issue has.

**Comment by lisa-wolfgang** [comment]
This has been resolved in my testing as of 6dc73f5.
