### ISSUE TITLE
Please add DPI aware for Windows build.

### ISSUE THREAD

**Issue by SlimeNull** [cemu-project/Cemu#828]
Just add the following content to application's manifest:

```xml
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
      <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
    </windowsSettings>
  </application>
```

**Comment by Squall-Leonhart** [comment]
That's not enough to make Cemu fully dpi aware, there are some dialogs and controls that do not scale correctly.

**Comment by Silent-Remux** [comment]
Regardless of op's opinions, this would be a good idea.

**Comment by Squall-Leonhart** [comment]
Duplicate of https://github.com/cemu-project/Cemu/issues/155

**Comment by dxgldotorg** [comment]
Adding longPathAware is dangerous - the developer must make sure they don't have any MAX_PATH length buffers that could be vulnerable to buffer overruns.

The manifest entry is there for the developer to attest that the application can handle paths greater than MAX_PATH lengths.
