### ISSUE TITLE
[macOS] Cemu's menu bar doesn't work while game is in fullscreen

### ISSUE THREAD

**Issue by mavethee** [cemu-project/Cemu#830]
[x] You have provided the version (commit hash) of Cemu you are using.
- Cemu 2.0-39 (https://github.com/cemu-project/Cemu/commit/eda4cf4b241d56c5c16f6aa4d135b8a269676a76)

[x] You have provided sufficient detail for the issue to be reproduced.
- Run any game in fullscreen, try to either open settings, Cemu folder or load Amiibo.

[x] You have provided system specs (if relevant).

SoC: Apple M1 (8c/8c)
RAM: 16GB
OS: macOS 13.4

**Comment by mavethee** [comment]
> It should not even be displayed in fullscreen.

Well yes, but you can moving mouse to the top corners of the screen will give you the ability to use it, just it doesn't work as intended, as I can't even quit fullscreen to use the menu for e.g. loading Amiibos.

**Comment by Exzap** [comment]
Did you enable the `Fullscreen menu bar` option in the settings?

**Comment by mavethee** [comment]
Yes, it is enabled.

**Comment by jainze** [comment]
Copy of [#609](https://github.com/cemu-project/Cemu/issues/609)?

**Comment by mavethee** [comment]
> Copy of [#609](https://github.com/cemu-project/Cemu/issues/609)?

Yeah seems like, sorry when I was looking for similar issues i had troubles with naming and couldnt find any.
