### ISSUE TITLE
Controller not work with Steam Remote Play

### ISSUE THREAD

**Issue by aa889788** [cemu-project/Cemu#831]
I use steam remote play to host my own cloud gaming server in a docker, other games works fine with the xbox one s controller, 
but cemu could not work with it, before launch a game, the input dialog has no response to my operations, after launch the game, I have to re-select the Steam Virtual Gamepad in the pull-down menu, an the controller will work for just a few seconds

**Comment by aa889788** [comment]
[log.txt](https://github.com/cemu-project/Cemu/files/11555169/log.txt)

**Comment by Condemnedfate** [comment]
What version of Cemu and are you using the stable or beta branch of Steam? I was having issues with 2.0-36 and the Steam stable branch with controllers not working right with emulators. Controllers were only using the desktop layout with the stable branch, I had to switch to the beta branch for this to be corrected and now I'm able to steam to a steam link box successfully.

**Comment by Exzap** [comment]
Closing since this issue is stale
