### ISSUE TITLE
Cemu has a weird and conflicting scheduling behaviour with new X3D CPUs

### ISSUE THREAD

**Issue by devilhunter84** [cemu-project/Cemu#832]
Been at this for a while and haven't found a solution yet, but it seems that Cemu has a scheduling problem with the new multi CCD x3D CPUs from AMD.

I have a 7950x3D which has 2x CCDs, while other more popular x3D CPUs like the 7800x3D or the 5800x3D have only 1x CCD (cache only)

When you start a Cemu game CCD1 (faster frequency ccd) gets preferred and loaded, and when you enter fullscreen CCD0 (slower cache ccd) gets preferred and loaded.

The new system from Microsoft and AMD for detecting Games and automatically throwing them on CCD0 (cache) does not get used here, since XBOX Game Bar (that's how they do it) is not detecting Cemu as a game, the tickbox isn't showing up for Cemu as it does for all other fullscreen games.

And here's the bit of wonkiness explained because the main problem starts here:

- Window mode randomly uses cores from all CCDs, but preferrs CCD1 (frequency) - you do not want both CCDs loaded because of the latency between the CCDs
- Fullscreen mode only wants CCD0 (cache)
- Fullscreen mode out of focus (multi monitor, for example clicking on Firefox in the second monitor, but game is still fullscreen) throws the loads out of CCD0 and back randomly onto CCD0 and CCD1 again.

- the main problem: forcing Cemu to use the CPU cores from CCD1 (these Cores can have almost 1GHz more then the cache ones during load) via Task Manager or Process Lasso works really badly, if you click in and out of the Cemu game then the games become instantly instable and slow down to sub 1fps, even if the games are in window mode. I can see that Cemu ABSOLUTELY wants to use other Cores then Windows tells it to and form the looks of it Cemu and Windows are really fighting where to put the CPU load to.
- Switching between other apps while Cemu is running and has it's tasks forced onto CCD1 also has this effect, the whole system stutters while Cemu and Windows duke it out.
- staying in window mode and forcing Cemu onto CCD1 works for a few seconds until you click somethign els on your PC then the Cemu games slow down to sub 1fps again.
- there is an option to set CCD1 as a standard in the BIOS, but this has an effect on other apps and games which i'd rather not do. (some of my games don't use the cache CCD then)

This behaviour seems to be something that is coded into Cemu, i have no other app that behaves this way when i force them other CPU cores with Process Lasso.

I wanted to try out where the performance is better, either on the Cache CCD or the frequency CCD, but Cemu absolutely does not want manual CPU affinity set (and switching fullscreen/window or even between other apps)

OS: Windows 11
CPU: Ryzen 7950x3D
GPU: nvidia 3060ti
Ram: 64GB DDR5

Cemu version: tried multiple, currently 2.0-39
Tried CPU Core managers: Task Manager, Process Lasso

**Comment by Squall-Leonhart** [comment]
Leave it alone, Ryzen already has CPPC hints that tell the kernel what core on what complex is the best and will execute the driver off of that, trying to do what you're doing is just causing the nvidia multithreaded driver optimisations in the user mode process to be on a different complex to the kernel driver processing which will cause communication between them to cross the complex
