### ISSUE TITLE
Shader cache not stored in a Time-Machined directory on macOS

### ISSUE THREAD

**Issue by jainze** [cemu-project/Cemu#834]
The ~/Library/Caches folder doesn't appear to be backed up by Time Machine on macOS. It makes sense not to back up generated shaders, but the /transferable folder could benefit greatly by being included in a backup.

**Comment by Squall-Leonhart** [comment]
oh great, more mac specific directory handling to care about.

**Comment by jainze** [comment]
> oh great, more mac specific directory handling to care about.

😅 I get your point, but isn't the Windows situation way more confusing? I saw the recent discussion from the Dolphin team about which AppData subdirectory to use from now on, and it was rather convoluted. 

Friendly platform digs aside, how *is* it handled on Windows? Like I said, it's a good idea to not back up the generated shaders at all (that's what you'd actually want), but the transferable cache is a valuable resource. Where are each put?

**Comment by qurious-pixel** [comment]
You could always soft link (or hard link depending how Time Machine handles symlinks) to a path in the home directory of your transferable Caches.

For RPCS3, I run a script that copies the shader Caches to a specific location when I close the Emulator.

**Comment by jainze** [comment]
> You could always soft link (or hard link depending how Time Machine handles symlinks) to a path in the home directory of your transferable Caches.
> 
> For RPCS3, I run a script that copies the shader Caches to a specific location when I close the Emulator.

True enough, and I actually run a periodic manual backup of that directory. My point is that it’s worth considering as a change. The devs might disagree, but I’d be wrong not to mention it. 

For what it’s worth, after some digging, most other emulators that I have that have Vulkan shader caches store them in Application Support, the same place that Cemu stores everything else.

**Comment by aem111607** [comment]
Add a symlink in your Caches/Cemu folder to another cemu shader cache folder somewhere that is backed up. Caches aren't backed up by Time Machine, because caches are not usually important data.
