### ISSUE TITLE
Add a list of amiibos like Ryujinx, if possible

### ISSUE THREAD

**Issue by MistakingManx** [cemu-project/Cemu#839]
**Feature Request**
In Ryujinx, the Switch emulator, there's a tool called "Scan an Amiibo" which pops up a list of specific amiibos the game supports.

I don't know if that level of specification is possible with the Wii U, but would it be possible to include the same list, a bunch of known Amiibos, similar to how Ryujinx's "list all" option works?

Thank you for reading my suggestion!

**Comment by Exzap** [comment]
I recognize the convenience of this, but the legality of it is questionable for two reasons:
- Amiibo data is copyrighted. To what degree is arguable but it's definitively a gray area to ship Amiibo signatures or parts thereof with the emulator.
- Amiibos are physical "paid DLC". Bypassing the need to own Amiibos can be equated to piracy built into the emulator.

It's a bit more complicated than this and I know that Ryujinx tries to work around these issues by using an external service, but it's still not legally sound in the end so I rather not we implement this.
