### ISSUE TITLE
Low GPU Clocks

### ISSUE THREAD

**Issue by factorial52** [cemu-project/Cemu#848]
I've been playing BOTW on my laptop. It hovers around 30-35 fps in the overworld. I've been trying to figure out for a while why performance tanks in shrines, basically to the point of locking up briefly every few seconds. Shrines should be easier to run, and I think that's the problem.

It looks like my GPU core clock drops way down, game slows to a crawl, core clock comes back up, repeat.

It's not throttling due to thermal or power constraints. I was actually able to fix the problem, at least in a strange way. If I have yuzu running at the same time with force max clocks enabled the problem is completely fixed. FPS drops to about 20, which is understandable, but it's steady, and the clocks stay high.

I'm not sure if I'm going anywhere with this, or asking for a fix, I have other systems to play on anyway. I just couldn't find anyone with this problem in all my searching, so I thought I'd write it down.

I can get more info if needed. Not with my computer currently.

Running on Arch Linux, all packages installed are from this date
https://archive.archlinux.org/repos/2023/06/05/
On current Cemu (version ends in 39)
CPU is 5700U

Also worth noting, this only happens on Vulkan.

**Comment by goeiecool9999** [comment]
This seems like something gamemode could probably fix. There should be an option to enable it in the general settings.

**Comment by Squall-Leonhart** [comment]
> This seems like something gamemode could probably fix. There should be an option to enable it in the general settings.

insufficient memory bandwidth for the current configuration of the game being played could cause low gpu util too, especially if this 5700U is paired with a single DIMM.
