### ISSUE TITLE
Opening game directory does not work on MacOS

### ISSUE THREAD

**Issue by MarioPeperoni** [cemu-project/Cemu#849]
When attempting to access any of the folders (Game Directory, Save Directory, Update Directory or DLC Directory) on MacOS, you encounter the following error: `error 2: No such file or directory.` This is likely caused by the macOS using a different file path format than `file:`. It works on windows for sure but I have not checked if it is an issue on Linux

1. Open the application on MacOS.
2. Right click on any of the options mentioned above.
3. "error 2: No such file or directory."

<img width="244" alt="image" src="https://github.com/cemu-project/Cemu/assets/68820849/3d40742c-c3a2-4c5a-a554-b7da4ecc4b3f">

_Version: Cemu 2.0-39_

**Comment by aem111607** [comment]
Works for me.

**Comment by Squall-Leonhart** [comment]
looks like you copied the settings file from a windows machine,

**Comment by HKL-Kevin** [comment]
<img width="1280" alt="image" src="https://github.com/cemu-project/Cemu/assets/44154392/15e52fb2-0b18-48f5-8aaa-e02bd55471d6">
also Cemu 2.0-59,macOS 13.4.1

**Comment by yogithesymbian** [comment]
In previous years, I could do this directly with a right-click. Now that I've nostalgically reinstalled it, I am having the same issue.

**Comment by yogithesymbian** [comment]
device mbp m1 with latest cemu version

**Comment by yogithesymbian** [comment]
```
Failed to open URL "file:/Users/my_name/Library/Application Support/Cemu/mlc01/usr/save/00050000/101c9400" in default browser. (error 2: No such file or directory)
````
i manage my games in Documents/cemu_room/my-game-here
