### ISSUE TITLE
[MacOS] [Skylanders] Portal Of Power Not Working

### ISSUE THREAD

**Issue by KermitPrplYT** [cemu-project/Cemu#851]

**Comment by KermitPrplYT** [comment]
There is a separate thread, yes, but that one is for linux. This thread is for MacOS.

**Comment by Squall-Leonhart** [comment]
Unix based OS's need a specific driver,

a driver which i doubt is even available for Mac considering its insane code signing requirements.

**Comment by KermitPrplYT** [comment]
oh.
