### ISSUE TITLE
Nothing works on the latest MacOS release

### ISSUE THREAD

**Issue by qwerty523** [cemu-project/Cemu#853]
Just tried out the latest development release for Mac, but it turns out that the emulator barely works. I can load up the games and see the pre-title stuff, but when it comes to the actual title screen, half the graphics are either broken or missing entirely, or for some games, the graphics work fine but trying to start the actual game causes the app to suddenly close itself. Can't seem to do anything else. (The games I tried were Super Mario Maker and New Super Mario Bros. U.) 
Device info:
<img width="392" alt="Screenshot 2023-06-08 at 1 00 43 PM" src="https://github.com/cemu-project/Cemu/assets/98148464/f2e27903-3bd7-413f-8b85-08aa5e0ed125">

**Comment by Squall-Leonhart** [comment]
I'm pretty sure only newer non-iris macs have the metal capabilities necessary for Cemu.

**Comment by qwerty523** [comment]
> I'm pretty sure only newer non-iris macs have the metal capabilities necessary for Cemu.

Intel? And also, it's not performance-related. The stuff that DID load ran at a steady 57 FPS.

**Comment by Squall-Leonhart** [comment]
The Iris 5xxx and 6xxx IGP's only have hardware support for Vulkan to api level 1.0 when exposed through MoltenVK, the newer macs get 1.2

**Comment by aem111607** [comment]
Games don't work, check the compatibility list: https://cemu.emiyl.com/
