### ISSUE TITLE
Poor performance with no reason

### ISSUE THREAD

**Issue by LorenzoSTF** [cemu-project/Cemu#857]
Its a very detailed problem. Im trying to play Zelda BOTW with a RX 6700 XT, a R5 1600 and 16 Gb of RAM at 3200 MHz. The game was installed in an SSD with the shaders cache installed too. I saw videos of people using gt 970ti and playing the game at +70 fps. When opening the game it just drop forme the menu at 144 hz to the game at 35 fps. The weird things is that the frametimes are also very inconsistent at the start and after some time it manages to get to 50 fps. I asked a lot on the discord server and no one could give me a solution and for that reason I came here to ask you what I can do to solve this issues.

Thank you very much for your time in advance

**Comment by Crementif** [comment]
This place is meant for general issues with Cemu that affect everyone, not just you. You might just need to be a little more patient till someone gets along to solve your issue.
