### ISSUE TITLE
Zombie controller profile

### ISSUE THREAD

**Issue by Mrcubix** [cemu-project/Cemu#858]
Version: 2.0-39
Description: Deleted profiles get loaded but seemingly doesn't appear in the profiles list.

On my first use of CEMU, i used a DS4 Controller, i created a profile named `ps4` then set all bind & other settings and saved.
Later on, since that's the controller thing i had on hand, i used a DS3 controller, and that's when i started having issues.

First of all, my DS4 profile get selected whenever my controller get disconnected mid-play, forcing me to go back to the input setting menu and selecting the `ps3` profile.

When i got tired of it, i removed the `ps4` profile.
Thought i got rid of the issue but nope, it's still selecting that profile on disconnection, and when opening cemu again!
Again, i removed the `ps4` profile using the input settings menu, yet, it still appear if i go back to that menu after closing and opening cemu again.
If i check the list of profiles, only `ps3` appear.

What i'm expecting: CEMU should not be loading removed profiles, in fact, it should be complitely getting rid of that profile from whatever settings file is used.
When a controller is disconnected, do not fallback to that profile, fallback to the appropriate profile, being, the last one used for that controller. 

Logs: [log.txt](https://github.com/cemu-project/Cemu/files/11713527/log.txt)

**Comment by Squall-Leonhart** [comment]
This is not how profiles work lol.

**Comment by Mrcubix** [comment]
They sure does not work, indeed

**Comment by Exzap** [comment]
If you upgraded from an older version of Cemu the legacy controller profiles can sometimes cause issues. Try deleting everything in the `controllerProfiles/` folder and setup the profiles again.

**Comment by Mrcubix** [comment]
Unfortunately, that's not the issue, this is done on a clean, first use of CEMU as a whole.
I would note that there is a file named something like `Controller 0` that got created at that time, which seems weird since my ps3 profile seemingly had the right filename, being the name of the profile.

**Comment by Exzap** [comment]
`Controller 0` is just a copy of whatever profile is loaded and active.

Anyway I cant really make sense of your explanation. How can it switch profiles if there is only one? Not that it should ever switch profiles on its own. Maybe you can post some screenshots of your input settings

**Comment by nonobio** [comment]
Hi @Mrcubix ,

I'm a new user with the same issue: old deleted profiles are loaded every time I close and restart Cemu.
This old name is on the <profile> line when I open the XML. If I change it to the new name, Cemu displays then the good name. But it is weird... I think there is an issue because I can't save my rumble setting (100ù), it always go back to 0, but maybe it is another story...

**Comment by Squall-Leonhart** [comment]
Delete the input profiles from the cemu directory.

**Comment by nonobio** [comment]
Ok , I deleted all my profiles. Not sure if it resolve the issue if I will rename it but I will not do that for the moment.
About the rumble issue, I found a workaround here: https://github.com/cemu-project/Cemu/issues/542

**Comment by Exzap** [comment]
There have been quite a lot of changes since July and from the description alone it was not possible to track this down. If this problem still occurs please reopen a new issue.
