### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [cemu-project/Cemu#86]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [curlDebug_notifySubmitRequest](https://github.com/cemu-project/Cemu/blob/560a2e536f2c9db1c2b47411030229bef2d43aaa/src/Cafe/OS/libs/nlibcurl/nlibcurlDebug.hpp#L42 "curlDebug_notifySubmitRequest function")
- [MergeShaderCacheFile](https://github.com/cemu-project/Cemu/blob/560a2e536f2c9db1c2b47411030229bef2d43aaa/src/tools/ShaderCacheMerger.cpp#L22 "MergeShaderCacheFile function")
- [PipelineInfo](https://github.com/cemu-project/Cemu/blob/560a2e536f2c9db1c2b47411030229bef2d43aaa/src/Cafe/HW/Latte/Renderer/Vulkan/VKRPipelineInfo.cpp#L52 "Destructor for PipelineInfo")

**Comment by Crementif** [comment]
Could this be turned into a pull request? I don't really want to have the github issues to be full of minimal coding issues since that'd cause spam.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by Crementif** [comment]
Automatic formatting and code issue detection tools have been discussed, but we're busy with other things for now. We'll fix these minor issues once we get to that.
