### ISSUE TITLE
Latest git fails to build on Arch 

### ISSUE THREAD

**Issue by wantija** [cemu-project/Cemu#860]
`[ 99%] Building CXX object src/Common/CMakeFiles/CemuCommon.dir/ExceptionHandler/ExceptionHandler_posix.cpp.o
[ 99%] Linking CXX static library libCemuCommon.a
[ 99%] Built target CemuCommon
make[2]: *** No rule to make target '/usr/lib/libzarchive.a', needed by '/home/daniel/.cache/pikaur/build/cemu-git/src/cemu/bin/Cemu_release'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[100%] Building CXX object src/CMakeFiles/CemuBin.dir/cmake_pch.hxx.gch
make[1]: *** [CMakeFiles/Makefile2:411: src/CMakeFiles/CemuBin.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
`
Compiling the latest git of cemu and the build fails, looks like it's a zarchive issue but I have no idea how to solve it.

**Comment by jn64** [comment]
> `/home/daniel/.cache/pikaur/build/cemu-git`

If you're using the [_cemu-git_ AUR package](https://aur.archlinux.org/packages/cemu-git), please report to the package maintainer.

**Comment by wantija** [comment]
thanks, turns out it was an issue with the aur helper
