### ISSUE TITLE
DSUController settings crash Cemu

### ISSUE THREAD

**Issue by e00E** [cemu-project/Cemu#869]
Arch Linux, Cemu built through AUR

> cemu --version
> 2.0-353 (experimental)

Playing around with adding and removing DSUController inputs, I quickly see Cemu crashing. I'm not posting the stacktrace because it is useless due to missing debug symbols. The log doesn't contain relevant information either.

**Comment by Crementif** [comment]
Can you try building Cemu from source and try wayland? The aur package isn't provided by us thus isn't officially supported.

**Comment by e00E** [comment]
I can reproduce it with the official AppImage version. The stacktrace is still useless.
