### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cemu-project/Cemu#87]
I would like to point out that identifiers like “[`_AES_H_`](https://github.com/cemu-project/Cemu/blob/560a2e536f2c9db1c2b47411030229bef2d43aaa/src/util/crypto/aes128.h#L1 "Update candidate")” and “[`__OSFiberThreadEntry`](https://github.com/cemu-project/Cemu/blob/560a2e536f2c9db1c2b47411030229bef2d43aaa/src/Cafe/OS/libs/coreinit/coreinit_Thread.cpp#L27 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Crementif** [comment]
Is this also fixed by clang-tidy? Also, feels like too minor of an issue, gonna close this since these things can be addressed over time.

**Comment by elfring** [comment]
>Is this also fixed by clang-tidy?

I do not get the impression that [more desirable source code adjustments would be supported for this issue by the mentioned tool](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/reserved-identifier.html "Checks for usages of identifiers reserved for use by the implementation") at the moment.

:thought_balloon: I suggest to avoid that software components [depend on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?").
