### ISSUE TITLE
windwaker hd low fps 

### ISSUE THREAD

**Issue by alienmorf** [cemu-project/Cemu#872]
<img width="1089" alt="Screenshot 2023-06-19 at 07 10 55" src="https://github.com/cemu-project/Cemu/assets/70683904/df466e4b-ad0e-4ab4-a25e-62b09db60a35">

in places with much particles

hardware: MacBook Pro M1 Max (max cores), 64Gb RAM, 1Tb SSD

**Comment by alienmorf** [comment]
MacOS 13.4 Ventura

**Comment by MickL** [comment]
I have a Mac M2 Max which have way enough power to handle this game and it actually runs super smooth even in 4k. BUT for example on the first island when the light beams were visible the frames drop towards 10 fps. Or when a bomb explodes the frames drop.

I wouldnt bother but the game seems to be tied on the frame rate, so when it drops it is like slow motion.

**Comment by alienmorf** [comment]
I have 0 problems on my Steam Deck😊But why M1 Max can’t handle it 😞Best regards, Mike AnisimovOn 25 Nov 2024, at 00:29, Mick Lawitzke ***@***.***> wrote:﻿
I have a Mac M2 Max which have way enough power to handle this game and it actually runs super smooth even in 4k. BUT for example on the first island when the light beams were visible the frames drop towards 10 fps. Or when a bomb explodes the frames drop.
I wouldnt bother but the game seems to be tied on the frame rate, so when it drops it is like slow motion.

**Comment by MickL** [comment]
Thats really interesting! M2 Max should be multiple times as powerful. There must be something with this particle effects. The section I posted above (on Drakonia) is unplayable.
