### ISSUE TITLE
Error installing updates (BOTW) v1.26.2+

### ISSUE THREAD

**Issue by HybridShivam** [cemu-project/Cemu#88]
Version : v1.26.2+ Windows 10
When opening the meta.xml of the update folder the following error occurs.

`''Error: The system cannot find the path specified. space: The system cannot find the path specified: '''' ''`

Works properly in v1.26.1
I don't think any more information is relevant.
The update path is not too large.

<img src="https://user-images.githubusercontent.com/28728749/187040116-ff5ccadd-35c0-45c1-bba2-719ffb6d352d.png" width="300" />

Edit : Installing game update/dlc in v1.26.1, then updating cemu works.

**Comment by griffi-gh** [comment]
(P.S: you don't need to install updates anymore, just put them in your games folder)

**Comment by Squall-Leonhart** [comment]
I believe this is resolved now?

**Comment by griffi-gh** [comment]
> I believe this is resolved now?

¯\_(ツ)_/¯, try it and see

**Comment by Immersion95** [comment]
It works with the NUS format here without installing.
