### ISSUE TITLE
Clothe color is strange in Tekken Tag 2

### ISSUE THREAD

**Issue by Kiminari-Suzuki** [cemu-project/Cemu#881]
![スクリーンショット (280)](https://github.com/cemu-project/Cemu/assets/95355632/1f7ded31-2efd-43cc-ab03-2d96465e8f00)
Hello. I played Tekken Tag 2 on Cemu version after 2.0. Then clothe color is strange like this. But on version 1.26.2(stable) it works well. Please fix it.

**Comment by Exzap** [comment]
Duplicate of #23
