### ISSUE TITLE
Broken keyboard input in Wii U Internet Browser

### ISSUE THREAD

**Issue by niko325c** [cemu-project/Cemu#882]
Cemu Version: 2.0-42

### System specs:
OS: Windows 11 Pro 22H2
CPU: Intel Core i7 8665U @ 1.90GHz
GPU: Intel UHD Graphics 620
RAM: 16GB

### Description of issue:
When entering text and other symbols into text boxes on websites, which include writeable textboxes, text doesn't get written/inserted correctly. The text becomes a garbled mess based on the letters typed into the Cemu Software keyboard. 

Images showing the issue:
<img width="642" alt="Skærmbillede 2023-06-27 171622" src="https://github.com/cemu-project/Cemu/assets/38987957/dcf636f3-fea0-4554-af94-e8d5d376bd0f">

<img width="642" alt="image" src="https://github.com/cemu-project/Cemu/assets/38987957/b936c407-777c-4790-8564-4e4ddf7db4ee">

<img width="642" alt="image" src="https://github.com/cemu-project/Cemu/assets/38987957/7ae9ac6c-0232-4a70-ae25-ed458ca7b6b3">

Makes some interactions with websites in the Wii U Internet Browser impossible (or very hard), such as logging into websites and searching for websites with search engines such as google. This issue doesn't affect the address bar.
This only seems to affect the Wii U Internet Browser.

This has been an issue even before Cemu 1.26.2f.

I believe this is an inaccuracy in the Cemu Software Keyboard. But I do not have the knowledge or experience to provide any further technical information.

### How to reproduce:
1. Go onto a website that includes a textbox such as google. 
2. Click on the textbox.
3. Write a few words.
4. Close the on-screen keyboard.

### Log:
[log.txt](https://github.com/cemu-project/Cemu/files/11884607/log.txt)

**Comment by Squall-Leonhart** [comment]
Only affects the HLE keyboard, the official software keyboard works fine

https://wiki.cemu.info/wiki/System_RPL_Files

**Comment by niko325c** [comment]
Thanks, I didn't know about that. I am using a full mlc dump of my own Wii U, but I haven't dumped the slc files. So il'l be doing that and see if it helps.
