### ISSUE TITLE
Sony DualSense Edge Motion Controls Not Detected

### ISSUE THREAD

**Issue by besselfunct** [cemu-project/Cemu#884]
- **Bug**: Motion controls on Sony DualSense Edge not detected by Cemu.
- **Cemu Version**: 2.0-42 (experimental)
- **How to Reproduce**: Connect Sony DualSense Edge controller with Steam Input disabled. Add a WiiU Gamepad emulation profile, and select SDL controller API and DualSense Edge Wireless Controller. Attempt to activate motion control in Settings, but the checkbox is grayed out.
- **Additional Details**: Default `udev` rules (as of June 23 2023) resulted in this controller being identified as a regular DualSense controller, which caused issues with button mapping and motion controls. Had to update `udev` rules to include [this](https://codeberg.org/fabiscafe/game-devices-udev/src/branch/main/71-sony-controllers.rules) file for proper controller recognition. Now, motion controls are working in Yuzu, but not in Cemu.  

I realize that this controller isn't particularly common, but I'd like to try to get it working. I feel like it's something simple, but I don't know how to go about debugging it.

**System Specs**
OS: Pop!_OS 22.04 LTS
CPU: Intel i5 13600K
GPU: AMD 7900XT
Motherboard: Gigabyte Z790 UD AC

**Comment by Squall-Leonhart** [comment]
This will be resolved when Cemu updates to SDL 2.28.

**Comment by besselfunct** [comment]
Need isn't dire. I just couldn't figure out why it was showing up in one app and not the other. In my prior experience, motion controls either work everywhere, or they're completely broken. I've never had something only partially recognized.

I'll just use my DS4 until the library version gets bumped.
