### ISSUE TITLE
Super Smash Bros U does not boot on Linux

### ISSUE THREAD

**Issue by gamrXerus** [cemu-project/Cemu#89]
I was able to compile Cemu 2.0 on Lubuntu 22.04. Some games work, but others do not. This includes Super Smash Bros U which crashes on boot. I have attached a log file and a backtrace to help troubleshoot the issue. It may be some sort of threading issue as gdb says at the beginning __pthread_kill_implementation (no_tid=0, signo=5, threadid=140731614217792) at ./nptl/pthread_kill.c:4444 	./nptl/pthread_kill.c: No such file or directory.
log:
[log.txt](https://github.com/cemu-project/Cemu/files/9438426/log.txt)
gdb backtrace
[gdb-CemuSSBU.txt](https://github.com/cemu-project/Cemu/files/9438430/gdb-CemuSSBU.txt)

Specs:
Core i9 11900K
16GB RAM
AMD Radeon RX 6800
Mesa 22.3.0-devel

**Comment by bitscher** [comment]
It seems you hit a debug assert, you could try compiling the Public Release target.

**Comment by gamrXerus** [comment]
> It seems you hit a debug assert, you could try compiling the Public Release target.

You were right. I recompiled Cemu using cmake .. -DPUBLIC_RELEASE=ON and was able to launch the game. Thank you.
