### ISSUE TITLE
steamworld collection

### ISSUE THREAD

**Issue by nicatgames** [cemu-project/Cemu#891]
cemu 2.0-42
in steamworld collection even though the game boots up fine, when selecting one of the two games there is an infinite loading screen and you can't get ingame.
ryzen 7 3800x
gtx 1660 super
16gb ram

**Comment by nicatgames** [comment]
if you could please try it out with your own copy. Not the eshop versions, but the physical collection.

**Comment by Squall-Leonhart** [comment]
this game requires system rpl file,s but this might be due to the same bug that regressed just dance 2019.
