### ISSUE TITLE
Cemu 2.0-44 Vulkan caches not stored for faster reload

### ISSUE THREAD

**Issue by Hexaae** [cemu-project/Cemu#895]
I'm currently using NVidia SD 536.40 WHQL on my ASUS GL703GS (i7-8750H 32GB RAM + 1070 8GB) with Win 11 22H2.

I updated Cemu from 2.0-38 to -44 and noticed game loading like ZBOTW will have to re-generate VK caches every single time I launch the game (~4min). With previous versions I remember it was necessary only the first time after you updated video drivers and then vk cache loading was very fast (~30secs).

Is this "normal"? ...Cemu internal changes? NVidia drivers problem?

**Comment by Squall-Leonhart** [comment]
Some Cemu changes will nullify an existing cache, but i am not aware of one that does since 2.0.30

2.0.42 did [Remove remnants of frame profiler code](https://github.com/cemu-project/Cemu/commit/45072fccb2e263757bd68b96686ded96fb50be78) which touched the latte core files, which may have?

**Comment by Hexaae** [comment]
I'm just testing previous versions one by one to see when, in case, it started... Could be also an NVidia driver problem after all.

**Comment by Squall-Leonhart** [comment]
I can confirm this btw, 43 > 44 doesn't use the cache, how odd.

**Comment by Hexaae** [comment]
It seems a driver issue to me: I tried back up to -12 and still didn't use cached VK pipelines launching it twice or more :(
Let's see in next days if everything goes back to normal by itself.

**Comment by Exzap** [comment]
You can try deleting the `shaderCache/driver/` folder and see if that helps.

**Comment by Hexaae** [comment]
Just tried and VK cached pipeline is always slow as the very first time to generate... strange. I think it can be an NVidia issue (IIRC this already happened in the past).

**Comment by Hexaae** [comment]
...after reboots and Windows updates, still no improvements.
CEMU 2.0-44, VK caches are (re)generated every time I launch ZBOTW (4 minutes!) with NVidia drivers 536.40 SD on my GTX 1070 8GB.
Shader caches reload instead is ok.

**Comment by Hexaae** [comment]
Oh dear...! Again... and it took again the usual 4 minutes to regenerate the VK pipeline caches.
Seems totally random 😖

**Comment by Squall-Leonhart** [comment]
try increasing the shader cache size in nvcp

**Comment by Hexaae** [comment]
I can confirm the increased cachesize limit fixes the issue:
![image](https://github.com/cemu-project/Cemu/assets/8591462/ede20082-6022-4bcb-a817-55797fdf8652)
... but I don't understand why when CEMU is launched from Steam VK cached pipelines loading is always slow, even if you disabled Steam shader cache.

**Comment by Squall-Leonhart** [comment]
Steam intercepts the vk cache and **can** contribute to longer compiles, its not a for sure thing

https://github.com/yuzu-emu/yuzu/issues/10911

**Comment by Hexaae** [comment]
Just for curiosity after I read this: https://forums.flightsimulator.com/t/known-issue-updated-13th-of-july-crashing-with-nvidia-gpu-drivers-536-40-532-03-531-79-531-68-531-61-531-41/591685
I rolled back to NVidia 528.49 SD (from 536.40 SD) and Steam loading is now the same as running CEMU alone (!?), but there is more... on my old Pascal 1070 8GB the VK pipelines cache loading is BLAZING fast! We're talking about 3secs vs 11secs with Yoshi's Woolly World, and even from scratch first compile is way faster then with current NVidia 536.40 SD!

**Comment by Hexaae** [comment]
**STEAM SLOWDOWN**
After an accurate monitoring I've found that disabling "SteamOverlayVulkanLayer64.dll" from loading fixes the issue with Steam and slow CEMU caches loading. As I supposed, forcing not to load that Steam VK overlay library by CEMU.exe indeed makes CEMU from Steam as fast as run alone:
![image](https://github.com/cemu-project/Cemu/assets/8591462/634ffc39-f7aa-43f2-84c1-8c6921e2bb2f)

**Comment by Hexaae** [comment]
09.Oct.2023 the problem seems to have solved itself with current Steam version.

**Comment by ezamelczyk** [comment]
I'm playing on a mac and my game also loads vk pipelines for a few minutes before every game launch and the more I play the longer it takes. Is this solvable?

**Comment by Hexaae** [comment]
> I'm playing on a mac and my game also loads vk pipelines for a few minutes before every game launch and the more I play the longer it takes. Is this solvable?

Did you try to delete cached pipeline? RMB - right mouse button - on the game from the list and choose Remove Shader caches?
![image](https://github.com/cemu-project/Cemu/assets/8591462/66e8ceb9-2fea-408d-a7d3-a41e060490e3)
Yes, will delete also your cached pipelines huge files, but they are not needed anymore with recent CEMU compiling real-time.
For NVidia/Windows there is also this other trick for faster loading: 
https://www.reddit.com/r/cemu/comments/1999i4r/faster_cache_loading_with_these_nvidia_profile/

**Comment by ezamelczyk** [comment]
I deleted them but the issue came back.
