### ISSUE TITLE
"Windows display scaling"lead to pixelated graphics.

### ISSUE THREAD

**Issue by YuWongXX** [cemu-project/Cemu#896]
All games looks pixelated until "disable display scaling on high dpi settings".
But if I disable display scaling, CEMU forces to enable exclusive fullscreen.
Yuzu handles it very well though.

**Comment by Squall-Leonhart** [comment]
there is absolutely no connection between the dpi scaling and the fullscreen type.

**Comment by YuWongXX** [comment]
In CEMU 1.26.2 It works perfectly
