### ISSUE TITLE
Black Ops 2 get stuck loading on Linux

### ISSUE THREAD

**Issue by gamrXerus** [cemu-project/Cemu#90]
Cal of Duty Black Ops 2 get stuck loading on boot. I have attached a log file and a backtrace to help troubleshoot the issue. The beginning of the gdb backtrace says Thread 1 "MainThread" received signal SIGINT, Interrupt and 
../sysdeps/unix/sysv/linux/poll.c: No such file or directory
log:
[log.txt](https://github.com/cemu-project/Cemu/files/9438444/log.txt)
gdb backtrace
[gdb-CemuBO2.txt](https://github.com/cemu-project/Cemu/files/9438446/gdb-CemuBO2.txt)

Specs:
Core i9 11900K
16GB RAM
AMD Radeon RX 6800
Mesa 22.3.0-devel
Lubuntu 22.04

**Comment by Exzap** [comment]
Closing this since it's stale and there is a very high chance this is fixed by now. If the problem still occurs feel free to open a new issue
