### ISSUE TITLE
[Xenoblade Chronicles X] When selecting "Return to Title Screen" in-game, infinite loading, never progresses

### ISSUE THREAD

**Issue by MultiKoopa** [cemu-project/Cemu#904]
![image](https://github.com/cemu-project/Cemu/assets/30543543/0e1cf393-8855-4760-b788-833ad9e53bee)

The little loading circle in the bottom-right corner spins, the music keeps playing, the game doesn't freeze, but the progress bar never actually progresses at all, and returning to title screen never happens. There's no error in CEMU happening, so the log file is never actually updated when I eventually close CEMU manually.

No online activated, all graphics packs disabled. Checked with somebody else in the Discord, same issue there.

Windows 11 Pro 64-bit, Cemu 2.0-44

**Comment by JaimieVandenbergh** [comment]
Confirmed by me on 2.0-44/Mac, same thing.

**Comment by Squall-Leonhart** [comment]
shouldn't be that difficult to implement this sysapp call.
