### ISSUE TITLE
Inputs do not work when playing splatoon [2.44]

### ISSUE THREAD

**Issue by alanotics** [cemu-project/Cemu#905]
When I play splatoon on my system [GTX 1650 Ti. an i5-10300H CPU, 8gb DDR4 RAM], inputs do not go through specifically when playing this game.
I tried playing on the latest stable release and it works flawlessly. I have tested with multiple graphics configurations and nothing has fixed the issue.
The game loads in however I cannot do anything on the charater select and occasionally when opening it goes to the title screen, but I cannot go through.
The game version is 272.

Win 11 Home

**Comment by Squall-Leonhart** [comment]
splatoon requires the wii u gamepad or a wii mote.
