### ISSUE TITLE
Mario & Sonic Sochi 2014 no longer can boot past menus (among other issues)

### ISSUE THREAD

**Issue by TheRealWario** [cemu-project/Cemu#906]
In Mario & Sonic at the Sochi 2014 Olympic Winter Games, the game will consistently crash after the title screen. This started to happen in the first 2.0 release, if I can recall, and is still there as of the latest experimental build. Even when it did work, in the latest stable build, there were graphical artifacts in the menus, and the wiimote motion plus wouldn’t be detected even if configured in the emulated controllers. There was also no graphic packs either, but that may be remedied when the game is brought to a playable state.

**Comment by Squall-Leonhart** [comment]
The official status for this game is "Runs", not "Playable"

The description for which is
> Games in this category can get in-game and usually run very well, but major graphical or audio glitches or game-breaking bugs make it difficult to continue playing or finish the game.

Games that are already categorized to this should not be brought up on the github as an issue, as they are already covered under the continued development towards accurate (as HLE can get) emulation, and have pre-existing [open issues on the old tracker.
](https://bugs.cemu.info/issues/352)
It is not unusual for "Runs" to flip back to "Loads" as development progresses, as sometimes the fixing of one bug exposes another.

**Comment by TheRealWario** [comment]
I will probably close this issue and replace it with a proper one, due to the age and vague wording of this one. This is still a problem not yet fixed, so I do want to have this issue documented properly.
