### ISSUE TITLE
".desktop"-files created by Cemu do not work, if the path to Cemu contains spaces or some other symbols

### ISSUE THREAD

**Issue by ghost** [cemu-project/Cemu#912]
When creating a ".desktop"-file for a game with Cemu, and the path to Cemu contains spaces, or other symbols, that need a `\` in front of them, it will not show up in the app-menu in GNOME (and probably other app-menus too).

This can be manually fixed, by modifying the "Exec=" line in the ".desktop"-files by adding `\` in front of spaces, and some other  symbols that need them, like (double) quotes.

`Exec=/home/username/Games/"Nintendo Wii U"-Emulator/Cemu/Cemu-2.0-45-x86_64.AppImage …` does not work.
This is how Cemu currently does it.

`Exec=/home/username/Games/\"Nintendo\ Wii\ U\"-Emulator/Cemu/Cemu-2.0-45-x86_64.AppImage …` does work.
This is what should be there instead.

Cemu-version: Cemu-2.0-45-x86_64.AppImage
Operating-system: "Debian GNU/Linux 12"

**Comment by qurious-pixel** [comment]
Modifying with single quotes around the double quotes does work.

For a path at: home > username > Games > "Nintendo Wii U"-Emulator > Cemu 

 ```
Exec='/home/username/Games/"Nintendo Wii U"-Emulator/Cemu/Cemu-2.0-45-x86_64.AppImage'
```

**Comment by ThisNekoGuy** [comment]
Typically, we handle this on Linux in situations like this by inserting backslashes before spaces and other special characters like parenthesis, like this when we can't use quotes:
```bash
mkdir "test - testing"
cd test\ -\ testing
```
Just having Cemu insert backslashes where appropriate like that should be fine
