### ISSUE TITLE
Wii U Menu on Cemu 2.0-45 has rendering issues when using OpenGL

### ISSUE THREAD

**Issue by jonbarrow** [cemu-project/Cemu#913]
Running the Wii U Menu on Cemu release 2.0-45 with OpenGL has several rendering issues, at least on Ubuntu 22.04. Most assets have black borders around them, and text is misaligned and sometimes missing lettings

These issues do not happen when using Vulkan on the same system

<details>
<summary>OpenGL</summary>

![Screenshot from 2023-07-24 01-54-56](https://github.com/cemu-project/Cemu/assets/27011796/85f07fa9-2769-4650-aac2-affaf669af56)
</details>

<details>
<summary>Vulkan</summary>

![Screenshot from 2023-07-24 02-04-00](https://github.com/cemu-project/Cemu/assets/27011796/cc1e1016-6cfd-49b1-8b05-e325631fcfcc)
</details>

**Comment by jonbarrow** [comment]
> - You have provided sufficient detail for the issue to be reproduced.

Are you implying that there isn't sufficient detail to reproduce here? What more could have been added, exactly? To reproduce you just need to start the Wii U Meny title in 2.0-45 and use OpenGL, as I said?

> - You have provided system specs (if relevant).

My full system specs didn't seem relevant (which this says to only include if it is) outside of my operating system, which I provided, but if want my specs, here you go

- Ubuntu 22.04
- Intel i7-4790
- 32GB of ram

> - For any issues, a log file

I didn't include a full log file because with OpenGLs debug output (which I assume would be the relevant parts here) the log file is over 200mb. If there's a more relevant area to include I would more than happy to provide it

**Comment by Exzap** [comment]
I can not replicate this on any of my machines. Might be a driver issue?

**Comment by BisucitKrueger** [comment]
Just wanted to say thanks for making it work at all

**Comment by jonbarrow** [comment]
> this may just be because Intel HD Graphics 4600 doesn't have full OpenGL 4.5 support.

This was it, it seems to be an issue with bad OpenGL support with the Intel HD 4600. I just bought a new GPU, the GTX 1050 TI, and now with OpenGL 4.6 things run without issue

Closing now, thanks for that suggestion and sorry for the trouble
