### ISSUE TITLE
[Linux] Cemu does not work with fmt 10

### ISSUE THREAD

**Issue by alba4k** [cemu-project/Cemu#920]
[fmtlib](https://github.com/fmtlib/fmt) recently saw a major release (10.0.0) that Cemu seems to be incompatible with.

updating it causes Cemu to fail to open.

trying to open Cemu just errors `cemu: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory`

**Comment by Exzap** [comment]
Which distro and which binary format of Cemu are you running? (flatpak, appimage, etc.)

**Comment by hirak99** [comment]
It does not also compile with libfmt 10.

Previously compiled versions may not find libfmt.so.9 if the distro has it already upgraded, e.g. Arch has moved to libfmt 10.

**Comment by alba4k** [comment]
I am indeed on arch using Arch. I have Cemu from the AUR (chaotic-aur, but doesn't really matter) and fmt from the extra repo

**Comment by hirak99** [comment]
@alba4k as a workaround if you still have the cemu binary compiled, you can try this -

1. Get hold of the libfmt.so.9 binary. If you have 9.1.0, a symlink `ln -s libfmt.so.9.1.0 binary libfmt.so.9` works too.
2. Make a temporary directory until Cemu is updated, and put the libfmt.so.9 there.
3. Start cemu as `LD_LIBRARY_PATH ~/my_holdback_limfmt_dir cemu`

This will give cemu access to the library without downgrading it for the whole system.

This does not resolve the issue however, compilation of cemu is broken with libfmt 10.0.

**Comment by alba4k** [comment]
Just in case anybody is reading this, you did a typo, `LD_LIBRARY_PATH=/path/to/link.so.9 cemu`

anyway thanks I will try that

**Comment by hirak99** [comment]
Yeah - you need an actual `libfmt.so.9.1.0` or `libfmt.so.9` for this.

Linking the libfmt.so.10 does not work.

**Comment by alba4k** [comment]
I see

I will take it out of an old package then ig

**Comment by jn64** [comment]
Just to note, the next Fedora version (current Rawhide, will be 39, expected 2023-10-24) also has fmt 10. I turned off Rawhide builds for my Cemu package at the moment because no time to deal with it.

**Comment by kescherCode** [comment]
This is being worked on at #924.

**Comment by alba4k** [comment]
fmt 10 works now

libboost doesnt anymore lol (https://github.com/cemu-project/Cemu/issues/958)

**Comment by jn64** [comment]
> fmt 10 works now

Are you sure?

AUR Cemu was changed to use fmt9 https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=cemu&id=7dc9b52e7817e7ded0161318cd18970d07ba044c

**Comment by Tachi107** [comment]
stdlibc++ 13, LLVM's libc++ 17 and MSVC now seem to support `std::format`, would it be feasible to use it now?

**Comment by jn64** [comment]
Does it work for anyone? Build on Fedora 39 (fmt 10) still fails, didn't look
into it yet because I just noticed 757d458

**Comment by jn64** [comment]
Never mind, 757d458 says fmt 10.1.x.

F39/rawhide is still on 10.0.0. Tracking at rhbz#2231706
