### ISSUE TITLE
[Feature request] Microsoft Xbox Elite Wireless Controller Series 2 support

### ISSUE THREAD

**Issue by davidhedlund** [cemu-project/Cemu#925]
Underside of Microsoft Bluetooth Elite Series 2 Controller, with paddles installed:
![image](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/11e34a36-56f7-4ed6-a5f0-385b802bf9b5)

To avoid confusion: Microsoft Bluetooth Elite Series 2 Core is the gamepad without the paddles installed. This feature request includes paddle buttons support in retroarch as well.

Personally, I'm primarily interested in GNU/Linux support, because I don't use Windows.

**Comment by Squall-Leonhart** [comment]
You can access the paddles with SDL(via WGI), they are not exposed to Xinput and never will be.

**Comment by davidhedlund** [comment]
> You can access the paddles with SDL(via WGI), they are not exposed to Xinput and never will be.

How can I access the paddles from Linux?

**Comment by Squall-Leonhart** [comment]
Update to a 6.1 based linux kernel, or find the relevant driver and cherry pick the change that enabled them.

**Comment by Exzap** [comment]
This is up to SDL which we use for controller handling on Linux
