### ISSUE TITLE
Feature request: support games in .app/.tmd/.h3 format

### ISSUE THREAD

**Issue by mariomadproductions** [cemu-project/Cemu#929]
This would be useful for people that store digital games in their original format (rather than a derived/lossy-converted format like the extracted meta/content/code folders).

Edit: this would also go part of the way towards supporting disc images, as those use the same format.

**Comment by mariomadproductions** [comment]
> Cemu supporting CDN format would mean having to store keys, which isn't the best idea. Besides, cemu is emulating a WiiU, which does not operate on the packed files and must unpack them before use.

It wouldn't need to include keys in the source/release, the user can just supply them like they supply system files.

Yeah this is a convenience feature.

**Comment by spudpiggy** [comment]
I forgot cdn format was even a thing lmao
At the very least Cemu should let you unpack cdns if you supplied your own keys and then install them normally

**Comment by mariomadproductions** [comment]
> 

Ideally it should be able to read them without unpacking, but yeah even that would be useful.

**Comment by Masamune3210** [comment]
reading them without unpacking would likely be that useful, the act of decompressing and decrypting the files takes a not insignificant amount of processing

**Comment by mariomadproductions** [comment]
> reading them without unpacking would likely be that useful, the act of decompressing and decrypting the files takes a not insignificant amount of processing

I don't think the data is compressed. And the Wii U itself copes fine when its running games of a disc (which store the game data in the same format). ninfs for PC can mount 3DS CDN data too, which can then be run in Citra, and I think that is a pretty similar format.

So actually, this feature would be useful if cemu were to implement reading Wii U disc images too, so it is in fact relevant to emulation, not just a convenience feature. I didn't think of that before. 🙃

**Comment by Exzap** [comment]
Cemu already supports disc images. It also already has code to open and read WUP format (or ".app format" or however you wanna call it) since it is needed by the download manager for the extraction and installation step.

It would be relatively trivial to add support for WUP to title scanning and mounting too. I may look into that when I get a chance.

**Comment by jonbarrow** [comment]
> rather than a derived/lossy-converted format like the extracted meta/content/code folders

It isn't lossy or "derived", though? It's just the decrypted and extracted version of the same files. The meta/content/code folders is how the WiiU stores eShop titles after being downloaded?

What benefit is there to keeping the titles stored this way?

**Comment by Exzap** [comment]
Converting from .app/WUD to extracted loses some information:
- Digital signatures, hashes and encryption key
- FST-specific file flags
- Symlinks get resolved during extraction
Games don't generally care about any of this, but it's not lossless in the strict sense.

However, when you install a title on the console it seems to keep all of the above intact by dumping the original .app filesystem into code/title.fst. It also keeps title.tmd in code/title.tmd. As far as I know, none of the PC based extraction tools do this. There is also no tool yet to convert it back, so even if the representation were lossless it's a one way conversion for now.

**Comment by mariomadproductions** [comment]
> > rather than a derived/lossy-converted format like the extracted meta/content/code folders
> 
> It isn't lossy or "derived", though? It's just the decrypted and extracted version of the same files. The meta/content/code folders is how the WiiU stores eShop titles after being downloaded?
> 
> What benefit is there to keeping the titles stored this way?

Basically because that's how the data is stored on the server (and therefore that's how eShop preservation projects store the data). And as Exzap says, its a lossy conversion - for Wii, DSi and 3DS, the process is basically just decryption and not extraction, but its still lossy, even if there are known ways to re-create the original data (if you have info on the original CDN data).

> Converting from .app/WUD to extracted loses some information:
> 
> * Digital signatures, hashes and encryption key
> * FST-specific file flags
> * Symlinks get resolved during extraction
> 
> Games don't generally care about any of this, but it's not lossless in the strict sense.
> 
> Interestingly enough, when you install a title on the console it seems to keep all of the above intact by dumping the original .app filesystem into code/title.fst. It also keeps title.tmd in code/title.tmd. As far as I know, none of the PC based extraction tools do this. There is also no tool yet to convert it back, so even if the representation were lossless it's a one way conversion for now.

Interesting, I didn't know about the title.fst file. Sounds like you might still need prior information to do the conversion (signatures, hashes, keys), like with Wii/DSi/3DS, but still, that's better than I thought.

**Comment by jonbarrow** [comment]
> And as Exzap says, its a lossy conversion

I guess in the most absolutely strict sense, sure. But originally I had assumed you thought the actual game data was losing some kind of information, which isn't the case

> Interestingly enough, when you install a title on the console it seems to keep all of the above intact by dumping the original .app filesystem into code/title.fst

The title.fst is just extracted from the first .app file listed in the tmd, the console doesn't create this file on it's own it's part of the download. I used to use this as part of an old custom NUS downloader I made years ago to only extract certain files from games (the TGA icons)

**Comment by Exzap** [comment]
> The title.fst is just extracted from the first .app file listed in the tmd, the console doesn't create this file on it's own it's part of the download.

Just to clarify, it's not a regular file inside the FST. It is the FST header and filetable itself dumped into a file. In that sense there has to be special code to extract it because the regular file extraction process doesn't see it.

You can verify this easily by printing out all the filenames stored inside any FST partition, it doesn't have a "title.fst" entry.

**Comment by jonbarrow** [comment]
> Just to clarify, it's not a regular file inside the FST. It is the FST header and filetable itself dumped into a file. In that sense there has to be special code to extract it because the regular file extraction process doesn't see it.
> 
> You can verify this easily by printing out all the filenames stored inside any FST partition, it doesn't have a "title.fst" entry.

I'm not sure what you mean by "special code" here, it's just encrypted as the first .app file. I have verified this just now using the most recent Splatoon update. I wrote a tool which downloads the first .app file listed in the games tmd from the CDN, decrypted it, and wrote the decrypted contents to disk. I compared it to the `title.fst` from my console, and they're the exact same file

```
$  md5sum decrypted ~/.local/share/Cemu/mlc01/usr/title/0005000e/10176900/code/title.fst
7f1b4a287aca7c90775cdb5e3bd3a415  decrypted
7f1b4a287aca7c90775cdb5e3bd3a415  /home/jon/.local/share/Cemu/mlc01/usr/title/0005000e/10176900/code/title.fst
```

Yes you need special code to read the FST, but the `title.fst` file itself is just AES encrypted like the packed CDN contents that gets extracted afterwards

I'm aware that the `title.fst` is not, itself, part of FST, but that wasn't what I was saying. Your original comment on the file made it sound like the WiiU created this file on it's own, which isn't the case. It's downloaded with the rest of the contents from the CDN

**Comment by Exzap** [comment]
> I'm aware that the title.fst is not, itself, part of FST, but that wasn't what I was saying

Good, that was really my only point. We got a bit hung up on semantics it seems.
