### ISSUE TITLE
[Feature Request] Have the packaging be in a .deb Format

### ISSUE THREAD

**Issue by enderpirate98** [cemu-project/Cemu#93]
For software distributions it would be the most practical for everything to be a source file for forking reasons and have it be in a .deb format for standard installations so that the process will be simplified and the package itself can be updated through the standard repositories.

**Comment by Crementif** [comment]
We don't plan on packaging or distributing Cemu for now, see #78. We'll later reconsider this once we've got a flatpak and appimage, which should make it easy for users to download and use Cemu.
