### ISSUE TITLE
[Linux] Unhandled exception after commit 22bf642 (local build)

### ISSUE THREAD

**Issue by kturques** [cemu-project/Cemu#936]
After commit 22bf6420d265399d8a31d518026e39328ab15812, Cemu builds, but fail to start on Linux with the following message:
`Unhandled standard exception of type "N3fmt2v912format_errorE" with message "string pointer is null"; terminating the application.`

When I comment `logPlatformInfo()` from `Initialize()` in `src/Cafe/CafeSystem.cpp`, it works again

Same error compiling with gcc or clang

System info:
- openSUSE Tumbleweed 20230809
- gcc (SUSE Linux) 13.2.1 20230803 [revision cc279d6c64562f05019e1d12d0d825f9391b5553]
- clang version 16.0.6
- libfmt9 version 9.1.0-2.3
- cmake version 3.27.1
- boost version 1.82.0-1.3
- cmake command: `cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DENABLE_DISCORD_RPC=OFF -DENABLE_VCPKG=OFF -DPORTABLE=OFF -DEXPERIMENTAL_VERSION=999999`

**Comment by AMDBartek** [comment]
Yup, can confirm on Kubuntu 23.04.

**Comment by jonbarrow** [comment]
Also confirmed on Ubuntu 22.04, fresh clone and regular build instructions

**Comment by Exzap** [comment]
Should be fixed with 892ae13680a30d71b489ca754ddaa2b17828f85e Can you verify?

**Comment by kturques** [comment]
> Should be fixed with [892ae13](https://github.com/cemu-project/Cemu/commit/892ae13680a30d71b489ca754ddaa2b17828f85e) Can you verify?

Fixed. Thank you
