### ISSUE TITLE
[Feature Request] command-line option to create WUA for a title (Base + Updates + DLCs)

### ISSUE THREAD

**Issue by MestreLion** [cemu-project/Cemu#943]
This is related to #35 , but focusing on non-GUI conversion instead of batch operation. In a way, if we have a command-line option to convert a single title then it's easy to do batch conversion in a script. My goal is to automate the process of converting a WUX library in a headless way, possibly adding updates and DLCs to a given title.

Assuming a given title has:
- A `.wux` file for the base game, and its corresponding entry in `keys.txt`
- Some updates and DLCs in folders containing the required `meta/meta.xml` (or, even better, `.zip` files of those)

Currently, one would have to use several steps in Cemu's GUI to create the WUA:
- Copy the `keys.txt` to Cemu's install folder
- Launch Cemu and configure its MLC and Game paths so it scans the WUX
- File > Install game title, update or DLC... > Select folder containing `meta/meta.xml`
- Repeat the above for each update or DLC
- Open Tools > Title Manager
- Right click the base game (now in WUD format) > Convert to compressed Wii U archive (.wua)
- Confirm the dialog where Cemu (smartly) already included the installed updates and DLCs for that title

A command line option to automate all the above GUI steps could be something like:
```sh
cemu [--keys keys.txt|--key 'a9b8...'] --convert title.wux /some/dlc/ /some/update.zip ... --output title.wua
```

Is this an intended or welcome feature?

**Comment by Exzap** [comment]
This is beyond the scope of this project. Cemu is by no means intended to be a generic conversion tool.

It's maybe not exactly what you are asking for, but you can already automate conversion using existing command line tools. It may require a little bit of scripting depending on your exact needs. Use [JWUDTool](https://github.com/Maschell/JWUDTool) to unpack `.wud/.wux` and [ZArchive](https://github.com/Exzap/ZArchive) to create a `.wua` from the title folders.

**Comment by MestreLion** [comment]
> https://github.com/Exzap/ZArchive

Thanks @Squall-Leonhart ! But that is only a piece of the puzzle, and it doesn't even have a command-line. True, it's not hard to code a simple one, but the next challenge would be: how to merge a WUX an its key with an update folder and DLCs the same way as Cemu does in order to generate a valid WUA?

**Comment by MestreLion** [comment]
Thanks for replying @Exzap !

> This is beyond the scope of this project. Cemu is by no means intended to be a generic conversion tool.

Well, I don't mean to use it as a _generic_ conversion, but rather to create WUAs to be used in Cemu itself.

Is this really out of scope? I mean, Cemu already perform all those steps via GUI, so the code is there. My request is simply to expose such functionality in its command-line.

My scenario: Batocera running in a Mini PC with a controller and no Keyboard or Mouse, library populated via SSH/rsync from my Workstation PC. But recently Batocera stopped supporting WUX, but it supports WUA, possibly as promoted by Cemu as the way forward (and I can see why, it's a great format). 

So now I can no longer simply `rsync` my library to its ROMs folders, the Workstation has no Cemu installed, and using Cemu's GUI from EmulationStation in the Mini PC is very clunky, if possible at all.

So I was hoping for a way to script a conversion using the installed and working Cemu in the Batocera machine, to populate the ROMs folders so EmulationStation will show and launch them.

> It's maybe not exactly what you are asking for, but you can already automate conversion using existing command line tools. You can use [JWUDTool](https://github.com/Maschell/JWUDTool) to unpack `.wud/.wux` and [ZArchive](https://github.com/Exzap/ZArchive) to create a `.wua` from the title folders. It may require a little bit of scripting depending on your exact needs.

I have no problem with shell scripting, but what would be the exact layout for the WUA? How should I merge the extracted WUX with a given update and DLC trees? Any direction or needed command line arguments would be highly appreciated!

**Comment by Exzap** [comment]
> Is this really out of scope? I mean, Cemu already perform all those steps via GUI, so the code is there. My request is simply to expose such functionality in its command-line.

You are making a lot of assumptions about how flexible title handling is in Cemu and how the WUA conversion works. The latter is interwoven with the UI code and can't really be invoked standalone without refactoring. There are other issues like WUA conversion using the shared persistent title list and we don't have the infrastructure for temporarily adding titles and keys via command line.

Of course these problems can be solved but it's all very far removed from our main priority (emulation). Conversion via UI was already a fringe feature but at least made sense to have a user friendly way of converting titles since we wanted to encourage the use of the WUA format when it released.

> I have no problem with shell scripting, but what would be the exact layout for the WUA? How should I merge the extracted WUX with a given update and DLC trees? Any direction or needed command line arguments would be highly appreciated!

The [ZArchive readme](https://github.com/Exzap/ZArchive#wii-u-specifics) has info on the layout required for `.WUA`. You can also unpack an existing wua to see the folder layout that it uses. It's all pretty self explanatory imho. You never merge files btw, the base game, update, dlc all go into separate directories which then are packed into a single (wua).
