### ISSUE TITLE
Color Splash: Not all the graphics are loaded

### ISSUE THREAD

**Issue by avbaral** [cemu-project/Cemu#947]
When opening up Color Splash, the title screen works for a bit. Then it immediately turns black and white as if the colors are not loaded in.  Also, when Mario interacts with objects, the shining effect stays on the screen.
<img width="1256" alt="Screenshot 2023-08-23 at 09 01 06" src="https://github.com/cemu-project/Cemu/assets/136860395/0e695eaf-96d2-4480-92fc-0d70909aab29">
Here's the log.txt:
[log.txt](https://github.com/cemu-project/Cemu/files/12420054/log.txt)

**Comment by Exzap** [comment]
For MacOS troubleshooting please visit our discord. Most likely, this is cant be fixed and is just due to the unfinished state of the MacOS version of Cemu.
