### ISSUE TITLE
[Feature] Add support for Wii-U gamepad in CEMU

### ISSUE THREAD

**Issue by eHerbaciarz** [cemu-project/Cemu#948]
Add support for Wii-U gamepad in CEMU - 
I saw that there is a project that allows you to connect a Wii-U gamepad to a computer - Link: https://wiiubrew.org/wiki/UsendMii

Maybe this project could help with that and its solutions could be implemented in CEMU

**Comment by Squall-Leonhart** [comment]
Nothing here can be used directly in cemu, and this guide was already long known.

The resulting controller still winds up communicating to a Vigem server on the PC.

**Comment by Exzap** [comment]
UsendMii forwards everything through a running Wii U, which imho defeats the purpose in the context of Cemu.

Connecting to the GamePad directly is unfortunately not easily possible (see projects like [pc2drc](https://github.com/thefloppydriver/pc2drc) and even if it were, adding realtime video streaming to Cemu is no easy task.

**Comment by Drago-Cuven** [comment]
so its just never happening...

**Comment by drphobus** [comment]
Just a question, would it be possible with a usb dongle aka like the Delphin bar that works dolphin emulator for the Wii controllers.
i suspect even if it is posable its just too fringe to exist.

**Comment by ShitheadMaximum** [comment]
Yes! this was recently announced. With support for CEMU. However, it costs around $60, and is being released rather slowly. https://www.youtube.com/watch?v=BdRCj5-UNqU
