### ISSUE TITLE
Useless "Check for updates" in non-windows releases

### ISSUE THREAD

**Issue by davidhedlund** [cemu-project/Cemu#952]
* Download  Cemu-2.0-46-x86_64.AppImage from https://github.com/cemu-project/Cemu/releases/tag/v2.0-46
* Make Cemu-2.0-46-x86_64.AppImage executable and run it
* Go to: Help -> Check for updates

![image](https://github.com/cemu-project/Cemu/assets/6416073/72ad3a79-ffa6-49f6-b9cd-8f06188f03b5)

It should indicate that an update exists since Cemu-2.0-47-x86_64.AppImage is out: https://github.com/cemu-project/Cemu/releases/tag/v2.0-47

**Comment by Exzap** [comment]
Auto updating is not yet implemented for anything but Windows

**Comment by davidhedlund** [comment]
> Auto updating is not yet implemented for anything but Windows

Oh. Shouldn't "Check for updates" be removed until it has been implemented in other operating systems?

**Comment by davidhedlund** [comment]
Thank you.

**Comment by davidhedlund** [comment]
It's great that the menu item has been disabled. I just identified GNU/Linux, and macOS in the commit, so I change the title that the auto update should be added specifically for them. Can you please re-open this issue @Exzap ?

**Comment by jn64** [comment]
Not sure it's worth implementing for Linux. IMO users should prefer flatpak or
distro packages which are more convenient than AppImage. For such packages, the
app's own update checking would be an anti-feature and disabled anyway.

**Comment by davidhedlund** [comment]
> Not sure it's worth implementing for Linux. IMO users should prefer flatpak or distro packages which are more convenient than AppImage. For such packages, the app's own update checking would be an anti-feature and disabled anyway.

True. And for macOS?

**Comment by davidhedlund** [comment]
@jn64 ?

**Comment by davidhedlund** [comment]
It is now possible to update Cemu through "Help -> Check for updates"
