### ISSUE TITLE
Linux kernel 5.15 + Nintendo Switch Pro Controller: Severely limited left/right sticks

### ISSUE THREAD

**Issue by davidhedlund** [cemu-project/Cemu#954]
# Linux kernel 5.15 + Nintendo Switch Pro Controller: Issue
Software:
* Cemu-2.0-47-x86_64.AppImage
* [Trisquel GNU/Linux](trisquel.info/) 11 (linux kernel 5.15)

Gamepad:
* Nintendo Switch Pro Controller

Gamepad status:
* _New Super Mario Bros. U_: Left stick issue: Cannot navigate to the right direction at random times. **However, this is also a problem in Yuzu in _New Super Mario Bros. U Deluxe_.**
* _The Legend of Zelda: Twilight Princess HD_: Left stick issue: Cannot run the character. Right stick issue: It takes twice as long to rotate the view angle.
* _The Legend of Zelda: The Wind Waker_: Left stick issue: Cannot run the character. Right stick issue: It takes twice as long to rotate the view angle.

Instructions:
Just open the games, create a default profile, and start the game. Press "+" to skip the intros, so you can evaluate this issue as quick as possible. For example, when you have started _The Legend of Zelda: Twilight Princess HD_ you cannot run like seen on this [YouTube-videohere](https://youtu.be/E4xKEuTSGmo?t=224). You don't need to hold any button in combination with moving the left stick to run in these games.

I tried to hold the left stick button for more than 10 seconds in a single direction. At best, Link started to walk a little bit faster, but he never ran. You cannot play these games with this issue.

## Related:
Nintendo Switch Pro Controller requires a separate configuration is used for Linux 5.15 and earlier: https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Nintendo%20-%20Switch%20Pro%20Controller%20(old).cfg while this configuration file, https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Nintendo%20-%20Switch%20Pro%20Controller.cfg is used for Linux 5.16 and later.

# Linux kernel 5.19 + Nintendo Switch Pro Controller: Working
Software:
* Cemu-2.0-47-x86_64.AppImage
* Ubuntu MATE 22.04 (linux kernel 5.19)

Gamepad:
* Nintendo Switch Pro Controller

Gamepad status:
* _New Super Mario Bros. U_: No issues
* _The Legend of Zelda: Twilight Princess HD_: No issues
* _The Legend of Zelda: The Wind Waker_: No issues

# Sony DualSense regardless linux kernel version: Working
Software:
* Cemu-2.0-47-x86_64.AppImage
* Trisquel GNU/Linux 11 (linux kernel 5.15)

Gamepad:
* Sony DualSense

Gamepad status:
* _New Super Mario Bros. U_: No issues
* _The Legend of Zelda: Twilight Princess HD_: No issues
* _The Legend of Zelda: The Wind Waker_: No issues

**Comment by davidhedlund** [comment]
Related:
* Nintendo Switch Pro Controller requires a separate configuration is used for Linux 5.15 and earlier: https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Nintendo%20-%20Switch%20Pro%20Controller%20(old).cfg while this configuration file, https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Nintendo%20-%20Switch%20Pro%20Controller.cfg is used for Linux 5.16 and later.

**Comment by davidhedlund** [comment]
# Sony DualSense regarless linux kernel version: No issue
Gamepad:
* Sony DualSense

Software:
* Cemu-2.0-47-x86_64.AppImage
* Trisquel GNU/Linux 11 (linux kernel 5.15)
* The Legend of Zelda: Twilight Princess HD

Can run as expected with the left stick.

# Ubuntu MATE (linux 5.19): No issue
Gamepad:
* Nintendo Switch Pro Controller

Software:
* Cemu-2.0-47-x86_64.AppImage
* Ubuntu MATE 22.04 (linux kernel 5.19)
* The Legend of Zelda: Twilight Princess HD

Can run as expected with the left stick.

**Comment by Squall-Leonhart** [comment]
Its up to you to make sure your environment is setup and compatible with the application you intend to run, as a linux user.

on 5.15, you need to manually pull in and build the necessary Switch controller drivers, that are native to 5.16+

**Comment by davidhedlund** [comment]
> Its up to you to make sure your environment is setup and compatible with the application you intend to run, as a linux user.
> 
> on 5.15, you need to manually pull in and possibly build the necessary Switch controller drivers ([hid-nintendo-dkms](https://github.com/nicman23/dkms-hid-nintendo)), that are native to 5.16+
> 
> SDL 2.2x+ defaults are configured around that driver, so whatever your 5.15 kernel is doing won't work without that driver, and the configuration won't be reverted to fit your older environment.

The simplest approach in Trisquel is to run: sudo apt install linux-generic-hwe-11.0
