### ISSUE TITLE
[Linux] Cemu does not work with libboost 1.83

### ISSUE THREAD

**Issue by alba4k** [cemu-project/Cemu#958]
[libboost](https://www.boost.org/) recently saw a major release (1.83.0) that Cemu seems to be incompatible with.

updating it causes Cemu to fail to open.

trying to open Cemu just errors `cemu: error while loading shared libraries: libboost_program_options.so.1.81.0: cannot open shared object file: No such file or directory`

This issue btw is just a copy paste of https://github.com/cemu-project/Cemu/issues/920 and the same workaround works here too with libboost_program_options.so.1.81.0

**Comment by jn64** [comment]
Did you rebuild Cemu with boost 1.83?

https://wiki.archlinux.org/title/AUR#Updating_packages

Also, please stop attaching random binaries and suggesting others use it as a workaround.

**Comment by alba4k** [comment]
Sorry, was assuming it was worth mentioning. No, I did not try to rebuild it, but my best guess would be that it would work fine
