### ISSUE TITLE
Cemu game dlc not loading in the game

### ISSUE THREAD

**Issue by Brilionn** [cemu-project/Cemu#959]
I am using the steam deck and I have tried cemu from discover and emudeck(2.0-47). No matter how I put the files(download titles or from console) the dlc will not load for some reason. The log file even shows that the dlc is being seen and used but the game just doesn’t show  it. I don’t know how to get around this but if somebody knows I’d appreciate it

**Comment by Exzap** [comment]
Please use the discord or subreddit for troubleshooting
