### ISSUE TITLE
Homebrew Format Support

### ISSUE THREAD

**Issue by TurtleP** [cemu-project/Cemu#962]
Hi,

I'm the developer of [LÖVE Potion](https://github.com/lovebrew/lovepotion). I didn't see any issues open (or closed, unless the GitHub app isn't showing them) about this.

Essentially, I prefer to test a lot of my features and bug fixes on official hardware. However, Wii U is a bit of a pain point for me because there's a few work arounds and delays (which are semi-minor) compared to 3DS and Switch development.

Anyways, `wut` has added a new format, `wuhb` which allows homebrew to be bundled into a single application. This works wonderfully on hardware via Aroma cfw, but if I wanted to test on Cemu I cannot since it doesn't load the format.

One of the original ideas was for me to have the same tree structure on the virtual sd card (e.g. code, content, etc), but as of right now it doesn't even load. It used to work when I was doing initial work on the Wii U version. That's a separate issue I need to debug.

Regardless, supporting the `wuhb` format would be very convenient for homebrew developers since everything is bundled into one binary. I understand Cemu is still experimental, but as mentioned before, I can easily run my 3DS or Switch homebrew on their emulators if I wanted.

**Comment by aboood40091** [comment]
(I do see your point in wanting `wuhb` support, but the 3DS and Switch arguments are irrelevant.)
