### ISSUE TITLE
NES Remix 1 and 2 crash after start on menu from version 2.0-46 onwards

### ISSUE THREAD

**Issue by Doodl0** [cemu-project/Cemu#973]
I am running this on Windows with a AMD Ryzen 5 3600 and a Nvidia RTX 3060Ti. If it helps, I was able to reproduce this issue on a Steam Deck, running Cemu with Proton

From version 2.0-46 and onwards, NES Remix 1 and 2 crash after pressing start on the title screen. If I remove my save file and start over, they both work until the games tries to save (NES Remix 1) or I reload the game (NES Remix 2). I am running the European version of the games, and have tried redumping them from my Wii U with Dumpling. 

Here is a copy of [the log](https://github.com/cemu-project/Cemu/files/12690852/log.-.Copy.txt) for NES Remix 1
And here is a copy of [the log](https://github.com/cemu-project/Cemu/files/12690870/log.txt) for NES Remix 2

**Comment by Squall-Leonhart** [comment]
I cannot replicate this.

**Comment by TheMysteriousStar** [comment]
I could replicate this for NES Remix 1 but not 2 (I use US version for both)

**Comment by Squall-Leonhart** [comment]
I have a reproduction, my dumb ass was using the Pack version.

The crash occurs when the game tries to interact with online data for scores

**Comment by Squall-Leonhart** [comment]
Testing a fix locally

**Comment by Squall-Leonhart** [comment]
my fix works, but might not be the right way to go about this, the issue might be an invalid return in the offline postdb.

**Comment by Doodl0** [comment]
Thanks! After building, this works perfectly and even restores the championship mode in NES Remix 2, which I forgot to mention also broke. Hopefully this gets merged asap
