### ISSUE TITLE
colour splash crashes upon painting anything

### ISSUE THREAD

**Issue by virroi** [cemu-project/Cemu#975]
paint in colour splash crashes

**Comment by Exzap** [comment]
Github issues are for detailed bug reports. If you need help troubleshooting please use our discord or subreddit 

At any rate, this may be the same issue as #618. The solution is to update your graphic drivers

**Comment by virroi** [comment]
> Github issues are for detailed bug reports. If you need help troubleshooting please use our discord or subreddit
> 
> At any rate, this may be the same issue as #618. The solution is to update your graphic drivers

i updated my drivers already recently but i still get crashes, my gpu is 1650 super
