### ISSUE TITLE
Hero's path in BOTW progress is gone after updating to 2.0-53

### ISSUE THREAD

**Issue by hikka10** [cemu-project/Cemu#985]
I tried coping over the save file to a 2.0-52 folder and a 1.27.1 folder but the issue remains. My hero's path progress is gone. Is there something else i can provide or i can do to get it back somehow?

**Comment by GuigoHub** [comment]
Had a similar issue, but in my case, CEMU crashes after loading the game shaders

**Comment by Squall-Leonhart** [comment]
> I tried coping over the save file to a 2.0-52 folder and a 1.27.1 folder but the issue remains. My hero's path progress is gone. Is there something else i can provide or i can do to get it back somehow?

this would imply your DLC isn't registered

**Comment by Exzap** [comment]
Can you upload log.txt after loading into the game. It should be in the Cemu folder. Assuming you are using Windows.
Also what version did you upgrade from?

**Comment by hikka10** [comment]
> Can you upload log.txt after loading into the game. It should be in the Cemu folder. Assuming you are using Windows. Also what version did you upgrade from?

[log.txt](https://github.com/cemu-project/Cemu/files/12784767/log.txt)
I upgraded from 2.0-52

**Comment by Squall-Leonhart** [comment]
To use Cemu legally you must use your own games. See the [Dumping Guide](https://cemu.cfw.guide/dumping-games).

Keep in mind that any form of piracy is strictly forbidden on this server (including games and title keys). This server only provides help for those who've obtained their games legally.
