### ISSUE TITLE
[Linux] Cemu only uses GTK file picker.

### ISSUE THREAD

**Issue by AxerTheAxe** [cemu-project/Cemu#991]
Hi, I have noticed that Cemu does not respect the `GTK_USE_PORTAL=1` environment variable. This will tell GTK to request the file picker from the XDG Desktop Portal. I have tested this with every other GTK program I have and they all work correctly. Cemu is the only program I have found to not work with this.

**System:**
ArchLinux
KDE Plasma
**Tested on:**
Cemu Appimage
Cemu compiled from source

**Expected Behaviour:**
Launches XDG file picker.
![image](https://github.com/cemu-project/Cemu/assets/99703210/b9bfb881-ab36-4f68-8fd7-31d9852d2609)

**Unexpected Behavior:**
Launches GTK file picker.
![image](https://github.com/cemu-project/Cemu/assets/99703210/72d06f00-fc65-41bc-b2fb-6bf53b7a92af)

**Comment by Exzap** [comment]
This may be an wxWidgets limitation? Cemu isn't using GTK directly, instead it uses wxWidgets which has GTK as it's backend on Linux. Did you test other wxWidgets applications to see if they have the same problem?

**Comment by AxerTheAxe** [comment]
Just tested a few and that appears to be the case.

**Comment by AxerTheAxe** [comment]
Accidentally closed the issue. I will be looking for a solution and will close again if I cannot find anything. Thanks for the info.

**Comment by AxerTheAxe** [comment]
What version of wxWidgets is used in the latest appimage?
