### ISSUE TITLE
"x" on keyboard not work on latest version (2.0-55)

### ISSUE THREAD

**Issue by Emil2010** [cemu-project/Cemu#992]

**Comment by Squall-Leonhart** [comment]
X on keyboard works fine.

**Comment by Emil2010** [comment]
i tested in super smash bros for wii u and "x" on keyboard not work, but type with "x" i can

**Comment by Emil2010** [comment]
windows 10, on cemu not work (game and settings)

**Comment by Emil2010** [comment]
thanks for resolving this issue
